.gitignore
README.md
cpp/README.md

Added instructions to build C++ on `macOS` and `Ubuntu 22.04`

Update README to add instruction for building C++

---

README.md

Add the `scipy 2022` conference poster link to the project README.md file.

Add scipy2022 poster link to README

---

cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc

When we executing predicate pushdown, we will first read the columns in the filter schema (#36). We don't need to read these columns again when executing the Projection (#32).
For example, for a query:
```sql
SELECT image, split FROM data WHERE split = "train" 
```
The column `split` will be populated during filtering execution (#36), thus it should not be read again to populate the final results.  With `Schema::Exclude`, we can remove filtered schema from projected schema (in `arrow::dataset::ScanOptions`).

Add Schema::Exclude(schema).

---

cpp/CMakeLists.txt
python/setup.py
python/tools/Dockerfile.manylinux2014
python/tools/auditwheel
python/tools/build_manylinux_wheels.sh
python/tools/build_wheel.sh

Using `manylinux2014` to build the the wheels for python 3.8 - 3.10. Makes the wheels compatible with the pyarrow installed via `pypi`.
Note: This does not work with conda pyarrow.

Build python wheels using Manylinux

---

.github/workflows/cpp.yml

A quick fix for Mac builds failed to link faulty-built protobuf 21.2 from homebrew.

CI fix: update mac homebrew to use the latest version of protobuf

---

cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc

Push the projection over `list<struct>` to the struct level. 
It supports the use cases like  `schema = <annotations: list<struct<box:<xmin, ymin, xmax, ymax>>>`, `Schema.Project("annotations.box.xmin")`.

[BUG] Fix Projection over nested list of structs.

---

README.md
python/lance/_lib.pyx
python/setup.py

On Mac, `python setup.py build` complaints about not finding `-larrow_python`.

Fix compiling cython on Mac

---

python/thirdparty/build.sh

For local development it's much faster to be able do python setup.py develop
So we use the previous thirdparty build script to build pyarrow against
system libarrow that we installed to enable liblance build.
The main change in this PR is changing the arrow ref being checked out. By
default this builds pyarrow 8.0.0.devXXX, which fails the pylance requirement
of pyarrow>=8,<9. Instead we use the 8.0.1 tag in pyarrow

Restore the custom build script for pyarrow

---

cpp/src/lance/arrow/type.cc
cpp/src/lance/arrow/type.h
cpp/src/lance/arrow/type_test.cc
python/pyproject.toml
python/setup.py
python/thirdparty/build.sh
python/tools/Dockerfile.manylinux2014
python/tools/auditwheel
python/tools/build_manylinux_wheels.sh

Add type parsing for:
* timestamp
* date32/date64
* time32/time64
* null
Upgrade arrow to 9.0 and fix CI.
Closes #30

Add support for Arrow temporal types, large binarys, and null type

---

cpp/CMakeLists.txt

Fix a new CMake warning appears with cmake 2.24

Fix warnings for CMP0135

---

cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/io/writer.cc

large_binary write does not work but binary works fine.
Added two test cases below to demonstrate. 1 fails the other passes.

reproduce large binary write bug

---

cpp/src/lance/arrow/CMakeLists.txt
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/arrow/testing.h
cpp/src/lance/arrow/type.cc
cpp/src/lance/arrow/type.h
cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc
cpp/src/lance/format/visitors.cc
cpp/src/lance/io/reader.cc
cpp/src/lance/io/writer.cc
protos/format.proto

I'm sure I'm missing some edge cases but seems like this gives us what we want?

Basic extension type handling

---

cpp/src/lance/io/reader.cc
cpp/src/lance/io/reader_test.cc

Fix length calculation when reading list array with offset

---

python/benchmarks/bench_utils.py
python/benchmarks/coco.py
python/benchmarks/oxford_pet.py
python/benchmarks/parse_coco.py
python/benchmarks/parse_pet.py
python/lance/__init__.py
python/setup.py

Local data using Coco train2017 + val2017 instances (122K images)
Discoveries (priority ordering):

Coco benchmarks for lance and parquet formats

---

cpp/CMakeLists.txt
cpp/src/lance/io/CMakeLists.txt
cpp/src/lance/io/project.cc
cpp/src/lance/io/project_test.cc
cpp/src/lance/testing/CMakeLists.txt
cpp/src/lance/testing/io.cc
cpp/src/lance/testing/io.h

This PR fixes a segfault for queries like
```
SELECT id FROM table WHERE id = 10
```
where the filters cover all the projected columns.

Project skips scan if the filter covers all the columns

---

cpp/src/lance/arrow/stl.h
cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/encodings/plain.cc
cpp/src/lance/encodings/plain_test.cc
cpp/src/lance/io/writer.cc

Plain encoding supports writing boolean array

---

cpp/src/lance/encodings/binary.cc
cpp/src/lance/encodings/binary.h
cpp/src/lance/encodings/dictionary.cc
cpp/src/lance/encodings/plain.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/io/writer.cc

Closes #113.
The reason of the bug was that Arrow re-uses the underneath buffer object for multiple arrays. Each array is with different offsets on the same buffer.  `PlainEncoder` used to write Array::data() which always pointed to the first batch.

PlainEncoding uses raw value pointer to write data to disk.

---

python/benchmarks/bench_utils.py
python/lance/_lib.pyx
python/lance/tests/test_api.py

Support pyarrow write_dataset with partitions

---

cpp/include/lance/arrow/scanner.h
cpp/src/lance/arrow/scanner.cc
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/io/project_test.cc

Setting `BatchSize` via `lance::arrow::ScanBuilder`

Setting BatchSize via ScanBuilder

---

cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/io/filter.cc

Add `Schema::Project(const arrow::compute::Expression&)` method to project the fields based on the fields references in the expression.

Move Expression based schema project to Schema class

---

.github/workflows/python.yml
python/lance/__init__.py
python/lance/_lib.pyx
python/lance/pytorch/__init__.py
python/lance/pytorch/data.py
python/lance/tests/test_api.py
python/lance/tests/test_pytorch.py
python/setup.py

Basic and experimental implementation of `torch.Dataset`. 
Closes #109

Initial PyTorch Dataset support

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/bench_utils.cc
cpp/benchmarks/bench_utils.h
cpp/benchmarks/convert.cc
cpp/benchmarks/scan.cc

Provide a CLI executable to be used profiling scan performance

Provide binary to profiling scans

---

python/benchmarks/parse_pet.py
python/benchmarks/train_pet.py
python/lance/__init__.py
python/lance/pytorch/data.py

Multi-worker support in Pytorch Dataset

---

python/lance/__init__.py
python/lance/_lib.pyx
python/lance/pytorch/data.py
python/lance/tests/test_api.py
python/lance/types/box.py

lance dataset that overrides Dataset.scanner and Dataset.head

---

python/lance/tests/test_types.py
python/lance/types/__init__.py
python/lance/types/image.py

closes #159 
Instead of custom `Image.__new__`, we just have `Image.create` instead

Pickle Image

---

.gitignore
cpp/src/lance/arrow/file_lance.cc
python/benchmarks/bench_utils.py
python/benchmarks/oxford_pet/common.py
python/benchmarks/oxford_pet/datagen.py
python/benchmarks/oxford_pet/embeddings.py
python/benchmarks/oxford_pet/train.py
python/benchmarks/train_pet.py
python/lance/pytorch/data.py
python/lance/types/image.py

* Improve ergnomic of Pytorch Dataset to load local directory
* Auto tune learning rate and uses other hyperparameters from torchvision site.
* Example code to generate embeddings.

Improve ergonomic of the Pytorch dataset and Generate embeddings for oxford pet

---

python/benchmarks/bench_utils.py
python/benchmarks/parse_coco.py

This is a short term mitigation for #95

Convert coco annotations from the list of structs to struct of lists

---

python/benchmarks/parse_coco.py

Make the box format ready for PyTorch training.

Convert coco bounding box format to [x0,y0,x1,y1] format.

---

python/lance/tests/test_types.py
python/lance/types/__init__.py
python/lance/types/base.py
python/lance/types/box.py

Support point2d, box 2d/3d
Also added polygon 2d/3d to support segmentation

Extension type improvements to support 3d types

---

cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/scanner.cc
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h
cpp/src/lance/arrow/utils_test.cc
cpp/src/lance/io/exec/base.cc
cpp/src/lance/io/exec/base.h
cpp/src/lance/io/exec/project.cc
cpp/src/lance/io/exec/project.h
cpp/src/lance/io/exec/take.cc
cpp/src/lance/io/reader.cc
cpp/src/lance/io/record_batch_reader.cc

In the case for `dataset.scanner(columns=["foo"], filters=(col("bar") == 1)`, the result should only have column `foo`.

Exclude filter columns from projection

---

.github/workflows/bump-version.yml

Proposed release process:
1. top of main should be green
2. manually trigger this action
3. make a github "Release" with the tag created from step 2 above
4. GH to release to pypi should automatically trigger
5. GH to create a new patch release (e.g., v0.1 -> v0.2.dev0) should trigger automatically

action to bump version for new release

---

cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/io/exec/base.cc
cpp/src/lance/io/exec/base.h
cpp/src/lance/io/exec/filter.cc
cpp/src/lance/io/exec/project.cc
cpp/src/lance/io/exec/scan.cc
cpp/src/lance/io/exec/take.cc
cpp/src/lance/testing/io.cc
cpp/src/lance/testing/io.h

When the Scan node has a batch size smaller than the actual group size, `Take` needs to re-adjust the indices offset to align with the batch it reads. 
Closes #192

[C++] [BUG] Adjust offset when the batch size is set for reading

---

cpp/CMakeLists.txt
cpp/src/lance/io/exec/base.cc

Fix typo of calculating offsets for slicing index

---

cpp/CMakeLists.txt
python/lance/__init__.py
python/lance/tests/test_types.py
python/lance/types/__init__.py
python/pyproject.toml
python/setup.py
python/tools/delocate-wheel

[Python] Exclude relocating packages in homebrew

---

.github/workflows/make-patch-commit.yml
.github/workflows/pypi-publish.yml
python/setup.py

Once the release is published, automatically build wheels and upload to pypi and also increment version to the next patch.dev0 version.

GH release automation improvement

---

cpp/include/lance/arrow/file_lance.h
cpp/src/lance/arrow/arrow_dataset_test.cc
cpp/src/lance/arrow/file_lance.cc

Implement CountRows for fast path of countings

---

cpp/CMakeLists.txt
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h
cpp/src/lance/cmd/CMakeLists.txt
cpp/src/lance/cmd/lance.cc
cpp/src/lance/encodings/CMakeLists.txt
cpp/src/lance/encodings/encoder.cc
cpp/src/lance/encodings/encoder.h
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc
cpp/src/lance/testing/io.cc

Writing in C++ to reuse lance code

CLI to inspect lance dataset

---

.github/workflows/benchmarks.yml
python/benchmarks/oxford_pet/datagen.py

Fix datagen test

---

cpp/src/lance/encodings/binary.h
cpp/src/lance/encodings/encoder.cc
cpp/src/lance/encodings/encoder.h
cpp/src/lance/encodings/plain.cc

Improve query `SELECT external_image FROM oxford_pet WHERE class = 'pug'` by 6X  (12s -> 2s) on home computer.

Improve VarBinaryDecoder::Take performance by accumulating small batches

---

.gitattributes

I *think* this does what we want based on linguist docs:
https://github.com/github/linguist/blob/master/docs/overrides.md

Exclude jupyter notebook from github language stats

---

integration/duckdb/CMakeLists.txt
integration/duckdb/README.md
integration/duckdb/src/lance/duckdb/list_functions.cc
integration/duckdb/src/lance/duckdb/ml/pytorch.cc

Be able to build duckdb extension with opencv + pytorch on Intel and Apple Silicon Mac. 
Closes #246

[DUCKDB] Fix build on intel and apple silicon Mac

---

cpp/src/lance/encodings/plain.cc
cpp/src/lance/encodings/plain_test.cc
python/lance/pytorch/data.py
python/lance/tests/test_pytorch.py

Closes #240.
Also in the process, fixes a bug that read boolean values from the middle of a byte

Fix read boolean and PyTorch does not return empty array.

---

.github/workflows/cpp.yml

Pin Apache Arrow to 9.x to fix CI breakage.

[CI] pin arrow 9.0 in GHA

---

cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc

Merge two Schemas

---

cpp/CMakeLists.txt
cpp/include/lance/arrow/dataset.h
cpp/include/lance/arrow/file_lance.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_test.cc
cpp/src/lance/format/data_fragment.cc
cpp/src/lance/format/data_fragment.h
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h

Provide `LanceDataset::versions()` and `LanceDataset::latest_version()` methods to fetch available versions.

Fetch Dataset Versions

---

.gitignore
integration/duckdb/CMakeLists.txt
integration/duckdb/Makefile
integration/duckdb/README.md
integration/duckdb/cuda/Dockerfile
integration/duckdb/cuda/README.md
integration/duckdb/cuda/build_lance.sh
integration/duckdb/cuda/docker-compose.yml
integration/duckdb/src/lance/duckdb/ml/catalog.cc
integration/duckdb/src/lance/duckdb/ml/catalog.h
integration/duckdb/src/lance/duckdb/ml/functions.cc
integration/duckdb/src/lance/duckdb/ml/pytorch.cc
integration/duckdb/src/lance/duckdb/ml/pytorch.h
integration/duckdb/tests/conftest.py
integration/duckdb/tests/test_pytorch.py

create_pytorch('name', '/path/to/model.pth', 'cuda')
OR
create_pytorch('name', '/path/to/model.pth', 'cpu')
inputs are automatically moved to corresopnding device

Enable duckdb extension to build/run on CUDA-enabled pytorch

---

cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/dataset.cc
python/lance/__init__.py
python/lance/_lib.pyx
python/lance/tests/test_api.py

Provide `version()`, `versions()`, `latest_version()` methods to Python

[Python] Fetch dataset versions.

---

python/lance/__init__.py
python/lance/_lib.pyx

* To bring more feature parity with `pyarrow.dataset.write_dataset`.
* Fix docstring to make API docs look nicer.

[Python] Support group size and rows_per_file customization via write_dataset API

---

.github/workflows/cpp.yml
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h
cpp/src/lance/arrow/utils_test.cc
cpp/src/lance/io/exec/limit_test.cc
cpp/src/lance/io/exec/project.cc
cpp/src/lance/io/exec/scan.cc
cpp/src/lance/io/exec/scan.h
cpp/src/lance/io/exec/scan_test.cc

As the leaf execution node, allows ScanNode to reads multiple files within the same fragment, thus the DataFragment / schema evolution details are hidden from the rest of the I/O execution stack (other than Take probably.)

[C++] Scan Node reads multiple files

---

.github/workflows/build_mac_wheel/action.yml
python/lance/tests/util/test_duckdb.py
python/lance/tests/util/test_duckdb_ext.py
python/lance/util/duckdb.py
python/lance/util/duckdb_ext.py

It's too complicated to make users go through the installation process themselves. Instead let's create a small python utility function. In a python-centric workflow, this will be the easiest method. Alternatives can also be considered like providing a torch-like website or a command line utility that the user needs to download.

Add lance.util.duckdb to help install the extension transparently

---

cpp/src/lance/arrow/CMakeLists.txt
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/file_lance_ext.h
cpp/src/lance/arrow/fragment.cc
cpp/src/lance/arrow/fragment.h
cpp/src/lance/arrow/fragment_test.cc
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h
cpp/src/lance/io/exec/project.cc
cpp/src/lance/io/exec/project.h
cpp/src/lance/io/exec/project_test.cc
cpp/src/lance/io/exec/scan.cc
cpp/src/lance/io/exec/scan.h
cpp/src/lance/io/exec/take.cc
cpp/src/lance/io/exec/take.h
cpp/src/lance/io/reader.cc
cpp/src/lance/io/reader_test.cc
cpp/src/lance/io/record_batch_reader.cc
cpp/src/lance/io/record_batch_reader.h
cpp/src/lance/io/writer.h
cpp/src/lance/testing/io.cc
cpp/src/lance/testing/io.h

Use `LanceFragment` to build I/O exec plan, so that I/O exec plan can take multiple data files in the same Fragment into account.

[C++] Use LanceFragment to build I/O exec plan

---

docs/requirements.txt
python/notebooks/03_exploratory_data_analysis.ipynb
python/notebooks/quickstart.ipynb
python/setup.py

Requirements to get 0.6 working:
- #312 linux build works fine (had to explicitly add cmath.h)
- #312 osx build still fails: cmake errors complain about not being able to find malloc (which has been deprecated on osx).
- Update the artifacts on s3 (upload.sh)
- Update latest pointer to 0.2

Temporarily pin duckdb to 0.5.1

---

cpp/include/lance/arrow/dataset.h
cpp/include/lance/arrow/updater.h
cpp/src/lance/arrow/CMakeLists.txt
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_ext.h
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/fragment.cc
cpp/src/lance/arrow/fragment.h
cpp/src/lance/arrow/fragment_test.cc
cpp/src/lance/arrow/updater.cc
cpp/src/lance/arrow/updater_test.cc
cpp/src/lance/arrow/writer.cc
cpp/src/lance/encodings/plain.cc
cpp/src/lance/format/data_fragment.cc
cpp/src/lance/format/data_fragment.h
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h
cpp/src/lance/format/page_table.h
cpp/src/lance/io/endian.h
cpp/src/lance/io/exec/project.h
cpp/src/lance/io/exec/scan.cc
cpp/src/lance/io/exec/scan.h
cpp/src/lance/io/reader.cc
cpp/src/lance/io/writer.cc
cpp/src/lance/io/writer.h
cpp/src/lance/testing/io.cc

Minimal support of appending a column in C++ `LanceDataset`

[C++] Append column

---

cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/updater_test.cc
python/lance/_lib.pyx
python/lance/tests/test_schema_evolution.py

Provide equivalent of C++ API (#299) in Python.

[Python] Append columns

---

cpp/include/lance/arrow/dataset.h
cpp/include/lance/arrow/updater.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_test.cc
cpp/src/lance/arrow/updater.cc
cpp/src/lance/arrow/updater_test.cc
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h

Use column projection during update

---

python/lance/_lib.pyx
python/lance/tests/test_schema_evolution.py

Expose column projection when updating/append a column in Python.

[Python] Expose projection for append column

---

python/lance/__init__.py

[Python] lance.write_dataset takes pandas DataFrame

---

python/benchmarks/coco/train.py
python/benchmarks/oxford_pet/embeddings.py
python/benchmarks/oxford_pet/train.py
python/lance/pytorch/__init__.py
python/lance/pytorch/data.py
python/lance/tests/test_pytorch.py
python/notebooks/quickstart.ipynb

* Add `schema()` to Pytorch dataset
* rename `lance.pytorch.LanceDataset` to `lance.pytorch.Dataset`.
* Make `pytorch.Dataset` iterable for multiple times.

[Python] Improve PyTorch dataset ergonomic

---

python/lance/_lib.pyx
python/lance/tests/test_schema_evolution.py

[Python] append column with a in-memory Pyarrow Table

---

cpp/src/lance/arrow/dataset.cc
integration/duckdb/src/lance/duckdb/lance_reader.cc

[DUCKDB] Read a special version of dataset

---

python/lance/__init__.py
python/lance/tests/test_api.py
python/lance/util/__init__.py

Fix `lance.dataset()` to load local dataset without explicit `file://` scheme

[Python] Fix lance.dataset open local related path

---

cpp/CMakeLists.txt
cpp/src/lance/CMakeLists.txt
cpp/src/lance/util/CMakeLists.txt
cpp/src/lance/util/defer.cc
cpp/src/lance/util/defer.h
cpp/src/lance/util/defer_test.cc

Modeled after Golang's [`defer`](https://gobyexample.com/defer) and Google's [`abseil::Cleanup`](https://github.com/abseil/abseil-cpp/blob/master/absl/cleanup/cleanup.h).

[C++] Add RAII util (defer) to auto cleanup / close resources after exiting the scope

---

cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/dataset.cc
python/lance/__init__.py
python/lance/_lib.pyx
python/lance/tests/util/test_versioning.py
python/lance/util/versioning.py

1. Minor bug fixes
2. Add `ds.compute_metric(func)` and `ds.diff(v1, v2)` to dataset interface

Refactor dataset diff and compute metric

---

cpp/src/lance/arrow/dataset_test.cc
cpp/src/lance/format/manifest.cc
cpp/src/lance/io/pb.h

When dictionary array involved, the version aux data offset is usually not zero, because we will write dictionary value array first in the manifest file. The bug was due to the aux data position are not serialized correctly in the code path.

[BUG] Fix reading version aux data reading and writing

---

rust/src/dataset.rs
rust/src/error.rs
rust/src/format.rs
rust/src/format/fragment.rs
rust/src/format/manifest.rs
rust/src/format/metadata.rs
rust/src/io.rs
rust/src/io/object_reader.rs
rust/src/io/object_store.rs
rust/src/io/object_writer.rs
rust/src/io/reader.rs

Provide `read_struct<T: ProtoStruct>(pos)` and `write_struct<T: ProtoStruct>(pos)` .

[Rust] Read/Write Protobuf-backed struct directly from file or buffers.

---

rust/Cargo.toml
rust/benches/distance.rs
rust/src/utils.rs
rust/src/utils/distance.rs
rust/src/utils/testing.rs

Use `std::arch` provided by the stable Rust. We could use `std::simd` when it is ready for stable rust. 
```
RUSTFLAGS="-C target-feature=+avx2,+fma" cargo bench --bench distance
cargo bench --bench distance
```
| CPU  |  Default | Fallback | Naive Arrow Impl (+AVX2) |
|-----|--------|---------|--------------------------|
| AMD 5900X (X86_64) | 204ms | 1070ms | 1457ms |
| Apple M1 |  1267ms (same as fallback) | 1272 ms | 1551ms |
Note that, I did not hand write simd for M1 / Aarch64 yet, `std::arch::aarch64` seems not stable at the moment. Also, no BLAS-based performance is tested so that there is no extra dependency for Lance.

L2 distance

---

rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/format/manifest.rs
rust/src/io.rs
rust/src/io/exec.rs
rust/src/io/exec/scan.rs
rust/src/io/writer.rs

This PR refactors the scanner code out to a `Scan : ExecNode` struct. This is the first step to build the i/o execution path similar to C++.

Make Scan an ExecNode

---

rust/Cargo.toml
rust/src/bin/lq.rs
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/datatypes.rs
rust/src/error.rs
rust/src/index.rs
rust/src/index/vector.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/pq.rs
rust/src/io/object_store.rs
rust/src/io/object_writer.rs

```
Usage: lq index [OPTIONS] <ACTION> <URI>
Arguments:
<ACTION>  Actions on index [possible values: create]
<URI>     Dataset URI
Options:
-c, --column <NAME>          The column to build index on
-n, --name <NAME>            Index name
-t, --type <TYPE>            Set index type [possible values: ivf-pq]
-p, --num-partitions <NUM>   Nunber of IVF partitions. Only useful when the index type is 'ivf-pq' [default: 64]
-s, --num-sub-vectors <NUM>  Number of sub-vectors in Product Quantizer [default: 8]
-h, --help                   Print help
```

Cli to operate on dataset indices

---

rust/src/dataset.rs
rust/src/datatypes.rs
rust/src/encodings/binary.rs
rust/src/encodings/dictionary.rs
rust/src/encodings/plain.rs
rust/src/format/page_table.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs
rust/src/io.rs
rust/src/io/object_reader.rs
rust/src/io/object_store.rs
rust/src/io/object_writer.rs
rust/src/io/reader.rs

This is the prerequisite to provide a better performance local file system reader implementation. 
We will implement a `LocalObjectReader` that holds an open File descriptor, instead open/close a file for every read in `object_store` crate

Replace ObjectReader as a pub trait. 

---

rust/Cargo.toml
rust/benches/scan.rs
rust/src/io.rs
rust/src/io/local.rs
rust/src/io/object_store.rs

Avoid open/close file for each `get_range` call in `object_store` crates.

[Rust] Implement LocalObjectReader that holds an open file to improve performance.

---

rust/pylance/src/dataset.rs
rust/src/dataset.rs
rust/src/dataset/write.rs
rust/src/io/exec/knn.rs
rust/src/io/exec/limit.rs
rust/src/io/object_store.rs

Bring back Append support in schema evolution

[Rust] Minimal dataset append support

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

New arrow deb release breaks the build. 
And make it rust-focused.

Fix codespace prebuild

---

rust/Cargo.toml
rust/src/bin/lq.rs
rust/src/dataset.rs
rust/src/encodings/binary.rs
rust/src/encodings/dictionary.rs
rust/src/encodings/plain.rs
rust/src/io/object_store.rs
rust/src/io/object_writer.rs

Improve user experience: user does not need to specify environment vars to read s3 data correctly.

Load S3 credentials using default credentials chain

---

rust/Cargo.toml
rust/benches/kmeans.rs
rust/src/utils.rs
rust/src/utils/distance.rs
rust/src/utils/kmeans.rs

* Reduce memory copy between using Arrow vs other lib (i.e., ndarray or faiss)
* Pure rust implementation to remove the dependency of C++ libraries (i.e., FAISS)

Implement a kmean optimized for Arrow-backed vectors in pure rust.

---

rust/src/io/exec/scan.rs

Regular table scan go in order. KNN scan can be unordered

[rust] make scanning in order configurable

---

rust/Cargo.toml
rust/src/utils/distance.rs

Because benchmark indicates neon simd is faster to calculate l2 distance.

Remove Mac accelerate code

---

rust/src/dataset.rs

We can find the index in the sorted row IDs by binary search,
to improve reordering performance from $O(n^2)$ to $O(nlogn)$
Signed-off-by: yah01 <yah2er0ne@outlook.com>

Improve `take_rows()` performance by binary search

---

rust/Cargo.toml

DataFusion 18.0 is released and compatible with the rest of our arrow-32.0 usage.

Use the released crate for DataFusion

---

rust/src/dataset.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/pq.rs
rust/src/io/exec/knn.rs
rust/src/utils/distance.rs
rust/src/utils/kmeans.rs

Abstract L2 distance behind a `Distance` trait,  so that we can later use other distance computation method (i.e., cosine distance).

Refactor distance computation to allow pluggable dist function

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/lance/util.py
python/python/tests/test_dataset.py
python/src/dataset.rs

This commit adds an `asof` argument to the Lance dataset reader (per #506). 
Notes
- Python only supports datetime objects with microsecond precision, while Lance stores timestamps correct to nanoseconds. Seems unlikely this will cause issues, until new batches can be commited quicker than 1 us. 
- Added a method `active_version` that returns the currently checked out version of the dataset. It is also useful to sanity check the `asof` logic, which lives in python.

Add an argument to checkout a dataset as of a certain timestamp

---

rust/src/arrow.rs
rust/src/datatypes.rs
rust/src/io/writer.rs

This commit adds the Arrow Duration type per issue #577.

support arrow-rs duration type in lance

---

python/python/lance/dataset.py
python/src/dataset.rs
rust/src/dataset.rs
rust/src/index/vector.rs

Allow user to choose create cosine or l2 index from Python

[Python] Specify metric type in Dataset.create_index

---

rust/src/arrow.rs
rust/src/datafusion.rs
rust/src/datafusion/physical_expr.rs
rust/src/datatypes.rs
rust/src/lib.rs

Implement [Datafusion's Column](https://docs.rs/datafusion/latest/datafusion/physical_plan/expressions/struct.Column.html`) to support nested access.
Part of the work to use Datafusion to implement predicates pushdown.

[Rust] Implement a datafusion phyiscal expr Column that can reads nested columns

---

rust/src/datatypes.rs

Support filter pushdown to find the the remaining projection schema after the filtered fields are read.

Schema exclude fields

---

rust/src/index/vector/ivf.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs

minor interface change to make it work with MatrixView
note @eddyxu this is into your branch not main

make ProductQuantizer::fit_transform work with MatrixView

---

rust/src/utils/kmeans.rs

In case where the kmeans loop does not early stop, `stddev` is not set, thus the best kmean is not assigned to any `kmean` centroids.

[Bug] PQ training generates empty centroids

---

python/python/tests/test_dataset.py
rust/src/dataset.rs

When writing a new dataset with mode set as `append`, it is cast to `create` so it takes the code path for `create`. 
Reference #568

Allow append mode even if dataset doesn't already exist

---

.github/workflows/python.yml
rust/src/bin/lq.rs
rust/src/dataset/scanner.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs

Previously, at the merge sort stage, IVF does not returns k * refine_factor vectors for the Take node to load the original data. This fix makes IVF returns `k * refine_factor` vectors from `IVF::search`

[Bug] Fix IVF merge sort when refine factor is presented.

---

rust/Cargo.toml
rust/src/io/exec/planner.rs

Published a forked version of `sqlparser-lance`, which means that we can use crate version of sqlparser instead of git version as dependency, which prevents `cargo publish`.

[Rust] Use folked sqlparser to unblock rust crate release

---

.github/workflows/build_windows_wheel/action.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/rust.yml
python/python/tests/test_dataset.py
python/python/tests/test_lance.py
python/python/tests/test_vector_index.py
rust/Cargo.toml
rust/src/arrow/linalg.rs
rust/src/error.rs
rust/src/index/vector/opq.rs
rust/src/io/object_store.rs

These changes make lance compile and run on Windows, we are able to start a python REPL and create / read lance files.
Most of the changes are related how the file system interactions work. We support the following formats on Windows
- URIs: `file:///tmp/test.lance`
- slash: `c:/tmp/test.lance`
- backslash: `c:\\tmp\\test.lance`
I uploaded the generated wheel to [test.pypi ](https://test.pypi.org/project/pylance/0.3.19/#files)as was able to install it / run a sample script.
Lapack / svd / opq are not currently supported, see #740

Windows support

---

rust/src/index/vector.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs
rust/src/utils/distance.rs
rust/src/utils/distance/cosine.rs
rust/src/utils/distance/l2.rs
rust/src/utils/kmeans.rs

It eliminates some of the Arrow Array creation, resulted a speed up in vanama graph construction by 2-3x. 
Closes #747

[Rust] make distance function to take slice instead of Float32Array

---

protos/format.proto
protos/index.proto
python/python/tests/test_vector_index.py
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/format/index.rs
rust/src/format/manifest.rs
rust/src/index/vector/flat.rs
rust/src/io/exec/knn.rs

next PR will join flat search for new fragments

Vector search should support appending new rows

---

rust/src/format/metadata.rs
rust/src/io/reader.rs

Use to read a range of rows, without knowing the batch ids.

[Rust] FileReader read range API

---

.github/workflows/run_tests/action.yml
python/pyproject.toml
python/python/lance/dataset.py
python/python/tests/test_dataset.py

Support direct polars scan

---

protos/index.proto
rust/Cargo.toml
rust/src/arrow.rs
rust/src/index/vector.rs
rust/src/index/vector/graph.rs
rust/src/index/vector/graph/builder.rs
rust/src/index/vector/graph/persisted.rs

We are going to use lance to persist a graph, because lance offers good random access already, which is good for graph access.
This PR writes a graph as a two column table:
```
struct<
vertex: FixedSizeBinary(...),
neighbours: list<u32>,
>
```
It requires the vertex struct to be able to serialized to fixed size binary. 
It will be the `GraphBuilder`'s responsibility to re-orgnize the graph vertex in a way that it preserves certain locally.

[Rust] Persist graph using lance file format.

---

rust/src/arrow/kernels.rs
rust/src/arrow/linalg.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs

* Consolidate centorids computation to MatirxView, for later optimization
* Change `MatrixView::row()` to return `&[f32]` slice for better code and performance (by avoiding more memory allocation to create `Float32Array`)

Matrix::centroids method

---

python/pyproject.toml

Python tests failed on `<=0.16.9`:
```
>       polars_df = pl.scan_pyarrow_dataset(dataset)
E       AttributeError: module 'polars' has no attribute 'scan_pyarrow_dataset'
```

[Python] Set minimal version of Polars for python tests

---

python/src/reader.rs
rust/src/dataset/scanner.rs
rust/src/io.rs
rust/src/io/exec/knn.rs
rust/src/io/stream.rs

Refactor to extract `RecordBatchStream`. There will be two implementation, one is `DatasetRecordBatchStream` (already implemented), and `FragmentRecordBatchStream` (to support #557).

[Rust] Refactor RecordBatchStream trait

---

rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/scanner.rs
rust/src/index/vector/graph/persisted.rs
rust/src/io/reader.rs

a `FileFragment` struct modeled after [`pyarrow.dataset.Fragment`](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Fragment.html)

[Rust] Expose DataFragment as pubilc dataset api.

---

.github/workflows/pypi-publish.yml
benchmarks/tpch/README.md
benchmarks/tpch/benchmark.py

Compare lance vs parquet for TPCH Q1 and Q6 using SF1 dataset
**Steps to run the benchmark:**
1. `cd lance/benchmarks/tpch`
2. `mkdir dataset && cd dataset`
3. download parquet file lineitem from : "https://github.com/cwida/duckdb-data/releases/download/v1.0/lineitemsf1.snappy.parquet"; then rename it to "lineitem_sf1.parquet"
4. generate lance file from the parquet file in the same directory
5. `cd ..`
6. `python3 benchmark.py q1`

add python script to compare lance performance vs parquet TPCH

---

python/src/reader.rs
rust/src/io/object_store.rs

passing in the credentials directly does not work if you're in EC2 with IAM role configured. Instead we use `from_env` and let it pick up from the environment. 
closes #692

Get S3 credentials from_env

---

rust/src/arrow/kernels.rs

Add a `hash(arr: &dyn Array)` kernel to compute hash value returned from `std::hash::Hash`

[Rust] A arrow kernel to compute hash value of the array.

---

rust/Cargo.toml
rust/src/utils/distance/l2.rs

Allow SIMD L2 code running on not cache-line aligned and odd dimensions, which fall back to non-SIMD one transparently.

[Rust] L2 distance on not aligned data

---

python/python/tests/test_vector_index.py

possibly don't need to skip anything

Speed up vector index tests by reducing dataset size

---

rust/.cargo/config.toml
rust/Cargo.toml
rust/benches/l2.rs
rust/src/linalg/l2.rs

* Set default CPU target to haswell to enable AVX2 routine. Haswell is the oldest CPU still available on AWS and GCP now.  One generation newer (Broadwell) does not bring statistically significant improvement in our benchmarks.
* Fixed `pprof` build on Linux.
* Update the benchmark to reduce the calls to `Float32Array::values()` to make the comparision fair.

[Rust] Minor SIMD benchmark fix set minimal CPU target for AVX2

---

rust/src/encodings/plain.rs
rust/src/io/exec/projection.rs
rust/src/io/exec/take.rs

This happens when there was a row group that is larger than 4GB. Plain decoder calculating the chunked offsets using `u32` which causes overflow.

Fix offset overflow in plain decoder

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/lance/vector.py
python/python/tests/test_dataset.py
python/python/tests/test_lance.py
rust/src/index/vector/pq.rs
rust/src/linalg.rs
rust/src/linalg/cosine.rs
rust/src/linalg/norm_l2.rs

also a bunch of formatting fixes

Fix cosine similarity when missing simd alignment

---

rust/Cargo.toml

This closes https://github.com/eto-ai/lance/issues/806

add support for aws profile

---

python/Cargo.toml
rust/Cargo.toml
rust/src/arrow.rs
rust/src/arrow/linalg.rs
rust/src/arrow/schema.rs
rust/src/datafusion/physical_expr.rs
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/datatypes.rs
rust/src/encodings/binary.rs
rust/src/encodings/plain.rs
rust/src/format/fragment.rs
rust/src/index/vector/diskann.rs
rust/src/index/vector/diskann/builder.rs
rust/src/index/vector/graph/persisted.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs
rust/src/io/exec/knn.rs
rust/src/io/exec/planner.rs
rust/src/io/exec/scan.rs
rust/src/io/reader.rs
rust/src/io/writer.rs
rust/src/utils/kmeans.rs

Can't go to 38 yet even though it's out. Datafusion is on 37 latest.
We need 37 for Will's fix for handling schema metadata.

Upgrade Arrow to 37

---

rust/src/dataset.rs
rust/src/datatypes/field.rs
rust/src/datatypes/schema.rs

This makes it indistinguishable from nested fields and causes all sorts of problems. For now we just disallow them.

Add a check to make sure field names don't contain periods

---

rust/src/dataset.rs
rust/src/encodings/plain.rs
rust/src/index/vector/graph/persisted.rs
rust/src/io/reader.rs
rust/src/io/writer.rs

Remove lifetime from `FileWriter`, because the `pyo3` can not hold a struct with lifetime

Do not use lifetime on FileWriter

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/fragment.rs
python/src/lib.rs
python/src/updater.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/updater.rs
rust/src/encodings/plain.rs
rust/src/index/vector/graph/persisted.rs
rust/src/io/reader.rs
rust/src/io/writer.rs

It allows user to distributedly create `Fragments` first, and then commit a Dataset later.

Allow create fragment on non-existed dataset.

---

rust/src/encodings/plain.rs
rust/src/index/vector/pq.rs

Minor performance improvement.

[Rust] increase parallelism, reduce array build overhead

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/src/dataset.rs
rust/src/dataset.rs
rust/src/encodings/plain.rs
rust/src/index/vector.rs
rust/src/io/local.rs
rust/src/io/object_reader.rs
rust/src/io/object_store.rs
rust/src/io/reader.rs

Change API to `lance.dataset(uri, version, asof, block_size=None)`.

Allow user to customize BlockSize on ObjectStore.

---

rust/src/dataset/scanner.rs
rust/src/io/exec/projection.rs
rust/src/io/exec/take.rs

This is on top of #836 , just split out for easier review.
Basically in the Take node, we do a.merge(b) for schema but b.merge(a) for RecordBatch.
So then in Projection, we get a schema that has struct_field with subfields f1 and f2, but the data has struct_field with subfields f2 and f1.

Fix nested field filtering

---

rust/src/arrow.rs
rust/src/dataset/scanner.rs

Previously we didn't check the leaf nodes inside the struct fields in a projection which causes problems. when filtering / selecting from nested struct fields

Fix Projection for struct fields

---

rust/src/encodings/binary.rs

[Bug] Calculating the nulls from position slices in chunks.

---

rust/src/datatypes/field.rs

Previously we didn't project null struct fields

Fix projection for null struct fields

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/io/exec/scan.rs

* Also added type hints to `Dataset::to_batches()` .

Expose batch_readahead via Python scanner API

---

.gitignore
python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/fragment.rs
python/src/scanner.rs
rust/src/dataset/scanner.rs

Initial implementation of `LanceScanner.from_fragments()` for Python. Supports `Iterable[LanceFragment]` at the interface, but leaves actually using an iterator as a TODO.
Closes #860.

GH-860:  Create a scanner from fragments

---

rust/src/format/fragment.rs
rust/src/format/manifest.rs
rust/src/io/reader.rs

fix: fetch remainder of metadata if it is large

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/scanner.rs
rust/src/io/exec/scan.rs
rust/src/io/exec/take.rs

wip: allow scanning data in out of order

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/fragment.rs
python/src/scanner.rs
rust/src/dataset/fragment.rs
rust/src/dataset/scanner.rs

To support setting other scanner options along with the fragments, add `fragments` as an argument in the scanner itself.

feat: add fragments option to the scanner itself

---

rust/Cargo.toml

future 0.3.27 added `TryFlattenUnordered`, which we use now.
https://github.com/rust-lang/futures-rs/blob/master/CHANGELOG.md#0327---2023-03-11

fix: update minimal futures version

---

benchmarks/sift/index.py

* And track the benchmark results

Customize index type in index creation benchmark

---

.github/workflows/cargo-publish.yml

runs the equivalent of `cargo publish --all-features`

Github workflow to run cargo publish on release

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/fragment.rs
rust/src/bin/lq.rs
rust/src/dataset/scanner.rs

feat: allow setting offset without limit

---

rust/Cargo.toml
rust/src/datafusion/logical_expr.rs
rust/src/dataset/scanner.rs
rust/src/io/exec/planner.rs

closes #896
NOTE: if the column is `LargeUtf8` query currently panics. We need to do at least one of:
* Support `arrow_cast` in filter -- which might be hard I couldn't find a builtin function for this
* Support implicit conversion of `pattern` argument from `Utf8` to `LargeUtf8`
* make `parse_function` understand `regexp_match`
* add a coercing mechanism in `parse_filter`, where we convert non-boolean types to boolean implicitly -- `coerce_filter_type_to_boolean`
* add function dispatch in `create_physical_expr`
TODO:

allow filter with regex expression on columns

---

.github/workflows/rust.yml

windows build started to fail after #899 
error:
```
windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
= note: D:\a\lance\lance\rust\target\debug\deps\lance-f6d472ae34a42458.exe : fatal error LNK1180: insufficient disk space to complete link
```
bumping the action storage space to fix

bump windows-build storage to 1gb

---

rust/src/index/vector/diskann/search.rs
rust/src/io/object_store.rs

To support scan directory on local and cloud storage.

[Rust] ObjectStore::read_dir method

---

python/python/lance/dataset.py
python/python/lance/fragment.py

This avoids confusing errors like 
```
AttributeError: 'XXX' object has no attribute '_export_to_c'
```
We can also address this upstream in https://github.com/apache/arrow-rs/issues/4312

feat: typecheck arrow objects before sending to Rust

---

python/pyproject.toml

user wants to install lancedb in an environment with pandas 1.4 and cannot upgrade. This causes version incompatibility issues.

relax minimum pandas version to 1.4

---

rust/Cargo.toml
rust/benches/argmin.rs
rust/src/utils/testing.rs

partially addresses #762
I'm adding `argmin` first because it's a major hotspot when constructing index. See attached perf report.
I extracted `create_file` function from `vector_index` bench, ran it in a binary, and recorded with perf. The result shows that we spend 17% of the time in `argmin` function.
The total time of the program is 14s + some change. It took 1+ second alone to generate and write the data to disk before index begone. Discounting the data generation overhead, we can safely say that `argmin` is about 20% of the time spent when build an index.
I will follow up with AVX and Neon implementation of `argmin`.

argmin benchmark

---

protos/format.proto
rust/Cargo.toml
rust/src/error.rs
rust/src/format/fragment.rs
rust/src/io.rs
rust/src/io/deletion.rs

WIP: add deletion files to Lance format 

---

python/python/lance/dataset.py
python/src/dataset.rs
rust/benches/vector_index.rs
rust/src/bin/lq.rs
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/index.rs
rust/src/index/vector/diskann.rs
rust/src/index/vector/opq.rs

Closes https://github.com/lancedb/lancedb/issues/100

[Rust] Allow recreate index with the same name on the same column

---

rust/Cargo.toml
rust/benches/argmin.rs
rust/benches/cosine.rs
rust/src/linalg/cosine.rs

similar to #937 this one optimizes cosine distance.
before
```
[300.01 ms 302.41 ms 305.41 ms] Cosine(simd)
[302.51 ms 306.08 ms 311.26 ms] Cosine(simd) second rng seed
```
after
```
[86.878 ms 87.004 ms 87.263 ms] Cosine(simd)
[87.301 ms 102.65 ms 131.89 ms] Cosine(simd) second rng seed
```
Will add AVX unroll later today

add a benchmark for cosine distance and unroll ARM Neon simd

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/Cargo.toml
rust/src/arrow/record_batch.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/hash_join.rs
rust/src/dataset/hash_joiner.rs
rust/src/datatypes.rs
rust/src/error.rs
rust/src/format/manifest.rs
rust/src/lib.rs

Merge a pre-computed column / array.

---

rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/error.rs
rust/src/format/manifest.rs
rust/src/io/deletion.rs

Closes #915.
Adds `delete()` methods to both `Dataset` and `FileFragment`.

Write path for deletion files

---

rust/src/format/fragment.rs
rust/src/io/deletion.rs
rust/src/io/reader.rs

NOTE: Only supports `Scan` right now. Still need to add support for index scans.
TODOs:

add deletion file handling to scanner

---

docs/read_and_write.rst
python/python/tests/test_filter.py
rust/src/io/exec/planner.rs

Fixed #956. Allows casting, but also "typed literals" where you just put the type you want in front of the string.

Add basic support for cast in expressions

---

rust/src/index/vector.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs

Allow create IVF_PQ index with pre-populated kmean centroids.

[Rust] Allow to provide pre-existing IVF_PQ centroids during index creation

---

rust/src/format/fragment.rs
rust/src/io/reader.rs

remove deletion_vector method and handle Result from reading deletion file properly

---

rust/src/dataset/scanner.rs
rust/src/index/vector.rs
rust/src/index/vector/diskann/search.rs
rust/src/index/vector/pq.rs
rust/src/io/deletion.rs
rust/src/session.rs

closes #916
Implement deletion vector handling in `PQIndex`, where all vector index are stored.
TODO:

implement deletion vector handling in index scan

---

rust/src/encodings/binary.rs

fix #739 
Currently, when get data from cloud storage, the input range is specified as a half-open interval (left-closed and right-open). 
However, in actual HTTP requests, the range is interpreted as a closed interval(the byte positions specified are inclusive). This means that when the range size is 0, the generated HTTP request range can result in the end being smaller than the start, leading to an HTTP error code of [416](https://httpwg.org/specs/rfc7233.html#status.416) ("Range Not Satisfiable").
```
"api":{"name":"GetObject","bucket":"xxx","object":"xxx","status":"Requested Range Not Satisfiable","statusCode":416,...},
"requestHeader":{"Accept":"*/*","Range":"bytes=308827096-308827095","User-Agent":"object_store/0.5.6", ...}
```
To fix this, add a check before calling get_range to …

fix s3 get_range issues: 416, range not satisfiable

---

python/python/tests/test_vector_index.py
rust/src/dataset/scanner.rs
rust/src/io/exec/knn.rs

When we have an index and some unindexed data, we read from both and use a union node to combine the results. However, at the end of the plan, we only read from the first partition. This meant we only ever would read from the flat scan, and not from the index scan.
The test cases have been adjusted so that we try to retrieve more vector results than there was added data, so we can confirm that we are actually getting results from both parts.
I also enforce with an assertion that we only use 1 partition in the final plan. In the future, we might consider splitting things out into multiple partitions, once we have a better understanding of the performance impact in DataFusion.

fix: make sure we are always running with a single partition

---

protos/format.proto
rust/src/dataset.rs
rust/src/dataset/feature_flags.rs
rust/src/error.rs
rust/src/format/manifest.rs
rust/src/index.rs

As we add new features, we need to be sure our readers and writers aren't trying to access data they don't know how to interpret. This PRs adds feature flags to so they can detect if a table uses features it doesn't know about.
This is preferable to versions because:
1. It makes it easy to granularly see what features are unsupported
2. In a future where there are independent readers / writers, they don't have to implement features in a linear order.
Closes #973

feat: add feature flags to the dataset manifest

---

python/Cargo.toml
rust/Cargo.toml
rust/src/arrow.rs
rust/src/arrow/linalg/matrix.rs
rust/src/datafusion/logical_expr.rs
rust/src/datafusion/physical_expr.rs
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/encodings/dictionary.rs
rust/src/encodings/plain.rs
rust/src/index/vector/ivf.rs
rust/src/io/exec/planner.rs
rust/src/io/reader.rs
rust/src/io/writer.rs

update to arrow 40 and datafusion 26
arrow changes are a bunch of constructor, e.g. we now pass `Arc` instead of `&` for ArrayField.

upgrade to arrow 40 and datafusion 26

---

rust/src/arrow/kernels.rs
rust/src/index/vector/ivf.rs

Currently, we panic if NaN is found in the array argmin or argmax operate on.
Example where we can hit this:
```python
import lance
import pyarrow.compute as pc
import shutil
dims = 375
nrows = 18836
inner_vector = pc.cast(pa.array([0] * (nrows * dims)), pa.float32())
vector = pa.FixedSizeListArray.from_arrays(inner_vector, dims)
table = pa.Table.from_arrays([vector], ["vector"])
shutil.rmtree("test", ignore_errors=True)
dataset = lance.write_dataset(table, "test")
dataset.create_index(
"vector",
index_type="IVF_PQ",
metric="cosine",
num_partitions=4,
num_sub_vectors=125,
)
```

feat: handle NaN values in argmin

---

python/src/dataset.rs
rust/src/dataset.rs
rust/src/io/object_store.rs

We need a way to inject a customized `object_store::ObjectStore` into `lance::io::object_store::ObjectStore`.
We could go full java-style dependency injection and take a pre-constructed `object_store::ObjectStore`. But that seems to be way too big of a refactor. The refactor would probably break the assumptions built into `base_path` easily. This PR add a way to hook into `lance::io::object_store::ObjectStore` construction and allow callers to wrap the inner `object_store::ObjectStore` with custom logic.
* added a `WrappingObjectStore` trait which is a hook called after we construct `object_store::ObjectStore` from the uri provided.
* added `ObjectStoreParams` and `from_uri_and_params`

allow object store wrapper as part of dataset construction param

---

.github/workflows/rust.yml

split clippy to a separate workflow, disable incremental build for CI

---

rust/src/io/object_store.rs

We are hammering EC2/ECS metadata services over and over because we are calling the metadata service we to get creds on each request to AWS. The metadata service is returning 429 as we are making too many requests.
Caching AWS creds is a common practice to avoid throttles. 
TODO:

cache aws credentials until 30s before expiry

---

docs/read_and_write.rst
integration/duckdb_lance/Cargo.toml
python/python/lance/dataset.py
python/python/tests/test_dataset.py

Implement writing dataset with `Iterator[RecordBatch]`, like mentioned in the docs. This requires an argument of schema, so we throw a ValueError if it doesn't exist.
Minor ugliness: I check for `Iterator` type, not `Iterator[RecordBatch]`. Let me know if this causes some concerns.
Closes #1019

fix record batch writing to dataset

---

python/Cargo.toml
python/src/dataset.rs
python/src/fragment.rs
python/src/scanner.rs
python/src/updater.rs
rust/Cargo.toml
rust/README.md
rust/benches/ivf_pq.rs
rust/benches/scan.rs
rust/benches/vector_index.rs
rust/src/arrow.rs
rust/src/datafusion/physical_expr.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/hash_joiner.rs
rust/src/dataset/scanner.rs
rust/src/encodings/plain.rs
rust/src/index.rs
rust/src/index/vector/diskann.rs
rust/src/index/vector/diskann/builder.rs
rust/src/index/vector/graph/persisted.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs
rust/src/io/exec/knn.rs
rust/src/io/exec/take.rs
rust/src/io/reader.rs
rust/src/io/writer.rs

This PR upgrades Arrow and DataFusion.
It changes the signature of writing methods so that:
1. It takes owned boxes of RecordBatchReader instead of mutable reference. I think this makes more sense given readers are one-shot.
2. It adds a `Send` bound to the input reader argument. This makes the full method Send allowing write tasks to be sent to other threads.
fixes #1031

feat: upgrade arrow, make write Send

---

.github/workflows/rust.yml

goal: not to hit those pesky SIGILL CI failures

use a large runner for linux tests

---

rust/.vscode/settings.json
rust/Cargo.toml
rust/src/arrow.rs
rust/src/arrow/json.rs

Implement Round trip of json / arrow schema conversion. 
Use this as source of truth between rust/javascript/python.

[Rust] Convert between json / arrow schema

---

.github/workflows/run_tests/action.yml
docs/arrays.rst
docs/index.rst
python/Cargo.toml
python/pyproject.toml
python/python/lance/arrow.py
python/python/tests/test_arrow.py
python/python/tests/test_lance.py
python/src/arrow.rs
python/src/lib.rs
rust/Cargo.toml
rust/src/arrow.rs
rust/src/arrow/bfloat16.rs
rust/src/datatypes/field.rs

Add bfloat16 extension array

---

python/python/lance/dataset.py

Noticed there was a bunch of warnings when building the docs. This eliminates most of them, and make the formatting a bit nicer.

docs: reduce docs warnings

---

.github/workflows/benchmarks.yml
python/python/lance/util.py

1. stop the benchmarks action from running on every PR
2. the `ts_types` was reversed

fix bug in pandas check

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs

To allow scanner to customize `batch_size`.

[Python] Set batch_size in Dataset::scanner()

---

python/python/tests/test_lance.py
python/python/tests/test_vector_index.py
rust/src/dataset/scanner.rs
rust/src/index/vector.rs
rust/src/index/vector/diskann/search.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs
rust/src/index/vector/traits.rs
rust/src/io/exec/knn.rs
rust/src/linalg/l2.rs

Rename "score" to "_distance" 

---

rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/scanner.rs
rust/src/index.rs
rust/src/index/prefilter.rs
rust/src/index/vector.rs
rust/src/index/vector/diskann/search.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs
rust/src/index/vector/traits.rs
rust/src/io/deletion.rs
rust/src/io/exec/knn.rs
rust/src/io/exec/take.rs
rust/src/io/reader.rs
rust/src/session.rs

Closes #1112
Fixes several bugs related to deletions in take and vector search. This includes:
* `Fragment.take()` previously would return fewer rows than requested if there are deleted rows. Now the method will map the indices to valid row ids (skipping deleted rows), and will always return exactly the number of rows requested. The docs are also updated to describe this desired behavior so we can avoid the confusion in the future.
* `Dataset.take_rows()` now works even if there are deletions. Previously it was built assuming that running `take()` (now `take_rows()`) on a fragment would return exactly the number of rows requested, which isn't guaranteed if there are deletions. `take_rows()` has been modified to return `_rowid` so we can reconstruct the requested order in …

fix: take and search now work properly with deletions

---

.github/workflows/make-release-commit.yml

Pushing a new tag isn't useful if it doesn't contain the changes we want.

ci: fix the release commit script

---

rust/src/linalg/cosine.rs
rust/src/linalg/dot.rs
rust/src/linalg/l2.rs
rust/src/linalg/norm_l2.rs

Implement L2 normalization for f16/bf16/f64. No SIMD yet. 
Aarch64 neon instructions do not have f16/bf16 instructions.

Implement L2/norm/cosine/dot for bf16/f16/f64

---

python/Cargo.toml
rust/Cargo.toml
rust/src/io/exec/knn.rs
rust/src/io/exec/planner.rs
rust/src/io/exec/projection.rs
rust/src/io/exec/scan.rs
rust/src/io/exec/take.rs
rust/src/io/exec/testing.rs

Datafusion added a new `DisplayAs` trait (with method `fmt_as` that can be parameterized by a `verbose`/`default` style) which is inherited by `ExecutionPlan` and thus must be implemented on all our custom nodes.  Currently, I am just defaulting to existing `fmt` implementation regardless of the requested style (this seems to be the pattern used in most datafusion nodes as well).
Datafusion added a new parameter to the `like` function for `case_insensitive` which maps, in SQL, to `LIKE` vs. `ILIKE`.

feat: upgrade to datafusion 28.0.0 and arrow 43.0

---

rust/Cargo.toml
rust/src/index/cache.rs
rust/src/session.rs

Closes #1130 
Moka cache should be more performant when accessed from multiple threads concurrently.

feat: switch session caches to use moka cache instead of LruCache

---

rust/src/dataset.rs

Previously if caller tried to insert with custom credentials, it would fail because we didn't propagate credential when opening the dataset.

propagate credential when opening dataset for write

---

rust/src/io/object_store.rs

previously we could only set aws region via env var and IMDS, this PR opens up configuration during construction

expose aws region configurability

---

python/python/lance/fragment.py
python/python/lance/progress.py
python/python/tests/test_fragment.py
python/src/fragment.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/progress.rs
rust/src/dataset/write.rs
rust/src/io/object_store.rs
rust/src/io/object_writer.rs
rust/src/io/writer.rs

This is used for case where there is no coordination between distributed writers. It keeps track the start / finish / incomplete of each fragment writes, in case of the writer crashes in the middle.

Track writing fragment progress

---

rust/src/linalg/dot.rs

To make the sorting of dot distance mathematically correct. The bigger the dot product is, the closer two vectors are.

[Rust] Compute dot distance as negative dot product

---

.github/workflows/rust.yml
rust/benches/argmin.rs
rust/benches/cosine.rs
rust/benches/dot.rs
rust/benches/ivf_pq.rs
rust/benches/kmeans.rs
rust/benches/l2.rs
rust/benches/scan.rs
rust/src/dataset.rs
rust/src/index.rs
rust/src/index/vector/diskann.rs
rust/src/index/vector/diskann/builder.rs
rust/src/index/vector/graph/persisted.rs
rust/src/index/vector/ivf.rs
rust/src/io/commit.rs
rust/src/io/exec/knn.rs
rust/src/utils.rs
rust/src/utils/datagen.rs
rust/src/utils/testing.rs

- Move `generate_random_array` and `generate_random_array_with_seed` to datagen.rs
- Limit utils::testing to cfg[test] but include utils::datagen without the `#cfg[test]` predicate
- Add a CI step to build the benchmark code (without running them).
- Changed references from utils::testing::generate_random_array* to utils::datagen::generate_random_array* in a bunch of places.

[bench] Fix up rust benchmarks

---

python/pyproject.toml
rust/src/dataset.rs
rust/src/io/commit.rs

part of #1183
This PR adds `get_latest_version` to `CommitHandler` and use the commit handler to resolve latest version in `Dataset::open`

use commit handler to find the latest version of a dataset

---

protos/format.proto
python/python/tests/test_lance.py
rust/src/datatypes/field.rs

Previously we had just extracted the extension name from the field and discarded the rest of the metadata.  Unfortunately, these fields are used to parameterize extension types.  For example:
```
// A fixed shape tensor extension type for tensors with shape (2, 3)
metadata: {
"ARROW:extension:name": "arrow.fixed_shape_tensor",
"ARROW:extension:metadata": "{\"shape\":[2,3]}",
},
```
This PR keeps all of the metadata information.  This also allows for a lossless transformation when users have their own custom field metadata.

feat: add support for field metdata

---

python/Cargo.toml
python/python/lance/lance.pyi
python/python/lance/tf/tfrecord.py
python/python/tests/test_tf.py
python/src/executor.rs
python/src/lib.rs
rust/Cargo.toml
rust/src/io/object_store.rs
rust/src/utils.rs
rust/src/utils/tfrecord.rs

Adds utility functions for reading TFRecords files:
```python
def infer_tfrecord_schema(
uri: str, 
tensor_features: Optional[List[str]],
string_features: Optional[List[str]]
) -> pa.Schema:
"""Infer the schema for a TFRecord dataset"""
...
def read_tfrecord(uri: str, schema: pa.Schema) -> pa.RecordBatchReader:
"""
Read a TFRecord file as a stream of record batches. This can be fed directly
into lance.write_dataset().
"""
...
```
Closes: #1165

feat: parse TFRecords as Arrow data

---

python/python/lance/cleanup.py
python/python/lance/fragment.py
python/python/lance/progress.py
python/python/tests/test_fragment.py
python/src/dataset.rs
python/src/fragment.rs
python/src/lib.rs
rust/src/dataset/cleanup.rs
rust/src/io/object_store.rs

In #1146 we added a way to detect partial writes but no way to clean them up. This PR exposes a function that can be used to perform cleanup.
Also there were several bugs in #1146, so this PR also fixes those.

feat: add function to cleanup partial writes

---

rust/src/utils/tfrecord.rs

I haven't been able to repro this in the tests, but on some private sample data this fixes an error. The other fields are named "item" and marked as nullable, so it's possible to get a schema mismatch currently.

fix: make field name consistent

---

rust/src/dataset.rs
rust/src/dataset/cleanup.rs
rust/src/io/object_store.rs

This is just a small nit I came across while working on #1091 and I figured it would be easier to put these changes in their own PR.

refactor: pass params by reference in from_uri_and_params method

---

.github/workflows/rust.yml
rust/src/dataset/cleanup.rs
rust/src/format/manifest.rs
rust/src/utils/temporal.rs

#1176 added this.
Caused failure: https://github.com/lancedb/lance/actions/runs/6043004588

fix rust ci

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/scanner.rs
rust/src/dataset/scanner.rs

Adds a `count_rows` method to the scanner which will take any existing scanner filter into account.
Closes #841

feat: add count_rows to scanner

---

python/src/dataset.rs
rust/src/dataset.rs
rust/src/dataset/cleanup.rs
rust/src/dataset/transaction.rs
rust/src/io/commit.rs
rust/src/io/object_store.rs

This PR moves two hard coded functions `manifest_path` and `latest_manifest_path` into `CommitHandler` trait.
`CommitHandler` is now where we define logic for "here is a uri to a dataset, I want to get a version/put a version"
In #1190 a major problem I ran into is the tight coupling of logic for determining where a manifest is. We used to use `manifest_path` and `latest_manifest_path` in many places of the code base. However, hardcoded function makes customizing manifest commit logic tricky as we frequently would need to change all callsites. With this PR, we can customize manifest path resolving logic with IoC, where we can change the behavior by "injecting" a new `CommitHandler` implementation.

move manifest path logic into commit handler

---

rust/src/io/commit.rs
rust/src/io/commit/external_manifest.rs

part of #1183 <-- detailed design is here too
This PR implements
* `trait ExternalManifestStore` which abstracts an KV-like store with `put_if_not_exists` capability
* `ExternalManifestCommitHandler` which takes a trait object of `ExternalManifestStore` and handles concurrent write to lance dataset using this `dyn ExternalManifestStore`
TODO:

implement ExternalManifestCommitHandler and trait ExternalManifestStore

---

python/python/tests/test_dataset.py
rust/src/io/commit/external_manifest.rs

two tests are a little flaky
https://github.com/lancedb/lance/actions/runs/6053727633/job/16429797785 <-- rust `test_concurrent_commits_are_okay`
https://github.com/lancedb/lance/actions/runs/6052938492/job/16427381322 <-- python `test_asof_checkout`
I disabled `test_concurrent_commits_are_okay` for window because we won't use an external store on a local file system outside of test. It is okay to ignore window.

fix window test and sleep longer on asof test

---

.github/workflows/rust.yml
rust/.vscode/settings.json
rust/Cargo.toml
rust/src/io/commit.rs
rust/src/io/commit/dynamodb.rs
rust/src/io/commit/external_manifest.rs

part of #1183
This PR implements a DynamoDB backed `ExternalManifestStore`.
TODO

implement dynamodb external manifest store

---

rust/src/encodings/binary.rs
rust/src/encodings/plain.rs
rust/src/io/local.rs

When reading primitive and binary data, we are copying data. We can skip the copies if the buffer is already correctly aligned.
Also, for local filesystem we are spending a lot of time zeroing memory that we immediately write into. This PR change to just initialize without zeroing and write into the data. A check is added to make sure that we don't expose any uninitialized data in the output buffer.

perf: reduce copies and skip zeroing memory we read into

---

.github/workflows/python.yml
.github/workflows/run_integtests/action.yml
python/Cargo.toml
python/python/tests/conftest.py
python/python/tests/test_s3_ddb.py
rust/src/io/commit/dynamodb.rs
rust/src/io/object_store.rs

last functional piece for #1183 
This PR adds parsing for `s3+ddb://` scheme to uri parsing when opening a lance dataset
This PR also sets up AWS integration testing by using `minio` for s3 mocking and `dynamodb-local` for dynamodb mocking

add parsing in object store for s3+ddb scheme

---

docs/format.rst

* The images was mistakenly referenced with `.png`. This is fixed
* Fix a type that didn't include the close brace in monospace

fix images references in documents

---

rust/src/dataset/scanner.rs
rust/src/index/prefilter.rs
rust/src/index/vector/pq.rs

This restores the performance of the pq benchmark.  It does not truly fix the underlying problem yet since one would still get poor performance if there are missing fragments / rows.

feat: add a fast path for pq index if there are no missing fragments/rows

---

.github/workflows/bump-version/action.yml
python/Cargo.toml
python/pyproject.toml
rust/lance/Cargo.toml

Use `cargo-workspaces` to bump workspace version together.

[Rust] Bump workspace version

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/python/tests/test_fragment.py
python/src/dataset.rs
python/src/lib.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs

Previously the commit function did not use the new transactions feature.  This meant that a commit running concurrently with another operation could lead to bad behavior.  The commit operation was also limited mostly to overwrites.
Now commits can apply any kind of transaction operation.

feat: update the commit function to work with transactions

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs

* Create vector index over `pyarrow.FixedShapeTensorType`
* `Dataset::take(indices, column)` to allow projection over Dataset::take() operation.

[Python] Support creating index over tensor type and allow Dataset::take() with projection

---

.github/workflows/python.yml
.github/workflows/run_integtests/action.yml
.github/workflows/run_tests/action.yml
python/Makefile
python/README.md

move python test entrypoint to makefile so we can manage pytest marks easily.

move python test entrypoint to makefile

---

docs/conf.py
docs/read_and_write.rst
protos/transaction.proto
python/Cargo.toml
python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/lance/lance.pyi
python/python/lance/optimize.py
python/python/lance/optimize.pyi
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/dataset/optimize.rs
python/src/lib.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/format/fragment.rs

feat: add file compaction

---

python/python/lance/dataset.py
python/src/scanner.rs
rust/lance/src/dataset/scanner.rs

This PR add `explain_plan` to the scanner and exposes the API to python. This is handy to get a visual understanding of what's going on in the query. e.g.
```
In [8]: plan = ds.scanner(nearest={
...:                     "column": "vector",
...:                     "k": 10,
...:                     "q": [0.0 for _ in range(128)],
...:                     "use_index": True,
...:                     "metric": "L2",
...:                     "nprobes": 10,
...:                 }).explain_plan(False)
In [9]: print(plan)
Projection: fields=[id, vector, _distance]
Take: columns="_distance, _rowid, vector, id"
Take: columns="_distance, _rowid, vector"
KNNIndex: name=6b86192c-699f-405e-9e72-d2d84a84da84, k=10
```
^^^ Two take nodes could be merged into one

feat: expose query plan as a debug string

---

.github/workflows/pr-title.yml

When we squash merge PRs from Github it will use the PR title and the description as the commit comment.  This adds a job that checks these fields are correctly formatted according to the conventional commits specification.

chore: add pr title check

---

python/.cargo/config.toml
python/python/benchmarks/test_kmeans.py

This PR adds `target-cpu` profile to `python` folder. This should help with kmeans performance by targeting newers hardware.
Standard release build (before this PR)
```
-------------------------------------- benchmark 'kmeans': 1 tests --------------------------------------
Name (time in s)        Min     Max    Mean  StdDev  Median     IQR  Outliers     OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------
test_kmeans          1.7364  2.1359  1.9208  0.1639  1.8873  0.2711       2;0  0.5206       5           1
---------------------------------------------------------------------------------------------------------
```
Haswell w/ fat LTO
```
------------------------------------------- benchmark 'kmeans': 1 tests …
```

feat: add target cpu to python dir

---

rust/Cargo.toml
rust/lance-linalg/Cargo.toml
rust/lance-testing/Cargo.toml
rust/lance/Cargo.toml

Example dry run here: https://github.com/lancedb/lance/actions/runs/6188966323/job/16802039317?pr=1280
This PR fixes versions in our cargo config so we can release.

fix: crate config for release

---

rust/.cargo/config.toml
rust/Cargo.toml
rust/README.md
rust/lance-arrow/Cargo.toml
rust/lance-linalg/Cargo.toml
rust/lance-testing/Cargo.toml
rust/lance/Cargo.toml

This PR fixes cargo config conventions.
So we can publish to crates.io

fix: cargo toml to follow crates.io convenetion

---

rust/lance-arrow/Cargo.toml
rust/lance-arrow/src/bfloat16.rs
rust/lance-arrow/src/floats.rs
rust/lance-arrow/src/lib.rs
rust/lance-linalg/src/distance.rs
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/matrix.rs
rust/lance/src/index/vector/diskann/builder.rs
rust/lance/src/index/vector/graph/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/index/vector/utils.rs

The matrix view supports bf16/f16/f32/f64.

feat: support all float types in MatrixView

---

python/src/dataset.rs
rust/lance-arrow/src/floats.rs

Simplify the FloatArray traits over `arrow::Float{16/32/64}Array`

chore: simplify float traits

---

rust/lance/src/dataset.rs
rust/lance/src/datatypes.rs
rust/lance/src/datatypes/field.rs
rust/lance/src/datatypes/schema.rs
rust/lance/src/encodings/dictionary.rs
rust/lance/src/encodings/plain.rs
rust/lance/src/error.rs
rust/lance/src/index/vector/flat.rs
rust/lance/src/io/object_reader.rs
rust/lance/src/io/writer.rs

This PR add a test for KNN search on an empty table. Our code previously returns error because `KNNFlat` returned an empty record batch without `_distance` column. This PR makes `KNNFlat` return a schema with `_distance` column.
This PR also adds a test for KNN search on an empty table that was previously non-empty. This also seems to fail, but is not fixed in this PR. I created a new issue [here](https://github.com/lancedb/lance/issues/1288)
This PR sneaks in `location: Location` field to `crate::Error::Schema`. I needed this for debugging.

fix: search should not panic on empty table

---

rust/lance/src/dataset.rs

closes #1288
This test was failing because we couldn't process `.delete("true")`.

fix: search empty after delete test

---

.github/workflows/bump-version/action.yml

The action didn't update intra-workspace dependencies before because we didn't use exact versioning matching.
This PR forces update on all crates with pattern `lance*` and uses exact version matching

fix: bump version workflow

---

python/python/lance/optimize.py
python/python/tests/test_dataset.py
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs

Fixes #1303 
After compaction, the fragment ids may not be in sequential order. We were using 
`binary_search` to re-order results received from parallel `Fragment::take_rows()` calls, 
which requires sorted data. This PR switches to just doing linear search for now, which 
doesn't require sorting.
We should optimize this code path better in the future, but the batches are small enough for 
linear search is likely not too slow.

fix: knn search works after compaction

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/lance/src/dataset/scanner.rs

This adds a prefilter option to the list of scan options.  If prefilter is true then the filter is applied before the index (instead of after the index).  Currently this only works when using a flat KNN scan (e.g. when use_index is false) and so it may be very expensive on large datasets if the filter is not very selective.
Closes #1032

feat: add naive prefiltering

---

python/python/benchmarks/test_scan.py
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/encodings/binary.rs
rust/lance/src/io/exec/take.rs

This PR improves the performance of scanning with a filter. This uses late materialization in Lance, which is an entirely different code path from scanning without a filter. It first reads the filter columns, applies the filter, and then calls `take_rows()` to get the rows that matched the filter.
Two major optimizations have been made here:
1. `take_rows()` gets two new optimized code paths: one for when the indices are contiguous and one where they are sorted.
2. `BinaryDecoder::take()` is refactored so all data goes through only 1 memcpy and not 2. Before, we called `take()` on all ranges and the `concat()` to bring all the ranges together. This PR changes so we copy binary data into a perfectly pre-sized buffer. When we detect a range is contiguous and non-repeating, we just copy the …

perf: improve scan with filter performance

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py

Naive prefiltering was added to the scanner in https://github.com/lancedb/lance/pull/1276
I did not realize there was also a `to_table` method which is what lancedb uses.
This PR adds the prefilter option to `to_table` as well.

feat: add prefilter to the to_table method

---

rust/lance-linalg/benches/argmin.rs
rust/lance-linalg/src/kernels.rs
rust/lance-linalg/src/kmeans.rs
rust/lance/src/index/vector/diskann/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs

Implement fused argmin / argmax that takes an iterator instead of an array, to avoid memory allocation.

feat: fused argmin and argmax to avoid unnecessary memory allocation

---

.github/workflows/rust.yml
rust/lance/src/index/vector/ivf.rs
rust/lance/src/io/object_store.rs
rust/lance/src/io/object_writer.rs

Provide `ObjectStore::create_local(std::path::Path)` and `open_local(std::path::Path)`

chore: convenience methods for reading and writing local files

---

protos/format.proto
python/python/tests/test_dataset.py
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/format/page_table.rs
rust/lance/src/io/local.rs
rust/lance/src/io/reader.rs
rust/lance/src/io/writer.rs

Currently, `PageTable` assumes there are fields `0..num_columns`, where `num_columns` is the total number of columns in the dataset. This works for new files added, because we always write `0..(max_field_id + 1)` entries in the page table, but it breaks for old data files who have fewer fields. This is why after merge we can read the new columns (in the new files), but not the old columns. Also, because the PageTable is cached, we could read while using the same instance of `LanceDataset`, but as soon as we loaded in a new session, the PageTables would be re-read and break.
This PR modifies the `PageTable` format slightly so that the fields start at the minimum field id in that file's schema. This is backwards compatible for all tables that only have one data file per fragment, but breaks …

fix: make PageTable handle multiple files

---

rust/lance/Cargo.toml
rust/lance/src/io/commit/dynamodb.rs

Prior to this PR we describe dynamo db table everytime opening a dataset. This is okay when the number of calls to opening a table with dynamodb store is low. As `DescribeTable` has a account level limit of 2,500 RPS, we should avoid repeatedly calling the API.
This PR also fixes error formatting for aws sdk errors. AWS sdk error doesn't include the underlaying error unless asked for.

feat: add a cache for dynamodb schema validation

---

python/src/utils.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/kmeans.rs
rust/lance/benches/ivf_pq.rs

`cargo bench --bench ivf_pq` resulted about 20% speed up over `cosine`

chore: speed up kmean training for cosine

---

benchmarks/wiki/index.py
rust/lance/Cargo.toml
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/ivf/shuffler.rs
rust/lance/src/index/vector/kmeans.rs
rust/lance/src/io/object_store.rs
rust/lance/src/io/reader.rs
rust/lance/src/io/writer.rs

* Reduce the memory consumption to run IVF_PQ
* Building block for distributed IVF_PQ indexing
* Better multi-thread support during IVF assignment

feat: build ivf partition using disk based shuffler

---

python/python/lance/dataset.py
python/python/tests/test_vector_index.py

#515. Covers cases where column width is mismatched to query and where query input is not a vector.

feat: friendlier error messages in nearest api

---

docs/format.rst
protos/format.proto
rust/lance/src/format.rs
rust/lance/src/format/manifest.rs
rust/lance/src/format/metadata.rs
rust/lance/src/io/reader.rs
rust/lance/src/io/writer.rs

This PR adds page-level statistics to the Lance format. Computing the statistics and using them in queries is left for a future PR.
Changes:
* Define the statistics format in the format documentation.
* Added statistics metadata to the metadata
* Added reading and writing of the statistic page table. Refactored array read and write functions to take the page table as a parameter.
Closes #1318

feat: support storing page-level stats

---

protos/transaction.proto
rust/lance/src/dataset/transaction.rs
rust/lance/src/io/commit.rs

This will eventually be used to remap indices during a rewrite.  It allows us to know what the destination row ids will be during the rewrite operation.

feat: add new operation to reserve fragment ids

---

rust/lance/src/dataset.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/commit/external_manifest.rs

As a quick fix to address safety/consistency issues, we will find the latest manifest by scanning the `_versions` directory.
We continue to write the `_latest.manifest` file, so older readers are still compatible.
Performance considerations: in object stores like S3, we can get 1,000 objects listed with 1 request. So right now this adds 1 IO for those tables. Tables with more versions should probably have `cleanup_old_versions` applied.
Fixes: #1356
We will optimize this in follow ups, as described in #1362

fix: stop reading latest manifest

---

rust/lance/src/index.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs

I also simplify the remap tasks a bit by removing some unnecessary traits.

feat: remove tombstones from the IVF remapping process by shrinking the index

---

rust/lance/Cargo.toml
rust/lance/src/index/vector/pq.rs
rust/lance/src/utils.rs
rust/lance/src/utils/tokio.rs

The IVF search launches its sub-vector search in parallel:
```
let batches = stream::iter(part_ids)
.map(|part_id| async move {
self.search_in_partition(part_id as usize, query, pre_filter)
.await
})
.buffer_unordered(num_cpus::get())
.try_collect::<Vec<_>>()
.await?;
```
However, if the subvector is PQ (which it always is today) then the only part that is actually run in parallel is the load of the deletion file.  This is because an async function, without any awaits, is not actually asynchronous at all.  Or, phrased another way, don't create asynchronous functions that run a long time without an await.
This PR demonstrates a simple fix to this problem using rayon.  An alternative would be for `spawn_cpu` to use tokio's `spawn_blocking` but tokio themselves suggest this is not a …

feat: run pq portion of ivf_pq in parallel

---

protos/transaction.proto
python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/python/tests/test_optimize.py
python/src/dataset.rs
python/src/dataset/optimize.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/index.rs
rust/lance/src/index/vector.rs
rust/lance/src/io/commit.rs

During the commit_compaction step (the last part of compaction, after the fragments have been rewritten) we run an index remapper to remap the indices.  This is needed because the row addresses will have changed as part of the compaction.  We should only remap indices that had rows in affected fragments.
I also removed the "rewrite operation" from the python bindings.  This was already a fairly complicated operation and adding rewritten indices to it would make it even more complicated.  I don't think users are going to be orchestrating compaction themselves anytime soon (and we can add it back in if needed).  Furthermore, the plan compaction capability and serialization of compaction tasks is a much better solution for anyone that wants to orchestrate the compaction process.

feat: collect row ids and run index remapper

---

protos/transaction.proto
python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/python/tests/test_optimize.py
python/src/dataset.rs
python/src/dataset/optimize.rs
rust/lance-testing/src/datagen.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/datatypes/schema.rs
rust/lance/src/format/fragment.rs
rust/lance/src/index.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/opq.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/io/commit.rs

Currently, after compaction runs, any fragments that were covered by an index, and compacted, will no longer be covered by that index.
This PR fixes that.  During compaction we calculate the input and output row ids and then rewrite existing indices so that they cover the newly compacted fragments.
Closes #1378

feat: remap indices on compaction

---

python/python/tests/test_optimize.py
rust/lance/src/dataset/transaction.rs

A bug would occur when some of the rewrite groups were covered by the index and other rewrite groups were not.

fix: fix bug in index remapping when plan contained multiple rewrite groups

---

.github/workflows/build_linux_wheel/action.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
python/DEVELOPMENT.md
python/tools/Dockerfile.manylinux2014
python/tools/Dockerfile.manylinux2014_aarch64

The maturin action wheels support both x86 and Arm hosts to build for *either* target. This makes it a lot easier than our custom builds, which require the host to be the same as the target.
This removes our custom docker files and instead uses the ones provided by maturin.
closes #1286, #1392

ci: cross compile arm wheels

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/lance/src/dataset.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/commit/external_manifest.rs

expose latest version id api.
This is useful for efficiently check if another writer has committed a new version.

feat: expose latest version id api

---

rust/lance-linalg/src/distance.rs
rust/lance/src/index/vector/graph/builder.rs

Hopefully Rust is optimizing this already, but it's silly to wrap a function pointer in a trait object when we can just use the function pointer directly.

refactor: use function pointers instead of trait objects

---

rust/lance-core/src/error.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/format/fragment.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/io/deletion.rs
rust/lance/src/io/exec/knn.rs
rust/lance/src/io/exec/scan.rs
rust/lance/src/utils.rs
rust/lance/src/utils/future.rs

The previous handling of delete files in an ANN search was sub optimal in a few ways that are fixed by this PR:
* The synchronous portion of applying the prefilter was not run in parallel across the different PQ pages.  Now it is run in parallel as part of the spawn_cpu critical section.
* The synchronous work of calculating the prefilter (converting from delete file to, previously, a hashmap) was repeated for each PQ page.  Now we run this once, in parallel with the IVF centroid calculation and any IVF/PQ page loading.
* The prefilter was using a computationally heavy HashSet.  Now we use a roaring treemap.

perf: better parallelism in delete vector prefiltering

---

rust/lance-core/src/encodings/binary.rs
rust/lance-core/src/encodings/dictionary.rs
rust/lance-core/src/encodings/plain.rs

When a tokio::fs::File is dropped it does not wait for any ongoing writes to finish (as this would be a synchronous blocking wait).  Instead, it is recommended that you call `shutdown` or `flush`.  This was causing some unit tests to fail intermittently because we were creating a `File`, writing to it, then immediately reading from it.  Sometimes these reads would fail because the data had not actually been written yet.

test: fix flaky tests involving tokio::fs::File

---

python/python/lance/dataset.py
python/python/lance/vector.py
python/python/tests/test_dataset.py

the old computation calculated `k * sample_rate` as `sample_size` and then took the whole dataset unless there were `k * sample_size` rows which is `k * k * sample_rate`.  I've reworded the logic to hopefully be a bit clearer.
Once this was fixed the next issue was that the `dataset.sample` method doesn't actually exist and so I added it.

fix: fix an issue where the GPU index trainer was taking too much data into memory

---

python/src/fragment.rs
python/src/updater.rs

There were some lingering parts of Python that were creating their own runtime.

refactor: move all Python operations to the same runtime

---

rust/Cargo.toml

Updating `half` to `2.3.1`, which has been out for ~4 months.

chore: update half to 2.3.1

---

python/python/benchmarks/test_search.py
rust/lance-core/src/datatypes/schema.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/io/exec/knn.rs

Currently, prefiltering is restricted to searches that do not use an index.  This PR enables prefiltering to be used on an indexed column.  The approach is to first run a query to figure out the valid row ids and then pass this list of valid row ids to the index.

feat: allow prefiltering to be used with an index

---

python/python/lance/dataset.py
python/python/lance/vector.py
python/python/tests/conftest.py
python/python/tests/torch_tests/test_torch_kmeans.py

Allow `Dataset::create_index(..., accelerator=torch.device)` so that it can takes in `lance.torch.preferred_device()`

feat: create_index take torch.device object

---

.github/workflows/duckdb.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/rust.yml
.github/workflows/upload_wheel/action.yml
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/pq.rs
rust/lance-linalg/benches/cosine.rs
rust/lance-linalg/benches/l2.rs
rust/lance-linalg/src/distance.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance-linalg/src/distance/l2.rs
rust/lance-linalg/src/lib.rs
rust/lance-linalg/src/simd.rs
rust/lance-linalg/src/simd/f32.rs
rust/lance-linalg/src/simd/f32x8.rs
rust/lance/src/index/vector/diskann/builder.rs
rust/lance/src/index/vector/graph/persisted.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs

Make a SIMD lib for lance, to make writing SIMD easier and performant without needing `std::simd`. 
Only support `x86_64::avx2/fma` and onward, as well as `aarch64::neon` and onward.

feat: poor man's SIMD lib

---

.github/workflows/duckdb.yml
.github/workflows/notebook.yml
.github/workflows/pr-title.yml
.github/workflows/python.yml
.github/workflows/rust.yml

Adds concurrency config to cancel in progress actions when new commit pushed to PR or branch:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
When we have a PR open, and we notice some CI job has failed, it's common to immediately push a new commit with the fix before all the jobs have finished. This will start a new batch of jobs for the PR, but the old ones will continue to run in the background and will possibly also fail. This leads to confusing behaviour where we'll later receive emails about failed jobs on a PR from old commits.

ci: cancel in progress runs on new push

---

rust/lance/src/io/exec/projection.rs
rust/lance/src/io/exec/take.rs

These messages are annoying, and all they are saying is the stream was cancelled, which is generally intentional. We do take care to log error messages that weren't able to be sent because of cancellation, to make sure this doesn't mask any meaningful errors.
Fixes #1470

fix: remove channel closed messages

---

rust/lance-datagen/src/generator.rs
rust/lance/Cargo.toml
rust/lance/src/dataset/scanner.rs

This uses datafusion to sort the scanner results.  It will be needed for training scalar indices.  In addition, this PR adds some new capabilities to the array generators that I was using for testing the sort method.

feat: add sorting to the scanner

---

rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs

Closes. #1074
This pull request extends the `delete` method to accept the parameter `delete('true')` 
to bypass the filter when `predicate == 'true'`.

feat: support `true` in deletion logic

---

rust/.cargo/config.toml
rust/Cargo.toml
rust/lance-linalg/benches/norm_l2.rs
rust/lance-linalg/src/distance/norm_l2.rs

Explicilty convert to f32 on Mac M1/M2, achieve about 40% speed up without explicit SIMD, due to the lacking of `f16p` instructions in `std::arch::aarch64`.

perf: improve f16 performance for norm L2 on aarch64

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/test_fragment.py
python/src/dataset.rs
rust/lance-core/src/format/fragment.rs
rust/lance-core/src/io/deletion.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/write.rs
rust/lance/src/io/commit.rs

Issues like https://github.com/lancedb/lance/pull/1511 have shown the APIs where `0` is a sentinel value are dangerous and often mis-used. This PR changes `Fragment.physical_rows` and `DeletionFile.num_deleted_rows` to use `Option` instead, which forces the unknown case to be recognized and handled. This fixes some bugs in the handling of those.
There is another bug mentioned, but that is saved for another PR.

feat: safer API for physical_rows

---

python/src/dataset.rs
rust/lance-core/src/format/index.rs
rust/lance-index/src/lib.rs
rust/lance-index/src/scalar.rs
rust/lance-index/src/scalar/btree.rs
rust/lance-index/src/scalar/flat.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance-index/src/vector/pq.rs
rust/lance/benches/ivf_pq.rs
rust/lance/benches/scalar_index.rs
rust/lance/benches/vector_index.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/chunker.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/append.rs
rust/lance/src/index/cache.rs
rust/lance/src/index/scalar.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/diskann/builder.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/opq.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/exec/knn.rs
rust/lance/src/session.rs

Three new methods are added to the dataset (via `DatasetIndexExt`):
* `open_generic_index`
* `open_scalar_index`
* `open_vector_index`
Previously, there had only been `open_index` which was a free function (that took a `&Dataset`) and returned a `Arc<dyn VectorIndex>`.  That method still exists as an internal helper but users should now use `Dataset::open_vector_index` instead.
In addition, there is a new `IndexType` for `Scalar` and the `create_index` method will recognize this type.  Creating a scalar index currently does not require any parameters but it may in the future.
Opening a vector index today is rather involved.  First the proto metadata is loaded from disk.  This describes the detailed vector-specific parameters of the index (the index information in the manifest is very …

feat: make it possible to create and load scalar indices for a dataset

---

rust/lance-core/src/error.rs
rust/lance-core/src/io/object_store.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs
rust/lance/src/lib.rs

closes https://github.com/lancedb/lance/issues/1542
This takes a few components, and a lot of inspiration from the delta-rs implementation. The idea being it'll make it easier for others to adopt if it's familiar to other data formats (_with delta being the closest in nature to lance_).
Overall, I think these changes make it not only much more ergonomic, but also much easier to fine tune the lower level object store settings. 
```rust
let path = "gs://my-bucket/my_table.lance";
// using the default storage options
let dataset = lance::open_dataset(path).await.unwrap();
// using custom storage options
let mut options: HashMap<String, String> = HashMap::new();
options.insert(
"service_account_path".into(),
"~/.service_acct_key.json".into(),
);
let dataset = …
```

feat: allow for more advanced storage options in objectstore

---

rust/lance-linalg/Cargo.toml

Our build script is using the `std` function which was added in [`1.0.83`](https://github.com/rust-lang/cc-rs/releases/tag/1.0.83)

chore: update cc dependency to 1.0.83

---

rust/.cargo/config.toml
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/benches/norm_l2.rs

Generating bf16 from random f32's is biased.  Use random u16 as source instead.

chore: dotprod should be on mac target, not haswell and better randomness for bf16

---

rust/lance-arrow/src/floats.rs
rust/lance-index/src/vector.rs
rust/lance-index/src/vector/flat.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/pq.rs
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/benches/l2.rs
rust/lance-linalg/src/distance.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance-linalg/src/distance/l2.rs
rust/lance-linalg/src/distance/norm_l2.rs
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/simd/f16.c
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/io/exec/knn.rs

* Also makes all distant function returns `f32`, because it is the fastest type to do sorting later.

feat: make Dataset::nearest() accepts arbitrary query type

---

python/pyproject.toml
python/python/lance/cache.py
python/python/lance/sampler.py
python/python/lance/torch/data.py
python/python/tests/test_sampler.py
python/python/tests/torch_tests/test_data.py

Pytorch Dataset
* Work with PyTorch pipelines
* Local filesystem backed cache
* Faster pseudo random samplings. 
* Support project projection and filterings.

feat: torch cache-able dataset, with sampling support

---

rust/lance-core/src/io/object_store.rs

gs was converting to azure options instead of gcs options.

fix: google objectstore uses proper gs configuration

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/write.rs
rust/lance/src/index/append.rs
rust/lance/src/index/cache.rs
rust/lance/src/session.rs

This is to enable https://github.com/lancedb/lancedb/issues/641.

feat: expose index cache size

---

.github/workflows/build_mac_wheel/action.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml

Workaround until we find a proper fix for #1621.

ci: use M1 runner for now for release

---

python/Cargo.toml
rust/lance/Cargo.toml

`lance-linalg` has a feature flag `avx512fp16`, once enabled, it compiles the `f16.c` for auto-vectorized routines for `f16` on CPUs with `avx512fp16` instruction set.
This PR propagate the optional feature flag (avx512fp16) to the lance crate, so that we can build `avx512fp16` from the main crate as well.
Did not use `RUSTCFLAGS="-C target-feature=+avx512fp16" because rustc (`1.74` at the time of wriitng), does not pass this feature to `build.rs` .

chore: expose avx512fp16 feature via main lance crate

---

rust/lance-index/src/vector/ivf.rs
rust/lance/src/index/vector/ivf.rs

make IVF partition calculation parallelize

feat: make partition calculation parallel

---

rust/lance-core/src/utils/mask.rs
rust/lance-index/src/scalar/expression.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/io/exec/knn.rs

Provides our own TreeMap implementation, which is optimized for the case where an entire fragment is added. When a full fragment is to be marked, we use `None` instead of a full `RoaringBitmap`.
Fixes #1633

perf: more efficient treemap implementation for row ids

---

rust/lance-arrow/src/bfloat16.rs
rust/lance-index/benches/find_partitions.rs
rust/lance-linalg/benches/argmin.rs
rust/lance-linalg/benches/cosine.rs
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/benches/l2.rs
rust/lance-linalg/benches/norm_l2.rs
rust/lance-linalg/src/simd/f16.c
rust/lance-testing/src/datagen.rs

* Allow `generate_random_data` to create random array for bf16, f16, f32, f64
* Fix `BFloat16Array.as_slice()`
* Change cosine benchmark to support multiple data types

chore: make lance-linalg benchmark ready to test bf16 data

---

python/python/lance/torch/kmeans.py

we forgot to divide the sum of the vectors by the count. this PR fixes that

fix: correctly avg centroids in update logic in GPU IVF training

---

python/python/lance/dataset.py
python/python/lance/torch/data.py
python/python/lance/vector.py
rust/lance/src/index/vector/ivf.rs

These are a small collection of fixes I needed in order to run a benchmark for partitioning while using CUDA acceleration.
1. Regardless of whether IVF is going to be trained, we load in enough vectors to do the training. This causes OOM on large datasets, so I've changed this to skip loading those vectors if the IVF centroids have already been passed in. GPU training can handle larger than memory datasets thanks to it's data loader, so this makes large scale training with GPUs possible.
2. Added some cast to ints, as it's easy to accidentally get floats in some cases.
3. Handle older pyarrow versions in GPU training API

fix: prevent OOM when IVF centroids are provided

---

rust/lance/src/dataset/cleanup.rs

While working on an unrelated task I figured out a way that we can sometimes workaround the bogus "higher ranked lifetime" error.

perf: minor change to cleanup allowing for size to be collected in parallel

---

rust/lance/src/dataset.rs
rust/lance/src/dataset/write.rs
rust/lance/src/index/scalar.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/utils/tokio.rs

These are pretty minor fixes but I am trying to make sure that all the spans we have are debug level except for those at the dataset/scanner layer (which are info).  Then, I am trying to make sure that all of our debug scans always roll up to one of the info spans.  This generates better traces as there are fewer (and more meaningful) root spans.

chore: minor changes to tracing instrumentation

---

python/python/lance/sampler.py
python/python/tests/test_sampler.py

The original sampling logic may create row_id range that is out of total_record length.
This diff makes sure the row_ids are within the range
Fixes #1662

fix: row_id range fix for index training on gpu

---

rust/lance-arrow/src/floats.rs
rust/lance-index/src/vector/pq.rs

If a vector or PQ sub-vector are all zeros, the cosine distance will be NaN. which results a failure when assigning PQ code.
Raise more meaningful error message

feat: better warnings when the PQ assignment over cosine distance is wrong

---

python/python/lance/torch/data.py
python/python/lance/torch/kmeans.py

Provide a TensorDataset that shared the same behavior with `lance.torch.data.LanceDataset`, which returns tensors in batches.
So GPU kmeans can run against to the in memory tensors as well.

feat: a tensor dataset that shared with the same behavior as Lance torch Dataset

---

python/python/lance/dataset.py
python/python/lance/torch/data.py
python/python/lance/vector.py
python/src/dataset.rs
rust/lance-index/benches/find_partitions.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/builder.rs
rust/lance/src/dataset.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

This PR allows caller to pass in a precomputed `row_id -> ivf_partition` mapping. This is very helpful when the number of IVF is large and we want to rely on external mechanisms like GPU or distributed compute for computing these partitions.
Baseline:
```
[2023-12-04T18:03:19Z INFO  lance::index::vector::ivf::builder] IVF shuffler built
[2023-12-04T18:14:27Z INFO  lance::index::vector::ivf] Built IVF partitions: 722.0641s
```
This PR: (building partitons on GPU took 10 seconds)
```
[2023-12-04T17:36:55Z INFO  lance::index::vector::ivf] Loading precomputed partitions from file: 3ac9988f-74e6-4329-bedd-abf93a76c9e8.lance
[2023-12-04T17:36:55Z INFO  lance::index::vector::ivf] Loaded 10000000 rows of precomputed partitions
[2023-12-04T17:36:55Z INFO  lance::index::vector::ivf::builder] …
```

feat: add option to pass in precomputed row_id -> ivf partiton mapping and compute partiiton on GPU

---

python/python/benchmarks/test_scan.py
python/python/lance/dataset.py
python/src/dataset.rs
rust/lance-arrow/src/lib.rs
rust/lance-arrow/src/schema.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance-core/src/io/reader.rs
rust/lance-core/src/io/writer.rs
rust/lance-core/src/io/writer/statistics.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec.rs
rust/lance/src/io/exec/planner.rs
rust/lance/src/io/exec/pushdown_scan.rs
rust/lance/src/utils/tfrecord.rs

This PR introduces a new scan node that uses page-level statistics to decide which columns must be read to evaluate the predicate for each batch.
This is only hooked up for scans that don't use an index (scalar or ANN). Adding to other scans will be done in a future PR.
Closes #1264

feat: optimized pushdown scanner

---

python/python/lance/torch/async_dataset.py
python/python/lance/vector.py

The loader didn't exit and was block script completion. This PR adds a context manager that ensures the async worker is closed.
Also added some comments about the difference

fix: add shutdown to async loader

---

rust/lance-index/src/vector/pq.rs
rust/lance-linalg/src/distance/cosine.rs

In case where the residual vectors are zeros, it resulted in a dividing by zero error.

fix: use eplison to handle all zero cosine values

---

protos/format.proto

Older readers have a bug where they will read past the end of the file when reading the statistics metadata. Those older readers were before statistics were even used, so we don't care about them working. This commit moves the proto field so that only newer readers will pick it up.
Closes #1697

fix: prevent stats meta from breaking old readers

---

python/python/lance/torch/data.py
rust/Cargo.toml
rust/lance-index/Cargo.toml
rust/lance-index/src/scalar.rs
rust/lance-index/src/scalar/btree.rs
rust/lance-index/src/scalar/flat.rs
rust/lance-index/src/vector/ivf.rs
rust/lance/Cargo.toml
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/index.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs

revert back to hashmap for better performance for now.

perf: revert back to hashmap

---

rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

Removed hard-coded 4GB limit, as sometimes that produces errors like:
```
OSError: LanceError(IO): Resources exhausted: Failed to allocate additional 5618883160 bytes for ExternalSorter[0] with 0 bytes already allocated - maximum available is 4284481536, /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/convert/mod.rs:716:9
```
Instead users can set this as an environment variable:
```shell
export LANCE_MEMORY_LIMIT=$((4 * 1024 * 1024 * 1024))
```
I did an environment variable for now because the indexing parameters are a mess and I don't want to refactor them yet.
Because we don't know how much memory the client machine may have, we set it to unbounded by default.
Closes #1701

fix: remove default memory cap for index training

---

python/python/lance/dataset.py
python/python/tests/torch_tests/test_bench_utils.py
python/python/tests/torch_tests/test_data.py
rust/lance-core/src/utils/mask.rs
rust/lance-index/src/scalar.rs
rust/lance-index/src/scalar/expression.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/io/exec/scalar_index.rs

When we are doing a `ScalarIndexQuery` we do not need to worry about new and deleted data because the ANN search already handles deletion and won't run on new data.
When we are doing an indexed scan then we do need to worry about this.
For new data we do:
```
MATERIALIZE_INDEX -> TAKE -> UNION
SCAN -> FILTER -> PROJECT -> UNION
```
To handle deleted data we load the deletion vectors as part of the materialize index node.

feat: add support for new and deleted data to scalar indices

---

python/pyproject.toml
python/python/lance/arrow.py
python/python/lance/conftest.py
python/python/lance/lance/__init__.pyi
python/python/lance/lance/datagen/__init__.pyi
python/python/lance/optimize.pyi
python/python/lance/torch/async_dataset.py
python/python/lance/tracing.py
python/python/tests/test_datagen.py
python/python/tests/test_s3_ddb.py
python/python/tests/test_tracing.py

Add a ruff rule to enforce copyright header is presented in python files

chore: add ruff copyright check

---

rust/lance-core/src/encodings/binary.rs
rust/lance-core/src/encodings/dictionary.rs
rust/lance-core/src/encodings/plain.rs
rust/lance-core/src/format/page_table.rs
rust/lance-core/src/io/local.rs
rust/lance-core/src/io/object_store.rs

The `LocalObjectReader` was relying on `open` being a synchronous function which is not a safe assumption when working with NFS filesystems.  This PR changes it to an async function.

perf: use an asynchronous open function even for local files

---

rust/lance-core/src/encodings/plain.rs
rust/lance/src/io/exec/pushdown_scan.rs

* Adds small optimization to pushdown scan where we eagerly skip pages that don't match
* Fixes contiguous check in `make_chunked_requests`, which fixes a bug that causes vector columns to be read in very small pieces.

perf: small performance fixes for scan

---

python/src/utils.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-linalg/Cargo.toml
rust/lance-linalg/src/kmeans.rs

Use L2 over normalized vector to run cosine for kmeans.

fix: cosine kmeans

---

python/pyproject.toml
python/python/lance/sampler.py
python/python/lance/torch/async_dataset.py
python/python/lance/torch/data.py
python/python/lance/torch/kmeans.py
python/python/lance/vector.py

Better kmeans quality:
1. double the amount of takes allow during sampling
2. resample on every epoch
Dataset fix:
1. catch any error when draining the queue in async dataset
2. add logic to convert `FixedShapeTensorType` to tensor
Kmeans fix:
1. Remove normalize in `fit` method, where we might be calling `normalize` with a Dataset instance not a tensor. we already normalize in `_transform`

fix: various fixes to GPU kmeans

---

rust/lance-index/Cargo.toml
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf/io.rs

New IVF partition shuffle logic.
this shuffle has three stages
1. dump transformed data to a lance file. Only PQ transform is support right now because I hardcoded the schema
2. group by partition id and count the size of each partition
3. allocate vectors exactly sized to the partition sizes and stream the data into these memory buffer
TODO:

feat: handroll ivf partition shuffle

---

.github/workflows/build_linux_wheel/action.yml

The manylinux 2_17 image does not seem to be generating a working build of the `ring` library.  We had originally managed to get it to compile by setting `export CFLAGS_aarch64_unknown_linux_gnu="-D__ARM_ARCH=8"` however the library that was produced didn't work quite right and would generate "bad signature" when working with S3.  By bumping to manylinux 2_24 we are able to generate a successful build.  If someone needs 2_17 then they will need to dig into the `ring` library failure in more depth to figure out the exact cause of the issue.

fix: raise the manylinux version to 2_24 on aarch64 linux builds to avoid cross compilation issues

---

benchmarks/sift/index.py
benchmarks/sift/metrics.py
rust/lance/src/io/exec/knn.rs

Run end-to-end
```
./benchmark/sift/index.py f16.lance
./benchmark/sift/metrics.py f16.lance
```

fix: fix query over f16 knn node and sift benchmark

---

python/python/lance/fragment.py

We inherit from pyarrow but there are two properties that we don't override. This causes a segfault when doing tab completion. For now we just raise NotImplemented when these properties are invoked.

chore(python): prevent segfault using LanceFragment

---

python/python/lance/fragment.py
python/src/fragment.rs

Add `with_row_id` parameter to `to_table`, `to_batches`, and `scanner` methods of LanceFragment (similar to LanceDataset). This just so the developer does not need to manually compute the row id.

feat(python): add with_row_id to fragment scanner

---

python/python/lance/torch/distance.py
python/python/lance/torch/kmeans.py

* Add `logging.warnings` for Cuda OOM fallbacks
* Handle `pyarrow.FixedShapedTensorArray` in kmeans.fit
* Reduce repeatly `zeros/ones` allocation. 
* Allocate tensor directly on CUDA instead of moving from cpu to cuda

chore: minor improvement over kmeans algorithm

---

python/python/lance/dataset.py
python/python/lance/vector.py

Pytorch CUDA code pass the correct data type to rust , so rust can decide the data type correctly

chore: fix cuda-based indexing with f16

---

rust/lance-core/src/datatypes/schema.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/io/exec.rs
rust/lance/src/io/exec/knn.rs
rust/lance/src/io/exec/optimizer.rs
rust/lance/src/io/exec/planner.rs
rust/lance/src/io/exec/pushdown_scan.rs
rust/lance/src/io/exec/take.rs

This holds several bug fixes and refactors:
* Adds initial physical optimizer rules in lead up to #1782. I've noted further optimization passes we could write in the future.
* Fixes #1780
* Fixes issue where TakeExec was done twice in a row for Flat KNN queries.
* Fixes issue where scalar indices were being ignored for scans.
* Simplifies and expands test suite for the scanner `create_plan()` method.
This is a test footer.

fix: ensure query plans are correct

---

rust/lance-arrow/src/lib.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

This PR does a few things to the IVF shuffler
* add a `set_unsorted_buffers` method. This method allowes caller to set a list of buffers that is different from the `unsorted.lance` buffer used by default.
* This is helpful for using externally calculated buffers (say buffers from multiple GPUs)
* This also removed the limit of the number of rows that can be shuffled. Previously, we could only shuffle as many as 2^32-1 rows as we used a single shuffle buffer with a limit of 2^32 rows
* added logic to handle multiple shuffle buffers, by default we only use one buffer
* added a bunch of tests for the shuffler.
I will wire up python in the next PR to keep this smaller and more reviewable.

feat: allow externally generated shuffle buffer and multiple of them

---

rust/.cargo/config.toml
rust/lance-arrow/src/lib.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/io/commit/external_manifest.rs
rust/lance-datafusion/src/expr.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/commit/external_manifest.rs
rust/lance/src/io/exec/projection.rs
rust/lance/src/io/exec/take.rs

Rust `1.75` clippy introduces a bunch of new warnings. This PR fixes them.

chore: fix clippy lints on rust 1.75

---

python/python/lance/dataset.py
python/python/tests/test_lance.py
python/src/dataset.rs
rust/lance-index/src/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

Upstream fix for https://github.com/lancedb/lancedb/issues/767
TODO:

feat: expose shuffler parameters for controlling memory usage

---

python/python/tests/test_dataset.py
rust/lance-core/src/datatypes.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance-core/src/error.rs
rust/lance-core/src/io/writer.rs
rust/lance/src/dataset.rs

In addition, this fixes #1482 since we compare lance schemas and not arrow schemas (and lance schemas do not have an inner "item"/"element" field.)

feat: improve error message when schema mismatch occurs

---

python/Cargo.toml

[Half 2.3](https://github.com/starkat99/half-rs/releases/tag/v2.3.0) supports f16 HW acceleration. This is safe because our rust crate already uses 2.3.1

chore: bump half deps for HW acceleration in python

---

python/src/dataset.rs
rust/lance-core/src/format/index.rs
rust/lance-core/src/lib.rs
rust/lance-index/src/lib.rs
rust/lance-index/src/traits.rs
rust/lance/benches/ivf_pq.rs
rust/lance/benches/vector_index.rs
rust/lance/src/bin/lq.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/exec/scalar_index.rs

BREAKING CHANGE: removed single-purpose stats API from public API and refactored `DatasetIndexExt` to `lance-index`.
Also, fixed a few places that `unwrap()` results.

refactor!: index stats to handle error and bunch of bugs

---

rust/lance/src/dataset/optimize.rs

During compaction we read in the row ids so we can use them for remapping.  We read the row ids into a tree map which is most efficient if we can read them in order and the current code is in fact assuming that the row ids arrive in order.  However, we weren't actually scanning in order and this could lead to failures during compaction.

fix: spurious bug during compaction

---

python/python/tests/test_arrow.py
python/python/tests/test_tf.py
python/src/arrow.rs
rust/Cargo.toml
rust/lance-arrow/src/bfloat16.rs
rust/lance-arrow/src/floats.rs
rust/lance-core/src/datatypes.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/encodings/plain.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/utils/tfrecord.rs

I've given up for now on supporting generic extension types in FSL (#1693), so for now we'll have a special case for bfloat16 where we have a specific string that refers to our extension type.
This will unblock further development on vector search with bfloat16, but there is also still substantial UX work before we want to advertise this to users.
Closes #1684.

feat: roundtrip bfloat16 vectors to Lance format

---

python/python/tests/test_vector_index.py
rust/lance-index/src/traits.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/append.rs
rust/lance/src/index/cache.rs
rust/lance/src/io/commit.rs

perf: cache loaded index metadata

---

python/python/lance/util.py
python/python/tests/test_lance.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/lance-index/src/vector/ivf/builder.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

expose the option to set pre computed shuffle buffers to python
also added a util for sanity checking an index with in-sample queries

chore: expose externally computed shuffle buffer to python

---

python/python/lance/dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/lance-core/src/error.rs
rust/lance-index/src/lib.rs
rust/lance-index/src/scalar/btree.rs
rust/lance-index/src/scalar/flat.rs
rust/lance-index/src/traits.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/append.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs

BREAKING CHANGE: 
* change the structure of `index_statistics` return to include a list of index deltas.
* Do not return the cache hit rate because it is a global counter, not per-index status.
* Support f16/f32/f64 as IVF centroids.

chore: unindexed fragment can handle mulitple deltas

---

.github/workflows/cargo-publish.yml

Changes were introduced to the publish-crates action for how dev dependencies get resolved:
https://github.com/katyo/publish-crates/commit/2975306b7d9a99df113de64c106802fb5088be56#diff-20da981bb437131fc964cf3ac8dbda479f1ef5a050f6e750dd518f8a3c533663
This broke our build, as it made `lance-core` publish before it's dependency `lance-testing`.
Easiest solution is to pin the version of the action. Unfortunately, we can't pin to the upstream repo as not every commit has the `/dist` directory that gets created for releases (see [here](https://github.com/katyo/publish-crates/commit/c73a3c89510dd5d870696f1f084890d0b76224ab)), so I forked it.

ci: pin version of cargo publish action

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs

Currently, if you want to checkout a different version, you can't re-use the same session / cache. This means if you explicitly change version, you invalidate the cache, which isn't great.

feat: add a fast way to checkout a different version

---

python/src/dataset.rs
rust/lance-core/src/io/commit.rs
rust/lance-core/src/io/object_store.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance/benches/scalar_index.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/update.rs
rust/lance/src/index.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/commit/external_manifest.rs

There are a number of (rust API only) breaking changes:
* The `Dataset` methods `restore` and `append` no longer allow you to override the `ObjectStore` / `CommitHandler` of the existing dataset.  If you want to change these then reopen the dataset with a new `ObjectStore` / `CommitHandler`
* `ObjectStoreParams` no longer has `commit_handler`.  It has moved to `ReadParams` and `WriteParams`
* `DatasetBuilder::with_object_store` now requires the user to specify a `CommitHandler`
* `ObjectStore` no longer has a `commit_handler` and the various construction methods no longer accept one

refactor: move commit_handler out of ObjectStore and into Dataset

---

python/python/tests/test_vector_index.py
rust/lance-core/src/cache.rs
rust/lance-core/src/format.rs
rust/lance-core/src/format/manifest.rs
rust/lance-core/src/io/reader.rs
rust/lance-core/src/io/writer.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/index/vector/graph/persisted.rs

I'm working on splitting the file format and the table format into their own crates.  One point of difficulty was that the file reader referred to the fragment / manifest for loading deletion vectors and other information.  This PR brings all of that up into the fragment level.
The deletions are still passed to the file reader as a deletion vector, so this PR doesn't change where the work happens.  However the argument is now provided at read time instead of at open time.
There are no API changes and should be no changes to the format or how things are interpreted.  This is purely a refactor.

refactor: split any reference to fragment or manifest out of the file reader

---

python/python/tests/test_dataset.py
python/python/tests/test_filter.py
python/python/tests/test_fragment.py
python/python/tests/test_optimize.py
python/python/tests/test_vector_index.py
python/python/tests/torch_tests/test_data.py
rust/lance-linalg/src/kmeans.rs

Also remove all the print statements in the Python unit tests.
This reduces the number of lines in `run_tests` output from 66,657 to just 959! ([before](https://github.com/lancedb/lance/actions/runs/7619172254/job/20751766152#step:6:66660), [after](https://github.com/lancedb/lance/actions/runs/7628532848/job/20779819788?pr=1859#step:6:962))

test: make empty cluster message less noisy

---

rust/lance-io/src/object_store.rs

Fixes issue where there will be a panic when trying to read s3 dataset if aws credentials cannoy be resolved

fix: aws creds resolution panic

---

rust/lance/src/index/append.rs

this is a latent bug that only happens when there is concurrent:
* compact WITH index remap, and
* index append
because compact can reserve fragment ids and a smaller fragment id can now show up in a later commit.
By calling `push`, the new fragment with smaller id is never added to the bitmap

fix: latent bug in index append

---

python/python/tests/test_dataset.py
rust/lance/src/dataset/fragment.rs

The normal scan algorithm is:
```
open fragment reader with projected schema
for batch in batches:
scan batch
```
The pushdown algorithm is:
```
open fragment with full schema
for batch, simplified_projection in filter(batches):
projected scan batch(simplified_projection)
```
This means that the data files that need to be read could change from batch to batch.  This was not previously being accounted for and now it is.
Closes #1871

fix: do not panic when performing a pushdown scan on a multi-data-file fragment

---

.github/workflows/python.yml
.github/workflows/rust.yml

* Closes #1725 
* Still do release on Intel Mac for the time being.

chore: do not run test on intel mac anymore, and reduce python target

---

rust/lance-io/src/object_store.rs
rust/lance-table/src/io/commit.rs

Exposes `AwsCredentialAdapter` for purpose of allowing its cache to be used by the dynamo client.
This is necessary to get around a timeout loading credentials ... Currently dynamo client default to lazy_builder
https://docs.rs/aws-sdk-dynamodb/0.34.0/src/aws_sdk_dynamodb/config.rs.html#790
This lazy cache has a 5 second timeout loading credentials:
https://github.com/smithy-lang/smithy-rs/blob/e78c60dbf169403eedceb1b718b862b0c5e5ee09/aws/rust-runtime/aws-credential-types/src/cache/lazy_caching.rs#L93
This change allows the caller to more easily pass their own `ProvideCredentials` implementation and rely on the caching built into `AwsCredentialAdapter`.
```rs
use aws_config::default_provider::credentials::DefaultCredentialsChain;
use …
```

fix: improve ability to control dynamo creds cache

---

python/pyproject.toml
python/python/lance/dataset.py

`@lru_cache` on an instance method causes the cache to ref the instance, which causes a reference loop that can't be GC'd.
We could make a `weakref_self_lru_cache` for this purpose, but a `getattr` guard is simple enough

fix: remove lru_cache from instance method and add lint to catch future issues

---

docs/integrations/huggingface.rst
docs/integrations/integrations.rst
python/pyproject.toml
python/python/lance/dataset.py
python/python/lance/dependencies.py
python/python/tests/test_huggingface.py

Be able to directly write a huggingface dataset

feat(python): lance write huggingface dataset directly

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/python/tests/test_fragment.py
python/src/dataset.rs
python/src/lib.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance-core/src/error.rs
rust/lance-datafusion/src/exec.rs
rust/lance-datafusion/src/lib.rs
rust/lance-datafusion/src/utils.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance/benches/scalar_index.rs
rust/lance/src/datafusion.rs
rust/lance/src/datafusion/dataframe.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/merge_insert.rs

The "merge insert" operation can insert new rows, delete old rows, and update old rows, all in a single transaction.  It is a generic operation that is used to provide upsert, find-or-create, and "replace range".
closes #1456

feat: add "merge insert" operation based on merge operation in other databases

---

.github/workflows/duckdb.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/rust.yml

GHA announcement: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

ci: bump GHA to macos-14 to use free m1 GHA

---

rust/lance-core/src/utils.rs
rust/lance-core/src/utils/cpu.rs
rust/lance-linalg/Cargo.toml
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance-linalg/src/distance/l2.rs
rust/lance-linalg/src/distance/norm_l2.rs

Makes [avx512 fp16](https://networkbuilders.intel.com/solutionslibrary/intel-avx-512-fp16-instruction-set-for-intel-xeon-processor-based-products-technology-guide) support a runtime check. This will allow binaries compiled w/ the avx512fp16 feature to run hardware that doesn't support this feature (e.g. x86 before saphire rapids).
Check does not add performance penalty:
```
albertlockett@albert-ubuntu-saphire:~/lance/rust/lance-linalg$ TARGET_TIME=55 cargo bench \
--bench dot \
-F avx512fp16
Compiling lance-linalg v0.9.9 (/home/albertlockett/lance/rust/lance-linalg)
Finished bench [optimized + debuginfo] target(s) in 55.77s
Running benches/dot.rs (/home/albertlockett/lance/rust/target/release/deps/dot-f42dee3ad61e0342)
Gnuplot not found, using plotters backend
Dot(half::binary16::f16, …
```

fix: make avx512 fp16 a runtime check

---

python/python/lance/torch/kmeans.py

Spotted a one-line bug in _updated_centroids()

fix: small bug in _updated_centroids() in kmeans.py, wrong initialization of zero_counts

---

python/python/benchmarks/test_search.py
rust/lance-core/src/utils/mask.rs
rust/lance/src/io/exec/scalar_index.rs

Materialization converts a row id mask into a vector of row ids.  The old approach used a FragIdIter which was too slow.  In fact, we probably want to eventually get rid of FragIdIter entirely (see https://github.com/lancedb/lance/issues/1896).  In the meantime, when there is no block list, we can materialize by filtering the allow list with the fragment list instead.
This should greatly speed up indexed searches that don't have any vector search component.

perf: speed up materialization when there is no block list

---

.github/workflows/python.yml
docs/conf.py
docs/integrations/integrations.rst
python/pyproject.toml
python/python/benchmarks/conftest.py
python/python/benchmarks/test_bulk_write.py
python/python/benchmarks/test_scan.py
python/python/lance/_datagen.py
python/python/lance/_dataset/sharded_batch_iterator.py
python/python/lance/dataset.py
python/python/lance/progress.py
python/python/lance/sampler.py
python/python/lance/tf/data.py
python/python/lance/torch/bench_utils.py
python/python/lance/torch/data.py
python/python/lance/vector.py
python/python/tests/test_arrow.py
python/python/tests/test_datagen.py
python/python/tests/test_dataset.py
python/python/tests/test_filter.py
python/python/tests/test_fragment.py
python/python/tests/test_lance.py
python/python/tests/test_optimize.py
python/python/tests/test_s3_ddb.py
python/python/tests/test_tf.py
python/python/tests/test_vector_index.py
python/python/tests/torch_tests/test_data.py

* Provide a set of composable Sampler that works with lance dataset 
* New `ruff` made a bunch of format changes

feat: enable composable and customizable sampler in PyTorch data loader

---

rust/lance-file/src/reader.rs
rust/lance/src/dataset/fragment.rs

To support `ALTER COLUMN`, we need to start handling cases where the order of data files and order of columns aren't aligned. For example, if you have columns `a, b, c`, and then later replace column `b` in a new data file, you now have data files with `a, c` and `b`, respectively. But the schema is still `a, b, c`, so when you read from the data files, you can't just merge them (that would give `a, c, b`), you need to re-order them.

fix: handle out-of-order columns

---

rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/io/exec/pushdown_scan.rs
rust/lance/src/io/exec/scan.rs

This will be useful for cases where users want to add columns to a dataset that aren't based on existing columns. We still need to scan the row ids so we can match the batching structure in the new data files we write.

feat: allow opening FragmentReader with just row id

---

.pre-commit-config.yaml
python/Makefile
python/python/lance/dataset.py
python/python/tests/test_schema_evolution.py
python/src/dataset.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs

Renames the Rust method `drop()` to `drop_columns()` for clarity and also alignment with `add_columns()` and `alter_columns()`.
Closes #1076
Related #1674

feat(python): expose `drop_columns()` in Python

---

rust/lance-index/src/vector/ivf.rs
rust/lance-linalg/benches/compute_partition.rs
rust/lance-linalg/src/kmeans.rs

The centroids array can sometimes be quite large (on my test case it was 1536 dimension * 32Ki parts * 4 B = 192MiB.  When we compute partitions we do so in num_cpus^2 tasks (on my system this is 16 * 16 = 256).
We were copying the centroids data to each task (so for my test this required 48GiB of RAM).  Since this array is read-only, we can just make a shallow copy of the arrow array instead of copying the data.

fix: avoid a buffer copy and share the array to reduce RAM cost

---

python/python/lance/dataset.py
python/python/tests/test_schema_evolution.py
python/src/dataset.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance/src/dataset.rs

Initial pass on `alter_columns()` API. This allows renaming columns and making them nullable. A future PR will allow casting the type of column.

feat: add alter columns for names and nullability

---

.github/workflows/docs-check.yml
.github/workflows/docs-deploy.yml

In #1908, we upgraded all CI to Python 3.12, but noted that tensorflow doesn't support that Pyhton version. Unfortunately, this made our docs deployment failed, since we require tensorflow for those:
https://github.com/lancedb/lance/actions/runs/7791323487/job/21247154480
This brings down the required Python version for now.

ci: fix docs deployment

---

rust/lance-index/Cargo.toml
rust/lance-index/build.rs
rust/lance-index/src/lib.rs

Our build was broken because the `stdsimd` feature went away:
https://docs.rs/crate/lance/0.9.14/builds/1117911
But it doesn't seem like we actually use any SIMD in the index crate anyways, so I'm just removing that line. (It seems all the SIMD was moved to the `linalg` crate.

ci: remove stdsimd reference

---

python/python/lance/sampler.py
python/python/lance/torch/data.py
python/python/tests/torch_tests/test_data.py

When support was added for sampling in #1900 it broke support for filtering on full scans (sampling and filtering is not yet supported).  This PR repairs support for filtering on full scans.
Closes #1932

fix: repair the filter keyword in the torch dataset loader

---

python/python/lance/arrow.py
python/python/tests/test_arrow.py

fix: allow image extension types to be pickled in PyArrow 12

---

rust/lance-core/src/error.rs
rust/lance-io/Cargo.toml
rust/lance-io/benches/scheduler.rs
rust/lance-io/src/lib.rs
rust/lance-io/src/scheduler.rs

I'm trying to commit the new file reader as a series of smaller PRs to help with the review.  This is an early PR that adds an I/O scheduler and some benchmarks.

feat: create an I/O scheduler that will eventually be used by the new file reader

---

rust/lance-index/src/vector/pq.rs
rust/lance-index/src/vector/pq/distance.rs
rust/lance-index/src/vector/pq/utils.rs

Extract `build distance table` and `use distance table to compute L2` into two separate functions for reusability.

chore: refactor distance table to separate function

---

rust/lance-io/src/scheduler.rs

In some versions of tokio `SendError<T>` only implements `Debug` if `T` is `Debug` (and we can't easily do that here because `T` contains `Reader` which is not `Debug`).  So, instead, we just panic directly.  The `SendError` wouldn't contain any additional useful information anyways.

fix: compile error when older versions of tokio were used

---

rust/lance-index/src/vector/pq/distance.rs

```
$ RUSTFLAGS="-C target-cpu=cascadelake -C target-feature=+avx2,+avx512f,+avx512vl" cargo +nightly build
Compiling prost v0.12.3
warning: unstable feature specified for `-Ctarget-feature`: `avx512f`
|
= note: this feature is not stably supported; its behavior can change in the future
warning: unstable feature specified for `-Ctarget-feature`: `avx512vl`
|
= note: this feature is not stably supported; its behavior can change in the future
warning: `lance-arrow` (lib) generated 2 warnings
warning: `lance-linalg` (build script) generated 2 warnings (2 duplicates)
Compiling lance-linalg v0.9.18 (/home/albertlockett/sophon/src/lance/rust/lance-linalg)
warning: `lance-datagen` (lib) generated 2 warnings (2 duplicates)
Compiling lance-testing v0.9.18
Compiling prost-types v0.12.3
Compiling …
```

fix: nightly compile error

---

python/python/lance/dataset.py
python/python/tests/test_schema_evolution.py
python/src/dataset.rs
python/src/fragment.rs
rust/lance-arrow/Cargo.toml
rust/lance-arrow/src/lib.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/dataset/updater.rs

This allows casting a column in place. For example, a user could change a `fixed_size_list<f32, _>` column to a `fixed_size_list<f16, _>`. In a future PR, we will make sure the indices can be preserved as part of the transaction.

feat: allow casting in `alter_columns()`

---

rust/lance-io/src/local.rs

this makes it possible to recognize whether we are removing something not exists.
see https://github.com/lancedb/lancedb/issues/884

fix: map the ErrorKind::NotFound to Error::NotFound

---

python/python/tests/test_scalar_index.py
python/python/tests/test_vector_index.py
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/optimizer.rs
rust/lance/src/io/exec/planner.rs

BREAKING: vector queries no long return the vector column by default. i.e. unless the caller explicitly doesn't call `project` or `project(&["vec"])`, the vector column won't be returned
this PR implement `SELECT func(col) AS my_col` semantic to lance. Python changes will come in a later PR
this PR also partially addresses https://github.com/lancedb/lancedb/issues/953, where we no longer return the vector column by default

feat: allow projection expression

---

rust/lance-index/src/vector/hnsw/builder.rs

To be consistent with the paper.

fix: use 1 for beam search candidate length for the levels above the assigned level

---

rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs

- continue searching if candidate is closer than futherest result
- re-evaluate the furtherest result for each iteration
- remove furtherest result while adding new candidate
this fixes the very low recall problem, but it also brings the construction time to normal which may be much slower than former

fix: search stops early than expected

---

rust/lance-index/src/vector/hnsw.rs

simply returns the nearest k candidates will result in better recall and even faster

perf: remove the unnecessary selection while searching

---

rust/lance/src/dataset/scanner.rs

we used to do \`nested.field\`, and it is wrong.
This is changed to \`nested\`.\`field\`

fix: escape column names correctly

---

.github/workflows/cargo-publish.yml
java/lance-jni/Cargo.toml
python/Cargo.toml

https://github.com/lancedb/lance/pull/1928 moved the workspace `Cargo.toml` to the root directory

fix: crate publish

---

java/lance-jni/src/blocking_dataset.rs
java/lance-jni/src/error.rs
java/lance-jni/src/jni_helpers.rs
java/lance-jni/src/lib.rs
java/lance-jni/src/traits.rs
rust/lance/src/dataset/write.rs

Add conversions between Errors, Java/Rust objects.
Modeled after `pyo3`

chore(java): provide conversion utilities between jni objects and rust objects

---

rust/lance/src/index/prefilter.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/fixture_test.rs
rust/lance/src/index/vector/ivf.rs

Add a test that check if IVF is passing the correct vector to subvectors
failes as expected
```
---- index::vector::fixture_test::test::test_ivf_residual_handling stdout ----
thread 'index::vector::fixture_test::test::test_ivf_residual_handling' panicked at rust/lance/src/index/vector/fixture_test.rs:90:17:
assertion `left == right` failed
left: 0.0
right: 1.0
stack backtrace:
0: rust_begin_unwind
```

chore: add fixture test for IVF index

---

rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs

before:
```
level=7, ef_construct=30, ef=100 recall=0.9: construct=542.960s search=2087 us
```
after:
```
level=7, ef_construct=30, ef=100 recall=0.91: construct=546.145s search=1468 us
```

perf: greedy search for finding entry point

---

integration/duckdb_lance/duckdb-ext/README.md

Use correct Markdown syntax for a link.

docs: fix typo

---

rust/lance/examples/hnsw.rs

- now HNSW index could result in high recall without so many edges, so reduce the `max_edges`
- it will take a long building time so reduce the `ef_construction`

chore: update HNSW example

---

rust/lance-linalg/Cargo.toml
rust/lance-linalg/benches/norm_l2.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance-linalg/src/distance/l2.rs
rust/lance-linalg/src/distance/norm_l2.rs
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/lib.rs
rust/lance-linalg/src/simd/f16.c
rust/lance-linalg/src/test_utils.rs

This adds tests to each of the distance kernels making sure they produce accurate output over a wide range of inputs.

fix: stronger numeric guarantees for distance kernels

---

python/pyproject.toml

I haven't yet figured out the cause but this test seems to trigger it reliably:
```
def test_tfrecord_parsing(tmp_path, sample_tf_example):
serialized = sample_tf_example.SerializeToString()
path = tmp_path / "test.tfrecord"
with tf.io.TFRecordWriter(str(path)) as writer:
writer.write(serialized)
inferred_schema = infer_tfrecord_schema(str(path))
assert inferred_schema == pa.schema({
"1_int": pa.int64(),
"2_int_list": pa.list_(pa.int64()),
"3_float": pa.float32(),
"4_float_list": pa.list_(pa.float32()),
"5_bytes": pa.binary(),
"6_bytes_list": pa.list_(pa.binary()),
"7_string": pa.binary(),
"8_tensor": pa.binary(),
"9_tensor_bf16": pa.binary(),
})
inferred_schema = infer_tfrecord_schema(
str(path),
tensor_features=["8_tensor", "9_tensor_bf16"],
string_features=["7_string"],
)
```

fix: pin away from pyarrow 15.0.1 as it is causing segmentation fault in tests

---

Cargo.toml
rust/lance-core/src/utils/testing.rs
rust/lance-datagen/src/generator.rs
rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/utils/temporal.rs

Bump chrono to 0.4.25 and fix warnings.

chore: upgrade chrono and fix deprecation warnings

---

python/python/lance/dataset.py
python/python/tests/test_scalar_index.py
rust/lance-datafusion/src/expr.rs
rust/lance-datagen/src/generator.rs
rust/lance-index/src/scalar/lance_format.rs

This adds support for scalar indices to timestamp, date, and time columns.  Datafusion does not have a min/max accumulator for duration columns (I think there is some angst around how durations are ordered) and so we cannot support duration.  Time columns are supported but I can't find any way to create a time literal in Datafusion so those indices may be less useful at the moment.
Closes #1945

feat: add support for scalar indices on temporal columns

---

rust/lance-file/src/writer.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/storage.rs
rust/lance-index/src/vector/utils.rs

Store `ivf` in the lance file schema.

chore: store ivf in arrow schema

---

rust/lance-index/build.rs
rust/lance-linalg/build.rs

This PR removes the `rustup` dependency by assuming the default rustup toolchain version as `stable`.
It fixes a bug when it builds with standalone `cargo` (no rustup) given by package managers.

fix: assume default rust toolchain as stable

---

docs/examples/examples.rst
docs/examples/llm_dataset_creation.rst
docs/index.rst

Adds an example for creating an LLM Dataset using Lance and Huggingface datasets. Also adds the examples page index.
Fixes #2027 
cc: @AyushExel

docs: add llm dataset creation example

---

rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/io/exec/utils.rs

https://github.com/lancedb/lance/commit/73b4b30233bbad573be8013bddf2955f4d11bf2a broke the build because it was written against an older DF version and we had updated between the last time CI ran on the PR and the actual merge.
This updates the merge insert code to use the newer DF APIs.

fix: update merge_insert code to use latest df version

---

python/python/tests/test_optimize.py
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/transaction.rs

fix: force fragments to be stored in the manifest in id-order

---

python/python/tests/test_dataset.py
rust/lance/src/dataset/write/merge_insert.rs

In addition, this switches the join order so that the smaller table (source table) is on the left.

fix: fix bug in indexed merge insert where new data could cause merge insert to panic

---

.github/workflows/rust.yml
codecov.yml

enable codecov
also, because instrumentation build is slow at runtime:
* switch over to big buildjet runner
* pin rust version to `1.76` (1.70 is the default on buildjet)
* switch cache over to buildjet

chore: enable codecov

---

docs/examples/examples.rst
docs/examples/llm_dataset_creation.rst
docs/examples/llm_training.rst

This PR adds the LLM training example using a Lance dataset to the docs.
Fixes: #2029 
cc: @AyushExel

docs: add llm training example

---

python/python/tests/test_schema_evolution.py
rust/lance-file/src/reader.rs
rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/index/vector/hnsw.rs

During the refactor to split things into lance-file and lance-table I introduced a bug.  There were a number of code paths for opening a file reader and I consolidated them into one.  However, when we were reading one data file from several data files, we ended up trying to load too many fields from the page table (more fields than exist in the page table).
Most of the time, this was ok.  The read would read past the end of the page table and grab part of the schema (effectively garbage data).  We never actually accessed this data and so we would get away with it.  However, if the fragment schema was considerably larger than the data file schema, then the read would go past the end of the file and cause an error.

fix: only read the data file's fields from the page table and not the whole dataset's fields

---

python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/lib.rs
rust/lance/src/io/commit.rs

Exposes a utility function to check whether a Dataset's manifest needs a migration to be considered the latest version. Most users have no business calling this, so it's kept in the private module.

feat: expose migration check

---

rust/lance-index/src/vector/ivf/shuffler.rs

before this it prints something like "123ms seconds"

chore: fix the time unit in logs

---

rust/lance/src/index/vector/ivf.rs

closes #2085
avoid panic when partition_id out of bounds

fix: load_partition return Error when partition_id out of bounds

---

rust/lance/src/index/vector/ivf/io.rs

improves 25% on 8.5M rows dataset (19 minutes)

perf: fully building HNSW partitions in parallel

---

rust/lance/src/index/vector/ivf/io.rs

this reduces the memory footprint about 2X less

chore: drop data after copied to reduce memory footprint

---

rust/lance-datafusion/src/exec.rs

Right now we use the greedy spill pool when we use spilling for btree index training.  This is because the btree index plan is:
```
Input Stream -> Sort    -> SortPreservingMerge -> Output
Input Stream (old data) -/
```
My thought was that `Sort` was the only spillable operator and we could use the greedy pool.  It turns out that `SortPreservingMerge` is also spillable and we can't get away with the greedy pool.

fix: use the fair spill pool instead of the greedy spill pool

---

rust/lance-arrow/src/lib.rs
rust/lance-datagen/src/generator.rs

This allows for random generation of float16, decimals, intervals, durations, and structs.

feat: extend datagen to cover more types

---

python/python/lance/fragment.py
python/python/tests/test_fragment.py
python/src/fragment.rs

I missed these when I added dynamic projection

chore: expose dynamic projection on fragment API

---

docs/read_and_write.rst
python/python/lance/__init__.py
python/python/lance/dataset.py
python/src/dataset.rs

This allows users to pass object storage configuration in Lance in Python. Previously, users could only configure these settings through environment variables.
Closes #1930

feat(python): expose storage options

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/lib.rs

This adds several traits.  On the encode side we have `BufferEncoder`, `ArrayEncoder`, and `FieldEncoder`.  On the decode side we have `PhysicalPageDecoder`, `LogicalPageDecoder`, `PhysicalPageScheduler`, and `LogicalPageScheduler`.
Prereqs:

feat: add core traits for encoders & decoders in the v2 format

---

rust/lance-datagen/src/generator.rs
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings.rs
rust/lance-encoding/src/encodings/logical.rs
rust/lance-encoding/src/encodings/logical/fixed_size_list.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/encodings/physical.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/encodings/physical/bitmap.rs
rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
rust/lance-encoding/src/encodings/physical/value.rs
rust/lance-encoding/src/lib.rs
rust/lance-encoding/src/testing.rs

This adds encoders and decoders for non-nullable versions of all the arrow types
Prerequisites:

feat: add encoders/decoders for basic types

---

.github/workflows/python.yml
docker-compose.yml
docs/read_and_write.rst
python/DEVELOPMENT.md
python/pyproject.toml
python/python/lance/dataset.py
python/python/tests/conftest.py
python/python/tests/test_s3_ddb.py
python/src/dataset.rs
rust/lance-io/src/object_store.rs
rust/lance-table/src/io/commit.rs

This PR makes several changes:
1. Fixes an issue where `StorageOptions` would be bypassed in favor of `DefaultCredentialsChain` for the commit lock.
2. Makes credentials in `storage_options` take precedence over `DefaultCredentialsChain`. This way credentials passed in through function parameters will actually be used. Closes #1155
3. Fixes an issue were `Dataset.checkout_version()` would cause the dataset to lose it's storage configurations.
4. Refactored the integration tests so they are easier to run locally. `pytest` now handles the setup and teardown of buckets and dynamodb tables. Users just have to run `docker compose up`. Also, this is now documented in the `DEVELOPMENT.md`.
5. Bucket region is now automatically detected when using AWS S3.
6. We no longer hardcode allowing …

feat: easier and consistent S3 configuration

---

Cargo.toml
python/Cargo.toml

this is required because we need Config `enable_type_names` method.
Fixes issue when installing python:
```
$ maturin develop
error[E0599]: no method named `enable_type_names` found for struct `Config` in the current scope
--> /Users/albertlockett/Development/sophon/src/lance/rust/lance-encoding/build.rs:8:17
|
8 |     prost_build.enable_type_names();
|                 ^^^^^^^^^^^^^^^^^ method not found in `Config`
```

fix: set prost to minimum 0.12.2

---

Cargo.toml
python/Cargo.toml
rust/lance-datafusion/Cargo.toml
rust/lance-datafusion/src/expr.rs
rust/lance/Cargo.toml
rust/lance/src/dataset/scanner.rs

Hide substrait behind a feature.  This will remove the libgit2 dependency in the short term.  In the medium term this won't be needed because datafusion's next release should include substrait 0.29.3 which removes libgit2.  However, we still might want to keep substrait behind a feature just to stick to a general spirit of keeping things lean.

feat: make substrait optional to allow avoiding libgit2

---

rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-index/src/vector/sq.rs
rust/lance-index/src/vector/sq/transform.rs
rust/lance-index/src/vector/transform.rs
rust/lance/src/index/vector/hnsw.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf/io.rs

- refactor the index building path of IVF_HNSW_PQ & IVF_HNSW_SQ
- remove SQ transformer, make the building much faster
- reduce memory footprint while building (about 2x less)
- fix the graph was trained with cosine distance type

chore: refine the IVF_HNSW index building path

---

.github/workflows/python.yml
python/pyproject.toml

Remove python 3.11 CI because we can run full CI with python 3.12 now.

ci: full python 3.12 ci

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical.rs
rust/lance-encoding/src/encodings/logical/utf8.rs

Eventually, when we want to support things like FSST, we may need to move string encoding down to the physical level.  For now, we simply encode string arrays as `List<u8>`.

feat: add string arrays to the set of v2 encodings

---

python/Cargo.toml
python/pyproject.toml
python/python/lance/file.py
python/python/lance/lance/__init__.pyi
python/python/tests/test_file.py
python/src/dataset.rs
python/src/error.rs
python/src/file.rs
python/src/lib.rs
python/src/scanner.rs
rust/lance-encoding/src/encoder.rs
rust/lance-file/src/v2/reader.rs
rust/lance-file/src/v2/writer.rs
rust/lance-io/src/object_store.rs
rust/lance-io/src/object_writer.rs

feat: add python bindings for the v2 reader/writer

---

python/pyproject.toml

See comment.  This should fix our CI on arm.  Can revert this once https://github.com/h5py/h5py/issues/2408 is resolved.

fix: pin h5py version to avoid missing arm wheels

---

python/python/tests/test_ray.py

The test assumes that ray will infer the range as int64.  However, it uses numpy to do the inference and numpy's integer inference is platform dependent: https://github.com/numpy/numpy/issues/9464

fix: fix ray test broken on windows

---

rust/lance-table/src/format/manifest.rs
rust/lance/src/io/commit.rs

The fix #2148 assumed that the first fragment would have all the used field ids, but its actually possible for later fragments to have more. This PR makes us more robust to these complex layouts.

fix: handle varying field ids

---

protos/encodings.proto
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/encodings/logical/utf8.rs
rust/lance-encoding/src/encodings/physical.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/encodings/physical/bitmap.rs
rust/lance-encoding/src/encodings/physical/buffers.rs
rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
rust/lance-encoding/src/encodings/physical/value.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/src/v2/writer.rs

Struct and list will come later.  This PR was getting large enough as it was.
There is some refactoring that is happening as part of this PR also.  The basic encoder was previously and array encoder that took in two buffer encodings.  However, this meant we couldn't use the basic encoder to encode FSL since FSL is an array encoder.  So I changed the basic encoder to be an encoder that takes an encoder for validity and an array encoder for values.
I then also created the "value encoder" as an array encoder and renamed the existing value encoder (a buffer encoder) to the flat encoder.
In addition there was some minor refactoring needed to keep track of buffer indices.  Previously array encodings always mapped to 2 buffers.  Now they might map to more than 2 buffers (e.g. FSL with its own …

feat: add v2 nullability for primitive / fsl

---

python/python/tests/test_scalar_index.py
rust/lance-datafusion/Cargo.toml
rust/lance-datafusion/src/exec.rs

I'm not sure if we will want these long term so I don't want to expose them programmatically.  I'm hoping we can fix datafusion's out of core sort and so these won't need to be configurable.

fix: add env variables to bypass/configure spill pool size

---

.github/workflows/java.yml
java/core/lance-jni/src/blocking_dataset.rs
java/core/lance-jni/src/error.rs
java/core/lance-jni/src/fragment.rs
java/core/lance-jni/src/lib.rs
java/core/lance-jni/src/traits.rs
java/core/pom.xml
java/core/src/main/java/com/lancedb/lance/Dataset.java
java/core/src/main/java/com/lancedb/lance/Fragment.java
java/core/src/test/java/com/lancedb/lance/DatasetTest.java
java/core/src/test/java/com/lancedb/lance/FragmentTest.java
java/pom.xml

Add lance_jni create empty dataset, create fragment, and get schema

feat(java): add lance jni create empty dataset, create fragment, and get schema

---

rust/lance-arrow/Cargo.toml
rust/lance-datagen/Cargo.toml
rust/lance-datagen/src/generator.rs
rust/lance-io/src/stream.rs
rust/lance-table/Cargo.toml
rust/lance-table/src/utils.rs
rust/lance-table/src/utils/stream.rs

Applying row ids and deletion vectors is currently a file-level operation.  However, these are table-level concepts and I need to move them to the fragment reader (the v2 file reader doesn't use these concepts).
Eventually, we may like to pushdown deletions (to get "free" materialization), but that can wait until we are ready (I'm not sure we will reuse DeletionVector and may use something simpler?  Also, it'll be a while before we care about this particular optimization I think)
Note: this PR does not remove the source utilities (e.g. we are not changing the file reader).  That will come in a future PR.

refactor: move existing utilities from file reader into fragment-level operations

---

rust/lance/src/dataset/fragment.rs

As discussed in https://github.com/lancedb/lance/issues/2186

feat: more validation of fragments

---

python/python/lance/debug.py
python/python/lance/debug.pyi
python/python/lance/fragment.py
python/python/tests/test_debug.py
python/python/tests/test_fragment.py
python/src/debug.rs
python/src/fragment.rs
python/src/lib.rs
rust/lance/src/dataset.rs

These functions provide debug printing on various important structures. They are mainly useful for debugging issues on the dataset.
Since they are mainly for debugging, they are free function in a submodule instead of easily discoverable methods on respective classes.
Also, this includes a drive-by fix: fixes #2174
As dicussed in https://github.com/lancedb/lance/issues/2186

feat: debug functions

---

protos/table.proto
python/python/tests/test_fragment.py
rust/lance-core/src/datatypes/schema.rs
rust/lance-file/src/reader.rs
rust/lance-file/src/v2/reader.rs
rust/lance-table/src/format/fragment.rs
rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/updater.rs
rust/lance/src/dataset/write.rs
rust/lance/src/io/commit.rs

Refactor the file opening code in fragment to use common paths.
Add validation logic for data files.
Fix alter_columns so that it drops data files that are no longer referenced.
Put in groundwork for new fragment info for v2.

refactor: rework fragment API in preparation for lance v2

---

python/python/benchmarks/test_scan.py
rust/lance-core/src/utils/deletion.rs
rust/lance-file/src/reader.rs
rust/lance-file/src/v2/reader.rs
rust/lance-io/src/lib.rs
rust/lance-table/src/utils/stream.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/updater.rs
rust/lance/src/io/exec/pushdown_scan.rs
rust/lance/src/io/exec/scan.rs

This fleshes out a "generic reader" trait added in a previous PR and implements the trait for the v1 reader.  It then adapts the scan path to use the generic reader.  There are still many paths (take, update, etc.) which use the legacy read path directly.  These can be migrated over more slowly as we go.
Next, I will add an implementation for the v2 reader and this should make it possible to use the v2 reader in the scan path.

refactor: migrate scan path from v1-only to generic reader

---

python/python/lance/dataset.py
python/python/lance/debug.pyi
python/python/lance/fragment.py
python/python/lance/schema.py
python/python/lance/schema.pyi
python/python/tests/test_dataset.py
python/python/tests/test_debug.py
python/python/tests/test_schema.py
python/src/dataset.rs
python/src/debug.rs
python/src/fragment.rs
python/src/lib.rs
python/src/schema.rs
python/src/updater.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs

`LanceFragment.add_columns()` is broken for schemas with complex row id sequences. It needs to return the actual Lance schema used, rather than allowing the user to pass a PyArrow schema. PyArrow schemas are problematic because they assume field ids are contiguous and sequential, but they often are not. So we introduce a method `LanceFragment.merge_columns()` which returns both the new fragment and the actual Lance schema.
* Added new `lance.schema.LanceSchema` class, representing a Lance schema.
* Added `LanceDataset.lance_schema` property that returns a `LanceSchema`.
* Deprecated `LanceFragment.add_columns()` in favor of `LanceFragment.merge_columns()`, which returns `Tuple[FragmentMetadata, LanceSchema]`.
* Also motivating this change: I'd like to later re-introduce …

feat: replace `LanceFragment.add_columns` with `merge_columns`

---

protos/table.proto
python/python/lance/fragment.py
python/python/tests/test_fragment.py
python/python/tests/test_ray.py
rust/lance-file/Cargo.toml
rust/lance-file/src/page_table.rs
rust/lance-file/src/reader.rs
rust/lance-file/src/writer.rs
rust/lance-table/src/format/fragment.rs
rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/dataset/write/update.rs

Fixes two bugs, both associated with schemas that have holes in the field ids:
1. `write_fragments()` and `LanceFragment.create()` assume they can derive the field ids from the Arrow schema. This is not the case if there are holes in the schema. Therefore, when the mode is `Append`, we check the existing schema of the dataset and use its field ids. Fixes #2179
2. `PageTable` assumed that there were no holes in the field ids. It was parametrized as `field_id_offset` and `num_fields`, assuming the field ids were `field_id_offset..(field_id_offset + num_fields)`. This is changed to be parametrized by the min and max field id.

feat: support complex schemas in append

---

rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs

the option enables to extend the candidates from `ef_construction` to `ef_construction * m`, this is too slow because it extends the candidates to multiple of `ef_construction` , it turns out it's impossible to enable this, we can train the index with larger `ef_construction`, which is much eaiser to tune

chore: remove extend_candidates option

---

rust/lance/src/dataset/scanner.rs
rust/lance/src/index/vector.rs
rust/lance/src/session.rs
rust/lance/src/session/index_extension.rs

Add support for loading vector index types that are not natively supported in lance. This is done by registering a `VectorIndexExtension` in `Session`. During index loading, if the index type is not well known, we will check if there is an extension for it. This only works for `v0.2` index.
This PR omits extensions points for creating and appending to the index to keep the change small. I will add create and append in following PRs.
This PR also extracted `TestVectorDataset` in `scanner::test` to `scanner::test_dataset`, which is `pub` and guarded under `#[cfg(test)]`

feat: allow loading extension vector index

---

python/python/tests/test_schema.py
python/src/schema.rs

Nested fields need to have their parent-child relationships re-built when deserializing. We were missing that step.

fix: pickle LanceSchema nested fields correctly

---

.github/workflows/python.yml
.pre-commit-config.yaml
python/Makefile
python/python/benchmarks/test_bulk_write.py
python/python/benchmarks/test_scan.py
python/python/lance/arrow.py
python/python/lance/dataset.py
python/python/lance/progress.py
python/python/lance/ray/sink.py
python/python/lance/tf/data.py
python/python/lance/torch/bench_utils.py
python/python/lance/vector.py
python/python/tests/test_arrow.py
python/python/tests/test_datagen.py
python/python/tests/test_dataset.py
python/python/tests/test_debug.py
python/python/tests/test_filter.py
python/python/tests/test_fragment.py
python/python/tests/test_lance.py
python/python/tests/test_optimize.py
python/python/tests/test_s3_ddb.py
python/python/tests/test_scalar_index.py
python/python/tests/test_schema_evolution.py
python/python/tests/test_tf.py
python/python/tests/test_vector_index.py
python/python/tests/torch_tests/test_data.py

We had originally added --preview to our ruff invocations because it was required to enforce rule CPY001 which checks for a copyright header.  We have since moved that check to a dedicated tool and removed the ruff rule so we can safely remove --preview.
The --preview flag was a problem because IDEs and manual invocation would often leave it off and it turns out that the formatting changes based on the presence of `--preview` (it doesn't just enable / disable rules but actually changes the behavior of rules too).
By removing --preview we should make it easier for developers because there will be less configuration of their development environment required.

chore: remove --preview from ruff invocations

---

python/python/tests/test_schema.py

I suspect this snuck in during a recent PR that was concurrent with the PR to remove `--preview` from `ruff format`.

chore: fix formatting in test_schema.py

---

.github/workflows/python.yml
python/pyproject.toml

`ruff` 0.4.1 works with our current code base.

chore: bump to ruff 0.4.1

---

.github/workflows/build_linux_wheel/action.yml
.github/workflows/build_mac_wheel/action.yml
.github/workflows/build_windows_wheel/action.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/run_tests/action.yml
python/Cargo.toml
python/pyproject.toml

BREAKING CHANGE: minimal python version is set to Python 3.9

chore: bump minimal python version to 39

---

python/src/dataset/optimize.rs
python/src/fragment.rs

Some small features I wanted while prototyping LSM tree stuff.

feat(python): expose FragmentMetadata attrs and compaction repr

---

rust/lance-index/src/vector/hnsw/builder.rs

I forgot to change the value when changed the formulation to calculate the level

fix: use 1/ln(m) as the `mL` value for better performance

---

rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/graph/storage.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/sq/storage.rs

1/n -- trying to unify `HNSWBuilder` and `HNSWIndex`
move build time vector distance API to `VectorStorage` trait so we can pass in abstracted `VectorStorage`

chore: use VectorStorage in HNSWBuilder

---

rust/lance-index/src/vector/pq/builder.rs
rust/lance-index/src/vector/pq/utils.rs
rust/lance/src/index/vector/ivf.rs

see details: https://github.com/lancedb/lancedb/issues/1222

feat: forbid creating index if num_sub_vectors doesn't divide dim

---

rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance-testing/src/datagen.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/io.rs

- normalize vectors by `normalize_fsl`
- change the default HNSW build params `ef_constrction: 100 -> 150`
- fix the ground truth for cosine

fix: creating IVF_HNSW index fails with cosine metric type

---

rust/lance-index/src/lib.rs
rust/lance/src/index.rs
rust/lance/src/index/scalar.rs
rust/lance/src/index/vector.rs
rust/lance/src/session.rs
rust/lance/src/session/index_extension.rs

This PR gives vector index extension the ability to create index
changes:
* add `IndexExtension` and `ScalarIndexExtension` -- `ScalarIndexExtension` does nothing and has no API for now
* add `index_type` and `index_name` to `IndexParams` trait -- this is used to route `create_index` call to the correct handler
* `s/register_vector_index_extension/register_index_extension/`
* add test for index roundtrip -- create + load
Next PR will add index append API.

feat: add create_index to vector index extensions

---

python/python/lance/file.py
python/python/lance/lance/__init__.pyi
python/src/file.rs
rust/lance-arrow/src/deepcopy.rs
rust/lance-arrow/src/lib.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/Cargo.toml
rust/lance-file/src/v2/writer.rs

When a record batch crosses the FFI layer we lose the ability to deallocate that batch one array at a time (every array in the batch keeps a reference counted pointer to the batch).  This is a problem for the writer because we usually want to flush some arrays to disk and keep other arrays in memory for a while longer.  However, we do want to release the arrays we flush to disk to avoid memory leaks.
This issue was highlighted in a test / demo that attempted to write video data to a lance file.  In this situation we were writing the data one row at a time.  There were only 30,000 rows in the source data but this was hundreds of GB.  None of the metadata columns would ever flush to disk (e.g. a 4 byte int column @ 30,000 rows is only 120KB).  These metadata arrays were keeping the video …

fix: copy arrays when placing them in the v2 writer's accumulation queue

---

rust/lance-file/src/format/metadata.rs
rust/lance-file/src/reader.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs

this test shows that when we take from a fragment that exist, but the row id is out of bound, we panic.

fix: out of bound panics in take rows

---

rust/lance-datafusion/src/utils.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance/benches/scalar_index.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/fragment/write.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/utils.rs
rust/lance/src/utils/test.rs

Adds a test utility to generate a more hostile layout. Adds to one test function. Will add to more in follow up PRs.

test: test write methods against more varied layouts

---

rust/lance-io/Cargo.toml
rust/lance-io/src/object_store.rs
rust/lance-io/src/object_store/gcs_wrapper.rs
rust/lance-io/src/object_store/tracing.rs
rust/lance-io/tests/gcs_integration.rs

This is an interim fix for just GCS to solve https://github.com/lancedb/lance/issues/2247
Because of the challenges of casting between `&dyn ObjectStore` and `&dyn MultiPartStore`, it's not easy in the current version of `object_store` to implement this generically over all stores. However, in the next version of `object_store` (0.10.0), there is a new API for `put_multipart()` that will make it easy to extend this implementation to all stores.

feat: raise GCS object size limit to 2.5TB

---

.github/labeler.yml
.github/release.yml
.github/workflows/pr-title.yml

We make contributors categorize their PRs with the conventional commits titles. Right now, I manually separate different kinds of changes into sections in the release notes. This PR automates that process.
We use a labeler action to add PR labels based on the title. Then `.github/release.yml` will use those labels to create section headers. See docs here: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations
This is similar to how polars does their releases: https://github.com/pola-rs/polars/releases

ci: automate release notes

---

protos/encodings.proto
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/testing.rs

This adds support for nulls in lists and adds support for lists that contain more than i32::MAX items (note: this is a lot more common since we write offset pages much slower than item pages)

feat: add nullability and u64 support to list codec

---

rust/lance/src/dataset/scanner.rs

The pushdown scan currently requires fully materializing a batch in memory.  As a result, it is not capable of supporting the `batch_size` parameter in the scanner.  This fix is not great, it disables pushdown optimization when a batch size is specified, but if users truly need a batch size (to constrain memory) then its better to give them what they ask for at higher cost.
I would like to do a more correct fix soon but probably not until I work on pushdown for v2 (I'm still not sure if the "late materialization" will be part of the file reader itself or if we still need a dedicated pushdown node.

fix: don't use pushdown scan if a custom batch size has been set

---

Cargo.toml

closes https://github.com/lancedb/lance/issues/2279

chore: `half` dependency unpin and bump

---

.github/workflows/rust.yml

https://github.com/lancedb/lance/pull/2281 did not trigger CI runs.

ci: make sure the tests run if only the root cargo file is updated

---

python/src/file.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-io/src/object_reader.rs

Previously we were requiring that all items referenced by a page of offsets be loaded before any batches were returned.  This can be a problem when a list offsets page has many rows (e.g. a million) spread across many list item pages (hundreds).  In this case we can start emitting batches as soon as the first item page(s) have loaded.  That is what this PR does.

feat: don't load all list items before returning a batch

---

rust/lance-datagen/benches/array_gen.rs
rust/lance-datagen/src/generator.rs
rust/lance-encoding/benches/decoder.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/benches/reader.rs
rust/lance-file/src/v2/reader.rs
rust/lance-file/src/v2/writer.rs
rust/lance-index/src/scalar/flat.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance-table/src/utils/stream.rs
rust/lance/benches/scalar_index.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/io/exec/utils.rs

Very minor change but one that has been annoying me for a while.  The datagen allows columns to be specified with or without a name ("without a name" means one is automatically generated based on the column index).  If a name is specified it must be a `String`.  The vast majority of usage does specify a name and provides it as a `&str`.  As a result we have a lot of boilerplate `Some("foo".to_string())` that I would like to avoid.
To generate a column without a name use the function `anon_col`.
When generating a column with a name the name is now provided as `impl Into<String>` instead of `Option<String>`.

chore: simplify the datagen API

---

rust/lance/src/dataset/scanner.rs
rust/lance/src/utils/test.rs

This also fixes the "disable pushdown if custom batch size requested" logic which wasn't working correctly.  I also added a test to ensure that we are getting the benefits we expect.

perf: re-enable late materialization on full scans

---

rust/lance-io/src/object_store/gcs_wrapper.rs

This adds experimental environment variables for configuring how to handle retries and parallelism for uploads. We'll see how this works in production workloads before we decide what the permanent API is.

feat: add experimental limit variables for GCS

---

python/python/tests/test_dataset.py
rust/lance-file/src/reader.rs
rust/lance-io/src/lib.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs

Taking row offset 100 might be valid even if a fragment only has 10 rows.  This is because that fragment might have once had 1000 rows and 990 of them were deleted.  We need to make sure we do the bounds check on the addressible range and not the materialized range.  This means that some takes might return empty / deleted (id == null) rows and this is ok.

fix: relax 'take out of bounds' check which could cause failure if flat searching deleted rows

---

rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/transform.rs
rust/lance-index/src/vector/ivf/transformer.rs
rust/lance-index/src/vector/kmeans.rs
rust/lance-index/src/vector/pq.rs
rust/lance-index/src/vector/pq/builder.rs
rust/lance-index/src/vector/pq/distance.rs
rust/lance-index/src/vector/pq/utils.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-linalg/benches/cosine.rs
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/benches/l2.rs
rust/lance-linalg/src/distance.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance-linalg/src/distance/l2.rs
rust/lance-linalg/src/distance/norm_l2.rs
rust/lance-linalg/src/kmeans.rs
rust/lance/src/index/vector/ivf.rs

No logic change in this PR. It only changes the types used for L2 / Dot / Cosine.
This is part of the cleanup to make the code simpler to support Hamming / KMode.

chore: remove type restriction from ArrowFloatType over distance traits

---

rust/lance-core/src/utils/deletion.rs
rust/lance-table/src/format/fragment.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/updater.rs
rust/lance/src/dataset/write.rs
rust/lance/src/io/exec/pushdown_scan.rs

The old implementation depended on the batch size of the file to determine the deleted row ids.  This implementation does not but will respect the batch size, if given.

feat: add v2 support to fragment merge / update paths

---

Cargo.toml
python/src/utils.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/transform.rs
rust/lance-index/src/vector/kmeans.rs
rust/lance-linalg/Cargo.toml
rust/lance-linalg/benches/kmeans.rs
rust/lance-linalg/src/clustering.rs
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/lib.rs

* Use `rayon` to replace homemade tokio multi-threading and tiling
* Simplify KMeans interface to `Clustering`, preparing for KMode implementation
* Found surprising speed up by using rayon.

refactor: simplify kmeans and clustering API, prepare for kmode

---

Cargo.toml
python/src/file.rs
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/fixed_size_list.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/encodings/physical/bitmap.rs
rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
rust/lance-encoding/src/encodings/physical/value.rs
rust/lance-encoding/src/lib.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/benches/reader.rs
rust/lance-file/src/v2/io.rs
rust/lance-file/src/v2/reader.rs
rust/lance-io/Cargo.toml
rust/lance-io/benches/scheduler.rs
rust/lance-io/src/lib.rs
rust/lance-io/src/scheduler.rs
rust/lance-io/src/testing.rs
rust/lance/src/dataset/fragment.rs

This also renames store scheduler to scan scheduler.  I'm thinking I don't want to get into the thorny issue of how to prioritize I/O requests across different scans.  So, with this approach, if multiple scans are running at the same time, then they will overschedule (and let the OS deal with it).  This can be revisited in the future.
Closes #1958

feat: add priority to I/O scheduler

---

.github/workflows/pr-title.yml
Cargo.toml
python/Cargo.toml

https://github.com/lancedb/lance/commit/33d576f9d6d5783b7678d0950dfb2d3abd2cb837 introduced a breaking change but did not bump the minor version.  This PR only bumps the minor version.

chore: bump version to 0.11 to reflect breaking changes

---

python/python/benchmarks/test_index.py

this is slow cause we now reconstruct the entire index after merging data.
for 512d 1M rows IVF_HNSW_SQ dataset:
merge 500 rows: 41.4195s
merge 5 batches (100 rows per batch): 42.3950s
for 512d 100K rows IVF_HNSW_SQ dataset:
merge 500 rows: 2.2307s
merge 5 batches (100 rows per batch): 2.2654s
for 512d 1M rows IVF_PQ dataset:
merge 500 rows: 174.4656ms
merge 5 batches (100 rows per batch): 178.6720ms

test: benchmark the index merge performance

---

rust/lance-core/src/cache.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance/benches/scalar_index.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/append.rs
rust/lance/src/index/scalar.rs

We were not using the cache before which meant every scalar index query had to load a bunch of metadata from the index files (some of which was quite expensive)
Closes #2313

perf: use the file metadata cache in scalar indices

---

python/python/lance/file.py
python/python/lance/lance/__init__.pyi
python/python/tests/test_file.py
python/src/file.rs
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/src/v2/reader.rs

This also plumbs out basic support for take_rows and is a prerequisite for adding a fragment-level take

feat: add take_rows operation to the v2 file reader's python bindings

---

.github/workflows/build_mac_wheel/action.yml
.github/workflows/build_windows_wheel/action.yml
.github/workflows/python.yml

Github deprecated node16 based steps. It requires to upgrade to the node-20 steps.

ci: bump nodejs version in github actions

---

.github/workflows/pr-title.yml

Earlier in https://github.com/lancedb/lance/pull/2332#issuecomment-2110173164 we switched to `pull_request` events to checkout the correct PR. However, in those actions, GHA doesn't have permissions to label PRs, so that change broke the labeler job. This switches back of `pull_request_target`, but adds code to checkout the correct branch when checking for breaking changes.

ci: fix labeler permissions

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/fixed_size_list.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/src/v2/reader.rs

This PR modifies both scheduling and the decode stream.  These modifications should mainly affect the logical encodings (list / struct).  The changes to the other encodings are fairly minimal.
In the scheduler we now track where we are in the field tree.  This is both for debugging purposes (so we can log in trace messages the current path) and because we now need to send the path as part of the message we send to the decode stream.
The decoder changes are more significant.  Previously, we combined waiting for I/O and waiting for additional encoders into the same phase.  This logic was more complex, but more importantly, it also assumed that the decoder could recreate the order in which the scheduler scheduled pages.  For example, if we scan through the columns and encounter one that …

fix: rework decoding to fix bugs in nested struct decoding

---

rust/lance-index/src/scalar/expression.rs

fix: recognize a simple expression like 'is_foo' as a scalar index query

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/fixed_size_list.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/src/v2/reader.rs

We had previously scanned through the items pages triggering decoding in a manner that was very similar to the struct decoder but incomplete.
Now, we reuse the struct decoder in the list decoder.  So the "indirect schedule & decode" is nearly identical to a direct schedule & decode.  This removed some near-duplicate code and makes it so that we can handle list-struct (or list-anything)
This also forced us to fix another issue that was preventing us from decoding files with more than 2^32 rows.

fix: rework list encoder to handle list-struct

---

rust/lance-datagen/src/generator.rs
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/physical/value.rs
rust/lance-io/src/lib.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/write.rs
rust/lance/src/session/index_extension.rs
rust/lance/src/utils/test.rs

This also enables a lot of tests to run on both the v1 and the v2 format

feat: add fragment take / fixed-size-binary support to v2 format

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/fixed_size_list.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/testing.rs

Fix an issue that could occur when a batch of lists has zero size (even if the page does not)
Add test cases for above.
Fix list priority which got messed up when we changed to using a struct decoder

fix: minor bug fixes for v2

---

Cargo.toml
rust/lance-index/Cargo.toml
rust/lance-index/src/vector/graph.rs

bitvec is 8x smaller than Vec<bool>, tests show there's no performance diff

chore: replace Vec<bool> with bitvec

---

rust/lance-file/src/format/metadata.rs
rust/lance-io/src/utils.rs
rust/lance-table/src/format/fragment.rs
rust/lance-table/src/format/index.rs
rust/lance-table/src/format/manifest.rs
rust/lance-table/src/io/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/io/commit.rs

Minor refactor to allow conversions *from* proto structs to be fallible and also consume the struct. This reduces some data copies, though it's probably not all that impactful.

refactor: make proto conversion fallible and not copy

---

rust/lance/src/dataset.rs
rust/lance/src/dataset/schema_evolution.rs
rust/lance/src/dataset/take.rs

This just moves some function implementations and associated tests into own files.
Partly doing this because `RowIdMeta` struct was going to conflict with some row id stuff later. But also making the file shorter and easier to add more tests to.

refactor: separate take and schema evolution impls to own files

---

Cargo.toml
protos/rowids.proto
rust/lance-core/src/utils/address.rs
rust/lance-table/Cargo.toml
rust/lance-table/benches/row_id_index.rs
rust/lance-table/build.rs
rust/lance-table/src/lib.rs
rust/lance-table/src/rowids.rs
rust/lance-table/src/rowids/bitmap.rs
rust/lance-table/src/rowids/encoded_array.rs
rust/lance-table/src/rowids/index.rs
rust/lance-table/src/rowids/segment.rs
rust/lance-table/src/rowids/serde.rs

These are experimental indices to map from stable row ids to row addresses. It's possible there are some improvements to serialization format or performance we will make before stabilizing, but I'd like to defer that work so we can unblock work with the stable row ids.
These row id indices are optimized for storage size (in-memory and on-disk) and access speed.
Closes: #2308

feat: row id index structures (experimental)

---

rust/lance-index/src/vector.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance-index/src/vector/v3.rs
rust/lance-index/src/vector/v3/shuffler.rs
rust/lance-index/src/vector/v3/storage.rs
rust/lance-index/src/vector/v3/subindex.rs
rust/lance/src/index/vector/hnsw.rs

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* closes #2380
* closes #2378
* closes #2377
* closes #2376

feat: define Flat index as a scan over VectorStorage

---

rust/lance-index/src/vector/ivf/shuffler.rs

reduce number of IOs to improve shuffle performance.

fix: concat batches before writing to avoid small IO slow down

---

rust/lance-index/src/vector/ivf/shuffler.rs

This reverts commit 571a70a77951aa1d1e437179c7908d697f4db917.

Revert "fix: concat batches before writing to avoid small IO slow down (#2384)"

---

Cargo.toml
protos/encodings.proto
rust/lance-encoding/Cargo.toml
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/physical.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/encodings/physical/bitmap.rs
rust/lance-encoding/src/encodings/physical/buffers.rs
rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
rust/lance-encoding/src/encodings/physical/value.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/src/v2/reader.rs

This PR introduces general compression for value page buffers, starting with zstd, to reduce the on-disk size of all types of value arrays.
Here are the key details:
1. After some code exploration, I implemented this as a buffer encoder for `ValueEncoder` instead of as an independent physical encoder. Please let me know if this approach is suitable.
2. Enhancements to `ValuePageScheduler.schedule_ranges` allow it to read the entire buffer range for compressed buffers. To support this, I added a new `buffer_size` metadata to several buffer structs, populating these variables using metadata from Lance.
3. Currently, only zstd compression with the default level (level 3) is implemented. If this approach is deemed suitable, we can consider adding more general compression methods in the …

feat: general compression for value page buffer

---

rust/lance/src/dataset.rs
rust/lance/src/dataset/updater.rs

The updater has a check in the deletion restorer to make sure each batch has the same size as the batch size (if using v1 files).  This is not true for the final batch because it might be smaller than the batch size.  This PR adds a unit test to regress this case and fixes the validation logic.

fix: fix incorrect validation logic in updater

---

python/python/tests/test_file.py
rust/lance-file/src/v2/writer.rs

Pages with multiple buffers (today just primitive pages where some of the values are null) were being mangled as a result.  This was not caught during testing since we only had null testing in encoding unit tests which don't go through lance files.  I've added a basic test for nulls to the python tests to catch this in the future.

fix: fix file writer which was not writing page buffers in the correct order

---

rust/lance/src/dataset.rs

chore: replace `self.uri.to_string()` with `self.uri.clone()`

---

.github/workflows/license-header-check.yml
.github/workflows/pr-title.yml

ci: bump GHA node version to 20

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/lance/ray/sink.py
python/python/tests/test_dataset.py
python/python/tests/test_fragment.py
python/src/dataset.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/schema_evolution.rs
rust/lance/src/dataset/take.rs
rust/lance/src/dataset/updater.rs
rust/lance/src/dataset/write.rs
rust/lance/src/session/index_extension.rs
rust/lance/src/utils/test.rs

As the v2 format becomes the default we don't want to call it "experimental" any longer

refactor: rename use_experimental_writer to use_legacy_format

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/physical/basic.rs
rust/lance-encoding/src/encodings/physical/bitmap.rs
rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
rust/lance-encoding/src/encodings/physical/value.rs

This should allow for page schedulers to schedule indirect I/O if they need to and will unblock conversion of the binary field scheduler into a page scheduler

refactor: minor refactor to allow I/O scheduler to be cloned in page schedulers

---

python/python/tests/test_dataset.py
rust/lance-table/src/feature_flags.rs
rust/lance-testing/src/datagen.rs
rust/lance/src/dataset.rs
rust/lance/src/io/commit.rs

We want to avoid mixed-format datasets.  In theory, they should work.  However, it just expands our list of potential test scenarios without any real benefit.  Also, its easier to expose the use_legacy_format flag in lancedb if we only have to modify the create table operation.

feat: once a table has been created with v1 or v2 format then it should always use that format

---

rust/lance-datafusion/Cargo.toml
rust/lance-datafusion/src/chunker.rs
rust/lance/src/dataset/write.rs

In the v2 write path it was chunking to make sure that we don't put more than `max_rows_per_file` rows into any file.  However, this also became a point of accumulation.  This PR removes that accumulation but still inserts the breaks for `max_rows_per_file`.

fix: incorrect chunking was making lance datasets use too much RAM

---

rust/lance-file/src/reader.rs
rust/lance-file/src/writer.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance-table/src/utils/stream.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/write.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/io/exec/pushdown_scan.rs

Consolidates row_id logic. This is to make the stable row id logic much easier to work with.

refactor: pull row_id and deletion vector out of v1 file reader

---

python/src/utils.rs
rust/lance-core/src/utils/mask.rs
rust/lance-index/Cargo.toml
rust/lance-index/benches/find_partitions.rs
rust/lance-index/benches/sq.rs
rust/lance-index/src/prefilter.rs
rust/lance-index/src/vector.rs
rust/lance-index/src/vector/flat/index.rs
rust/lance-index/src/vector/flat/storage.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-index/src/vector/sq.rs
rust/lance-index/src/vector/sq/builder.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance-index/src/vector/sq/transform.rs
rust/lance-index/src/vector/v3/storage.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/index/vector/builder.rs
rust/lance/src/index/vector/fixture_test.rs
rust/lance/src/index/vector/hnsw.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/sq.rs
rust/lance/src/session/index_extension.rs

* Use chunked storage for `ScalarQuantizationStorage`, so that we can append new values cheaply. 
* It does auto-compaction after a hard-code threshold is met.

chore: chunked SQ storage

---

Cargo.toml
protos/encodings.proto
python/Cargo.toml
python/src/file.rs
rust/lance-datafusion/src/expr.rs
rust/lance-encoding-datafusion/Cargo.toml
rust/lance-encoding-datafusion/src/lib.rs
rust/lance-encoding-datafusion/src/substrait.rs
rust/lance-encoding-datafusion/src/zone.rs
rust/lance-encoding/benches/decoder.rs
rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs
rust/lance-encoding/src/encodings/logical/struct.rs
rust/lance-encoding/src/testing.rs
rust/lance-file/Cargo.toml
rust/lance-file/benches/reader.rs
rust/lance-file/src/v2.rs
rust/lance-file/src/v2/reader.rs
rust/lance-file/src/v2/testing.rs
rust/lance-file/src/v2/writer.rs
rust/lance-index/Cargo.toml
rust/lance-index/src/vector/storage.rs
rust/lance-index/src/vector/v3/shuffler.rs
rust/lance/Cargo.toml
rust/lance/src/dataset/fragment.rs
rust/lance/src/index/vector/builder.rs
rust/lance/src/index/vector/ivf/v2.rs

This PR adds quite a few pre-requisites as well:
* We add the concept of a "filter" to the read path
* We make the selection of decoder extensible with the `FieldDecoderStrategy` and `DecoderMiddlewareChain`
* Various changes to the decode path so that we can handle the case where the number of rows scheduled is less than the number of rows originally asked for
* We add Lance deserialization to `EncodedBatch` (serialization was added in an earlier PR)
* We fix some bugs in the serialization and deserialization of `EncodedBatch`
The basic flow is this:
* On write, we store statistics for each leaf column.  These are a record batch of min/max/null_count with a row for every X rows (X is configurable and we should experiment with it).
* This batch is encoded into a single buffer (as a mini …

feat: add pushdown to the read path

---

docs/read_and_write.rst
protos/table.proto
python/python/lance/dataset.py
rust/lance-arrow/src/lib.rs
rust/lance-core/src/lib.rs
rust/lance-core/src/utils/deletion.rs
rust/lance-table/benches/row_id_index.rs
rust/lance-table/src/format/fragment.rs
rust/lance-table/src/format/manifest.rs
rust/lance-table/src/rowids.rs
rust/lance-table/src/rowids/index.rs
rust/lance-table/src/utils.rs
rust/lance-table/src/utils/stream.rs
rust/lance/src/datafusion/logical_plan.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/rowids.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/take.rs
rust/lance/src/io/exec/pushdown_scan.rs
rust/lance/src/io/exec/scan.rs
rust/lance/src/io/exec/take.rs

Modifies the scanner to now support two options: `with_row_id` and `with_row_address`. Row addresses are what we used to call `_rowid`. They are returned as the `_rowaddr` column. For backwards compatibility, the `_rowid` column will be a copy of `_rowaddr` for datasets that aren't using stable row ids. For those that have activated the stable row id feature, they will have the row ids in the `_rowid` column.

feat: scan with stable row id

---

python/python/lance/torch/data.py
python/python/tests/torch_tests/test_data.py

fix: lance.torch.LanceDataset spelt readahead wrong

---

python/python/lance/dataset.py
python/src/dataset.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-core/src/datatypes/schema.rs
rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs

This allows us to send the pickled dataset across IPC and not require a reload of the manifest on the remote.  It should be safe since manifests are read only.  It uses the existing protobuf serialization for manifests.
If the manifest contains a dictionary field then we still need to load the dictionary information on the remote.  Perhaps we can pickle the dictionary at some point (or, with lv2, maybe dictionary won't need to be in manifest)

feat: pickle the manifest when pickling a dataset

---

java/core/lance-jni/Cargo.toml
java/core/lance-jni/src/ffi.rs
java/core/lance-jni/src/lib.rs

Enable the release of lance-jni so that it's utils can be reused by lancedb-jni rust module

chore(java): enable lance-jni rust release

---

python/python/lance/dataset.py

Currently, if `create_index` is used with non-standard storage backends, or configuration options passed at runtime, `lance` does not respect the storage option specified. This can be resolved by checking and passing `storage_options` from the `create_index` methods to allow for the `LanceDataset` to be recreated.

fix: respect storage options on `create_index`

---

rust/lance/src/dataset.rs

If the size of the manifest file is greater than 4KiB but the manifest itself is less than 4KiB then we can decode it from memory.  However, we look at the wrong location in the block when decoding the manifest and panic.

fix: incorrect logic when decoding manifest from last block

---

python/src/schema.rs
python/src/utils.rs
rust/lance-core/src/datatypes/field.rs
rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/flat/index.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/hnsw/index.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-index/src/vector/storage.rs
rust/lance-index/src/vector/v3/subindex.rs
rust/lance/examples/hnsw.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/ivf/v2.rs

- impl `IvfSubIndex` for HNSW
- remove IO related methods from HNSW
- remove unused `Result` return type for some HNSW methods

refactor: impl the sub index trait for HNSW and clean code

---

rust/lance-index/src/vector/sq/storage.rs
rust/lance-linalg/src/distance/dot.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

* Make SQ storage work with Dot distance
* Add test for `IVF_HNSW_SQ` + `Dot`

feat: make IVF_HNSW_SQ work with dot distance

---

rust/lance/src/io/exec/knn.rs

`with_new_children` is used by `transform_*` functions in phyiscal plan optimizer. Without correct `with_new_children` optimizer rules are useless.

chore: implement with_new_children correctly for index nodes

---

rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/io.rs

The HNSW building does nothing if there's only 1 row, this leads to we can't find this single node while searching

fix: low recall if many partitions with only 1 row

---

rust/lance/src/index/vector/ivf/builder.rs

At 50M rows this writes 1GB to the trace file :laughing:

perf: don't write precomputed partitions to trace file
