- rust/lance-table/src/utils/stream.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/take.rs
Part of https://github.com/lancedb/lance/issues/2307
* `Dataset::take_rows()` is now taking `row_ids`, which may now be stable row ids. These are translated into row addresses internally, and then use the existing logic.
* `Fragment::take_rows()` now optionally returns row address column, if asked, instead of row id.
> feat: support stable row ids in Dataset::take_rows()

- .github/workflows/python.yml
Fix pytorch CI failure on arm64 by changing to buildjet service
> ci: fix pytorch CI failure in arm64 jobs

- Cargo.toml
- python/Cargo.toml
- rust/lance-linalg/src/distance/dot.rs
- rust/lance-linalg/src/kernels.rs
- rust/lance-linalg/src/kmeans.rs
BREAKING CHANGE: Fix dot distance calculation from `-|xy|` to `1 - |xy|`. 
* Add `log::info` to show loss after kmeans converge earlier.
> fix: dot distance so kmeans can converge

- rust/lance-index/Cargo.toml
- rust/lance-index/benches/pq_assignment.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/utils.rs
- rust/lance-linalg/src/kmeans.rs
* Added benchmark for pq assignment to use fast routing
* Use compute_partition for fast kmeans find partition
> perf: use faster kmean find partition routing for pq assignment

- rust/lance/src/index.rs
A [recent change](https://github.com/lancedb/lance/commit/36c08d586d51a77b0ef5b67adac86f709ff9241b) moved these types out of the public API of `lance_index` and into the private API of `lance`.  This broke a customer (full disclosure, us) that was relying on these types.
These types are well documented and straightforward.  I think they were intended to be part of a public API.  However, I could be wrong.  Exposing them allows users to supply their own prefilter implementations when using `lance_index` utilities directly.  I think it would be fair to call the API experimental if we want to but the prefilter has been stable for a bit.
> feat: expose DatasetPreFilter, PreFilter, and FilterLoader to the public API

- Cargo.toml
- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/dynamodb.rs
Upgrades `aws-config` because `aws-config@0.56` has a dependency on `ring@0.16` [^1] which does not support `aarch64-pc-windows` [^2].
> error: failed to run custom build command for `ring v0.16.20`.
Support for `aarch64-pc-windows` was added in `ring@0.17` [^3] which `aws-config@0.57` uses [^4].
Unfortunately, there's a hideous amount of changes between these two version, although no breaking changes are mentioned in the changelog [^5]. Does a maintainer here have a suggestion of what kind of testing we might need to do?
[^1]: https://github.com/awslabs/aws-sdk-rust/blob/d212f8dd428e140b8ff414261f6921b2901a7dbc/sdk/aws-config/Cargo.toml#L98-L100
[^2]: https://github.com/briansmith/ring/issues/1514
[^3]: https://github.com/briansmith/ring/issues/1167#issuecomment-1745560468
[^4]: …
> chore: upgrade aws-config for aarch64-pc-windows support

- .github/workflows/rust.yml
Example: 
https://github.com/lancedb/lance/actions/runs/9662156349/job/26651441132?pr=2527
```
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
```
Closes #2002
Inspired by https://github.com/GreptimeTeam/greptimedb/pull/4143/files
> ci: fix stepWithCompactEncoding error on MacOS

- python/python/tests/test_optimize.py
- python/python/tests/test_vector_index.py
- rust/lance-index/src/vector/flat.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec.rs
- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/take.rs
> refactor: flat search to use datafusion top k

- rust/lance-table/src/io/commit/dynamodb.rs
Found this issue while trying to debug LanceDB, but I think a user had reported they were having trouble debugging this feature too.
Previous unhelpful error message:
`LanceError(IO): WrappedSdkError: service error, /Users/willjones/.cargo/git/checkouts/lance-b31243ab5673a03e/fb84707/rust/lance-table/src/io/commit/dynamodb.rs:37:23`
New error message:
`LanceError(IO): WrappedSdkError: request_id: db9807d8-8d17-45d1-973e-babfaf177998, service_error: Response { status: 400, version: HTTP/1.1, headers: {"content-type": "application/json", "x-amzn-errortype": "ResourceNotFoundException", "content-length": "98", "x-amzn-requestid": "db9807d8-8d17-45d1-973e-babfaf177998", "x-amz-crc32": "137764666", "connection": "close", "date": "Thu, 27 Jun 2024 16:05:49 GMT", "server": "hypercorn-h11"}, …
> fix: show underlying cause of DynamoDB service error

- python/python/tests/test_fragment.py
- rust/lance/src/dataset/fragment/write.rs
Previously it was ignoring the `use_legacy_format` option
> feat: make it possible to create v2 fragments using the fragment API

- python/python/lance/dataset.py
- python/python/lance/fragment.py
- python/src/dataset.rs
- rust/lance/src/dataset/fragment/write.rs
Install the package with local change:
`maturin develop`
Verified the following code did not work before and worked after the changes.
```
import lance
from lance.fragment import LanceFragment, FragmentMetadata
uri = 's3://xxxxx'
storage_options = {
'aws_access_key_id': 'xxx',
'aws_secret_access_key': 'xxx'
}
data = pa.table({"a": [1, 2], "b": ["a", "b"]})
fragment = LanceFragment.create(uri, data, storage_options=storage_options)
fragment = FragmentMetadata.from_json(fragment._metadata.json())
operation = lance.LanceOperation.Overwrite(tab1.schema, fragments=[fragment])
dataset = lance.LanceDataset.commit(uri, operation, storage_options=storage_options)
```
> fix: propagate storage_options to LanceFragment.create and LanceDataset.commit

- python/python/benchmarks/test_index.py
- python/python/lance/dataset.py
- python/python/lance/indices.py
- python/python/lance/lance/indices/__init__.pyi
- python/python/lance/vector.py
- python/python/tests/test_indices.py
- python/src/indices.rs
- python/src/lib.rs
- rust/lance/src/index/vector/ivf.rs
This is the start of breaking IVF / PQ index training up into four standalone methods with check pointing in between each method.
> feat: create standalone IVF training API in python

- .github/workflows/rust.yml
- rust/lance-linalg/build.rs
Issues have come up where the benchmarks couldn't be built on all platforms. This PR makes sure we check in CI that benchmarks and tests are all buildable on each platform.
https://github.com/lancedb/lance/pull/2523#pullrequestreview-2138893921
> ci: cargo check on various platforms

- python/python/lance/file.py
- python/python/lance/lance/__init__.pyi
- python/python/tests/test_file.py
- python/src/file.rs
- rust/lance-file/benches/reader.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/testing.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance-index/src/vector/v3/shuffler.rs
- rust/lance/src/dataset/fragment/write.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/index/vector/builder.rs
This is needed for some of the index refactoring work I'm doing.  It can be difficult to know the schema in advance and, in many (most) cases, the desired file schema is the same as the data schema and so there is no real benefit to providing it in advance.
This PR also removes the "path" argument from the rust constructor.  The path is already part of the ObjectWriter and there is no need for the file writer to keep a second copy.
> feat: allow users to create a file writer without a schema

- python/python/tests/test_vector_index.py
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/ivf/v2.rs
- rust/lance/src/index/vector/utils.rs
Adds locks for loading of index partitions. This voids multiple threads querying concurrently from both allocating memory to load the partition, which can cause memory issues during application startup.
> fix: avoid multiple threads loading same index partition

- python/python/tests/test_tf.py
importing tensorflow cause failures on main. 
https://github.com/lancedb/lance/actions/runs/9814654020/job/27102586923
> chore: skip tensorflow tests

- Cargo.toml
- rust/lance-encoding/Cargo.toml
- rust/lance-encoding/src/encoder.rs
Currently, to determine whether dictionary encoding should be applied, we use a `HashSet` for accurate cardinality calculation. However, I believe that perfect accuracy in cardinality isn't necessary in this context. Therefore, we could use HyperLogLog for a rough cardinality estimation, which might save memory and potentially speed up the cardinality check.
* `HyperLogLog` uses a fixed size of memory, determined by the precision in the code. And the `HashSet` uses the `threshold * each_item_string_size` of memory, if certain items are large, `HashSet` may use non trivial amount of memory
* `HyperLogLog` has an error rate (1.56%, translated from precision 12), while `HashSet` is accurate
> feat: use hyperloglog for cardinality estimation for dictionary encoding

- python/python/benchmarks/test_search.py
- python/python/lance/dataset.py
- python/src/dataset.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance/src/index.rs
- rust/lance/src/index/prefilter.rs
- rust/lance/src/index/scalar.rs
This also fixes a minor synchronization perf issue in the prefilter search path
> feat: integrate bitmap index into top-level lance APIs

- python/python/tests/test_file.py
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
In the future we can maybe add support for a few more things as well:
* User's should be able to read back into whatever schema they want (this is present in the rust already but missing from python because projection is missing from python, so this is mostly just tests)
* Perhaps add some kind of read option to "normalize" a schema so we always read back the field as "item".  Right now, if no schema is provided at read time, we mirror exactly the write time schema, this will cause non-item field names to propagate which is maybe not the best choice.  This could also be a write time option to normalize the schema on write.
> fix: add support for list fields with names other than 'item'

- rust/lance-index/src/vector/graph.rs
- rust/lance-index/src/vector/hnsw/builder.rs
- replace RoaringBitmap with BitVec
- use pool to avoid allocating bitset for each query with prefilter
- fall back to flat search if too many rows filtered out
- prefetch with flat search
> feat: do flat search if too many rows are filtered out

- python/python/benchmarks/test_search.py
- python/python/lance/dataset.py
- python/src/dataset.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/expression.rs
- rust/lance-index/src/scalar/flat.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/scalar/tag.rs
- rust/lance/benches/scalar_index.rs
- rust/lance/src/index.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/io/exec/scalar_index.rs
This PR adds a new kind of scalar index, the LABEL_LIST scalar index.  A label list index can only be created on list columns (the item data type has to be one of the data types that can be used for btree/bitmap indices).  The label list index can speed up array_has_any and array_has_all queries.
This is useful for tag-like columns where each row has some number of labels and the overall cardinality of the labels is relatively low (the index in-memory size will depend on the cardinality of the labels).
This PR also introduces the idea that different scalar indices may support different types of queries.  There is now `SargableQuery` (what is used by btree and bitmap) and `LabelListQuery` (used by the new label list index).  Going forward we should probably break the FullTextQuery out of …
> feat: add label list index

- python/python/benchmarks/test_search.py
- rust/lance-core/src/utils/mask.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/expression.rs
- rust/lance-index/src/scalar/flat.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance/benches/scalar_index.rs
The filtering paths that use scalar indices are all built to use `RowIdTreeMap`.  Scalar indices were built to use `UInt64Array`.  This means we have to copy from one to the other (an O(N log(N)) operation.  When we just had btree indices this was a fairly cheap operation since the indices shouldn't be returning large #'s of rows anyways.  Now that we have `BITMAP` and `LABEL_LIST` we can have indices that return very large #'s of rows and this copy was expensive.  By changing the scalar indices to use `RowIdTreeMap` directly we skip the conversion.
NOTE: any `LABEL_LIST` or `BITMAP` index that was previously created will be invalid and will need to be recreated.  Since we haven't had an official release of these index types I am not considering this a breaking change.
> perf: change scalar index to return RowIdTreeMap instead of u64 array

- python/python/benchmarks/test_index.py
- python/python/lance/indices.py
- python/python/lance/vector.py
- python/python/tests/test_indices.py
This also fixes up the tqdm progress bar for partition assignment so that it has a definite end.  This also makes one small tweak to the indices builder, moving the column argument into the builder constructor, since this argument will be shared by all methods in the class.
> feat: add standalone partition assignment operation

- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index/vector/ivf/v2.rs
we call `search_in_partition` directly instead of `search` after recent changes, so move the waiting for prefilter ready to `search_in_partition`
> fix: search panic with prefilter and HNSW

- rust/lance-index/Cargo.toml
- rust/lance-index/benches/inverted.rs
- rust/lance-index/src/scalar/inverted.rs
- add stopword filter to avoid words that occur everywhere causing very bad performance
- store tokens, inverted list and docs in `HashMap`
- use docs in `LargeStringArray` cause single doc could be large then the total length could be over `i32::MAX`
- more effecient updating for inverted list
110.3%+ faster
```
invert(1000000)         time:   [20.542 µs 20.844 µs 21.229 µs]
change: [-53.850% -52.380% -51.289%] (p = 0.00 < 0.05)
```
> perf: improve inverted index performance

- Cargo.toml
There seems to be an issue now with the older version of the AWS SDK and AWS SSO. Upgrading to a newer version fixed this.
Fixes #2614
> fix: upgrade AWS SDK

- python/src/dataset.rs
- rust/lance-datafusion/Cargo.toml
- rust/lance-datafusion/src/lib.rs
- rust/lance-datafusion/src/logical_expr.rs
- rust/lance-datafusion/src/planner.rs
- rust/lance-datafusion/src/sql.rs
- rust/lance-index/src/scalar/expression.rs
- rust/lance/src/datafusion.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec.rs
- rust/lance/src/io/exec/optimizer.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/utils.rs
This is purely a refactor and I inserted the appropriate re-exports into `lance` that there is no API change.  There were two minor extractions that were not purely moves:
`get_physical_optimizer` went from a static function on `Planner` to a free function in `optimizer.rs`
`create_filter_plan` and `FilterPlan` moved into `lance_index` as `PlannerIndexExt`
> refactor: move planner.rs, logical_expr.rs, and sql.rs from lance to lance_datafusion

- .github/workflows/python.yml
- python/python/lance/ray/sink.py
- python/python/tests/test_s3_ddb.py
- python/src/dataset.rs
Adds the ability to pass `storage_options` to `_BaseLanceDatasink` to allow specifying them for `LanceDatasink` and `LanceCommitter` (`LanceFragmentWriter` already supports passing these).
We need to customize them because some of our datasets are hosted on `R2`
> feat: add storage_options to _BaseLanceDatasink, LanceDatasink, LanceCommitter

- rust/lance/src/dataset/scanner.rs
We want to create a query plan that first runs prefiltering on selected fragments.
Then for rows passing the prefilter, we probe the ANN index with `filter_row_ids`.
In this plan, the returned result rows will only come from the selected fragments, so there will be no violation to the query semantics.
> perf: allow fragment scan for nearest query if there is a prefilter

- Cargo.toml
- rust/lance-encoding/compression-algo/fsst/examples/benchmark.rs
- rust/lance-encoding/compression-algo/fsst/src/fsst.rs
before:
after:
to reproduce:
`cargo run --release --example benchmark `
in `rust/lance-encoding/compression-algo/fsst`
machine info:
`11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz`
`Linux 192 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux`
> perf: speed up fsst decompression

- python/pyproject.toml
Pyarrow does not seem to support numpy 2.0.  We need to avoid it until they are ready.
> fix: pin numpy version to avoid numpy >= 2.0 until pyarrow supports it

- rust/lance-index/src/prefilter.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/inverted/wand.rs
- rust/lance/examples/full_text_search.rs
- rust/lance/src/index/prefilter.rs
This improves the full text search 3x faster without recall loss.
With WAND, we don't need to calculate the score for all matched documents, it would skip the documents that are impossible to be in the results.
ref: https://www.researchgate.net/publication/221613425_Efficient_query_evaluation_using_a_two-level_retrieval_process
This also adds a method `mask()` for `PreFilter` trait, to get the `RowIdMask`, because it's hard to use the `filter_row_ids` method in the WAND implementation
> perf: skip documents with WAND

- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec.rs
- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/projection.rs
We implemented our own custom projection `ExecutionPlan` that took a schema to project. With the latest DataFusion functions (particularly `named_struct`) we can now express this in terms of the built-in `ProjectionExec`. This reduces the maintenance burden on us and ensures the equivalents properties and optimizations rules from DataFusion work well without much effort on our part.
> refactor: remove custom ProjectionExec

- python/python/benchmarks/test_index.py
- python/python/lance/indices.py
- python/python/lance/lance/indices/__init__.pyi
- python/python/tests/test_indices.py
- python/src/indices.rs
- rust/lance-encoding/src/testing.rs
- rust/lance/src/index/vector/ivf/builder.rs
This makes the vector transform stage a standalone operation.
> feat: standalone vector transform stage

- rust/lance-file/src/v2/reader.rs
- rust/lance/src/dataset/fragment.rs
After this cache, we can remove two S3 reads from an ANN query, which can reduce ~100ms query latency.
See https://github.com/lancedb/lance/issues/2642
> perf: add v2 fragment file metadata to the FileMetadataCache

- Cargo.toml
- python/Cargo.toml
- rust/lance-index/src/scalar/btree.rs
`all_fields` deprecated, replace it with `flattened_fields`
> chore: upgrade arrow-rs to 52.2

- rust/lance/Cargo.toml
- rust/lance/benches/take.rs
- rust/lance/src/dataset.rs
add a benchmark for random take.
> perf: add random take benchmark

- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
We probably need to add "encode an empty array" tests for all encoding types.
> fix: correctly encode a list<string> type when all items are empty

- rust/lance-encoding/src/buffer.rs
- rust/lance/benches/take.rs
Fix `rust 1.80` clippy warnings in `lance-encoding`
> chore: fix cargo clippy warning in encoding crate

- Cargo.toml
> chore: upgrade object_store to 0.10.2 because security alert

- rust/lance/src/index.rs
- rust/lance/src/index/vector/pq.rs
adds a more helpful error message for https://github.com/lancedb/lancedb/issues/1465
> fix: improve error message when can't train PQ on too small dataset

- docs/read_and_write.rst
- python/python/lance/dataset.py
- rust/lance/src/dataset.rs
* Adds a documentation section for schema evolution methods, describing each.
* Consolidates methods for schema evolution in Rust, so they have their own header.
> docs: schema evolution

- protos/table.proto
- python/python/tests/test_dataset.py
- rust/lance-arrow/src/lib.rs
- rust/lance-core/src/utils/tokio.rs
- rust/lance-datafusion/src/dataframe.rs
- rust/lance-datafusion/src/exec.rs
- rust/lance/src/datafusion/dataframe.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/commit.rs
Closes #2610
* Supports subschemas in `merge_insert` for updates only
* Inserts and deletes left as TODO
* Field id `-2` is now reserved as a field "tombstone". These tombstones are fields that are no longer in the schema, usually because those fields are now in a different data file.
* Fixed a bug in `Merger` where statistics were reset on each batch.
> feat: merge_insert update subcolumns

- rust/lance-linalg/build.rs
- rust/lance-linalg/src/distance/cosine.rs
- rust/lance-linalg/src/distance/l2.rs
- rust/lance-linalg/src/distance/norm_l2.rs
This also renames kernel_suppport to kernel_support
> chore: fix kernel_suppport clippy warnings

- python/python/tests/test_dataset.py
Windows test has been flakey. Hopefully this will make those cleanup tests less flakey.
Example: https://github.com/lancedb/lance/actions/runs/10185602507/job/28175515906
> ci: increase gap for moment

- python/python/tests/test_indices.py
We are close to having green CI on Lance `main`. test_vector_transform is failing ever since we merged #2657
I think this is because we still have the file open but are re-using the same file uri. We need to close it to overwrite it.
> test: fix `test_vector_index` on Windows

- python/Cargo.toml
- python/python/tests/test_scalar_index.py
- python/src/dataset.rs
- rust/lance-index/src/lib.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-table/src/format/index.rs
- rust/lance/examples/full_text_search.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/rowids.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/index.rs
- rust/lance/src/index/append.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/session.rs
Breaking Change
Different scalar index types are shown up differently from `list_indices()`
> feat!: distinguishable scalar index types

- python/python/lance/__init__.py
- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/refs.rs
This PR expands upon the new tags API so that we can load from tags using the top-level `lance.dataset` Python API. Once accepted, the changes from this PR will be used to update the quickstart notebook to demonstrate the new tags functionality.
> feat: expand tags api

- protos/encodings.proto
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/bitpack.rs
- rust/lance-encoding/src/encodings/physical/buffers.rs
- rust/lance-encoding/src/encodings/physical/value.rs
Adds support for bitpacking for signed types Int8, Int16, Int32 and Int64. In this case, we use one extra bit in the encoding for as the sign bit, and when decoding pad using 1 instead of 0 when expanding the bitpacked buffer
> feat: support bitpacking for signed types

- rust/lance/src/dataset/scanner.rs
> feat: return BM25 scores for FTS

- rust/lance-datagen/src/generator.rs
- rust/lance-encoding/src/encodings/physical/basic.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/testing.rs
Need a tiny bit of extra logic because an array with the null data type will report 0 as its null count.
> feat: add support for the null data type to v2

- python/src/file.rs
- rust/lance-encoding-datafusion/src/lib.rs
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/benches/decoder.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/benches/reader.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/testing.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/vector/ivf/shuffler.rs
- rust/lance-index/src/vector/v3/shuffler.rs
- rust/lance-io/Cargo.toml
- rust/lance-io/benches/scheduler.rs
- rust/lance-io/src/scheduler.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/take.rs
- rust/lance/src/utils.rs
Adds backpressure to the I/O scheduler.  The general problem is rather tricky.  If your I/O threads all pause because your I/O buffer is full and then your decode threads are waiting for queued I/O tasks then you will have a deadlock.
I/O priority should allow us to avoid this situation but it is something that will need to be monitored, especially if users want to set really small I/O buffer sizes.  For this reason I haven't made any of the new settings  configurable (except for deadlock detection which we may turn on for debugging purposes if people seem to have encountered a deadlock).
One way you can hit this deadlock is to create a file with 10 pages where each page has 10GB of data.  Even a single read will fill up the I/O buffer.  We submit the reads in priority order but we have 8 …
> feat: add backpressure to v2 I/O scheduler

- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance/benches/scalar_index.rs
- rust/lance/src/index/scalar.rs
Closes #2661.
This PR adds a `scan_unordered_chunks` method to the `TrainingSource` trait and provides basic implementations where required. `train_bitmap_index` has been updated to take advantage of this new method. Please advise if any other indexing algorithms do not require sorted columns and I'll update accordingly.
> feat: make scalar index training configurable

- python/python/tests/test_dataset.py
- rust/lance/src/dataset/scanner.rs
There's a number of places (updates, compaction, etc.) where the default batch size is used and it is not configurable.  However, the default is too large in many cases.  We should probably eventually make all of these operations configurable (batch size, readahead, etc.) or perhaps change the default batch size to be based on data size but in the meantime this provides a potential workaround.
> feat: make default batch size configurable via environment variable

- rust/lance-encoding/src/encodings/physical/bitpack.rs
- rust/lance-encoding/src/encodings/physical/value.rs
resolves https://github.com/lancedb/lancedb/issues/1490
There was a bug in the calculation that moved the offset of uncompressed buffer forward. This occurred when the number of bits was byte aligned but did not divide evenly into the number of uncompressed bits.
> fix: out of bounds error in bitpacking

- python/python/lance/dataset.py
- python/python/tests/test_vector_index.py
- rust/lance-index/src/vector/pq.rs
we loaded PQ with distance type `cosine`, but actually always expect normalized vectors and use L2 for all cases PQ, this PR fixes this issue.
> fix: optimize cosine IVF_PQ index

- rust/lance-encoding/src/encodings/physical/packed_struct.rs
- rust/lance-table/src/rowids.rs
- rust/lance-table/src/rowids/segment.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/optimize/remapping.rs
- rust/lance/src/dataset/transaction.rs
Part of #2307.
Also addresses #2397
> feat: move-stable row ids in compaction

- rust/lance/src/index/append.rs
- rust/lance/src/index/vector/builder.rs
Only IVF_HNSW_* is with this bug,
this bug leads to the appending always builds index over the entire dataset, then we may get wrong results.
This fix also means that slow appending would be fixed
> fix: search results are not correct after appending index

- python/python/benchmarks/test_index.py
- python/python/lance/dataset.py
- python/python/lance/indices.py
- python/python/tests/test_indices.py
- python/src/dataset.rs
- python/src/indices.rs
- rust/lance-index/src/vector/ivf.rs
- rust/lance-index/src/vector/ivf/transform.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/transform.rs
- rust/lance-index/src/vector/residual.rs
- rust/lance-index/src/vector/sq/transform.rs
- rust/lance-index/src/vector/transform.rs
- rust/lance/src/index/vector/ivf/builder.rs
* Adds with_row_address to python bindings (for internal use case)
* Removes rayon from transform functions (there is already plenty of data-parallelism here in the outer loop)
* Use `Vec<Vec<_>>` instead of `HashMap` for partition id lookup.
> perf: various fixes to improve vector transform performance at high scales

- rust/lance-index/src/scalar/inverted/index.rs
before we had only Scalar/Vector for `IndexType`,
now we've added concrete types for it, so let it be `Inverted`
> fix: correct index type of inverted index

- Cargo.toml
- python/Cargo.toml
- python/python/tests/test_scalar_index.py
- python/python/tests/test_vector_index.py
- rust/lance-encoding/compression-algo/fsst/Cargo.toml
- rust/lance-index/src/lib.rs
- rust/lance/src/dataset.rs
- rust/lance/src/index.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/ivf/v2.rs
Before this, we try to fetch the index_type from stats of index, but many indices don't put index_type in it.
This breaks:
- Before this, IVF_PQ, IVF_HNSW_PQ would return `index_type=IVF`, now it's the concrete index type (IVF_PQ, IVF_HNSW_PQ)
- Before this, scalar indices would return `index_type=None`, now they return their type
> feat!: index_statistics returns the concrete index type

- python/python/tests/test_vector_index.py
It sometimes fails with:
```
FAILED python/tests/test_vector_index.py::test_index_cache_size - assert 0.9889441728591919 > 0.99
+  where 0.9889441728591919 = <built-in method index_cache_hit_rate of _lib._Dataset object at 0xfffe31904af0>()
+    where <built-in method index_cache_hit_rate of _lib._Dataset object at 0xfffe31904af0> = <_lib._Dataset object at 0xfffe31904af0>.index_cache_hit_rate
+      where <_lib._Dataset object at 0xfffe31904af0> = <lance.dataset.LanceDataset object at 0xfffe31930340>._ds
```
Since the failures are always on ARM I think the root cause might be the relaxed nature of the counter.  We could just make the counter and acquire / consume counter but I don't think super accurate index stats are all that important (indeed, metric stats like this are often the …
> chore: relax the check in test_index_cache_size

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/transaction.rs
> fix: drop indices if all fragment ids are missing

- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
I'm not yet entirely certain what creates these but have encountered them at least once now and they can cause the reader to get confused (e.g. we don't await an empty page because `unawaited` is 0 and this causes an unwrap error later)
> fix: ignore pages with zero rows

- python/python/lance/dataset.py
- python/python/tests/test_optimize.py
- python/src/dataset/optimize.rs
- rust/lance/src/dataset/optimize.rs
Another approach could be to always set `max_bytes_per_file` large enough to handle the compaction but I'm not sure if that would be a good idea or not.
Currently we will just silently "undercompact" (and potentially create runt files)
However, if we enable it, then we could potentially create huge files
> feat: add `max_bytes_per_file` and `batch_size` to CompactionOptions

- python/python/benchmarks/test_search.py
- python/python/tests/test_dataset.py
- rust/lance-encoding/src/decoder.rs
- rust/lance/src/dataset/scanner.rs
Late materialization is a great benefit when executing a highly selective filter.  However, if a filter is highly selective it means that each input batch will probably only have a few matching rows.  The current implementation executes take for each filtered batch.  E.g. instead of a single call of `take(500, 10000, 300000)` we get three calls `take(500)`, `take(10000)`, and `take(300000)`.  This means:
* We can't coalesce
* More CPU overhead (many calls to take_ranges)
* Very small output batches (user's batch size is not respected)
On cloud storage I see a 10x plus benefit in scan performance.
We have a benchmark for this (EDA search plot 4) which should assist with preventing regression in the future: https://bencher.dev/console/projects/weston-lancedb/plots
> perf: coalesce ids before executing take

- rust/lance-datafusion/Cargo.toml
- rust/lance-datafusion/src/exec.rs
- rust/lance/src/dataset/write/merge_insert.rs
Closes #2705.
This PR uses `lazy_static` to introduce two default session contexts:
- `DEFAULT_SESSION_CONTEXT`
- `DEFAULT_SESSION_CONTEXT_WITH_SPILLING`
Users request the session context via the new `get_session_context` function. If the user requests a session context with the default memory pool size, then one of the above contexts are returned. Otherwise, we compute a new session context like before.
> perf: cache default session contexts

- rust/lance-encoding/src/decoder.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-index/src/vector/storage.rs
- rust/lance/src/index/vector/ivf/v2.rs
If the reader is dropped during a scan then the scheduler thread is ended after the decoder thread and the io thread.  This means the scheduler thread might get an error sending to a closed receiver.  Previously we would panic on these errors.  With this change we simply log a debug message and end early.
> fix: don't panic when v2 scans end early (reader is dropped)

- .pre-commit-config.yaml
Address feature request https://github.com/lancedb/lance/issues/2739 (which is created by myself).
The `cargo` formatter I used comes from https://lancedb.github.io/lance/contributing.html#rust-development
Precommit hook mainly borrows from https://github.com/doublify/pre-commit-rust
git diff to show effect:
> chore: add rust format in precommit hook

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-io/src/scheduler.rs
- rust/lance/src/dataset/scanner.rs
fix: fix a potential deadlock when working with extremely large batches
> feat: make the I/O buffer size configurable

- docs/format.rst
The lack of second colon made it interpret the block as a comment 🤦 .
Fixes #2743
> docs: fix version table so it renders

- python/python/lance/optimize.py
- python/python/tests/test_optimize.py
The options were being passed through correctly but the documentation was incorrect.  This PR also adds a test confirming that `Compaction.plan` respects the new options.
> docs: document newly added compaction options in optimize.py

- python/python/tests/test_dataset.py
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/testing.rs
This could lead to deadlocks when the io_buffer_size is small (or when page sizes are very large).
Unfortunately, this is not the ideal scheduling algorithm, it uses too much RAM, but it's better to do that than deadlock.  Details in #2753
> fix: fix two cases in the v2 decoder where the decode order didn't match the scheduling priority

- rust/lance-index/src/scalar/inverted.rs
The FTS index doesn't require the data to be sorted, this could save much memory for large dataset
> chore: scan unordered chunks for training FTS index

- python/python/benchmarks/test_index.py
- python/src/indices.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance-index/Cargo.toml
- rust/lance-index/src/vector/ivf/shuffler.rs
With this fix shuffling performance at 1M rows goes from ~2.8 seconds to ~0.8 seconds.  At 1B rows we can shuffle in ~6 minutes.
> perf: various fixes to improve shuffling performance at high scales

- rust/lance-encoding/src/decoder.rs
The FTS index would read the entire posting list at once, for very large dataset this log would be printed many times for each query
> chore: change the level of log of reading large batch to debug

- python/python/tests/test_dataset.py
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
This actually addresses #2753 without requiring changes to the format but it's more complex and requires more bookkeeping than I'd prefer so I want to leave #2753 open to come up with a better solution at some point.
> fix: rework priority handling for lists.  We now properly schedule list item pages in priority order

- rust/lance-encoding/src/decoder.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/wand.rs
- calculating max score for each posting list and storing them in metadata, this helps WAND to skip more documents
- pick the shortest posting list to move (it's equal to select the one with largest IDF) so we can make less movements
This improves the FTS performance about 2x faster
> perf: calculate the max scores for posting lists then have a tighter upper bound

- rust/lance-index/src/vector/graph.rs
- rust/lance-index/src/vector/hnsw/builder.rs
The HNSW implementation has two core search functions:
- `greedy_search`
- `beam_search` (somewhat of a misnomer as-implemented, but that's not not relevant here)
Adding prefetching was key to speeding up the latter, which is where the bulk of the work happens. This is a small PR adding it to the former as well, resulting in a small speedup to HNSW (more pronounced with small values of `k`).
No algorithmic changes here.
`greedy_search` on its own is sped up by about 80% on SIFT1M after this PR.
> perf: add prefetching to hnsw greedy_search

- rust/lance-index/src/scalar/inverted/index.rs
We never use the global frequency of token, and we can calculate it from posting list of the token if we need it in future.
Sort the tokens in lexicographic order so we can apply prefix compression in the future
> chore: remove global frequency of tokens and sort tokens lexicographically

- docs/read_and_write.rst
This PR tries to fix #2748 by passing the newly defined table `new_table` into `execute()` function.
> docs: fix #2748, "Merge Insert" doc error

- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/external_manifest.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/io/commit/dynamodb.rs
- rust/lance/src/io/commit/external_manifest.rs
BREAKING CHANGE: this makes tables written with this and future versions unreadable by Lance v0.8.3 and earlier.
We stopped reading this way back in October of last year (#1365). Continuing to write this can actually cause us to hit per-object mutation rate limits in GCS, so we have some reason to stop doing this now.
> feat: stop writing `_latest.manifest`

- rust/lance/src/dataset/optimize.rs
Adds basic logging to compaction so that users can see some indication of progress on very long-running compaction jobs.  Example output:
```
2024-08-26T17:36:31Z INFO  lance::dataset::optimize] Compaction task 155cbe87-d8fe-44c7-baa2-2072f4353efa: Begin compacting 300 rows across 2 fragments
[2024-08-26T17:36:31Z INFO  lance::dataset::optimize] Compaction task 37e5da68-cd91-4e64-a3e4-3702714332b1: Begin compacting 300 rows across 2 fragments
[2024-08-26T17:36:31Z INFO  lance::dataset::optimize] Compaction task 155cbe87-d8fe-44c7-baa2-2072f4353efa: Read progress 112/300
[2024-08-26T17:36:31Z INFO  lance::dataset::optimize] Compaction task 155cbe87-d8fe-44c7-baa2-2072f4353efa: Read progress 225/300
[2024-08-26T17:36:31Z INFO  lance::dataset::optimize] Compaction task …
```
> feat: add logging to compaction

- rust/lance-encoding/benches/buffer.rs
Accidentally introduced a compiler error in my latest merge
> fix: add not-linux version of benches to avoid bench compiler error on mac

- rust/lance-io/src/object_writer.rs
I feel like I am creating a lot of environment variables lately :cold_sweat: but this one would be pretty tricky to push down.
I am testing with GCS, creating a 2TiB file, and it fails pretty much 100% of the time when following our gradually growing part size strategy.  I would like to know why, and plan to continue investigating.  However, in the meantime, it would help if we had some control over the part size.
This PR allows the user to pick the initial part size buffer size.  It does not change the growth strategy though.  At each step it will pick either the larger of "user supplied value" or "value we would have used with default strategy".  So if the user picks a very large value (e.g. 256MB) then the growth strategy will still start growing the buffer size at some point.
I also …
> feat: add an environment variable LANCE_INITIAL_UPLOAD_SIZE

- python/python/lance/dataset.py
- python/python/tests/test_scalar_index.py
- python/src/dataset.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance/src/index.rs
- rust/lance/src/index/scalar.rs
The positions can be very large, it's a waste for users who don't need phrase query, so provide a param to build the index without positions, don't build FTS index with positions by default
> feat: provide param to control whether to build FTS index with positions

- python/python/lance/dataset.py
- python/python/lance/fragment.py
- python/python/tests/test_fragment.py
- python/src/dataset.rs
- python/src/fragment.rs
- python/src/lib.rs
- rust/lance-encoding/src/version.rs
- rust/lance-file/src/lib.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-table/src/format/fragment.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/io/commit.rs
Previously `LanceFragment.create_from_file` only worked for v1 files.  This makes it possible to use for v2 files.  I also added a check in the commit step to confirm we do not allow files to be added unless they match the dataset version.
> feat: allow creating fragments from v2 files, expose rewrite operation to python

- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/io/exec/scan.rs
Now that backpressure is working properly we don't really need to limit fragment readahead too much in v2.  It has much less bearing on how much RAM is used.  In fact, we generally want to make sure that fragment readahead is higher than the I/O parallelism.
This PR also adds a new environment variable `LANCE_DEFAULT_FRAGMENT_READAHEAD` that can be used to change the default readahead used.  This can be useful in cases where the user can't set the readahead directly (e.g. duckdb pushdown, compaction, indexing jobs, etc.)
> feat: use a considerably higher default for frag readahead in v2

- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
If the list offsets are bigger than the struct items (easy if there are many lists) and there are multiple pages of offsets then the list encoding needs to force a page from the items page.  This causes `flush` to be called multiple times which the struct encoder wasn't expecting.  This would lead the struct header column to have multiple pages which, while not technically a problem, causes an assertion to fail on read.
We could relax the assertion but it is simpler to just not write that kind of file in the first place.
> fix: fix v2 error that can happen when writing list<struct<...>> with many empty lists

- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance/examples/full_text_search.rs
- parallelizing tokenizing
- processing doc's tokens by batch to avoid holding write lock for a long time
- parallelizing collecting token occurrences
- don't concat batches of inverted lists
- don't clone the token strings when writing the `TokenSet` 
- store positions continuously to reduce memory footprint
It's can't fully utilize the CPU cause the indexing process isn't friendly to parallelism, it's about 800% utilization with my 16 cores machine. But this still depends on the data, MS MARCO contains too many tokens that aren't English words.
the indexing time has been reduced to:
- no positions: reduced to ~7min from 25min on MS MARCO dataset.
- with positions: 10.5min on MS MARCO dataset.
the memory footprint has been reduced multiple times, especially with positions.
> perf: parallelize FTS indexing

- rust/lance/src/index/append.rs
The FTS index doesn't require the data be sorted, so just don't do it to save resources
> chore: don't sort the data when optimizing the FTS index

- python/python/lance/torch/data.py
- python/python/tests/torch_tests/test_data.py
Fixes #2819
<details>
<summary>Test script</summary>
```py
import lance
import pyarrow.compute as pc
import time
import lance.torch.data as ltd
import torch
from torch.utils.data import DataLoader
import numpy as np
dims = 128
nrows = 10_000_000
def next_batch(batch_size, offset):
values = pc.random(dims * batch_size).cast('float32')
return pa.table({
'id': pa.array([offset + j for j in range(batch_size)]),
'vector': pa.FixedSizeListArray.from_arrays(values, dims),
}).to_batches()[0]
def batch_iter(num_rows):
i = 0
while i < num_rows:
batch_size = min(10_000, num_rows - i)
yield next_batch(batch_size, i)
i += batch_size
schema = next_batch(1, 0).schema
ds_path_1 = "./temp-test-torch-1.lance"
lance.write_dataset(batch_iter(nrows), ds_path_1, schema=schema, …
```
> fix: torch to_tensor for FixedShapeTensorType data

- rust/lance/src/io/exec/scalar_index.rs
Fixes #2768
After these changes, we can do the query using <2GB of RAM instead of 33GB! 🚀
> perf: split MaterializeIndex stream into batches

- docs/format.rst
- java/core/lance-jni/src/blocking_dataset.rs
- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/scheduler.rs
- rust/lance-table/src/format/manifest.rs
- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/external_manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/dataset/write/update.rs
- rust/lance/src/index.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/io/commit/dynamodb.rs
- rust/lance/src/io/commit/external_manifest.rs
- rust/lance/src/utils/test.rs
This introduces `ManifestNamingScheme` with a `V1` and `V2` variant. `V1` is the existing naming scheme. `V2` uses a scheme optimized for object storage listing mechanisms, making looking up the latest manifest constant time.
**On S3, this makes `lance.dataset()` take only  125 ms, regardless of how many versions of the dataset existed. Previously this time grew linearly with number of versions.**
We also provide a method `migrate_manifest_paths_v2`. Because this method alters the manifest path scheme, and agreement on the scheme is critical for the write path, it's important is it not run while any read or write operations happen on that table. That's why this migration can't happen in the background like some other migrations.
Closes #2790
> feat: constant-time manifest lookup on object stores

- python/python/tests/test_file.py
- rust/lance-encoding/src/encoder.rs
- rust/lance-file/src/v2/writer.rs
Sometimes the v2 writer will split a batch into multiple pages.  When it does this it encodes those pages in parallel.  It is possible those encoding tasks finish out of order and the writer was then writing the pages out of order.  This mean the order of one column could get out of sync with the order of another column.
> fix: ensure the v2 file writer does not mix up the order of a column

- rust/lance-index/src/scalar/inverted/builder.rs
Tested it on MS MARCO and before this the remap can't be finished in 35m (I didn't wait for finishing because that's too long), and now it's 3.15min
> perf: parallelize remapping to improve FTS compaction

- rust/lance-index/src/scalar/inverted/index.rs
get 30% improvement with the concurrent loading,
can help reduce the cold latency of full text search
> perf: concurrent loading FTS index files

- python/python/tests/conftest.py
- python/python/tests/test_dataset.py
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
When decoding we have to "wait until more than X rows are ready"
There was an issue with how we handled empty lists.  For example, if the list offsets are:
```
0 10 30 60 60 100
```
The question is what do we do when we need to wait until more than 3 rows are ready.  3 rows means we have 60 items.  The old logic looked for the next offset greater than 60 (i.e. 100) and waited until we had 100 items.  This mirrors some logic we do on the reverse side when we calculate how many rows are available based on how many items we have.
However, that is wrong.  If we have 60 items we actually have 4 rows available and so we have more than 3 rows available.  The logic is much simpler.  Just wait until we have at least `offsets[desired_rows + 1]` items.  If that value is equal to …
> fix: calculate decode priority correctly

- rust/lance-datafusion/src/logical_expr.rs
- rust/lance-encoding/benches/decoder.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/write.rs
> fix: vector column mismatch should not be a IO Error

- python/python/tests/test_integration.py
The error that is raised by DuckDB in this situation changed between versions 1.0.0 and 1.1.0 but we don't really care too much.  We just want to make sure the error text is meaningful.
> chore: don't be so strict about checking the error type in duckdb test

- python/Makefile
The AWS integration tests were failing because we run out of disk space.  We have about 30GB of disk space per job.  Docker (setting up minio), the rust cache, building the wheels, and running the tests all utilize quite a bit of disk space.
As a (possibly short-term) solution we change the integration tests job to run only the integration tests and not all of the tests.
> chore: fix aws-integ-test from running out of disk space

- python/python/lance/file.py
- python/python/lance/lance/__init__.pyi
- python/python/tests/test_s3_ddb.py
- python/src/file.rs
- python/src/indices.rs
The PR propogates the storage_options to the LanceFileWriter and LanceFileReader and updates the code to create the object reader. 
Installed the package with local change:
`maturin develop`
Verified the following code didn't work before but works now
```
from lance.file import LanceFileReader, LanceFileWriter
uri = 's3://xxxxx'
storage_options = {
'aws_access_key_id': 'xxx',
'aws_secret_access_key': 'xxx'
}
table = pa.table({"a": [1, 2, 3]})
path = f"{lance_uri}/foo.lance"
global_buffer_text = "hello"
global_buffer_bytes = bytes(global_buffer_text, "utf-8")
with LanceFileWriter(str(path),storage_options=lance_storage_options) as writer:
writer.write_batch(table)
global_buffer_pos = writer.add_global_buffer(global_buffer_bytes)
reader = LanceFileReader(str(path), …
```
> feat: propagate `storage_options` to `LanceFileWriter` and `LanceFileReader`

- .github/workflows/pr-title.yml
- Cargo.toml
- ci/check_versions.py
- python/Cargo.toml
Forgot to increment the version in https://github.com/lancedb/lance/pull/2829
> ci: make it easier to see breaking change that fails ci job

- rust/lance-index/src/scalar/label_list.rs
- rust/lance/src/index/scalar.rs
> fix: check label list list column type earlier

- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
before it would return empty result if any word is unknown
> chore: always return error for phrase query if there's no position

- python/python/tests/test_scalar_index.py
- rust/lance-datafusion/src/expr.rs
- rust/lance-linalg/build.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index.rs
- rust/lance/src/index/scalar.rs
also fix BTree index isn't used if the column is with LargeUtf8 data type
> fix: can't filter on string column which has FTS index

- .github/workflows/rust.yml
- rust/lance/src/arrow/json.rs
> feat: support decimal 128 and 256 json types

- .github/workflows/pypi-publish.yml
This reverts commit 10c4c67d2328647a32e02b73a3879f0f6580c0a3.
For Amazon Linux 2, EOL June 2025, glibc 2.26.
> Revert "chore!: remove manylinux 2014 build (#2891)"

- python/python/tests/test_dataset.py
- rust/lance-core/src/utils/deletion.rs
- rust/lance/src/dataset/fragment.rs
We need to push back the scan start and potentially grab more rows than requested to make sure we fulfill the request.  For v2 files we could also convert the row range into multiple ranges instead of grabbing more rows than required.  This might be something to investigate in the future.
> fix: limit/offset pushdown was not working correctly in the presence of deletions

- Cargo.toml
- java/core/lance-jni/Cargo.toml
- java/core/pom.xml
- java/pom.xml
- java/spark/pom.xml
Solve the issue when publishing rust
```
- cargo package -v --no-verify                            ✔
error: all dependencies must have a version specified when packaging.
dependency `lance-encoding` does not specify a version
Note: The packaged dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```
Give the java pom correct versions
> fix: fix release versions

- python/python/lance/fragment.py
- python/python/tests/test_dataset.py
- python/src/fragment.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/updater.rs
- rust/lance/src/dataset/write/merge_insert.rs
There's a few other places where updater is used (e.g. merge_insert / add_columns) and we may want to review those paths as well.
This is technically a breaking change on the rust API and so I will mark it as such.
BREAKING CHANGE: `Fragment::updater` now accepts a new `batch_size` argument
> feat!: add batch_size option to merge_columns

- Cargo.toml
- java/core/pom.xml
- java/pom.xml
- java/spark/pom.xml
- python/Cargo.toml
Revert "Bump version"
This reverts commit https://github.com/lancedb/lance/commit/f3eef61e29e3c2211ace2d1fa47ef553d63cb8f6.
> fix: revert Bump version f3eef61

- .github/workflows/cargo-publish.yml
https://github.com/lancedb/lance/actions/runs/10908634424
v0.18.0 cargo release failed with timeout
enlarge the timeout and add workflow dispatch with tag
> fix: enlarge cargo release timeout and add workflow dispatch

- rust/lance-core/src/cache.rs
- rust/lance/src/session.rs
Right now the `Debug` for `Session` is just `Session()`, which is pretty unhelpful. Needed this recently to debug the cache.
> feat: make `Debug`  for  useful `Session`

- rust/lance-datafusion/src/exec.rs
- rust/lance/src/dataset/scanner.rs
Currently we log the debug representation of the plan (twice!) every time a plan is executed.  This is way too much information (e.g. the object store's debug information is repeated many times).  In one egregious case I was dealing with that had 8k fragments this was generating 35MB of log data!
This PR changes to an indented display representation of the plan.
> feat: log the execution plan in a more compact fashion

- python/python/tests/test_file.py
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/encodings/physical/basic.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/block_compress.rs
- rust/lance-encoding/src/encodings/physical/dictionary.rs
- rust/lance-encoding/src/encodings/physical/fixed_size_binary.rs
- rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/encodings/physical/packed_struct.rs
The recent encodings refactor https://github.com/lancedb/lance/pull/2817 broke our ability to write fixed size list arrays of nullable values (we could still handle nullable fixed size list arrays).  This PR restores the capability.
> fix: restore ability to write fixed size list of nullable

- rust/lance-io/src/local.rs
- rust/lance-io/src/object_reader.rs
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/traits.rs
- rust/lance-table/src/io/deletion.rs
When loading deletion files we were directly accessing `ObjectStore::inner` which bypasses the retry loop.  This makes loading deletion files somewhat brittle and was causing issues in scans (which can load a lot of deletion files at the same time they are loading lots of other ranges).
This PR changes the deletion file load to use the `ObjectStore` and adds convenience methods to make this easier in the future.
In the future we should also move this load to use a `FileScheduler` instead of `ObjectStore` so that these deletion file loads do not violate our max-iops-per-scan but that can be done later.
> fix: use retry loop when loading deletion files

- .github/workflows/build_linux_wheel/action.yml
- .github/workflows/cargo-publish.yml
- .github/workflows/pypi-publish.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
- rust/lance-linalg/build.rs
- rust/lance-linalg/src/distance/dot.rs
> chore: change default compiler to clang

- python/python/benchmarks/test_compression.py
- python/python/tests/test_file.py
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
This allows block compression (zstd) in the narrow case of using it for binary data.  A more generalized approach to block compression can be handled as part of 2.1.
> feat: reconnect block compression

- python/python/lance/torch/distance.py
- python/python/tests/test_indices.py
The first problem is that we were filling the ids array with NAN if the distance was NAN but that leads to the ids array becoming float which torch doesn't like.
The second is that we were reshaping after filling instead of filling and then reshaping.  The old approach led to broadcasting the ids matrix from [N;1] to [N;N].
> fix: fix dot distance for cuda

- python/python/lance/dataset.py
- python/python/lance/fragment.py
- python/python/lance/ray/sink.py
- python/python/tests/test_dataset.py
- rust/lance/src/dataset.rs
This was supposed to be the logic but was not tested and was not being used correctly.
> fix: use existing storage version on overwrite, if none specified

- rust/lance-datafusion/src/planner.rs
> fix: support negative values in SQL array literals

- python/python/tests/test_dataset.py
- rust/lance-io/src/scheduler.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/io/exec/scan.rs
We read batches from data files in a round-robin fashion.  With the old priority mechanism all data in file 1 would be scheduled before file 2.  This means we'd deadlock if file 1 was bigger than the I/O buffer size.
Now, each fragment has a unique priority, but the priority within the fragment is the same for all data files.
This should avoid deadlock as long as the I/O buffer size is larger than any given batch (may want to issue warning or fail if we can detect when the batch size is too large).
> fix: v2 deadlock when there are multiple data files

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance-arrow/src/lib.rs
- rust/lance-arrow/src/schema.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance-io/src/object_store.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec/take.rs
Previously we always used late materialization.  In many cases this resulted in far too many IOPS which impacted the performance (and the cost) of queries.
The new approach uses early materialization for cloud storage (except for variable sized fields)
For local storage any field that has 10 or fewer bytes per value is early materialized
> feat: allow users to specify late/early materialization, adjust default threshold

- rust/lance-io/src/scheduler.rs
This also fixes a bug where we were not shutting down the I/O loop which would eventually lead to a small memory leak.
> feat: add an optional process-wide limit for IOPS

- rust/lance/src/index/vector/ivf/v2.rs
In testing we saw that `refine_factor` was not increasing recall even when set to a large enough value that it should be doing brute force search in V3 indices. After tracing through the code we found that `refine_factor` was not being utilized in the individual partitions `search_in_partition` function, so they could only return at most `k` values to be refined. This change makes it so that the `search_in_partition` function will return `refine_factor * k` values for further refinement.
> fix: `refine_factor` should be used in `search_in_partition` for IVF V2 Indices

- python/python/lance/dataset.py
- python/python/tests/test_vector_index.py
- python/src/dataset.rs
- rust/lance-index/src/optimize.rs
- rust/lance/src/index.rs
- rust/lance/src/index/append.rs
lance in rust would cache the index metadata so no need to cache it in python.
- also added an option to control which indices to optimize
- also added tests for optimize_indices
> fix: list_indices never updated after first call

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance/src/dataset/scanner.rs
There are some cases today where scalar indices can make query performance worse.  This is usually when a scalar index search has many results (e.g. "x != 7").  Ideally, we will fix our planner to not use the scalar index in this case.  However, even if we do that, there will probably be cases where it would be nice (for debugging purposes if nothing else) to be able to disable the scalar index for a query.
> feat: allow scalar indices to be disabled for a query

- python/src/file.rs
- rust/lance-core/src/cache.rs
- rust/lance-core/src/utils.rs
- rust/lance-core/src/utils/path.rs
- rust/lance-datafusion/src/substrait.rs
- rust/lance-encoding-datafusion/src/lib.rs
- rust/lance-encoding-datafusion/src/substrait.rs
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/benches/decoder.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/benches/reader.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/testing.rs
- rust/lance-index/benches/inverted.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/vector/ivf/shuffler.rs
- rust/lance-index/src/vector/v3/shuffler.rs
- rust/lance/benches/scalar_index.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/index.rs
- rust/lance/src/index.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
There is still a bit more testing work to do before pushdown is fully supported in v2 and until we start using `LanceDfFieldDecoderStrategy` in the file reader it won't be accessible to users.  However, this PR has a number of structural refactors for v2 and is big enough as it is.
This adds a cache to the v2 schedulers.  This is needed in this PR because we want to use the cache to store zone maps.  However, it will be needed in future 2.1 work as well because we want to cache things like "rows per chunk" and "dictionaries".
This adds an initialization routine to v2 schedulers.  Again, this is needed for zone maps but will also be used by 2.1 features.
Lastly, this PR does, in fact, reconnect the zone maps feature, restoring blocks that had been commented out.
> feat: reconnect pushdown to v2

- python/python/lance/ray/sink.py
- python/python/tests/test_ray.py
Reproduce python code:
```python
import ray
from lance.ray.sink import LanceDatasink
ray.init()
sink = LanceDatasink("./data.lance")
ray.data.range(10).filter((lambda row: row["id"] > 10)).map(lambda x: {"id": x["id"], "str": f"str-{x['id']}"}).write_datasink(sink)
```
When using the lance ray sink to write lance file, the empty sink which may be caused by filter operator in ray data will cause these exception. 
```
File "/opt/conda/lib/python3.11/site-packages/ray/data/dataset.py", line 3621, in write_datasink
datasink.on_write_complete(write_results)
File "/opt/conda/lib/python3.11/site-packages/lance/ray/sink.py", line 141, in on_write_complete
op = lance.LanceOperation.Overwrite(schema, fragments)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 5, in __init__ …
```
> fix: fix ray sink error when there are no data to write

- rust/lance-core/src/cache.rs
- rust/lance/src/index/cache.rs
- rust/lance/src/index/vector/ivf/v2.rs
- remove dup cache size consts
- replace the index size param
> fix: remove dup cache consts and respect index size param

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/wand.rs
> fix: don't always include first doc

- rust/lance-core/src/error.rs
- rust/lance-datafusion/src/logical_expr.rs
- rust/lance-datafusion/src/planner.rs
Show as invalid input instead of server internal error
> feat: improve datafusion SQL planning and parsing errors

- rust/lance/src/dataset.rs
- rust/lance/src/io/commit.rs
Fixes https://github.com/lancedb/lance/issues/2403
> fix: better error for concurrent create

- .github/workflows/rust-benchmark.yml
Cronjob to generate report on https://lancedb.github.io/lance-benchmark-results/dev/bench/
> ci: run rust benchmark and generate report

- python/python/tests/test_file.py
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
> fix: include the list item field schema

- docs/read_and_write.rst
- python/python/tests/test_dataset.py
- rust/lance-datafusion/src/planner.rs
Adds support for accessing list items and struct fields with subscripting: `x[0]` and `x['field_name']`. These can be chained.
Unfortunately there is an issue with our SQL parser related to using `.` I wasn't able to figure out. Follow up issue here: https://github.com/lancedb/lance/issues/2967
> feat: nested list access

- python/python/lance/__init__.py
- python/python/lance/blob.py
- python/python/tests/test_blob.py
Many APIs for working with binary data expect file objects.  This PR adds a small utility to convert a binary array into an iterable of file objects.
This will get more sophisticated in future releases where the input can be a column or row ids instead of a binary array (allowing for sort of scan on demand workflow that will be more memory efficient for extremely large blobs)
> feat: add a python API for reading arrays of binary/large_binary as file objects

- protos/encodings.proto
- python/python/tests/test_file.py
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/Cargo.toml
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/bitmap.rs
- rust/lance-encoding/src/encodings/physical/dictionary.rs
- rust/lance-encoding/src/encodings/physical/fixed_size_binary.rs
- rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
- rust/lance-encoding/src/encodings/physical/packed_struct.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/lib.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance-io/src/scheduler.rs
Compared to the regular large binary encoding this will have considerably less metadata (since there will be fewer pages).  In the future it will also be possible to read just the descriptions (allowing for different ways of reading the data such as file objects).
The scheduling algorithm is also more conservative as well.  We don't fetch descriptions until we need them and we only read in one batch of blob data at a time (instead of an entire page).  This means the reader will probably be slightly less performant (though, when reading values this large, it shouldn't be too noticeable) but will use considerably less RAM.
> feat: add a blob encoding for large binary values

- rust/lance/src/dataset.rs
This is faster than doing `dataset.checkout_version(dataset.latest_version_id().await?).await?`, since we don't need to do an extra IOP to get the size and manifest path style of the version. (We do this in LanceDB right now.)
> feat(rust): add checkout_latest to Dataset

- java/.gitignore
- java/core/lance-jni/src/blocking_dataset.rs
- java/core/lance-jni/src/fragment.rs
- java/core/lance-jni/src/utils.rs
- java/core/src/main/java/com/lancedb/lance/Dataset.java
- java/core/src/main/java/com/lancedb/lance/Fragment.java
- java/core/src/main/java/com/lancedb/lance/FragmentOperation.java
- java/core/src/main/java/com/lancedb/lance/WriteParams.java
- java/core/src/test/java/com/lancedb/lance/FragmentTest.java
- java/core/src/test/java/com/lancedb/lance/TestUtils.java
- java/spark/src/main/java/com/lancedb/lance/spark/LanceCatalog.java
- java/spark/src/main/java/com/lancedb/lance/spark/LanceConfig.java
- java/spark/src/main/java/com/lancedb/lance/spark/SparkOptions.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceDatasetAdapter.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceFragmentScanner.java
- java/spark/src/main/java/com/lancedb/lance/spark/write/LanceDataWriter.java
#2854
Set storage options configuration in spark-default
```
spark.sql.catalog.lance com.lancedb.lance.spark.LanceCatalog
spark.sql.catalog.lance.access_key_id AKAKAKAKAKAKAKAKAKAKAKAKAKAKAKAKAKAKAKAK
spark.sql.catalog.lance.secret_access_key SKSKSKSKSKSKSKSKSKSKSKSKSKSKSKSKSKSK
spark.sql.catalog.lance.aws_region region
spark.sql.catalog.lance.aws_endpoint https://Endpoint
spark.sql.catalog.lance.virtual_hosted_style_request true
```
Then you can read and write lance file for object store.
```scala
val df = Seq(
("Alice", 1),
("Bob", 2)
).toDF("name", "id")
df.write.format("lance").option("path", "s3://test/lance/demo.lance").save()
val data = spark.read.format("lance").option("path", "s3://test/lance/demo.lance").load();
data.show(10)
```
> feat: support storage options for spark read and write

- python/python/benchmarks/test_index.py
- python/python/lance/dataset.py
- python/python/lance/vector.py
- python/python/tests/test_dataset.py
This feature improves disk IO dependence, but it is quite limited. This only works if the index type is IVF_PQ, and it will not work efficiently for local PQ in the future (unless we store _all_ the PQ models in VRAM).
Importantly, this allows us to bypass local temp storage for storing residuals. However, this still stores PQ codes locally temporarily due to how we've implemented accelerator support, but these are much smaller (exact ratio depends on params).
I tested on my local machine, which is sufficiently fast that the accelerated builds are IO limited (but IO is also fast). I used wikipedia-40M
New feature disabled:
ivf training time: 52s
ivf transform time: 89s
pq training time: 18s
pq assignment time: 143s
create_index rust time: 8.9s
New feature enabled:
combined training time: …
> feat: one-pass IVF_PQ accelerated builds

- protos/table.proto
- protos/transaction.proto
- python/src/dataset.rs
- rust/lance-table/README.md
- rust/lance-table/src/feature_flags.rs
- rust/lance-table/src/format/manifest.rs
- rust/lance-table/src/io/manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/utils/test.rs
Closes #2200 
#2200 reference the concept of "table metadata". This PR uses the name "config" to avoid potential confusion with other uses of the word "metadata" throughout the Lance format.
This PR introduces:
- A new `table.proto` field called `config`.
- New `Dataset` methods: `update_config` and `delete_config_keys`.
- `config` field in `Manifest` with public methods for updating and deleting.
- A new transaction operation `UpdateConfig` along with conflict logic that returns an error if an operation mutates a key that is being upserted by another operation.
- A new writer feature flag called `FLAG_TABLE_CONFIG`.
- Unit tests for new `Dataset` methods, concurrent config updaters, and conflict resolution logic.
> feat: add table config

- rust/lance/src/index.rs
Create the vector index error when the schema has nullable field.
When the vector column had build index already, the dataset scaner will assign the filter in function `compute_partitions`.
```python
if dataset.schema.field(column).nullable and filter_nan:
filt = f"{column} is not null"
else:
filt = None
```
The scanner will use the scalar index scanner and this scanner treat the vector index as scalar index(btree index).
This pr will filter the vector index in `scalar_index_info` and it will only return the scalar index now.
> fix: filter the vec index in function Index::scalar_index_info

- rust/lance/src/index.rs
This PR adds a field to `index_stats` where we now return the number of rows covered by each delta in `num_indexed_rows_per_delta`
TODO:
> feat: expose number of rows covered per delta

- protos/encodings.proto
- protos/file2.proto
- python/python/tests/test_file.py
- python/src/file.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance/src/dataset/write/merge_insert.rs
Adds a mini-block encoder
Adds "structural encoder" (2.1 concept) for struct and primitive
Adds compressor impl's for value compression
> feat: add the basic encode path for 2.1

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/take.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/take.rs
I was trying to add a new option (load_blobs) to the scan exec and realized the args had gotten a little out of control.  I refactored them into a struct.  I've since abandoned my original idea (load_blobs) but wanted to see if others felt the refactor was worth keeping.
> refactor: convert scan args into struct

- python/Cargo.toml
- python/python/lance/dataset.py
- python/python/lance/file.py
- python/python/tests/test_schema_evolution.py
- python/src/dataset.rs
- rust/lance/src/dataset/schema_evolution.rs
The existing `add_columns` capability works well when you have a UDF or SQL function that you want Lance to run for you.  However, there are times when the new column values have already been determined (e.g. when a cluster farmed out the calculation of the values).  In this case we want a simple way to add new columns from existing values.
> feat: make it possible to add columns from existing data

- python/python/tests/test_blob.py
- rust/lance/src/dataset/blob.rs
When `read` returns it should update the cursor to the end of the data just read.  However, we were calculating this as `end` and not `end - position`.
The cursor is supposed to be relative to the start of the blob in the file (e.g. 0 == `position`).
> fix: update cursor correctly in blob file API

- rust/lance-index/src/scalar/lance_format.rs
- rust/lance/src/dataset.rs
> fix: create FTS on empty table/strings

- python/python/lance/torch/distance.py
Else we get OOMs with too many centroids + too many dimensions + not enough vram
> perf: reduce the minimum chunk size for l2 distance calculations

- .github/workflows/pr-title.yml
Part of the job checks out the pull request (this isn't done automatically because this runs with `pull_request_target` which checks out the base by default).
That step was using `merge_commit_sha` which is not correct (this still checks out the base).  The fix instead checks out `head.sha` which is correct.
It is not possible to get a `merge_commit_sha`  (there is a request for this [here](https://github.com/actions/checkout/issues/518)) but `head.sha` should be good enough for our purposes.
> ci: fix version check CI job

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec/fts.rs
this introduces multiple fields FTS in `best_fields`, it finds documents that match any field, and uses the score from the best field.
> feat: support FTS on multiple fields

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance-table/src/format.rs
- rust/lance-table/src/format/manifest.rs
- rust/lance-table/src/io/commit.rs
- rust/lance/src/dataset.rs
- rust/lance/src/io/commit.rs
A detached commit is a commit that is not part of the regular dataset lineage.  It will never show up as the latest commit and is completely separate from the linear history of the dataset.
This can be useful for:
* Making temporary changes to a dataset, like adding a column of values while computing an index without ever truly materializing the column.
* Situations where the dataset's lineage is managed remotely and all commits are detached commits without any linear history (blob storage will use this)
Closes #2889
> feat: adds support for detached commits

- .github/workflows/run_integtests/action.yml
- python/pyproject.toml
The ray pin is due to #3042 
The numpy pin was previously added because pyarrow was not compatible with numpy 2.  However, I believe that problem has since been resolved.
> chore: pin ray version <2.38 and remove numpy pin

- protos/encodings.proto
- rust/lance-core/src/datatypes.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/block_compress.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/format.rs
This PR aims to address https://github.com/lancedb/lance/issues/3033, and expose the compression level for general compression.
> feat: expose compression-level configuration for general compression

- java/core/lance-jni/src/blocking_scanner.rs
- python/python/lance/__init__.py
- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/python/tests/test_integration.py
- python/src/dataset.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
This is particularly useful for operations like "delete by id"
I ran into a fair bit of difficulty with this PR and punted a few things to follow-ups (#2971 #2972).
> feat: make it possible to use rowid and rowaddr in filters

- python/python/tests/test_ingestion.py
- rust/lance-core/src/datatypes.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance-file/src/writer.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/write.rs
Previously, we used batch schema to check if incoming data was compatible with the dataset.  This has a few problems:
* You couldn't add a non-nullable batch to a nullable dataset even though this should be perfectly valid
* You couldn't add a nullable batch to a non-nullable dataset even when the batch didn't contain nulls
* It's possible (and with pyarrow, easy) to create a batch that has nulls but the fields are marked non-null, this led to confusing errors.
This PR resolves those issues by checking the null count of the actual arrays instead of relying on the schema assigned to the data.
Closes #1936
> feat: more flexible and sophisticated handling of non-null constraints

- rust/lance-index/src/vector/graph.rs
TL;DR: `PartialOrd` impl for `f32` requires two cmp instructions and `PartialOrd::lt` is not reduced to a single instruction. With `total_cmp` we avoid this overhead. See https://godbolt.org/z/ez4EaEs3W
Note: maybe we could gain more perf by implementing a `NaN-less` cmp?
V1:
```
Running query with nprobes: 1, refine_factor: 0
Time: 652.877µs
Running query with nprobes: 10, refine_factor: 0
Time: 818.418µs
Running query with nprobes: 50, refine_factor: 0
Time: 1.406433ms
Running query with nprobes: 100, refine_factor: 0
Time: 1.747243ms
Running query with nprobes: 512, refine_factor: 0
Time: 5.754752ms
```
V3 before perf fix
```
Running query with nprobes: 1, refine_factor: 0
Time: 752.659µs
Running query with nprobes: 10, refine_factor: 0
Time: 2.379638ms
Running query with nprobes: 50, …
```
> perf: use total cmp for ordered float

- python/python/lance/dataset.py
- python/python/lance/indices.py
- python/python/tests/test_indices.py
- python/python/tests/test_vector_index.py
This was being checked deep in the Rust code on the CPU path.  However, on the accelerator path it was creating the index which would then give obscure errors when attempts were made to search it.
This PR adds a check early in the python code and adds unit tests for the various ways indices can be created.
> fix: verify num_sub_vectors is valid before creating index

- rust/lance/src/index/vector/ivf/v2.rs
V1 baseline
```
Running query with nprobes: 1, refine_factor: 0
Time: 652.877µs
Running query with nprobes: 10, refine_factor: 0
Time: 818.418µs
Running query with nprobes: 50, refine_factor: 0
Time: 1.406433ms
Running query with nprobes: 100, refine_factor: 0
Time: 1.747243ms
Running query with nprobes: 512, refine_factor: 0
Time: 5.754752ms
```
V3 after fix
```
Running query with nprobes: 1, refine_factor: 0
Time: 667.621µs
Running query with nprobes: 10, refine_factor: 0
Time: 707.589µs
Running query with nprobes: 50, refine_factor: 0
Time: 1.213155ms
Running query with nprobes: 100, refine_factor: 0
Time: 1.559892ms
Running query with nprobes: 512, refine_factor: 0
Time: 5.597119ms
```
> perf: parallel search partitions in subindex

- rust/lance-encoding/src/encodings/physical/block_compress.rs
- rust/lance-encoding/src/statistics.rs
This PR tries to add granularity of 1024 for computing bit_width, it can enable more fine grained bit width selection when do bit-packing
> chore: add granularity of 1024 to bit_width stats

- python/python/lance/sampler.py
- python/python/lance/torch/data.py
- python/python/tests/torch_tests/test_data.py
This will solve the downstream issue: https://github.com/lancedb/lancedb/issues/1766
> fix: always return correct batch size

- .github/workflows/java-publish.yml
- java/core/pom.xml
Now the lance java package only support build with debug mode.
Add a propertiy to support build with release mode.
```bash
mvn clean package -DskipTests -Drust.release.build=true
mvn clean package -DskipTests
```
> feat: support build lance java with rust release mode

- protos/file.proto
- protos/file2.proto
- protos/table.proto
- protos/transaction.proto
- python/python/tests/test_blob.py
- python/python/tests/test_file.py
- python/src/fragment.rs
- rust/lance-core/src/datatypes.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance-core/src/error.rs
- rust/lance-core/src/lib.rs
- rust/lance-file/src/datatypes.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-table/src/format/manifest.rs
- rust/lance-table/src/io/manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/blob.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/dataset/write/update.rs
- rust/lance/src/index.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/io/exec.rs
- rust/lance/src/io/exec/utils.rs
I'm open to terms other than "storage class" as well.  I also think we might want to use something other than "blob" as it can be easy to confuse the concepts of "blob encoding" (e.g. low page overhead, file-like API) and "blob storage class" (fewer rows per file).  In fact, the thresholds can even be different with the blob encoding threshold being 8-16MB but the blob storage class threshold being closer to 128KB
Closes #3029
> feat: introduce concept of "storage class" wtih separate dataset for "blob" storage data

- rust/lance-encoding/src/statistics.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance/src/dataset/transaction.rs
This PR tries to remove the cardinality calculation for fixed width data block, so we can speed up the write speed.
#3069
> chore: remove cardinality statistic gathering for fixed width data block

- rust/lance-encoding/src/statistics.rs
max length statistics can be used to for encoding selection of Variable-Width-Datablock(string, binary, etc.)
> feat: add max length statistics to VariableWidth Datablock

- rust/lance-core/src/utils/mask.rs
- rust/lance-index/src/scalar/bitmap.rs
Use `roaring::MultiOp` for faster union of bitmaps.
TODO:
> perf: implement fast path for union many row id tree map

- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/statistics.rs
This PR adds a `Compute_Stat` trait to DataBlock, to separate the statistics computation and statistics inquiry.
This PR also modifies `do_flush` and `encode_miniblock` in `PrimitiveStructuralEncoder` to enable write variable width data in 2.1(PrimitiveStructuralEncoder)
> feat: enable write variable width data in 2.1

- python/python/lance/dataset.py
- python/python/tests/test_balanced.py
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/take.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/update.rs
This allows compaction to succeed on the default storage.
Running compaction on the sibling storage can be added in a future PR.
In addition, this PR adds quite a few more test cases to make sure that a balanced dataset either performs as expected or gives a good "not yet supported" error message.
In addition, this PR reworks the dataset-offset based take (e.g. `LanceDataset::take`) to reuse the id-based & address-based take paths (e.g. `TakeBuilder`)
It also fixes a bug in the `TakeBuilder` path where duplicate IDs were not being handled.
These latter changes are not strictly needed but are preparing for an eventual revamp of the take operation to address https://github.com/lancedb/lance/issues/2977
> feat: add compaction support to balanced datasets

- python/python/tests/test_blob.py
- python/python/tests/test_file.py
- rust/lance-core/src/utils/bit.rs
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/benches/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/writer.rs
This ensures that all file buffers are aligned to 64 bytes (these are generally 8MiB buffers and so 64 bytes is trivial)
We also ensure that all mini-block chunks are aligned to 8 bytes.  This introduced a bit more padding but makes it easier to do things like store offsets into mini-block chunks.
> feat: align buffers in 2.1 files

- Cargo.toml
- rust/lance-datafusion/src/planner.rs
- rust/lance-encoding/src/data.rs
- rust/lance-io/benches/scheduler.rs
- rust/lance/benches/ivf_pq.rs
- rust/lance/benches/scan.rs
- rust/lance/benches/vector_index.rs
- rust/lance/src/bin/lq.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/io/exec/knn.rs
Follow up to #3074
Adds a clippy lint to say no println. Many of the leftovers were in tests.
> ci(rust): enforce no println

- python/python/lance/dataset.py
- python/python/lance/vector.py
- python/python/tests/test_vector_index.py
- rust/lance-index/src/vector/ivf/shuffler.rs
* cast ivf centroids to the same type as vectors before inference
* cast codebook to the same type as ivf centroid before passing to rust
* fix typing syntax
> fix: fp16 GPU training

- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
This PR tries to fix a logic error during selecting miniblock encoder.
> chore: fix miniblock selection logic error

- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/testing.rs
We align buffers in the file writer but we were not doing the same thing in the test utility.  This forced encodings to do extra copies.  We remove one such copy in this PR.
Closes #3115
> chore: lance-encoding test utility now properly aligns buffers

- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/storage.rs
- rust/lance-index/src/vector/quantizer.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/ivf/io.rs
- rust/lance/src/index/vector/ivf/v2.rs
- rust/lance/src/index/vector/pq.rs
30% improved:
```
5242880,L2,PQ=96,DIM=1536
time:   [161.24 ms 162.71 ms 164.08 ms]
change: [-30.390% -29.789% -29.192%] (p = 0.00 < 0.10)
Benchmarking 5242880,Cosine,PQ=96,DIM=1536: Warming up for 3.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 9.2s or enable flat sampling.
5242880,Cosine,PQ=96,DIM=1536
time:   [165.53 ms 167.12 ms 168.49 ms]
change: [-30.725% -30.233% -29.772%] (p = 0.00 < 0.10)
```
> perf: transpose the PQ codes to improve search performance

- protos/encodings.proto
- rust/lance-core/src/utils/bit.rs
- rust/lance-encoding/src/buffer.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/fixed_size_list.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/lib.rs
- rust/lance-encoding/src/repdef.rs
The encoding is only tested on tensors for now.  It should encode variable-width data but, without a repetition index, we are not yet able to schedule / decode variable width data.  In addition, I've created a few todos for follow-up.
> feat: add full zip encoding for wide data types

- protos/encodings.proto
- rust/lance-encoding/src/compression_algo/fsst/src/fsst.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/format.rs
This PR tries to integrate mini-block page layout with FSST compression.
During compression, it first FSST compresses the input data then write out the data use `BinaryMiniBlockEncoder`.
During decompression, it first uses `BinaryMiniBlockDecompressor` to decode the raw data read from disk, it then applies `FSST decompression`.
> feat: fsst compression with mini-block

- .github/workflows/java-publish.yml
- java/spark/pom.xml
- java/spark/src/main/java/com/lancedb/lance/spark/write/LanceArrowWriter.java
Remove the queue in LanceArrowWriter since it may cache all rows in queue and that will require a lot of jvm memory.
Use mutex to control the write rate of sinker. Writer will wait util the reader take the batch.
And more I had moved the `maven-shade-plugin` into a new profile which is diabled by default because `jar-with-dependencie` was conflict with many jars in spark dependencie
> refactor: remove the queue in LanceArrowWriter to reduce memory usage for spark sink

- Cargo.lock
- protos/table.proto
- python/Cargo.lock
- python/src/dataset.rs
- rust/lance-encoding/src/compression_algo/fsst/examples/benchmark.rs
- rust/lance-index/src/scalar.rs
- rust/lance-table/build.rs
- rust/lance-table/src/format/index.rs
- rust/lance/Cargo.toml
- rust/lance/examples/full_text_search.rs
- rust/lance/examples/hnsw.rs
- rust/lance/examples/ivf_hnsw.rs
- rust/lance/examples/write_read_ds.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/index.rs
- rust/lance/src/index/cache.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/io/commit.rs
This addresses a specific problem.  When a dataset had a scalar index on a string column we would perform I/O during the planning phase on every query that contained a filter.  This added considerably latency (especially against S3) to query times.
We now cache that lookup.
It also starts to tackle a more central problem as well.  Right now we our manifest stores very little information about indices (pretty much just the UUID).  Any further information must be obtained by loading the index.  This PR introduces the concept of "index details" which is a spot that an index can put index-specific (e.g. specific to btree or specific to bitmap) information that can be accessed during planning (by just looking at the manifest).  At the moment this concept is still fairly bare bones but I think, …
> feat: start recording index details in the mainifest, cache index type lookup

- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/benches/decoder.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-file/src/v2/reader.rs
This ensures that the setup routines happen inside of the benchmark function.  Otherwise datagen will be run for all benchmarks during the collection phase and the system will run out of RAM.
This also changes the routines to use `FileMetadataCache::no_cache` as it turns out `moka` doesn't immediately free its cache space on drop and, when used in a tight benchmark loop, this leads to running out of memory.
> chore: cleanup decoder benches

- rust/lance/src/dataset.rs
This will be used when we add list_versions to the remote SDK
> feat: make dataset version serializable

- Cargo.lock
- Cargo.toml
- java/core/lance-jni/src/utils.rs
- python/Cargo.lock
- python/Cargo.toml
- rust/lance-index/src/vector/pq.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index/vector.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
This also supports to create v3 IVF_PQ in Rust, then it introduces a breaking change
> fix!: low recall with cosine/dot on v3 index types

- rust/lance-index/src/vector/flat/index.rs
- rust/lance-index/src/vector/flat/storage.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/storage.rs
- rust/lance-index/src/vector/sq/storage.rs
- rust/lance-index/src/vector/storage.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index/vector.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
also introduces `distance_all` methods to distance calculator, to improve the new IVF_PQ search performance
we store the 4bit PQ codes in half-bytes
> feat: support 4bit PQ on new IVF_PQ

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/lib.rs
- rust/lance-core/src/cache.rs
- rust/lance-io/src/object_store.rs
- rust/lance-table/src/format/fragment.rs
- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/external_manifest.rs
- rust/lance-table/src/io/manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/dataset/write/update.rs
- rust/lance/src/index.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/utils/test.rs
* Cache transaction files
* Read transaction files with concurrency within commit loop
Closes #3057
> perf: optimize reading transactions in commit loop

- rust/lance/src/index/vector/pq.rs
It panicked when it applies filter on an empty partition
```
thread 'index::vector::pq::tests::test_filter_on_empty_pq_code' panicked at rust/lance/src/index/vector/pq.rs:125:14:
chunk size must be non-zero
```
> fix: handle filter on empty partition

- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/dynamodb.rs
- rust/lance-table/src/io/commit/external_manifest.rs
- rust/lance/src/io/commit/dynamodb.rs
First PR of https://github.com/lancedb/lancedb/issues/1812
Add the delete function to external manifest to delete manifest related metadata during drop_table
> fix: fix dynamodb drop table

- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance/src/index.rs
this can be reproduced by optimizing FTS without any new data.
the existing tokens could be reordered then the `offsets` broken, leads to the index would return random results.
existing tests only verify whether the new data can be queried, so we didn't find this bug.
added a test to query existing data
> fix: full text search index broken after optimize_indices()

- rust/lance-index/Cargo.toml
- rust/lance-index/benches/4bitpq_dist_table.rs
- rust/lance-index/benches/pq_dist_table.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/distance.rs
this is done by make the compiler know the size of distance table slice
```
5242880,L2,PQ=96,DIM=1536
time:   [148.44 ms 149.47 ms 150.50 ms]
change: [-53.716% -53.486% -53.252%] (p = 0.00 < 0.10)
5242880,Cosine,PQ=96,DIM=1536
time:   [191.84 ms 192.21 ms 192.75 ms]
change: [-46.738% -46.621% -46.461%] (p = 0.00 < 0.10)
```
> perf: improve PQ computing distances

- Cargo.lock
- java/core/lance-jni/Cargo.toml
- java/core/lance-jni/src/fragment.rs
- rust/lance-core/src/error.rs
- rust/lance-datafusion/src/utils.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/fragment/write.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/insert.rs
- rust/lance/src/dataset/write/merge_insert.rs
This PR allows end-users to use `SendableRecordBatchStream` and `Schema` directly for writing or appending a dataset.
It's vital to write&append async streams to a dataset.
Partially resolves #1792.
This PR has a side-effect like below.
* peek_stream_schema => abstracted by `StreamingWriteSource::into_stream_and_schema`.
* StreamingWriteSource
- StreamingWriteSource::into_stream => Prior `reader_to_stream` but also supports Streams.
- StreamingWriteSource::into_stream_and_schema => Prior (`reader_to_stream`, `peek_stream_schema`) but also supports Streams.
> feat: allow async stream for writing and appending to a dataset

- rust/lance-index/benches/pq_dist_table.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/utils.rs
- rust/lance-linalg/src/distance/l2.rs
```
construc_dist_table: 16000,l2,PQ=96,DIM=1536
time:   [157.75 µs 157.97 µs 158.19 µs]
change: [-28.865% -28.731% -28.581%] (p = 0.00 < 0.10)
construc_dist_table: 16000,dot,PQ=96,DIM=1536
time:   [275.56 µs 276.02 µs 276.47 µs]
change: [-2.8930% -2.4637% -2.0839%] (p = 0.00 < 0.10)
```
> perf: improve constructing dist table

- rust/lance/src/datafusion.rs
- rust/lance/src/datafusion/dataframe.rs
- rust/lance/src/utils/test.rs
This makes it easier to use `Lance` inside of datafusion (see unit test for example)
> feat: expose the table provider

- python/pyproject.toml
https://github.com/lancedb/lancedb/issues/1324 requires minimal pyarrow to be 14.0
https://arrow.apache.org/docs/14.0/python/generated/pyarrow.concat_tables.html
> chore(python): set minimal pyarrow to 14.0

- rust/lance-index/benches/4bitpq_dist_table.rs
- rust/lance-index/src/vector/pq/distance.rs
for 8bit:
time:   [582.61 µs 585.08 µs 587.42 µs]
change: [-9.7495% -6.2223% -2.3288%] (p = 0.01 < 0.10)
for 4bit:
time:   [549.20 µs 551.13 µs 553.55 µs]
change: [-38.117% -37.734% -37.350%] (p = 0.00 < 0.10)
> perf: improve dot distance computing

- rust/lance-encoding/src/decoder.rs
In https://github.com/lancedb/lance/pull/2913 we added an initialization routine to the scheduler.  Unfortunately, this caused a problem.  It put `schedule_ranges` behind an await which means that we wouldn't schedule ranges for all files in a scan immediately.  Instead, we wouldn't begin scheduling file X until we had reached nearly the last batch of file X-1.  This introduced stuttering in the read path and had a significant effect on performance.
The fix here moves the initialization into the dedicated scheduler thread and keeps the creation of the scheduler a synchronous task which is actually a bit simpler anyways I think.
> fix: fix performance regression introduced during reader refactor

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/inverted/wand.rs
> fix: panic if all docs are deleted in a posting list

- .github/workflows/benchmarks.yml
- .github/workflows/ci-benchmarks.yml
- python/python/ci_benchmarks/__init__.py
- python/python/ci_benchmarks/benchmarks/test_random_access.py
- python/python/ci_benchmarks/benchmarks/test_scan.py
- python/python/ci_benchmarks/benchmarks/test_search.py
- python/python/ci_benchmarks/datagen/__init__.py
- python/python/ci_benchmarks/datagen/gen_all.py
- python/python/ci_benchmarks/datagen/lineitems.py
- python/python/ci_benchmarks/datasets.py
Benchmarks report to https://bencher.dev/console/projects/weston-lancedb/plots
At some point it may be nice for these to be used for regression detection in PRs.  However, we need to get a stable baseline first.
These benchmarks rely on a private runner hosted by LanceDB and some private datasets.  They run against GCS.  It would be good to get some NVME & Azure & S3 benchmarks at some point.
> ci: add benchmark suite

- java/core/lance-jni/src/fragment.rs
- java/core/lance-jni/src/utils.rs
- java/core/src/main/java/com/lancedb/lance/Fragment.java
- java/core/src/main/java/com/lancedb/lance/FragmentMetadata.java
- java/core/src/test/java/com/lancedb/lance/FragmentTest.java
- java/core/src/test/java/com/lancedb/lance/ScannerTest.java
- java/core/src/test/java/com/lancedb/lance/TestUtils.java
- java/core/src/test/java/com/lancedb/lance/TestVectorDataset.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceDatasetAdapter.java
- java/spark/src/main/java/com/lancedb/lance/spark/write/LanceDataWriter.java
- java/spark/src/test/java/com/lancedb/lance/spark/write/SparkWriteTest.java
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/fragment/write.rs
Now `FileFragment::create` only support create one file fragment and in spark connector will cause these two issues:
1. if the spark task is empty, this api will have exception since there is no data to create the fragment.
2. if the task data stream is very large, it will generate a huge file in lance format. It is not friendly for spark parallism.
So I remove the assigned fragment id and add a new method named `FileFragment::create_fragments` to generate empty or multi fragments.
> feat: support write multi fragments or empty fragment in one spark task

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/scanner.rs
> fix: full text search may produce dup results when search over multiple columns

- java/.gitignore
`.java-version` is generated automatically by [jenv](https://www.jenv.be/). Jenv is a very popular tool that is used to manage java environment.
> chore: add .java-version to .gitignore for java module

- protos/encodings.proto
- python/Cargo.lock
- rust/lance-encoding/src/buffer.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/repdef.rs
- rust/lance-encoding/src/testing.rs
Empty & null lists are interesting.  If you have them then your final repetition & definition buffers will have more items than you have in your flattened array.  This fact required a considerably reworking in how we build and unravel rep/def buffers.
When building we record the position of the specials and then, when we serialize into rep/def buffers, we insert these special values.  When unraveling we need to deal with the fact that certain rep/def values are "invisible" to the current context in which we are unraveling.
In addition, we now need to start keeping track of the structure of each layer of repetition in the page metadata.  This helps us understand the meaning behind different definition levels later when we are unraveling.
This PR adds the changes to the rep/def utilities. …
> feat: enhance repdef utilities to handle empty / null lists

- python/python/ci_benchmarks/datagen/gen_all.py
- python/python/ci_benchmarks/datagen/lineitems.py
- python/python/ci_benchmarks/datasets.py
- python/python/lance/__init__.py
- python/python/lance/cuvs/kmeans.py
- python/python/lance/dataset.py
- python/python/lance/log.py
- python/python/lance/sampler.py
- python/python/lance/tf/data.py
- python/python/lance/torch/async_dataset.py
- python/python/lance/torch/distance.py
- python/python/lance/torch/kmeans.py
- python/python/lance/vector.py
- python/python/tests/test_log.py
> feat: let pylance use sub-level logger of logging

- .github/workflows/bump-version/action.yml
When we create the version bump commit it currently updates the lock file `Cargo.lock` to point to the new versions.  I suspect it is the `cargo ws version --no-git-commit -y --exact --force 'lance*' ${{ inputs.part }}` command that does this.  However, we have two lock files, and `python/Cargo.lock` is not updated.  This PR adds a step to the version bump to also update `python/Cargo.lock`.
> ci: update python/Cargo.log on version bump

- python/python/lance/torch/data.py
- python/python/tests/torch_tests/test_data.py
Support handling Blob data in PyTorch loader
> feat: support blob api in pytorch loader

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
Although `enable_move_stable_row_ids` is still under experimental, and it still need to be add to pylance write_dataset interface for experimental usage.
> feat(python): add experimental parameter `enable_move_stable_row_ids` for pylance

- protos/encodings.proto
- rust/lance-encoding-datafusion/src/zone.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-file/src/v2/writer.rs
The repetition index is what will give us random access support when we have list data.  At a high level it stores the number of top-level rows in each mini-block chunk.  We can use this later to figure out which chunks we need to read.
In reality things are a little more complicated because we don't mandate that each chunk starts with a brand new row (e.g. a row can span multiple mini-block chunks).  This is useful because we eventually want to support arbitrarily deep nested access.  If we create not-so-mini blocks in the presence of large lists then we introduce read amplification we'd like to avoid.
> feat: add the repetition index to the miniblock write path

- rust/lance-encoding/src/encodings/physical/packed_struct.rs
The current main has test failure in `test_fsl_packed_struct` because I introduced statistics gathering for `StructDataBlock`, but not statistics gathering in `FixedSizeListDataBlock`.
To fix this test, I can add statistics gathering(in this case, only `Stat::MaxLength` is needed) for `FixedSizeListDataBlock`.
I think the variants of `FixedSizeList's child datablock` can only be either `fixed width datablock` or another `fixed size list`? 
This PR however only disables the packed struct encoding test for `fixed size list`.
----------
after reading https://docs.rs/arrow-array/53.3.0/src/arrow_array/array/fixed_size_list_array.rs.html#133, it looks like that the child of a `fixed size list` can be any array type, which means to support `MaxLength` statistics for `fixed size list data …
> fix: test failure in `test_fsl_packed_struct`

- python/python/tests/test_filter.py
- python/python/tests/test_scalar_index.py
- rust/lance-datafusion/src/planner.rs
- rust/lance-index/src/scalar/expression.rs
This adds support for the sql `col BETWEEN x AND y` clause
> feat: support between sql clauses

- rust/lance-index/src/scalar/expression.rs
In the code parsing scalar expressions I am expecting binary expressions to follow a certain pattern (`column op scalar` and not `scalar op column`) and so I added a warning when I didn't see the pattern since that would mean my assumption was wrong and then I returned None.
However, the pattern I was expecting was a bit stricter than that (`indexed column op scalar`) and there are lots of cases where we might see `not indexed column op scalar` and yet returning `None` is exactly the right thing to do here so we're ok and don't need the warning.
> fix: remove overzealous warning

- python/python/tests/test_scalar_index.py
- rust/lance-arrow/src/deepcopy.rs
- rust/lance-encoding/src/data.rs
In some situations an array could be sliced in such a way that the array had no offset, but the array's null buffer did have an offset.  In these cases we were not deep copying the array correctly and the offset of the null buffer was lost.  This does mean, in some cases, the 2.0 writer could write incorrect nulls.  However, the input conditions would mean that the user's data would have to originate from rust in such a way that it was sliced like this.  It would be impossible for batches from the C data interface or from python to look like this.
> fix: correctly copy null buffer when making deep copy

- rust/lance-io/src/object_store.rs
We have this on by default for local fs and in-memory. We also want this for object storage.
> feat: enable tracing for object storage

- java/spark/src/main/java/com/lancedb/lance/spark/LanceDataset.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceFragmentScanner.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceInputPartition.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceScan.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceScanBuilder.java
- java/spark/src/main/java/com/lancedb/lance/spark/write/SparkWrite.java
- java/spark/src/test/java/com/lancedb/lance/spark/read/LanceColumnarPartitionReaderTest.java
Add the `SupportsPushDownLimit` and `SupportsPushDownOffset` interface for `LanceScanBuilder`.
When set the limit, lance spark scan will push it down the lance dataset.
When set the offset, lance spark scan will check the fragments first, only single fragment can push the offset down to the lance datasets since multi fragments has no meaning of offsets.
And rename all the LanceConfig fields from options into config.
> feat(java): support limit and offset interface for spark connector

- python/python/lance/dataset.py
- python/python/lance/log.py
Since we are now sharing `LANCE_LOG` with python logging and rust logging it was erroring out when the log level was set to `trace` since `trace` is not a valid python logging level.
In addition, I fix up the wording for the batch size, recognizing the fact that `CoalesceBatchesExec` (which we use in some filtering situations) could lead to batches larger than `batch_size`.
> fix: allow LANCE_LOG to be set to trace

- python/python/tests/test_vector_index.py
- python/src/dataset.rs
> fix: list indices always shows vector index type is IVF_PQ even it's not

- java/core/lance-jni/src/blocking_scanner.rs
- java/core/src/main/java/com/lancedb/lance/ipc/ColumnOrdering.java
- java/core/src/main/java/com/lancedb/lance/ipc/LanceScanner.java
- java/core/src/main/java/com/lancedb/lance/ipc/ScanOptions.java
- java/core/src/test/java/com/lancedb/lance/ScannerTest.java
- java/core/src/test/java/com/lancedb/lance/TestUtils.java
- java/spark/src/main/java/com/lancedb/lance/spark/SparkOptions.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceFragmentScanner.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceInputPartition.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceScan.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceScanBuilder.java
- java/spark/src/test/java/com/lancedb/lance/spark/read/LanceColumnarPartitionReaderTest.java
In my test for 10M rows of ssb test suite for this sql
```sql
select * from lance_table order by lo_orderkey limit 10
```
| PushDown | NonPushDown |
| ---- | ---- |
| 3s    | 26s |
> feat(java): support topn pushdown in spark connector

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- rust/lance/src/dataset/write/merge_insert.rs
In https://github.com/lancedb/lance/pull/2639 we added support for *updating* subcolumns. In https://github.com/lancedb/lance/pull/3041 we added support for *inserting* subcolumns. This PR adds support for upserting them (or doing insert-if-not-exists).
Closes #2904
```python
import lance
table = pa.table({
"id": range(3),
"a": [1.0, 2.0, 3.0],
"c": ["x", "x", "x"]
})
dataset = lance.write_dataset(table, "example")
new_data = pa.table({
"id": [2, 3],
"c": ["y", "y"]
})
(
dataset
.merge_insert(on="id")
.when_matched_update_all()
.when_not_matched_insert_all()
.execute(new_data)
)
dataset.to_table().to_pandas()
```
```
id    a  c
0   0  1.0  x
1   1  2.0  x
2   2  3.0  y
3   3  NaN  y
```
```python
new_data = pa.table({
"id": [3, 4],
"c": ["z", "z"]
})
(
dataset …
```
> feat: merge-insert supports inserting subset of columns

- python/python/tests/test_dataset.py
- rust/lance/src/dataset/scanner.rs
Fixes https://github.com/lancedb/lance/issues/3086
While adding test cases, I noticed that the following error would occur in the original code. But with this update, this is fixed too.
<details>
<summary>Error detail</summary>
When the offset is specified as larger than the number of rows without a limit. (This test case is added in this change)
`test_limit_offset` in `python/tests/test_dataset.py`
```python
assert dataset.to_table(offset=101) == table.slice(100, 0)
```
The error occurs here when attempting to execute `100 - 101` as a `u64`.
https://github.com/lancedb/lance/blob/537d4e1fa83a899e0a1d5601cd1db6c508f5a046/rust/lance/src/io/exec/scan.rs#L154-L154
```
attempt to subtract with overflow
thread 'dataset::scanner::test::test_limit::data_storage_version_1_LanceFileVersion__Stable' …
```
> fix(rust): adjust scan range to avoid unnecessary warnings

- docs/read_and_write.rst
- rust/lance-io/src/object_store.rs
Add `client_max_retries` and `client_retry_timeout` of `RetryConfig` for S3 client.
If there are some server error of object store server, the `object store` module of `arrow-rs` will retry `client_max_retries` times and also the total execute time is not over `client_retry_timeout`.
Closes #3182
> feat: add the s3 retry config options for storage option

- .github/workflows/rust.yml
- Cargo.toml
I'm going to leave this as a non-breaking change since that seems to be the consensus in the community from what I can gather.  That being said, this being a non-breaking change in downstream libraries is what caused this in the first place :confounded:
> feat: change MSRV from 1.78 to 1.80.1

- python/python/tests/test_filter.py
- rust/lance-arrow/src/lib.rs
- rust/lance-core/src/datatypes.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance/src/datafusion/logical_plan.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/updater.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec/optimizer.rs
- rust/lance/src/io/exec/take.rs
In various situations we need to fetch some fields from a struct and then later add more fields for the struct.  For example, maybe we have a `struct<big_string: string, filter: i32>`.  We might query with a filter on `filter` and then use late materialization to take `big_string`.  When we do this we were previously creating `struct<filter: i32, big_string: string>` which would cause issues since that isn't the correct data type.
In creating this fix I added a new `Projection` concept and I would like to slowly replace a lot of the places where we use schemas as projections to use `Projection` instead.  Not necessarily for performance but more for convenience.
> fix: when taking struct fields they should be merged into the output in the correct order

- rust/lance-index/src/scalar/inverted/wand.rs
- rust/lance/src/dataset.rs
fix #3264 
this happens when limit is set and there are some docs the their estimated score is greater than threshold
> fix: full text search with limit may return an incorrect results

- .github/workflows/ci-benchmarks.yml
This will make it possible to test new benchmarks added by PRs before we merge them into main
> ci: allow bencher benchmarks to be executed with workflow_dispatch

- python/python/ci_benchmarks/benchmarks/test_search.py
- rust/lance-index/src/scalar/btree.rs
The btree currently only caches the the lookup.  This means there will always need to be at least one IOP per search 4Ki rows that match the filter to load the sub-index (flat) data.
This PR adds a cache for the data pages as well.
The cache defaults to 512MiB and is technically configurable via `LANCE_BTREE_CACHE_SIZE` but this is just a stop-gap.  We should ideally have a single size limit for all scalar indices (or, even better, a single size limit for ALL indices).  However, this is a bit tricky.  I don't think moka caches can share capacity across several caches and using a single moka cache for all places we need cache is tricky because moka caches are typed (in some places we use `Arc<dyn Any>` which might be a possible solution though we still need to deal with the fact that we …
> feat: cache btree sub-index pages

- python/python/lance/ray/sink.py
- python/python/tests/test_ray.py
fix https://github.com/lancedb/lance/issues/3308
> fix: lance ray sink crash when fields contain none

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/label_list.rs
Creating empty scalar indices is not terribly useful but it can make certain workflows simpler where users setup all their indices first and then regularly add data and call optimize.  This PR fixes a few bugs that would be encountered in that workflow.
This also fixes a more serious issue where null values were being dropped when indices were updated.
> fix: allow empty scalar indices and don't drop nulls on update

- rust/lance/src/index/vector/builder.rs
parallelize v3 indexing partitions, this would improve indexing speed for IVF_PQ & IVF_FLAT on v3
> perf: parallelize indexing partitions

- rust/lance-core/src/cache.rs
- rust/lance-core/src/datatypes.rs
- rust/lance-core/src/utils/path.rs
- rust/lance-datagen/src/generator.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
The miniblock chunk data was always intended to be cached.  This is essential for good random access performance.  This PR adds that caching.
> feat: cache miniblock metadata

- python/python/tests/test_filter.py
- rust/lance-datafusion/src/logical_expr.rs
for example, current `str > 10` will throw exception. but `str BETWEEN 10 AND 20` will not throw exception.
with this PR check type coerce for between clause.
> fix: coerce scalar for between

- java/core/lance-jni/src/blocking_dataset.rs
- java/core/src/main/java/com/lancedb/lance/Dataset.java
- java/core/src/main/java/com/lancedb/lance/ipc/DataStatistics.java
- java/core/src/main/java/com/lancedb/lance/ipc/FieldStatistics.java
- java/core/src/test/java/com/lancedb/lance/DatasetTest.java
- java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceDatasetAdapter.java
- java/spark/src/main/java/com/lancedb/lance/spark/read/LanceStatistics.java
With #3328, now we can calculate the dataset disk size.
> feat(java): support get real data size for lance spark statistics interface

- rust/lance/src/dataset/scanner.rs
The code was a little over-eager with regards to eager materialization.  I think this was just a mistake from a recent refactor.  This led to a double-take (also in the code).  In most cases this double-take would be smoothed out by the double-take reducing optimization step.  However, in some cases (e.g. if there was a limit between the takes) the takes weren't being combined.
We _could_ improve the double-take optimization step to pushdown through a limit node but it was an easier to fix to avoid accidentally generating the double-take in the first place.
I added a test case for this in test_plans although that test case highlights another interesting optimization we could apply which is to push limits down into vector searches.
> fix: avoid double-take in some scenarios

- python/python/lance/dataset.py
- python/python/lance/fragment.py
- python/python/lance/lance/__init__.pyi
- python/python/tests/test_balanced.py
- python/python/tests/test_fragment.py
- python/src/dataset.rs
- python/src/fragment.rs
- python/src/lib.rs
- python/src/transaction.rs
Allow user use `write_fragments` for lance with blob storage class by returning a nullable list of blob ops
> feat: allow blob in `write_fragments`

- rust/lance-core/src/utils/deletion.rs
- rust/lance/src/dataset/take.rs
We were not properly handling deletions when mapping raw offsets to row addresses. This PR makes sure we use the deletion files to figure out the exact row addresses.
Fixes #3332
> fix: handle deletions in take

- python/python/lance/ray/sink.py
https://github.com/lancedb/lance/issues/3229
https://github.com/ray-project/ray/pull/49214
> fix: fix ray lance sink error

- rust/lance-io/src/lib.rs
- rust/lance/src/dataset/fragment.rs
if we scan _rowid or _rowaddr without other columns, an error will come up.
```
thread 'tokio-runtime-worker' panicked at rust/lance/src/dataset/[fragment.rs:1986](http://fragment.rs:1986/):18:
called `Result::unwrap()` on an `Err` value: InvalidInput { source: "Cannot slice from 0 with length 333275 given a selection of size 10", location: Location { file: "rust/lance-io/src/[lib.rs](http://lib.rs/)", line: 151, column: 27 } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at rust/lance/src/io/exec/[scan.rs:236](http://scan.rs:236/):40:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(13), "called `Result::unwrap()` on an `Err` value: InvalidInput { source: \"Cannot slice from 0 with length 333275 given a …
```
> fix: scan out of range

- rust/lance/src/index/vector/utils.rs
Super minor PR that just adds a bit more logging to the index training process.  I have been debugging some oddities in a lance deployment recently and it would be helpful to have this information.
> feat: log the number of rows we were able to sample

- python/python/lance/ray/sink.py
- python/python/tests/test_ray.py
@eddyxu @westonpace @Jay-ju Don't ask me why :) just try testing `None` with `LanceDatasink`.
See this comment: https://github.com/lancedb/lance/issues/3308#issuecomment-2579940079
Ref issue: https://github.com/lancedb/lance/issues/3308
> fix: cast null arrays to the appropriate type when coercing to a table

- .github/workflows/rust.yml
- deny.toml
- fix https://github.com/lancedb/lance/issues/3072
With two exceptions (ignored since they're not direct dependencies):
<summary>
- `encoding` used by lindera
- `instant` used by tantivy
</summary>
<details>
```
┌─ /GitHub/lance/Cargo.lock:180:1
│
180 │ encoding 0.2.33 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2021-0153
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0153
├ Last release was on 2016-08-28. The [issue](https://github.com/lifthrasiir/rust-encoding/issues/127) inquiring as to the status of the crate has gone unanswered by the maintainer.
- [encoding_rs](https://crates.io/crates/encoding_rs)
├ Announcement: …
```
> ci: add cargo-deny

- python/python/lance/fragment.py
- python/python/lance/lance/__init__.pyi
documents for new arguments of write_fragments method are missing.  and write_fragments is dependent typing now. I added two override signatures to make the type checker happy.
> fix(python): correct type hint for `write_fragments()`

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- rust/lance-datafusion/Cargo.toml
- rust/lance-datafusion/src/exec.rs
- rust/lance-datafusion/src/planner.rs
- rust/lance-datafusion/src/sql.rs
- rust/lance-datafusion/src/substrait.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance/src/datafusion/dataframe.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec/fts.rs
- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/optimizer.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/io/exec/scalar_index.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/testing.rs
I wanted to upgrade to 44 to check and see if the string sorting bug was fixed.  It wasn't.  However, it might still be useful to commit this since we'll need to upgrade at some point.
> feat: upgrade datafusion to 44.0

- rust/lance/src/arrow/json.rs
> fix: json schema serializes field metadata

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
Recent releases of Datafusion have been splitting the function library into features.  We want to enable all of the functions to avoid losing functionality (user reported regression that `sha256` is no longer an available function)
> feat: enable all datafusion functions

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/transaction.rs
> fix: updating schema/field metadata now retains fragments

- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance/src/index.rs
the posting lists must be written in the original order
> fix: full text search index may be corrupted after remapping

- rust/lance-core/src/datatypes/schema.rs
- rust/lance/src/dataset/schema_evolution.rs
> feat: add an all null column as a metadata-only operation

- python/python/lance/dataset.py
In pyarrow 19 the `serialize_expressions` return type changed to a `memoryview` (https://github.com/apache/arrow/commit/e0ab40d3793b1f795ff8cdfa61b96c727bd88df0).  It seems that pyo3 does not easily convert `memoryview` to `Vec<u8>` and so we convert to `bytes`.  I've tested this code with both pyarrow 17, 18, and 19.
> fix: handle the possibility that serialize_expressions returns a memoryview

- rust/lance-index/src/vector/ivf/transform.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/residual.rs
- rust/lance-index/src/vector/transform.rs
> perf: avoid re-alloc on assigning PQ

- python/python/tests/test_dataset.py
- rust/lance/src/dataset/write/merge_insert.rs
Fixes #3406
At the root of this is a bit of a footgun with DataFusion. Prior to this change, the query plan for getting data that was supposed to be sorted by `_rowaddr` was:
```
ProjectionExec: expr=[id@0 as id, vector@1 as vector, _rowaddr@2 as _rowaddr, _rowaddr@2 >> 32 as _fragment_id], schema=[id:Int64;N, vector:FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 32);N, _rowaddr:UInt64;N, _fragment_id:UInt64;N]
RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1, schema=[id:Int64;N, vector:FixedSizeList(Field { name: "item", data_type: Float32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, 32);N, _rowaddr:UInt64;N]
SortExec: expr=[_rowaddr@2 ASC], …
```
> fix: merge_insert with subcols sometimes outputs unexpected nulls

- .github/workflows/build_linux_wheel/action.yml
- .github/workflows/pypi-publish.yml
- .github/workflows/python.yml
We were using deprecated 2_24 for ARM, but that seems to have some issues. Dropping down to 2_17 for now to keep wide support, as I believe some of the popular cloud linuxes don't have >=2.28 glibc.
> ci: fix Python Arm build

- Cargo.lock
- rust/lance-io/Cargo.toml
- rust/lance-io/src/object_store.rs
Previously, setting a block_size parameter did not change the range coalescing being done in FileScheduler's [submit_request ](https://github.com/lancedb/lance/blob/main/rust/lance-io/src/scheduler.rs#L717) function. This was because the FileScheduler was using the block_size parameter in the underlying ObjectStore, but that parameter was not being properly propagated in the configure_store method. 
This change keeps the same defaults but always uses the parameter value if it is set. 
Verified via unit tests and profiling to determine increasing block size now does actually decrease the number of get_range queries.
> fix: ensure that 'block_size' parameter is properly propagated in the ObjectStore

- .github/workflows/build_linux_wheel/action.yml
- .github/workflows/pypi-publish.yml
We can get both 2_17 and 2_28 working if we use an ARM runner.
> ci: use ARM runner for Python ARM release builds

- Cargo.lock
- python/Cargo.lock
- rust/lance-encoding/Cargo.toml
We were pinned to an exact version, which caused issues for users of LanceDB https://github.com/lancedb/lancedb/issues/2043
✅ I've run tests with `bytemuck = "=1.14.0"`
> fix(rust): loosen bytemuck pin

- protos/encodings.proto
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/repdef.rs
- rust/lance-file/src/v2/reader.rs
This adds the last structural path for 2.1, full zip encoding of variable length data.  Scheduling this turned out to be a little trickier than I had planned.  There is no easy way to know where to slice the fully-zipped buffer when doing decoding.  Currently we settle this problem by unzipping in the indirect scheduling task.  There are some alternative possibilities that I have documented but for now I think this will be good enough and we can iterate on this going forwards.
> feat: finish up variable-length encodings in the full-zip path

- rust/lance-index/src/vector/sq/storage.rs
- rust/lance/src/io/exec/knn.rs
dynamically check for query type before quantizing to SQ codes
> fix: support fp16 type in SQ

- rust/lance/src/dataset/write/merge_insert.rs
Fixes #3419
We were using the `CPU_RUNTIME`, but there's a lot of IO happening here, and it wasn't configured to do that. Instead, I moved the operations onto the main runtime so it can perform the IO.
✅  I've testing this manually against S3 with the repro.
> fix: move IO tasks off of CPU runtime in merge_insert

- rust/lance-core/src/utils/tokio.rs
- rust/lance/src/index/append.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/pq.rs
- rust/lance/src/index/vector/utils.rs
We were not filtering out null values when sampling. Because we often call `array.values()` on Arrow arrays, which ignores the null bitmap, we are often silently treating the nulls as zeros (or possibly undefined values). Only thing that caught these nulls is an assertion. However, residualization occurring with L2 and Cosine often meant that these values were transformed and null information was lost before the assertion, which is why it got past previous unit tests.
This PR adds more assertions validating there aren't nulls, and makes sure the sampling code handles null vectors.
Closes #3402
Closes #3400
> fix: filter out null values when sampling for index training

- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/repdef.rs
- rust/lance-encoding/src/testing.rs
The bugs mostly originated from having `def` information but no `rep` information since the variable full zip path was originally built to support lists.
> feat: add testing of string/binary to 2.1 full-zip encoding and fix bugs

- .github/workflows/java.yml
We have some java builds timing out after 6 hours. We should look into the hang, but for now let's limit them to an hour.
> ci(java): timeout test jobs after an hour

- rust/lance-io/src/scheduler.rs
Until we're more optimized this warning is not terribly useful or actionable by users.
> chore: downgrade backpressure warning to a debug log message

- rust/lance-datagen/benches/array_gen.rs
- rust/lance-datagen/src/generator.rs
The current generator for binary data always generates data that has the exact same length.  This PR adds a variation that generates binary elements of different lengths (the lengths are uniformly sampled from a given range).
The existing generator is renamed to fixedbin and this one takes the varbin spot.
> chore: add binary array generator that generates different sized binary items

- rust/lance-core/src/utils.rs
- rust/lance-core/src/utils/parse.rs
- rust/lance-io/src/object_store.rs
- rust/lance/src/dataset.rs
- rust/lance/src/index.rs
Follow up to https://github.com/lancedb/lance/pull/3377. That PR made `index_statistics()` error by default. This ended up being a footgun for some users who rely heavily on that method. So instead of forcing the user to do the migration themself, we do it for them. It can be disabled using an environment variable.
> feat: auto-migrate old index metadata

- Cargo.lock
- python/Cargo.lock
fix CVE https://rustsec.org/advisories/RUSTSEC-2025-0004
> fix: bump openssl for CVE

- protos/transaction.proto
- python/python/lance/dataset.py
- python/python/lance/file.py
- python/python/lance/ray/sink.py
- python/python/tests/test_dataset.py
- python/src/transaction.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/transaction.rs
For internal design doc see notion or ping me
What this PR implements
Plan of attack:
* This PR: basic functionality, i.e. when there is no conflict calling this tx should just work
* Next PR: implement more fine-grained conflict resolution
* Potential future PR (when time permits): Allow partial replacement of a datafile. This can be done by "dropping" column indice in a datafile, thereby dropping the column in favor of another
TODO:
> feat: allow replacement of entire datafile when the schema lines up correctly

- rust/lance-arrow/src/lib.rs
- rust/lance-io/src/encodings/plain.rs
This fixes two bugs with the padding added by the bytes_to_array function in the plain encoder. This function is used for reading indexes in LanceDB cloud.
Problem 1:
Prior to this commit, space was reserved based on an incorrect multiplication of the user-supplied buffer's byte length and the bytewidth of the item type. Instead, we should multiply the bytewidth by the element count. The effect of this was previously to pad too much space at the end of parsed arrays.
Problem 2:
We previously had some logic that was padding a buffer by extending it with 0-valued uint32s, instead of 0-valued uint8. This resulted in a multiplication of the padding added by four.
> fix: remove extraneous padding in plain encoder

- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec/fts.rs
this method isn't implemented before this and it causes panic, we don't actually need this but maybe some optimizing would call this method for rewriting the plans
> fix: implement with_new_children for FTS

- .pre-commit-config.yaml
- java/core/src/test/java/com/lancedb/lance/FilterTest.java
- java/core/src/test/java/com/lancedb/lance/ScannerTest.java
- python/python/lance/dataset.py
- python/python/lance/fragment.py
- python/python/tests/test_dataset.py
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/write/merge_insert.rs
We added logic a while back to eagerly materialize fields if they are narrow and there is a filter.  However, we forgot to ensure that those fields are actually part of the final projection.  The result is that we end up loading many columns the user doesn't want and then throwing them away.
This fix changes the set of fields we load to only be those that are asked for.
> fix: don't eagerly materialize fields that the user hasn't asked for

- rust/lance-datagen/src/generator.rs
- rust/lance-encoding/build.rs
- rust/lance-encoding/src/buffer.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/binary.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/encodings/physical.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/block_compress.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/format.rs
- rust/lance-file/src/v2.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance/src/dataset/fragment.rs
This fixes a few performance bottlenecks on 2.1 take operations
* Change the protobuf config to generate `bytes::Bytes` instead of `Vec`.  This helps avoid some expensive FSST symbol table clones.
* Moka cache lookups during initialization are expensive.  Instead of one cache lookup per page we now do one cache lookup per column
* Our current scheduling approach for mini block was slow.  There were many switches to calculate info about the repetition index.  We now precompute that during initialization.  In addition, we now search the repetition index with a binary search instead of a full scan.
> perf: make miniblock decoding cheaper

- rust/lance/src/io/exec/knn.rs
this causes an error when query with distance range, and there are unindexed rows
> fix: flat KNN column stats order doesn't match schema

- rust/lance/src/dataset/scanner.rs
We are trying to build a Datafusion table provider in LanceDB and it receives expressions as DF logical exprs.  We can go DF expr -> substrait -> DF expr but it seems simpler to just expose the API to accept filters as DF exprs directly.
> feat: expose specifying scanner filters via datafusion

- python/pyproject.toml
This just adds the lance/schema.py, lance/file.py, lance/util.py files such that they can be checked with pyright. Fixes [#329](https://github.com/lancedb/lance/issues/3294)
> feat(python): add files lance/schema.py, lance/file.py, lance/util.py for pyright typecheck

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/btree.rs
- rust/lance/src/index/scalar.rs
Until we upgrade to the next DF release (46) we cannot rely on spilling when working with string data.  Users continue to get errors unrelated to the size of the spill pool or the amount of data they have.  This disables spilling entirely on string columns (which is the typical workaround) until we get a stable solution.
> fix: temporarily disable spilling when training indices on string columns

- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/io/exec/rowids.rs
- rust/lance/src/io/exec/scalar_index.rs
Some of these nodes don't have children (and so I think we thought `with_new_children` wouldn't be called on them).  Others were simply missing an implementation.
These missing impls are causing errors when trying to use lance as a table provider in lancedb.
> feat: add with_new_children implementations for several nodes

- .typos.toml
- protos/table.proto
- python/python/lance/dataset.py
- python/python/tests/test_scalar_index.py
- python/src/dataset.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance-core/src/utils/mask.rs
- rust/lance-index/Cargo.toml
- rust/lance-index/benches/ngram.rs
- rust/lance-index/src/lib.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/expression.rs
- rust/lance-index/src/scalar/flat.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/scalar/ngram.rs
- rust/lance/benches/scalar_index.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/index.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/io/exec/scalar_index.rs
Ngram indices are indices that can speed up various string filters.  To start with they will be able to speed up `contains(col, 'substr')` filters.  They work by creating a bitmap for each ngram (short sequence of characters) in a value.  For example, consider an index of 1-grams.  This would create a bitmap for each letter of the alphabet.  Then, at query time, we can use this to narrow down which strings could potentially satisfy the query.
This is the first scalar index that requires a "recheck" step.  It doesn't tell us exactly which rows satisfy the query.  It only narrows down the list.  Other indices that might behave like this are bloom filters and zone maps.  This means that we need to still apply the filter on the results of the index search.  A good portion of this PR is adding …
> feat: add support for ngram indices

- rust/lance-index/src/vector/sq.rs
Address potential out-of-range issues when scaling values to `u8` in the `ScalarQuantizer`. Introduce a test case to handle NaN values in the scaling function.
> fix: scalar quantization can't work with NaNs

- docs/read_and_write.rst
Correct minor typo in docs around using `alter_columns` to type cast. According to https://github.com/lancedb/lance/commit/45c158dd56888501458a6dd7783f85a3367ad1b5 `type` should be `data_type`.
> docs: fix typo in read_and_write.rst

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- python/Cargo.toml
- python/python/lance/dataset.py
Related to https://github.com/lancedb/lance/issues/3444
Removed unused kwargs parameter in [LanceDataset.take](https://github.com/lancedb/lance/blob/main/python/python/lance/dataset.py#L791)
> chore(api)!: remove unused param in take call

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- python/src/lib.rs
- python/src/scanner.rs
- rust/lance-core/src/utils/mask.rs
- rust/lance-datafusion/src/planner.rs
- rust/lance-encoding/src/compression_algo/fsst/src/fsst.rs
Some new suggestions were adding in 1.85 and they are tripping up CI builds
We need to temporarily ignore `useless_conversion` until we're able to upgrade arrow due to https://github.com/rust-lang/rust-clippy/issues/12039
We need to temporarily pin `chrono` until we're able to upgrade arrow due to https://github.com/chronotope/chrono/pull/1666
> chore: update clippy suggestions

- rust/lance-index/benches/ngram.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/ngram.rs
total indexing time reduced from 23s to 5s
```
ngram_index(1000000)    time:   [5.1192 s 5.1756 s 5.2319 s]
change: [-78.163% -77.791% -77.410%] (p = 0.00 < 0.05)
```
> perf: parallelize ngram indexing

- python/python/tests/test_schema_evolution.py
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/schema_evolution/optimize.rs
Adds support for adding all-null column via SQL.
If the user passes:
```rs
dataset.add_column(NewColumnTransform::SqlExpressions(vec!["new_col", "CAST(NULL AS int)"]);
```
We'll discover that the intention is to to create an all null column, and optimize the transform to:
```rs
dataset.add_column(NewColumnTransform::AllNull(Arc::new(
Schema::new(vec![
Field::new("new_col", DataType:Int32, true),
])
)
```
The motivation here is to be able to expose the capability to add the all null column as a metadata-only operation through the LanceDB SDKs. Currently these methods only support passing SQL expressions. A different option would have been to modify the arguments to the python table.add_column & typescript table.addColumn, but that seemed like more work so I wanted to propose this solution …
> feat: support add all null column as metadata-only operation via sql

- rust/lance-io/src/object_store/tracing.rs
- rust/lance/src/utils/test.rs
Adding enforcement that wrappers implement all ObjectStore methods. If they don't, then the specialized implementations in the base `ObjectStore` could be bypasses, causing key optimizations to be missed out on.
I didn't see any real cases here, but adding this to be cautious. `delete_stream()` a common one we might worry about it, but it seems like tracing store already had this.
> fix: prevent despecialization of object store methods

- docs/api/python.rst
- python/python/lance/dataset.py
* `drop_index` and `create_scalar_index` to the first level API doc
> docs: include create scalar index and drop index to the top level of Python API doc

- rust/lance-io/src/object_store.rs
Allow support of connecting to GCP with storage tokens instead of service key JSON or serialized key using object_store's [with_credentials](https://docs.rs/object_store/latest/object_store/gcp/struct.GoogleCloudStorageBuilder.html#method.with_credentials).
Tested and created dataset in GCP:
through notebook:
> feat: add gcp token-based auth support

- python/Cargo.lock
- python/Cargo.toml
- python/src/lib.rs
- rust/lance-table/src/io/deletion.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/dataset/write.rs
Data files, deletion files, and manifest files are significant user files that cannot easily be recovered or recreated (unlike indices or transactions)
We should log when these are created and deleted to help provide some minimum debugging and audit tracking.  This isn't a complete audit system, we aren't capturing the user responsible, etc. (at this level we don't know these things) but it can be integrated into a larger monitoring system to detect user events.  Also, it can help debug bugs like https://github.com/lancedb/lancedb/issues/2193 where files aren't there and we need to distinguish between "file was never created" and "file was removed".
> feat: emit a trace event when a significant user file is created or deleted

- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/physical.rs
When decoding something like `List<Dictionary<UInt8, LargeList>>` we were not correctly passing down the `LargeList` portion.  This caused decoding to fail later.
This will fix https://github.com/lancedb/lancedb/issues/2154
> fix: pass down correct types when creating indices and items scheduler

- python/python/lance/types.py
- python/python/tests/test_dataset.py
Fix this bug from `docs/read_and_write.rst` example:
https://github.com/lancedb/lance/blob/e12bb9eff2a52f753668d4b62c52e4d72b10d294/docs/read_and_write.rst?plain=1#L264
> feat: write_dataset from pylist and pydict

- .github/workflows/docs-check.yml
- .gitignore
- docs/arrays.rst
- docs/conf.py
- docs/format.rst
- docs/index.rst
- docs/read_and_write.rst
- docs/requirements.txt
* Tune conf.py for `doctest` extension
* Fix `Produce()` example to use an iterator to create data
* Added `intersphinx` support for `pyarrow`, `numpy` and `pandas`.
* Enable `make doctest` for all target
Part 1/N of efforts to address #2423
> docs: fix read_and_write example

- Cargo.lock
- rust/lance-core/src/error.rs
- rust/lance-index/Cargo.toml
- rust/lance-index/benches/ngram.rs
- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/scalar/ngram.rs
- rust/lance/src/index/scalar.rs
The biggest impactful change is that we can no longer apply ngram indices when the string contains 0, 1, or 2 characters (these strings are likely to match too many rows to make scalar indices useful anyways).
> feat: rework how we train ngram indices for better performance

- docs/api/api.rst
- docs/conf.py
- docs/introduction/read_and_write.rst
* Generate API docs automatically from plugin
* Add example of `LanceDataset.insert()` and `write_dataset`
5/N of #2423
> docs: add example of `Dataset.insert`

- Cargo.lock
- deny.toml
- python/Cargo.lock
- python/Cargo.toml
- rust/lance/Cargo.toml
The `humantime` package is no longer maintained.  We should move to avoid using it.  We were using it indirectly via `env_logger` and `object_store`.  This PR updates `env_logger` to the latest version (which uses `jiff` instead of `humantime`).
`object_store` is one of our core dependencies and we generally update it as new versions are released.  If (and when) `humantime` is replaced with `jiff` we will remove the dependency then.  This may be several months.  https://github.com/apache/arrow-rs/pull/7261 can be used for tracking.
Until then we should suppress the advisory.
> chore: suppress humantime advisory

- rust/lance-encoding/src/decoder.rs
In `DecodeBatchScheduler`, when performing `schedule_take` with a given list of indices, the current implementation generates a list of ranges, each containing a single index. However, in cases where the indices are continuous, we can merge them into a single range instead of multiple separate ranges. This optimization improves efficiency, particularly benefiting dense queries that return most of the records in the dataset, as demonstrated in our benchmarks.
> perf: coalesce continuous indices into ranges if possible

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/transaction.rs
> feat: add project transaction operation for pylance sdk

- .github/workflows/rust.yml
- rust/lance-io/src/object_store.rs
Expose the object store retry config to set via Env variable. 
During Azure network instability, the original retry config will only retry for around 20 seconds.
Expose these values to be configurable by users to survive flaky azure network.
> feat: set object store retry via environment variables

- python/python/tests/test_scalar_index.py
- rust/lance-datafusion/src/exec.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-io/src/scheduler.rs
- rust/lance/src/datafusion.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/take.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec/fts.rs
- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/pushdown_scan.rs
- rust/lance/src/io/exec/rowids.rs
- rust/lance/src/io/exec/scalar_index.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/take.rs
- rust/lance/src/io/exec/utils.rs
Previously, when handling a large take, the `TakeExec` would issue `batch_readahead`  calls to `LanceDataset::take_rows`.  Each call would then have its own scan scheduler and the result would be that we would overload the I/O parallelism.  On a take of 1M rows against S3 I got 400K request retries.
Now, there is one scan scheduler that is shared across the entire take operation, applying the same concurrency limits as before.
In addition, this PR adds the `batch_count` metric to our standard metrics.
In addition, this PR changes `MaterializeIndexExec` to emit batches based on the plan's batch size instead of a fixed constant.
In addition, this PR passes the `batch_size` parameter from the scanner into datafusion
> refactor: rework how take handles parallelism

- rust/lance-index/src/vector/hnsw.rs
- rust/lance-index/src/vector/pq.rs
- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/storage.rs
- rust/lance-index/src/vector/pq/transform.rs
- rust/lance-index/src/vector/storage.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
It seems caused by HNSW_PQ
the pruning process would calculate the distance between 2 neighbors, so with PQ, it constructs the distance table for one of the neighbor but uses it for only a few times, then the cost of constructing distance table becomes significant.
This brings the `dist_between` method back which calculates the distance directly without construing distance table
> fix: indexing time in unit tests is much slower than before

- rust/lance-index/src/vector/pq/storage.rs
- rust/lance/src/index/vector/ivf/v2.rs
because the v3 stores transposed PQ codes, then remap needs to restore the original codes when remapping
> fix: the PQ codes corrupted after remapping

- rust/lance-core/src/cache.rs
- rust/lance/src/dataset.rs
- rust/lance/src/index/cache.rs
- rust/lance/src/session.rs
`FileMetadataCache::deep_size_of` was the worst offender as it required iterating through all items.
`Dataset`'s debug can get quite large if there are several object store wrappers.  In addition, the debug for the manifest is quite large.
> fix: remove some expensive debug impls

- rust/lance/src/io/exec/take.rs
This internal API was removed in a recent commit.
> fix: reintroduce TakeExec.dataset method

- ci/check_versions.py
Python 3.11 and later versions natively support tomllib, but lower versions require third-party libraries like tomli or toml. 
For example:
```
import tomllib
import tomli as tomllib
```
> ci: support python310 tomli

- rust/lance/src/dataset.rs
- rust/lance/src/dataset/cleanup.rs
This will be extra helpful once this is merged: https://github.com/lancedb/lance/pull/3572
> feat: add tracing to cleanup

- rust/lance-file/src/reader.rs
A breaking change was introduced in https://github.com/jhpratt/deranged/issues/18 which was not given a semver bump.  As a result we pick it up and it fails the "no lock file" test.
This PR just avoids the try_into entirely since it doesn't seem to be necessary (we only work on 64-bit machines so usize->u64 should be safe).
> fix: work around deranged breaking change not labeled as such

- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/storage.rs
- rust/lance/src/index/vector/ivf/v2.rs
this fixes:
- divide by 0 error if remapping an empty PQ storage
- 4bit PQ panic if there are less than 16 rows
> fix: divide by 0 error if remapping PQ storage to empty

- rust/lance-index/src/vector/ivf/transform.rs
- rust/lance-index/src/vector/pq/storage.rs
- rust/lance-index/src/vector/storage.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
now we drop the `__ivf_part_id` when shuffling, the corner is that `num_partitions=1`:
1. if `num_partitions=1` then no shuffling is needed
2. the shuffler reader would return the data directly
3. then the `__ivf_part_id` is not dropped, it's written into the index file as well
> fix: schema isn't expected for IVF_PQ

- rust/lance-io/src/object_writer.rs
Propagate the parent span context to tasks spawned by ObjectWriter's AsyncWrite implementation. This is needed for callers might have tracing subscribers they're using for observability over write events, and without accurately having the span context propagated, tracing events that happen inside the spawned task are difficult to associate with the invoking write call.
> fix: propagate parent span to spawned ObjectWriter tasks

- java/core/pom.xml
- java/pom.xml
- java/spark/pom.xml
Reverts part of #3546 which added `-SNAPSHOT` to the versions.  Currently the CI build system does not publish Java artifacts on pre-releases.  There is also nothing in the build script to remove the `-SNAPSHOT` designation from the version.  As a result the publish failed.
Currently, CI requires the version specifier point to the next stable version that will be released.  This restores that so the next stable release can succeed.
> chore: remove SNAPSHOT from version

- rust/lance-encoding/src/encodings/logical/primitive.rs
`PrimitiveFieldEncoder` may generate empty `part`s and their corresponding encoding tasks, especially when `max_page_size` is small. This is unnecessary and can be confusing, as some empty part information gets recorded at the end, and redundant encoding tasks are processed needlessly. This PR fixes the issue by exiting the loop early when there is no data to process.
> fix: avoid creating empty encoding task and part for PrimitiveFieldEncoder

- python/Cargo.lock
- python/python/lance/dataset.py
- python/python/tests/test_scalar_index.py
- rust/lance-datafusion/Cargo.toml
- rust/lance-datafusion/src/datagen.rs
- rust/lance-datafusion/src/expr.rs
- rust/lance-datafusion/src/lib.rs
- rust/lance-datagen/src/generator.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/expression.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/scalar/ngram.rs
- rust/lance-table/src/utils/stream.rs
This PR also allows NANs to exist in the btree column
> feat: add support for fixed size binary to btree

- .github/workflows/python.yml
- .pre-commit-config.yaml
- python/python/lance/__init__.py
- python/python/lance/dependencies.py
- python/python/lance/util.py
- python/python/tests/test_scalar_index.py
When I execute "make format-python" every time for the Python code in the current main branch, there will always be format errors reported for these few files. So here, I want to correct the format here.
@westonpace @wjones127  Help review it.
> fix: fix python format

- Cargo.lock
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/object_writer.rs
- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/commit/dynamodb.rs
- rust/lance-table/src/io/commit/external_manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/refs.rs
- rust/lance/src/dataset/schema_evolution.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/dataset/write/update.rs
- rust/lance/src/index.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/io/commit/dynamodb.rs
- rust/lance/src/io/commit/external_manifest.rs
* Migrates all methods of `CommitHandler` to just use `ManifestLocation`.
* Eliminates `O(num_manifests)` IOPS from `cleanup_old_versions`, since we no longer have to make a separate `HEAD` request to get the size of the file.
* Eliminates `O(num_manifests)` IOPS from `list_versions()`, similar reasons as above.
* Adds `e_tag` to `ManifestLocation`, so we can check we are loading the expected manifest. This eliminates the possibility that we are caching an old version of the manifest, in cases where the dataset has been deleted and recreated to the same version number.
> perf: migrate to `ManifestLocation`, add e_tag

- python/python/lance/torch/data.py
When iterating over Torchdataset, sometimes the original data content is needed, but the current implementation can only return tensors.
> fix: allow TorchDataset to return raw data without direct tensor conversion

- rust/lance-io/src/object_store.rs
- rust/lance-io/src/object_store/list_retry.rs
- rust/lance-table/src/io/commit.rs
Addressing errors like:
```
LanceError(IO): Generic GCS error: Error getting list response body: error decoding response body, /src/lance/rust/lance-table/src/io/commit.rs:216:17
```
> fix: robust against body read failures in list endpoint

- rust/lance-encoding/src/encoder.rs
As part of 2.1 development we changed the threshold for dictionary encoding.  This threshold is shared by the 2.0 writer.  It can cause the 2.0 writer to fail and write corrupted data.
> fix: don't change dictionary threshold

- rust/lance-index/src/vector/ivf.rs
- rust/lance-index/src/vector/utils.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/ivf/v2.rs
when training IVF/PQ, we sample the dataset and filter out nulls, but we still need to filter out NaN/INFs
> fix: filter out infinite vectors

- .github/workflows/rust-benchmark.yml
The self-hosted machine is not maintained, and rust is too old to run benchmark.
https://github.com/lancedb/lance/actions/runs/14329500137
> ci: fix rust benchmark using warp arm to run

- Cargo.lock
- Cargo.toml
- deny.toml
- python/Cargo.lock
- rust/lance-table/src/format/manifest.rs
- rust/lance/Cargo.toml
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/insert.rs
- rust/lance/src/io/commit.rs
Closes #2100.
This PR introduces:
-  A hook called `auto_cleanup_hook`. If config keys `lance.auto_cleanup.interval` and `lance.auto_cleanup.older_than` are both set, then, every `n_versions % lance.auto_cleanup.interval`, `cleanup_old_versions` will automatically be called.
- A new write param `auto_cleanup: Option<AutoCleanupParams>`.  If `Some`, new datasets are configured with the necessary `lance.auto_cleanup` config keys. By default this sets the `interval=20` and `older_than=14`.
- A test to ensure hook is automatically invoked. Some older tests have been fixed as they either do not assume autoclaving will take place, or assume the initial default config is empty.
This PR is Rust-only. I can add Python bindings in a future PR if desired.
From #2100:
> feat: simple auto cleanup

- python/python/lance/dataset.py
- python/python/lance/lance/__init__.pyi
- python/python/lance/query.py
- python/src/dataset.rs
- python/src/lib.rs
- python/src/utils.rs
- rust/lance-index/benches/inverted.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/query.rs
- rust/lance-index/src/scalar/inverted/wand.rs
- rust/lance/src/dataset.rs
- rust/lance/src/io/exec/fts.rs
this also improves the phrase query performance by skipping documents that's impossible to be a candidate.
before we always set the WAND threshold to 0, and update the threshold when hit the limit. But for AND query, only documents that contain all terms can be a candidate, so the init threshold can be the sum of upper bounds
this also refines the pyo3 APIs so that we can get rid of that complicated `parse_fts_query` method
> feat: support AND query and improve phrase query performance

- Cargo.lock
- rust/lance-core/src/utils/tracing.rs
- rust/lance-index/benches/ngram.rs
- rust/lance-index/src/scalar/ngram.rs
- the slowest step is `merge_spills`, ~ 70%+ of total indexing time
- then the `tokneize_and_partition`, ~20% of total indexing time
this PR parallelizes `merge_spills`, gains 40%+ faster
> perf: improve ngram indexing performance

- Cargo.lock
- Cargo.toml
- java/core/pom.xml
- java/lance-jni/Cargo.lock
- java/pom.xml
- java/spark/pom.xml
- python/Cargo.lock
- python/Cargo.toml
- rust/lance-io/Cargo.toml
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/object_store/providers.rs
- rust/lance-io/src/object_store/providers/aws.rs
- rust/lance-io/src/object_store/providers/azure.rs
- rust/lance-io/src/object_store/providers/gcp.rs
- rust/lance-io/src/object_store/providers/local.rs
- rust/lance-io/src/object_store/providers/memory.rs
- rust/lance-table/Cargo.toml
- rust/lance-table/src/io/commit.rs
- rust/lance/Cargo.toml
- rust/lance/benches/take.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/commit.rs
BREAKING CHANGE: `ObjectStoreProvider::new_store` is now async.
* Moves all objects stores to be configured using a `ObjectStoreProvider`. This consolidation is a step towards being able to cache object stores for #3684
* Makes `aws`, `gcp`, and `azure` specific code optional under feature flags. This addresses part of #2646
* Deprecated passing object store explicitly in favor of implementing `ObjectStoreProvider`.
> refactor(rust)!: move all object stores to use `ObjectStoreProvider`

- rust/lance/src/io/exec/fts.rs
- rust/lance/src/io/exec/scalar_index.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/take.rs
- rust/lance/src/utils/test.rs
This ensures that our custom `ExecutionPlan` implementations do not spawn tasks until they are first polled.  Unfortunately, this appears to be a Datafusion requirement for foreign table providers.  It also introduces a bit of test utility to verify this.
> refactor: defer any task spanwing until first read

- rust/lance-index/src/scalar.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/lance_format.rs
The previous remapping relied on `all_page_ids` which could include duplicate page ids (I'm not sure why `dedup` was expected to work here).
Instead of using that approach I have fixed the remapping to just simply scan the entire index file.
> fix: avoid corrupting btree index when remapping nulls

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/btree.rs
If a user queried with `BETWEEN` and the `start` came after the `end` then it was possible for a btree index to generate a panic.  We should not panic and should instead return 0 results.
> fix: don't panic if between bounds are reversed

- rust/lance-arrow/src/lib.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-core/src/datatypes/schema.rs
Previously we only descended into children if the field was a struct.  This is a problem when we have lists of struct because we might fail to project out child fields.
> fix: intersection of list of struct

- rust/lance-core/src/utils/tokio.rs
The default value for LANCE_IO_CORE_RESERVATION is 2.  So if users are on a 2-core system we are always going to warn them.  This is generally just confusing for users and not really something they can do much about.  This changes the check to only emit the warning if the user is modifying LANCE_IO_CORE_RESERVATION (e.g. it is something other than 2).
> fix: don't emit the IO core reservation warning on 2-core systems

- .github/workflows/java.yml
Reduce the runtime of Java CI from over 10 minutes to 3 minutes. The caching configuration in CI requires (1) the working directory to be at the root, (2) the existence of cargo runtime, and (3) a correct mapping of the JNI build to the maven target directory, (4) do not clean the build artifact because that will clean all compiled rust artifacts.
> ci(java): improve caching for lance-jni

- rust/lance-core/src/container.rs
- rust/lance-core/src/container/list.rs
- rust/lance-core/src/lib.rs
This data structure is useful when we need to append a lot of values and finally iterate over all of them.
Compared to `Vec<T>`, this data structure doesn't waste much memory like `Vec<T>`, and doesn't need to copy the data when recap.
This is introduced for FTS indexing process, will apply this in next PR
> feat: add ExpLinkedList

- rust/lance/src/dataset.rs
- rust/lance/src/io/commit.rs
Modifies the handling of the Overwrite operation to respect `read_version` when `num_retries` is set to 0 (strict Overwrite).
A strict Overwrite fails if new commits have been written after `read_version`.
This allows users to more easily build custom transaction and retry logic if needed.
The first commit refactors only for code deduplication with no behavioral changes.
The remainder makes two behavioral changes:
1. Each commit will be tried at least once (previously, commits would always fail when `num_retries` is set to 0)
2. If the operation is Overwrite and `num_retries` is 0, the commit will be attempted based on `read_version` instead of attempting to check out the latest version of the dataset.
> feat: strict overwrite operation

- rust/lance/src/io/exec/fts.rs
- rust/lance/src/io/exec/knn.rs
- rust/lance/src/io/exec/rowids.rs
- rust/lance/src/io/exec/take.rs
- rust/lance/src/io/exec/utils.rs
Many of our nodes require a single input partition (for various reasons).  Other nodes don't benefit from multiple input partitions (and having them would use more RAM and/or violate I/O concurrency limits).  This PR correctly specifies these limitations.
> fix: correctly specify datafusion properties for input distribution in our custom exec nodes

- java/core/lance-jni/src/file_reader.rs
- java/core/lance-jni/src/fragment.rs
- java/core/lance-jni/src/traits.rs
- java/core/src/main/java/com/lancedb/lance/fragment/DataFile.java
- protos/table.proto
- python/python/lance/fragment.py
- python/python/tests/test_fragment.py
- python/src/file.rs
- python/src/fragment.rs
- rust/lance-file/benches/reader.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-file/src/v2/testing.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/vector/ivf/shuffler.rs
- rust/lance-index/src/vector/v3/shuffler.rs
- rust/lance-io/benches/scheduler.rs
- rust/lance-io/src/scheduler.rs
- rust/lance-table/src/format/fragment.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/index.rs
- rust/lance/src/index/vector/builder.rs
- rust/lance/src/index/vector/ivf/v2.rs
- rust/lance/src/io/commit.rs
Part of #3751.
* When we write data files, we store the size in bytes in the manifest.
* We use this size to skip the `HEAD` request needed to find the file footer byte range.
* When writing a dataset, we can read any missing sizes and fill them in.
> feat: store data file size in manifest

- rust/lance/src/io/exec/scan.rs
This exposes a public accessor for LanceScanExec's scan config, so that it may be used in optimizer rules.
> feat: expose public accessor for LanceScanExec config

- rust/lance-core/src/utils/tracing.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-io/src/object_store/list_retry.rs
- rust/lance-io/src/object_store/tracing.rs
- rust/lance-table/src/io/commit.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/utils/future.rs
* Change `TracedObjectStore` methods that return streams to attach the span to the streams, rather than just the creation of the streams.
* Attach a stream to `ReadBatchFutStream` returned from reading a fragment.
* Pass down span at various `tokio::spawn()` calls.
Perfetto still shows a jumbled mess, but I'm hoping this shows up more comprehensible in grafana.
> feat: fix various spans

- java/core/src/test/java/com/lancedb/lance/FileReaderWriterTest.java
- rust/lance-io/src/object_reader.rs
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/scheduler.rs
- rust/lance/src/dataset/fragment.rs
- rust/lance/src/utils/test.rs
If a whole data file is smaller than the `block_size`, just read the whole thing in one IO request. Part of #3751. Stacked on #3750.
This changes makes writing many small rows have much less of an impact on the scan performance. This helps the performance of anything that involves a scan:
1. Exact KNN search
2. Merge-insert
3. Compaction
> perf: read tiny files in 1 IOP

- rust/lance/src/io/commit.rs
If we got near the max retries, we would start retrying *without* any sleep or calling `dataset.checkout_latest()`. The latter guaranteed it would fail with `CommitConflict` (and then retry). The former made it eventually fail on a 429 from object store.
Bug was introduced in https://github.com/lancedb/lance/pull/3712
> fix: prevent infinite loop of writing manifest

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/bitmap.rs
If a compaction rewrites some (but not all) fragments in an index then the remapping will be partial remapping.  The bitmap index was not properly respecting this and was dropping rows that were not in the remapping (instead of keeping them as they were originally).
> fix: don't lose rows during bitmap remap if rows not being remapped

- docs/contributing.rst
`maturin develop` does not work at the top level directory, make it explicit in the guide.
```
➜  lance git:(improve-developer-guide-on-build) ✗ source .venv/bin/activate                  
((.venv) ) ➜  lance git:(improve-developer-guide-on-build) ✗ maturin develop          
💥 maturin failed
Caused by: Failed to parse Cargo.toml at /Users/haochengliu/Documents/projects/lance/Cargo.toml
Caused by: TOML parse error at line 1, column 1
|
1 | [workspace]
| ^
missing field `package`
```
> docs:clarify instructions on where to run maturin develop

- python/python/tests/test_scalar_index.py
- python/python/tests/test_vector_index.py
- rust/lance/src/dataset/scanner.rs
When performing a search (vector or FTS) we can use a scalar index to help us calculate the prefilter.  In some cases we don't even have to materialize the scalar index.  However, our old logic was too loose here and didn't materialize even when the scalar index was behind the vector/FTS index (didn't cover all the fragments).
This PR restricts the non-materialization path to only be followed when the scalar index is fully caught up to the vector/fts index.
> fix: flat scan frags not covered by scalar index when doing prefilter search

- python/python/tests/test_vector_index.py
- rust/lance/src/io/exec/knn.rs
the bug is that we may call `execute` multiple times, and it causes a panic in datafusion `RepartitionExec`, the conditions to repro:
1. the dataset has vector index and the vector index contains at least 2 deltas
2. the dataset has a scalar index, there are any unindexed rows for the scalar index
3. do vector search with prefilter
This also improves the performance of vector search with prefilter when there are more than 1 deltas, because before it performed scalar index query & scanning for each delta, but now it does only once
> fix: partition not used yet panic

- python/DEVELOPMENT.md
- python/Makefile
The target generated by Python is relatively large. Here, add a clean mechanism in the makefile to ensure that temporary builds can be deleted frequently.
@westonpace @wjones127 Could you help me review this part of the changes?
> feat(build): add make clean target for Python temporary files

- rust/lance/src/index/vector/utils.rs
we are sampling by the number of rows, but in multivector case, single row contains many vectors
> chore: use less sample size for multivector

- python/Cargo.toml
- rust/lance-core/src/utils.rs
- rust/lance-core/src/utils/stream.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-io/src/local.rs
- rust/lance-io/src/object_store/tracing.rs
- rust/lance-io/src/scheduler.rs
- rust/lance-table/src/io/deletion.rs
- rust/lance-table/src/utils/stream.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/io/exec/scan.rs
- rust/lance/src/io/exec/take.rs
* Fixes spans to record `object_store::path::Path` with `.as_ref()`, so it displays as `"/my/path"` instead of `Path { inner: "/my/path/" }`.
* Add `size` fields to some object store spans
* Pass span does into the background IO loop of the scheduler. This way we can see all IO calls associated with a query in its spans.
* Changes `read_deletion_file` span to only start if there is a deletion file. This reduces span spam in the traces where there are no deletion files.
* Change `apply_deletions` span to only start if there are deletions. Similar to above, reduces span clutter in traces.
* Add spans to `MergeInsertJob::execute_uncommitted_impl` and `CommitBuilder::execute` so we can clearly see the write and commit step in each attempt of `MergeInsert` job retries.
* Add spans for …
> feat: add tracing spans to ScanExec and TakeExec

- rust/lance-table/src/io/commit.rs
- rust/lance-table/src/io/manifest.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/index.rs
- rust/lance/src/index/cache.rs
- rust/lance/src/io/commit.rs
- rust/lance/src/utils/test.rs
* Eliminates a `HEAD` request to get the size of the manifest before attempting to read the index section.
* When we open a manifest file, if we happened to read the index section, decode it eagerly so we don't have to make an additional IO request later.
* When we write a manifest file, put the index metadata in the cache.
> perf: optimize load_indices

- python/python/lance/dataset.py
- python/python/tests/test_dataset.py
- python/src/dataset.rs
- rust/lance-core/src/utils/backoff.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/utils/test.rs
- rust/lance/src/utils/test/throttle_store.rs
Fixes #3776
This introduces a new retry strategy, called `SlotBackoff`, designed specifically for operations that can't overlap. Exponential backoff is more appropriate for adapting to rate limits.
The following are result for N concurrent upserts where each upsert takes about 300ms.
* Current is the current behavior
* "Long exponential" is using exponential backoff, but sizing the unit based on the elapsed time after the first attempt.
* Slots is the new `SlotBackoff` strategy.
> perf: reduce retry thrashing in merge_insert

- Cargo.toml
- python/python/tests/test_file.py
- rust/lance-io/src/object_store.rs
- rust/lance-io/src/object_store/providers/aws.rs
- rust/lance-io/src/object_store/providers/azure.rs
- rust/lance-io/src/object_store/providers/gcp.rs
- rust/lance-io/src/object_store/providers/local.rs
- rust/lance-io/src/object_store/providers/memory.rs
- rust/lance-io/src/scheduler.rs
We can often end up with large pages.  This is easier in 2.1 than it is in 2.0 but it can happen in 2.0 as well.  When this happens we make one large request into object storage.  However, these large requests are problematic.  Partly because we get less performance (less parallelism) and partly because they are prone to failure, especially timeout, when the object store is under stress.  As a result, it is better to split requests into smaller requests.
> feat: split large reads into smaller parallel reads

- rust/lance-index/src/scalar/bitmap.rs
This PR teaches the bitmap to write & read scalar indices by multiple record batches rather than just one so that it can handle enormous data size which may overflow int32::max.
A new test is added to test the fix.  It's skipped by default due to its > 10min runtime.
> fix: handle bitmap index overflow by implementing multi-batch read&write #3515

- .github/workflows/rust.yml
It seems the default runners no longer come with cargo-fmt.
> ci: add the setup-rust-toolchain action to the format & lint jobs

- rust/lance/src/dataset/scanner.rs
- rust/lance/src/io/exec/knn.rs
Updates the new_with_children method to update the node's prefilter source where applicable. Prior to this commit, the implementation prevented plan optimization from happening under some circumstances.
> fix: respect prefilter transformation in ANNIvfSubIndexExec

- .github/workflows/java.yml
If we specify the toolchain in the `.yml` file then it will ignore the value of https://github.com/lancedb/lance/blob/main/rust-toolchain.toml
Instead, we should not specify it, and update `rust-toolchain.toml` when we are ready to move rust versions.
> ci: use toolchain file in Java builds

- python/python/tests/test_dataset.py
- rust/lance/src/dataset/transaction.rs
In the data replacement operation we find an existing file and change the path.  We also need to change the size of the file as well.
> fix: update size of data file in data replacement operation

- python/python/tests/test_blob.py
- rust/lance-core/src/datatypes.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
Currently we translate nulls into a struct `{"position": 1, "size": 0}`.  As a result, we had the descriptions schema marked as non-nullable.  However, this is slightly confusing (if user scans blob column they should get null, not this placeholder struct) and caused issues when data files were missing (since we populate those with null).
This fixes the latter problem by changing the descriptions schema to nullable.  However, we should also fix the other problem at some point.  We would need to wrap the packed struct decoder we use for blob descriptions with a layer that converts this placeholder value to null.
That being said, we could probably enact this cleanup in 2.1 and not worry about it for 2.0 as it is fairly minor (users aren't generally looking at the blob descriptions).
Closes …
> fix: allow nulls when blob data files are missing

- .github/workflows/java-publish.yml
Execute release build on Linux x86 and arm64 and then release on mac so that we get consistent docker linux build
> ci(java): fix java release workflow

- rust/lance-table/src/io/commit.rs
- rust/lance/src/dataset.rs
- rust/lance/src/io/commit.rs
This fixes the failing test like https://github.com/lancedb/lance/actions/runs/15223146317/job/42821795030
Background: if users drops a dataset, and then re-create it, it's possible for long-lived readers to have loaded a manifest from the dataset prior to deletion. We might have identical manifest file names `1.manifest` and `1.manifest`, but different contents. To detect these cases, we keep track of the `e_tag` of these. This PR makes sure we use this `e_tag` in the cache key.
> fix: use `e_tag` in cache key for cached manifests

- .github/workflows/python.yml
- .github/workflows/run_tests/action.yml
- python/python/tests/test_torch.py
The macos CI jobs have been hanging consistently for quite some time.  After pytest finishes the python interpreter hangs on exit.  I was able to extract a stack trace using the `faulthandler` module combined with `gtimeout`:
```
Thread 0x00000001edfacf80 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py", line 111 in _stop_locked
File Current thread 0x00000001edfacf80 (most recent call first):
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py"", line /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py111" in _stop_locked
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multipro …
```
> ci: disable torch tests on macos CI

- rust/lance-io/src/object_store/list_retry.rs
https://github.com/lancedb/lance/pull/3644 introduced a static listing stream, with a bug that listing result could be dropped if the sender has finished sending all items but the receiver is still in pending state. When this bug happens, the dataset would checkout_latest to an old version, and when the the dataset is used in commit, writer continuously tries to commit to an existing version.
> fix: last item could be dropped from directory listing

- protos/table.proto
- python/src/dataset/optimize.rs
- python/src/transaction.rs
- rust/lance-core/src/utils/tracing.rs
- rust/lance-index/src/frag_reuse.rs
- rust/lance-index/src/lib.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/index.rs
- rust/lance/src/index/cache.rs
- rust/lance/src/index/frag_reuse.rs
BREAKING CHANGE: Signature of `dataset::optimize::commit_compaction` has renamed `options` as `remap_options`, and takes additional `CompactionOptions` as `options`. The `dataset::transaction::Operation::Rewrite` adds a new field `frag_reuse_index: Option<Index>` that holds optional fragment reuse index metadata if present.
This PR introduces a new index, fragment reuse index, to store compaction row address information after compactions. The index will be created when compaction has option defer_index_remap enabled.
The index is named as "fragment reuse" since the ultimate goal is to allow query to reuse old indexed fragments in replacement of new unindexed fragments for index queries. An alternative was to name it a "remap index", but that name was too confusing as the term "remap" is …
> feat!: introduce fragment reuse index to defer compaction index remap

- rust/lance-arrow/src/deepcopy.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
Close: https://github.com/lancedb/lance/issues/3825
> fix: `PrimitiveStructualEncoder` extract_validity buffer should follow flag keep_original_array

- rust/lance-core/src/container/list.rs
- rust/lance-index/src/lib.rs
- rust/lance-index/src/scalar/inverted/encoding.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance/src/dataset/optimize/remapping.rs
- rust/lance/src/index/frag_reuse.rs
when remap a posting list we use `ExpLinkedList::with_capacity` to avoid re-allocation, but we were using `ExpLinkedList::block_iter` to process the posting lists, and expecting the size of each block to be less or equal to `BLOCK_SIZE`, remapping a posting list with length greater than BLOCK_SIZE would case this
> fix: unexpected posting block size when remap posting list

- rust/lance/src/dataset/transaction.rs
As titled.
Some grammatical errors found when I read the transaction comment details
> docs: fix some grammatical errors for operations comments

- Cargo.lock
- java/core/lance-jni/src/file_reader.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-file/Cargo.toml
- rust/lance-file/src/v2/reader.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance/src/dataset/fragment.rs
In 2.1 we changed what is expected from the `ReaderProjection`.  We had fixed the `from_field_ids` constructor but not the `from_column_names` constructor.  In addition, I cleaned up the comments for `ReaderProjection` to explain this change.
> fix: skip non-leaf fields when projecting by column names in 2.1

- rust/lance-datafusion/src/substrait.rs
This also moves to using datafusion's `to_substrait_extended_expr` instead of creating a dummy plan like we were before (we should do this on the parse path eventually too)
> fix: correctly specify schema in encoded substrait for expr

- .github/workflows/rust.yml
This PR tend to address a build failure over the main branch.
---
[This task](https://github.com/lancedb/lance/actions/runs/15511966061/job/43674024324) failed for:
```shell
= note: some arguments are omitted. use `--verbose` to show all linker arguments
= note: mold: failed to write to an output file. Disk full?
collect2: fatal error: ld terminated with signal 7 [Bus error], core dumped
compilation terminated.
```
This PR can address this by:
- Maximize build space by removing not needed tools from runner
- ~~Don't use rust-cache for this job since rust deps can have update every day. The cache doesn't work most of the time.~~
> chore(ci): maximize build space to avoid no space left for rust build

- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
fixes https://github.com/lancedb/lance/issues/3962
`remove_outer_validity()` is called inside `encode_miniblock` and `encode_fullzip` which comes after dictionary encoding. This PR moves `remove_outer_validity` call before dictionary encoding.
> fix: call remove_outer_validity() before dictionary_encode

- python/python/tests/test_table_provider.py
- python/src/lib.rs
- rust/lance/src/io/exec/rowids.rs
We need to ensure all of our exec nodes do not spawn tasks in the execute fn until https://github.com/apache/datafusion/issues/16312 is addressed.  The `AddRowAddrExec` was violating this and this PR fixes that.
> fix: don't panic on DF table provider if test has filter on indexed column

- docs/performance.rst
- rust/lance-io/src/scheduler.rs
The 2.1 reader has various limits that will cause it to pause.  It will not read too much data at once (the readahead queue) and it will be limited by the `LANCE_IO_THREADS` variable which controls how many concurrent requests we allow for a single scan.
There is a further limit, which is a process-wide limit, on the number of concurrent IOPS.  Previously this limit was disabled.  However, it is rather easy to get in a situation where excessive IOPS are generated when doing any kind of multi-threaded workload.  For example, compaction will trigger this as it spawns multiple compaction tasks and each task needs to read from object storage.
This PR changes the default to enabled and sets it at 128.
> refactor: change the default process-wide IOPS limit to be 128

- Cargo.lock
- rust/lance-index/Cargo.toml
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/wand.rs
- rust/lance/src/io/exec/fts.rs
it happens only if all conditions satisfied:
- search with new search algo (block max wand), this means it's on the version that new FTS format has been introduced
- the FTS index is still in legacy format
- some posting list produces a candidate doc, that its doc id is greater than the first posting list's max doc id
> fix: panic caused by reading empty posting list

- rust/lance/src/dataset.rs
I don't know why this table config is not retrievable.
I added an interface for this. If this is unnecessary, I expect someone could tell me how to get it by any means
> feat(rust): add get config interface for dataset

- docs/distributed_write.rst
Fixes https://github.com/lancedb/lance/actions/runs/15718440005/job/44293946196. Note that this does not fix all the out of date Spark-Lance documentation. I am working on an update for that in https://github.com/lancedb/lance-spark/pull/24
> chore: fix broken spark doc link

- protos/file.proto
- rust/lance-core/src/datatypes/field.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance-file/src/datatypes.rs
Allow users to set primary key through Arrow schema metadata with `primary_key` config key. A primary key column must not be nullable. User can configure composite primary key through `,` delimiter, or using a custom delimiter specified by another `primary_key_delim` config key.
Closes #4003
> feat: support unenforced primary key concept in schema

- rust/lance-core/src/cache.rs
- rust/lance/src/session.rs
This can be used to compute the hit and miss rate of the caches.
> feat: add cache stats for new cache

- Cargo.lock
- deny.toml
- python/Cargo.lock
- rust/lance-encoding/Cargo.toml
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/statistics.rs
This PR addresses #3350. Now largeutf8 and largeBinary(64bits) are support in lance format v2.1
> feat: support large_string/large_binary in lance format v2.1

- docs/integrations/ray.rst
Description:  
This pull request corrects a typo in the Ray integration documentation. The method reference for "Lance Data Sink" was previously written as py:meth:`ray.data.Dataste.write_lance` and has been updated to the correct py:meth:`ray.data.Dataset.write_lance`. This ensures accurate documentation and prevents confusion for users referencing the API. No other changes were made.
> fix(doc): fix doc typo in Ray integration documentation for Lance Data Sink

- python/python/lance/dataset.py
Hi everyone, I'm new to lance. When I play with lance, I found the `write_dataset` behavior is different from the api documents. 
The document says it will raise an Error if uri doesn't exist. https://github.com/lancedb/lance/blob/main/python/python/lance/dataset.py#L3938
But actually it will create the dataset if uri doesn't exist. https://github.com/lancedb/lance/blob/main/rust/lance/src/dataset.rs#L498
I think this is a typo, fixing it will be more friendly to newcomers. Thanks.
> docs: fix write_dataset append mode obsolete description

- rust/lance/benches/take.rs
- rust/lance/src/dataset.rs
We noticed a performance gap when using the dataset, fragment, and file reader APIs for point query. Here we add bench cases to help investigating the problem.
> feat: add random take bench based on file reader api and fragment api

- python/python/lance/torch/data.py
I am implementing a scheme to turn some tasks of building indexes on the current GPU into a single-machine multi-GPU scheme. However, I found that the current TorchDataset cannot be switched between single-machine single-GPU and single-machine multi-GPU. T
herefore, a switch is added here.
> feat: add a toggle for automatic rank/world_size discovery

- .github/workflows/python.yml
- Cargo.lock
- Cargo.toml
This reverts commit e8cb182ffb637b4772665ebbf6a0911bbe19704e.
---
Revert our upgrade until https://github.com/lancedb/lance/issues/4100 get resolved.
This PR also adds `Cargo.toml` and `Cargo.lock` as triggers for the Python CI to help prevent similar issues from occurring in the future.
> Revert "chore: update tantivy version to 0.24.1 (#4098)"

- java/core/lance-jni/src/blocking_dataset.rs
- java/core/lance-jni/src/utils.rs
- java/core/src/main/java/com/lancedb/lance/Dataset.java
- java/core/src/test/java/com/lancedb/lance/DatasetTest.java
> feat(java): support config operation for Dataset

- Cargo.lock
- rust/examples/Cargo.toml
- rust/examples/src/full_text_search.rs
- rust/lance-datagen/src/generator.rs
- rust/lance-index/Cargo.toml
- rust/lance-index/benches/inverted.rs
- rust/lance-index/benches/ngram.rs
- rust/lance/Cargo.toml
- rust/lance/src/dataset/optimize.rs
While working with `RandomWords` in actual code, I realized that our previous API design wasn't ideal, so I proposed a new design that supports larger strings for easier use.
close https://github.com/lancedb/lance/issues/4013
> refactor(datagen): add RandomWord and RandomSentence to replace RandomWords

- Cargo.toml
#4046 removed lance-encoding-datafusion but did not fully remove its reference, causing version bump to miss it.
> chore: fully remove lance-encoding-datafusion

- .github/workflows/bump-version/action.yml
- Cargo.toml
- java/core/lance-jni/Cargo.lock
- java/core/lance-jni/Cargo.toml
This will improve CI build speed and reduce disk space further
> chore: remove lance-jni from workspace Cargo dependencies

- rust/lance-io/src/object_writer.rs
Found this small function rename inconsiste when studying the code
> refactor: rename UploadState state change function

- python/python/tests/test_huggingface.py
Fixes breaking CI like https://github.com/lancedb/lance/actions/runs/16180444945/job/45675632080 by using a different HF dataset that do not use its own script.
> ci: huggingface dataset scripts are no longer supported

- rust/lance-encoding/src/encodings/physical/block.rs
- rust/lance-encoding/src/v2/encodings/logical/primitive.rs
This PR addresses [lancedb/lance#4028](https://github.com/lancedb/lance/issues/4028) by introducing a length-prefixed format for the Zstd buffer compressor. The goal is to improve the decompression performance of Zstd-compressed buffers.
Currently, the Zstd buffer compressor uses the standard compression API and decompresses data using the Zstd streaming API. While functional, this approach is not optimal as the streaming decompression introduces overhead.
In this PR, I switch to a block decompression approach by:
* Prefixing each compressed buffer with its original (uncompressed) length (encoded as a 64-bit little-endian integer)
* Using Zstd’s block decompression API during decoding, which avoids the overhead of stream mode.
* Leveraging the Zstd magic number and a reserved bit in the …
> perf: use size prefixing for zstd buffer compressor for better decompressing performance

- python/src/dataset.rs
- rust/lance-index/src/lib.rs
This feature allows pylance to show the system index instead of ignoring them so they can be used by callers if necessary.
> feat: support inferring system index type

- README.md
The contributing link on the README.md page was broken, addressed by the issue #4183. This PR fixes the simple issue.
> fix: contributing link fixed on README.md

- rust/lance-io/src/scheduler.rs
Previously, BYTES_READ_COUNTER was incremented before awaiting the result of the async read operation. This could lead to incorrect metrics in case of I/O errors or failed reads.
> fix: move BYTES_READ_COUNTER update after await to ensure accuracy

- rust/lance-core/src/error.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/sql.rs
> feat: support sql api for dataset

- python/python/tests/test_lance.py
- python/src/dataset.rs
- rust/lance-core/src/datatypes/schema.rs
- rust/lance/src/dataset/scanner.rs
Currently, the scanner does not support passing in hidden columns, such as rowid and rowaddr, which will result in an error.
```
self = <lance.dataset.LanceScanner object at 0x7f330d7cbf60>
def to_reader(self) -> pa.RecordBatchReader:
>       return self._scanner.to_pyarrow()
E       ValueError: LanceError(Schema): Schema error: No field named _rowid. Valid fields are data_item_id., /data00/code/emr/lance/rust/lance-datafusion/src/projection.rs:171:25
```
This PR mainly allows both with_row_id in the scanner and rowid in the columns. The reason for this is that when performing push - down on the computing side, the schema in the dataframe is generally pushed directly to the columns, rather than setting properties specifically for a certain with_row_id or with_row_addr. 
Therefore, there …
> fix: allow rowid in columns for scanner

- Cargo.lock
> ci: fix nightly rust build failure of zerocopy

- .github/workflows/nightly_run.yml
Prevent forked repositories to keep running nightly jobs and fail. Example: https://github.com/jackye1995/lance/actions/runs/16394030190/job/46323723362
> ci: do nightly runs only on the main repository

- python/Cargo.lock
- rust/lance-core/src/datatypes.rs
- rust/lance-datagen/src/generator.rs
- rust/lance-encoding/src/compression.rs
- rust/lance-encoding/src/compression_algo/fsst/Cargo.toml
- rust/lance-encoding/src/compression_algo/fsst/src/fsst.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/encodings/physical/general.rs
- rust/lance-encoding/src/testing.rs
This PR addresses https://github.com/lancedb/lance/issues/3350. 
This enhancement enables Lance to handle datasets with string/binary fields exceeding 4GB in total size while maintaining optimal compression ratios through FSST.
It breaks the binary data layout for binary/string data in lance V2.1(unstable) format.
It also absorbs PR #4095 to not error on highly compressible FSST by Weston.
* Extends FSST compression support to handle large binary and string data by implementing 64-bit offset support alongside the existing 32-bit offsets for miniblock, fullzip and dictionary encoding. This enables efficient compression of variable-width data that exceeds the 4GB limit imposed by 32-bit offsets. 
* Made FSST compression generic - Updated FSST implementation to work with both 32-bit and …
> feat: add 64-bit offset support to FSST compression for large binary/string data in V2.1

- python/python/tests/test_scalar_index.py
- python/python/tests/test_vector_index.py
- rust/lance/src/dataset/scanner.rs
A recent change made it so that `_rowid` came before `_distance` in vector searches.  We have consistently output `_rowid` after any `_distance` or `_score` column.  This PR reverts that (presumably) unintentional side effect.
> fix: ensure _rowid comes after _distance and _score

- .github/workflows/cargo-publish.yml
This PR will enable trust publishing for all our rust crates. After this change, we don't need to have static key from crates.io anymore.
> ci: enable crates.io trust publishing

- .github/workflows/java-publish.yml
Closes #4305 
We need to continue to use Debian 10 to ping glibc version to 2.28
> ci: fix Debian 10 EOL for java publish workflow

- rust/lance-index/src/scalar/inverted/index.rs
lance returns an error for phrase queries if the FTS index is not created with `with_position=true`, this should be an invalid input error not index error
> fix: correct the error enum in case of missing positions for phrase queries

- java/core/lance-jni/src/lib.rs
- java/core/lance-jni/src/sql.rs
- java/core/src/main/java/com/lancedb/lance/Dataset.java
- java/core/src/main/java/com/lancedb/lance/SqlQuery.java
- java/core/src/main/java/com/lancedb/lance/sql/SqlQuery.java
- java/core/src/test/java/com/lancedb/lance/SqlQueryTest.java
Add sql query for java api.
epic: https://github.com/lancedb/lance/issues/3950
See:
https://github.com/lancedb/lance/pull/4267
https://github.com/lancedb/lance/pull/4086
> feat(java): expose sql api for java api

- rust/lance-index/src/vector/ivf/transform.rs
- rust/lance-index/src/vector/kmeans.rs
this is useful when we need to know the distance from each vector to the centroid it belongs to (the case of RabitQ)
> chore: return the distances when computing partitions

- rust/lance-datafusion/src/substrait.rs
- rust/lance/src/dataset/scanner.rs
Parsing and encoding Substrait requires a Datafusion `SessionState` in order to look up UDFs.  I was working on an integration that uses Datafusion UDFs and it was failing to parse Substrait filters because the parse routine was using a newly created default session context.  This PR makes the session state configurable.  It also gets rid of the old "dummy plan" approach and encodes the extended expression message directly.
> refactor: simplify substrait logic, allow session state to be injected

- protos/file.proto
- protos/table.proto
This patch fixes some formatting, but mainly wording and clarity in the comments in the table.proto file in order to remove ambiguity or fix accidents like mixing up file and fragment.
(This patch also cleans up file.proto a tiny bit)
> docs: clean up table.proto

- Cargo.toml
- rust/lance-core/Cargo.toml
- rust/lance-index/Cargo.toml
- rust/lance-io/Cargo.toml
- rust/lance-table/Cargo.toml
- rust/lance/Cargo.toml
- rust/lance/src/utils.rs
lance-io includes cloud features and critical types/methods that sibling libraries need without strictly needing cloud features. Make sure that lance-io is depended on by default without the default feature set except for lance which will pull in the requisite features as they're enabled.
This is so that building lancedb with default-features = false excludes the entire dependency chain for crates supporting the cloud features, shrinking the size and speeding up the build of the purely embedded version.
Both this and https://github.com/lancedb/lancedb/pull/2568 resolves https://github.com/lancedb/lancedb/issues/2567
Verified via:
```
cargo tree -p lancedb -e no-build -e no-dev --no-default-features -i aws-config | less
```
> fix: make sure cloud features aren't implicitly enabled (lancedb/lancedb#2567)

- rust/lance-encoding/src/decoder.rs
- rust/lance-file/src/v2/reader.rs
- rust/lance-io/src/object_store.rs
- rust/lance/src/io/exec/filtered_read.rs
The new filtered read applies deletion vectors before the read.  There was a bug in this logic so that, if the last row in the fragment was deleted, an empty range would be sent to the file reader.  For example, if a file had 50 rows and row 49 was deleted we would ask for rows `[0..49], [50..50]`.
The file reader then had a bug that, when it processed that empty range, it would panic.  This seems specific to 2.0 files with the list data type though the fix is to just ignore empty ranges at the top level.
> fix: don't panic when reading files if the last row was deleted

- python/python/tests/test_dataset.py
- rust/lance-core/src/datatypes/schema.rs
- rust/lance-datafusion/src/projection.rs
- rust/lance/src/datafusion/dataframe.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/sql.rs
Recent changes made it so we didn't report an error in `project` if a column did not exist.  This made it possible to get an error "no columns selected" when all columns asked for did not exist.  This was quite confusing.
This PR cleans up that behavior by reworking the projection slightly.
Previously, if a user requested zero columns, then they would receive an error "no columns selected and with_row_id is False, there is nothing to scan".  With this PR we now return empty record batches (with the correct number of rows).
> feat: allow empty projection

- java/core/lance-jni/src/blocking_dataset.rs
- java/core/lance-jni/src/schema.rs
- java/core/lance-jni/src/transaction.rs
- java/core/src/main/java/com/lancedb/lance/Dataset.java
- java/core/src/main/java/com/lancedb/lance/FragmentMetadata.java
- java/core/src/main/java/com/lancedb/lance/Transaction.java
- java/core/src/main/java/com/lancedb/lance/fragment/DataFile.java
- java/core/src/main/java/com/lancedb/lance/fragment/DeletionFile.java
- java/core/src/main/java/com/lancedb/lance/fragment/RowIdMeta.java
- java/core/src/main/java/com/lancedb/lance/operation/Append.java
- java/core/src/main/java/com/lancedb/lance/operation/Overwrite.java
- java/core/src/main/java/com/lancedb/lance/operation/Project.java
- java/core/src/main/java/com/lancedb/lance/operation/SchemaOperation.java
- java/core/src/test/java/com/lancedb/lance/DatasetTest.java
- java/core/src/test/java/com/lancedb/lance/TransactionTest.java
Close #4382 
So that java operations afterwards must implement read function
> feat(java): dataset supports reading transaction

- rust/lance/src/dataset/builder.rs
Some code seems to not have been annotated with a feature check for AWS correctly resulting in code failing to compile without the AWS feature.
> fix: make sure aws feature is applied to code correctly

- rust/lance-io/src/object_store/providers/oss.rs
When using OSS as output path, if we write to oss://bucket1/a/b/c, the data will be write to oss://bucket1/a/b/c/a/b/c, the root path should be `/` instead.
Close https://github.com/lancedb/lance/issues/4423
> fix: wrong OSS path append

- rust/lance-encoding/src/encodings/physical/rle.rs
- rust/lance/src/dataset.rs
close https://github.com/lancedb/lance/issues/4429
---
As described in #4429, highly compressed yet nested data using RLE can produce data chunks that exceed our 16KiB threshold. This happens because our RLE encoding currently considers only the data buffer size and does not account for the size of REP/DEF markers, which can consume up to 4 bytes per value.
Ideally, we should include REP/DEF sizes in the calculation, but that would require significant changes. In this PR, I implemented a workaround to address the issue at the cost of a slightly lower compression ratio. A more comprehensive fix will follow after discussion.
This PR also includes a repro as part of our unit test to prevent regression of this bug.
> fix: too large data chunk generated by highly compressed yet nested data with RLE

- rust/lance-core/src/utils.rs
- rust/lance-core/src/utils/assume.rs
- rust/lance-index/src/vector/pq/distance.rs
- rust/lance-index/src/vector/pq/utils.rs
- rust/lance-linalg/src/distance/dot.rs
- rust/lance-linalg/src/distance/l2.rs
```
construct_dist_table: l2,PQ=96,DIM=1536
time:   [116.87 µs 117.06 µs 117.32 µs]
change: [-3.9662% -3.5804% -3.1590%] (p = 0.00 < 0.10)
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
construct_dist_table: dot,PQ=96,DIM=1536
time:   [142.57 µs 142.76 µs 143.20 µs]
change: [-3.9276% -3.4103% -2.7466%] (p = 0.00 < 0.10)
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
compute_distances: 16000,l2,PQ=96,DIM=1536
time:   [370.34 µs 370.98 µs 371.97 µs]
change: [-2.0826% -1.6790% -1.3494%] (p = 0.00 < 0.10)
Found 1 outliers among 10 measurements (10.00%)
1 (10.00%) high mild
compute_distances: 16000,cosine,PQ=96,DIM=1536
time:   [390.10 µs 391.95 µs 393.27 µs]
change: …
```
> perf: introduce `assume` for generating better code

- rust/lance-encoding/src/encodings/logical/primitive.rs
`MiniBlockRepIndex::decode` used to be an allocation-heavy operation, creating numerous `Vec<Vec<u8>>` instances in memory only to drop them after parsing. The idea behind this PR is straightforward: decode the rep index directly from bytes without introducing any additional allocations.
```shell
Benchmarking V2_1 Single Random Take FileReader(1048577 file size, 1024 batches, 1000 rows per take)
Benchmarking V2_1 Single Random Take FileReader(1048577 file size, 1024 batches, 1000 rows per take): Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 16.7s, or reduce sample count to 20.
Benchmarking V2_1 Single Random Take FileReader(1048577 file size, 1024 batches, 1000 rows per take): Collecting 100 samples in estimated 16.699 s …
```
> refactor: optimize MiniBlockRepIndex decode by decoding from bytes directly

- .github/workflows/license-header-check.yml
- java/core/lance-jni/src/blocking_dataset.rs
- java/core/lance-jni/src/blocking_scanner.rs
- java/core/lance-jni/src/error.rs
- java/core/lance-jni/src/ffi.rs
- java/core/lance-jni/src/file_reader.rs
- java/core/lance-jni/src/file_writer.rs
- java/core/lance-jni/src/fragment.rs
- java/core/lance-jni/src/lib.rs
- java/core/lance-jni/src/schema.rs
- java/core/lance-jni/src/sql.rs
- java/core/lance-jni/src/traits.rs
- java/core/lance-jni/src/transaction.rs
- java/core/lance-jni/src/utils.rs
- java/jni_license_header.txt
- java/license_header.txt
I found that some source files under java/core/lance-jni are not licensed.  I added and picked the same SPDX style with other rust code files. I don't know if this is reasonable. Happy to get any feedback.
> chore: add license into java/core/lance-jni sources and integrate ci

- python/python/lance/dataset.py
- python/python/tests/test_create_empty_index.py
- python/src/dataset.rs
- python/src/tracing.rs
- rust/lance-index/src/traits.rs
- rust/lance-table/src/format/index.rs
- rust/lance/src/dataset.rs
- rust/lance/src/dataset/optimize.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/index.rs
- rust/lance/src/index/create.rs
- rust/lance/src/index/mem_wal.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/index/vector.rs
Closes #3940
* Adds a new `train` parameter to `create_index`.
* When `train=False`, the index will be created empty, with an empty `fragment_bitmap`. It just exists to store the index configuration.
* This is not yet supported for vector indices, as that will be done in a follow up. #4034
* Added a new `CreateIndexBuilder` to add this parameter in Rust. This allowed us to avoid having to break the current Rust API.
* Changed behavior of index retention: now when all data in an index has been deleted or overwritten, we may keep the index file still if there are no other files under that name. This means indexes are not dropped until user explicitly asks they are. 
```rust
dataset
.create_index_builder(&["category"], IndexType::Bitmap, &params)
.train(false)
.await?;
```
> feat: allow creating empty scalar indices

- rust/lance-index/src/scalar/btree.rs
this could happen if the indexed column is with a data type with offsets buffer, and the dataset has many rows to get the offset overflowed
> fix: btree prewarm causes offset overflow

- ci/bump_version.py
Fixes https://github.com/lancedb/lance/actions/runs/16956924074/job/48060843621
> ci: skip version validation for workspace version crates

- python/pyproject.toml
Part of https://github.com/lancedb/lance/issues/4472
I will remove it after ternsorflow have a fix.
> ci: pin tersorflow version to bring macOS ARM CI back

- rust/lance-encoding/benches/buffer.rs
- rust/lance-encoding/src/buffer.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/bitpacking.rs
- rust/lance-encoding/src/encodings/physical/block.rs
- rust/lance-encoding/src/encodings/physical/constant.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/encodings/physical/packed.rs
- rust/lance-encoding/src/encodings/physical/rle.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/previous/encodings/logical/blob.rs
- rust/lance-encoding/src/previous/encodings/physical/binary.rs
- rust/lance-encoding/src/previous/encodings/physical/bitpack.rs
- rust/lance-encoding/src/previous/encodings/physical/dictionary.rs
- rust/lance-encoding/src/previous/encodings/physical/fsst.rs
This PR removes the owned LanceBuffer to eliminate runtime `try_clone` checks.
We observed numerous instances in recent user environments where buffers were reused but not properly aligned, leading to frequent occurrences of owned LanceBuffers. Unfortunately, many `try_clone` checks went unverified, and we had been assuming they were borrowed buffers.
Rather than attempting to fix all the unchecked owned buffers, we reconsidered whether retaining these owned buffers is worthwhile. In practice, they have never provided tangible benefits in real-world use cases.
Therefore, we have decided to remove the owned LanceBuffer concept entirely, eliminating the need for runtime `try_clone` checks. This change simplifies the codebase and makes it significantly easier to maintain.
cc @westonpace, …
> refactor: remove owned LanceBuffer to eliminate runtime try_clone checks

- docs/src/integrations/datafusion.md
- rust/lance-datafusion/src/exec.rs
- rust/lance-datafusion/src/lib.rs
- rust/lance-datafusion/src/udf.rs
- rust/lance/src/dataset/sql.rs
First step of https://github.com/lancedb/lance/issues/3855
> feat: add contains_tokens udf

- rust/lance-index/src/vector/flat/index.rs
- rust/lance-index/src/vector/graph.rs
for partition with ~8K rows, the ANN index takes only 39.356µs to calculate the distances, but sorting the candidates by distances takes 132.739µs, it's even worse with larger partition, so use heap to reduce the overhead, which takes only 10.018µs
> perf: use heap to maintain topk results

- rust/lance-arrow/src/deepcopy.rs
- rust/lance-arrow/src/lib.rs
- rust/lance-index/src/scalar/inverted/index.rs
Fixes #4512 
In local testing, Arrow.get_array_memory_size() for LargeBinaryArray(MutableBuffer) will reserve large virtual memory space and report that space which is much bigger than actual memory usage, can result in tens to hundreds times bigger than actual memory usage.
This PR switch to calculate the actual data size + some estimated struct overhead. This PR may result in cache size underestimation.
Cache reporting: 57.67MB for 8343 entries (7KB per entry)
Process memory: ~200MB RSS (133MB for consisntent hashing ring)
Original reporting: Would have been 3.6GB (455KB per entry)
> fix: fix FTS index cache underutilization due to DeepSizeOf overestimation

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/wand.rs
if the filters match only a few rows, it may cause the WAND fails to filter out docs.
So we can evaluate only the matched rows, which would be much faster than running WAND first, this means to decompress at most `num_rows_matched * num_tokens` blocks
> perf: fallback to brute force FTS if filters matching fewer rows

- rust/lance-table/src/feature_flags.rs
- rust/lance-table/src/format.rs
Context:
https://github.com/lancedb/lance/pull/4257#issuecomment-3208930462
This is simpler than I thought...
> feat: provide feature flag for shallow cloning

- rust/lance-datafusion/src/projection.rs
- rust/lance/src/dataset/scanner.rs
In the past when we created a projection plan from a schema it was possible to mask out certain columns while still maintaining the overall structure.  This was only exposed via rust (no way to project with schema via python) but we (LanceDB) found at least one workflow relying on this behavior.
The behavior changed (unintentionally) in https://github.com/lancedb/lance/commit/eeea03c21e9c5082a1699c5eee3c14dd3d0ef60a and this PR restores the old behavior.  That being said, I don't particularly love that there are two different ways to specify a projection and it might be nice to update downstream workflows at some point or come up with some way to do masking via projection expressions.
> fix: restore behavior of projection plans from schema

- python/python/lance/dataset.py
- rust/lance-index/src/scalar/inverted/tokenizer.rs
Solves https://github.com/lancedb/lance/issues/4564
> docs: fix inverted index default values in pydoc

- rust/lance-index/src/scalar/inverted/wand.rs
- rust/lance/src/dataset.rs
this improves WAND perf in case of the query consists of many tokens:
- use bubble sort when the algo only needs to advance single iterator
- move less posting iterators when evaluate the documents if there are many iterators are at the same doc id
> perf: improve FTS performance for long query

- rust/lance-io/src/object_store.rs
- rust/lance-io/src/object_store/providers.rs
- rust/lance-io/src/scheduler.rs
- rust/lance/src/dataset/builder.rs
- rust/lance/src/dataset/cleanup.rs
- rust/lance/src/utils/test.rs
- rust/lance/src/utils/test/throttle_store.rs
Adds storage options to the wrap method of the WrappingObjectStore trait. This information may be necessary for the configuration of some kinds of object stores - for instance caching stores may care about azure storage account names.
Also exposes the cache_key trait method of ObjectStorageProvider, to enable custom storage providers to define their own methods of constructing keys.
> feat!: add storage options to wrapping object store

- java/core/lance-jni/src/fragment.rs
- java/core/src/main/java/com/lancedb/lance/Fragment.java
- java/core/src/main/java/com/lancedb/lance/RowAddress.java
- java/core/src/test/java/com/lancedb/lance/FragmentTest.java
- rust/lance/src/dataset/fragment.rs
This PR adds a method for Dataset to delete some rows (identified by _rowaddr list) from a specific Fragment.
This method will be used in Spark MOR update. The updated old rows are deleted from the Fragment using Deletion Vector. And updated new rows are written in new Fragments. In commit stage, Update transaction operation is committed on the Dataset to apply updation.
> feat(java): add deleteRows for Fragment

- python/python/tests/test_fragment.py
- python/src/fragment.rs
- Fixed the missing `base_id` field in the `asdict` method of `PyDeletionFile` 
- Added comprehensive test coverage for DeletionFile serialization with base_id
- Resolves TypeError when deserializing FragmentMetadata objects containing a DeletionFile with base_id
When attempting to serialize and deserialize a `FragmentMetadata` object with a `DeletionFile` that has a `base_id`, the deserialization fails with:
```
TypeError: DeletionFile.__new__() missing 1 required positional argument: 'base_id'
```
This occurs because the `asdict` method in `fragment.rs` (line 462) doesn't export the `base_id` parameter, which is required when reconstructing the `DeletionFile` object.
Added `dict.set_item(intern!(slf.py(), "base_id"), slf.0.base_id)?;` to include the `base_id` field in the dictionary …
> fix: include base_id in DeletionFile serialization

- python/pyproject.toml
- python/python/tests/test_json.py
- rust/lance-arrow/src/json.rs
- rust/lance-core/src/datatypes/field.rs
- rust/lance-datafusion/src/planner.rs
- rust/lance-datafusion/src/udf.rs
- rust/lance-datafusion/src/udf/json.rs
- rust/lance/src/dataset/scanner.rs
- rust/lance/src/dataset/utils.rs
- rust/lance/src/dataset/write.rs
Part of https://github.com/lancedb/lance/issues/4516
This PR will add UDFs for JSON so users can read JSON like:
```python
ds_path = Path(tmpdir) / "nested_json_test.lance"
lance.write_dataset(table, ds_path, data_storage_version="2.2")
dataset = lance.dataset(ds_path)
result = dataset.to_table(
filter="json_get_string(json_get(json_get(data, 'user'), 'profile'), 'name') = 'Alice'"
)
assert result.num_rows == 1
assert result["id"][0].as_py() == 1
result = dataset.to_table(
filter="json_extract(data, '$.user.profile.settings.theme') = '\"dark\"'"
)
assert result.num_rows == 1
assert result["id"][0].as_py() == 1
```
---
**This PR was primarily authored with Claude Code using Opus 4.1 and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned …
> feat: add UDFs for json

- java/core/src/test/java/com/lancedb/lance/SqlQueryTest.java
The right order is `assertEquals(expected, actual)` in JUnit.
> chore: fix wrong order of assertEquals

- Cargo.lock
- deny.toml
- python/Cargo.lock
- rust/lance-io/Cargo.toml
- rust/lance-io/src/object_store/providers/aws.rs
- rust/lance-io/src/object_store/providers/azure.rs
- rust/lance-io/src/object_store/providers/gcp.rs
User can set `use_opendal=true` storage option to enable this route. Any storage option will be passed to OpenDAL as is to initialize its operator.
Related to: https://github.com/apache/arrow-rs-object-store/issues/472
> feat: allow using opendal to access s3, azblob and gcs

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- rust/lance-core/src/utils/testing.rs
- rust/lance-io/src/object_store/tracing.rs
- rust/lance-io/src/testing.rs
- rust/lance/src/utils/test.rs
Updates object_store to 0.12.3. This fixes a deprecation warning that is produced when Lance is built with 0.12.3.
> chore: update object_store

- rust/lance-linalg/src/distance/dot.rs
Currently the error bound for float32 dot product sometimes become inaccurate and fails the test. This PR switches to use the bound described in [Accuracy and Stability of Numerical Algorithms - Chapter 3](http://ftp.demec.ufpr.br/CFD/bibliografia/Higham_2002_Accuracy%20and%20Stability%20of%20Numerical%20Algorithms.pdf) to calculate the error bound.
> fix: use better error estimation for float32 dot product

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- python/Cargo.lock
Upgrade jieba-rs to 0.8.1 to fix RUSTSEC-2025-0057
> chore: upgrade jieba-rs to 0.8.1

- java/lance-jni/src/blocking_dataset.rs
- java/lance-jni/src/ffi.rs
- java/lance-jni/src/fragment.rs
- java/lance-jni/src/utils.rs
- java/src/main/java/com/lancedb/lance/Dataset.java
- java/src/main/java/com/lancedb/lance/Fragment.java
- java/src/main/java/com/lancedb/lance/WriteParams.java
- java/src/test/java/com/lancedb/lance/DatasetTest.java
- java/src/test/java/com/lancedb/lance/TestUtils.java
This PR is about to add `enable_stable_row_ids` option to Java API.
I notice that `stable_row_ids` is an important feature that has been introduced to Rust module. I believe that the java ecosystem also need this feature.
> feat(java): extends WriteParams in java with `enable_stable_row_ids` option

- protos/table.proto
It is not possible to read DeletionFile.file_type and get back a value of "unspecified". For better or worse, an absent value will be read as ARROW_ARRAY: https://protobuf.dev/programming-guides/field_presence
> docs: non-optional enum fields in proto3 do not have explicit presence

- python/pyproject.toml
- python/python/tests/test_memory_leaks.py
- rust/lance-core/src/cache.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-index/benches/inverted.rs
- rust/lance-index/benches/ngram.rs
- rust/lance-index/benches/zonemap.rs
- rust/lance-index/src/scalar/bitmap.rs
- rust/lance-index/src/scalar/btree.rs
- rust/lance-index/src/scalar/inverted.rs
- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/json.rs
- rust/lance-index/src/scalar/label_list.rs
- rust/lance-index/src/scalar/lance_format.rs
- rust/lance-index/src/scalar/ngram.rs
- rust/lance-index/src/scalar/registry.rs
- rust/lance-index/src/scalar/zonemap.rs
- rust/lance-index/src/vector/ivf/shuffler.rs
- rust/lance/benches/scalar_index.rs
- rust/lance/src/index/scalar.rs
- rust/lance/src/index/vector/ivf.rs
- rust/lance/src/index/vector/ivf/v2.rs
- rust/lance/src/session.rs
- rust/lance/src/session/caches.rs
- rust/lance/src/session/index_caches.rs
Prior to this commit, when a dataset loaded an index into its index cache, it would attach a strong reference to its index index cache to the index.
This resulted in a circular reference: the dataset's cache contained self-referential values. This prevented the cache from getting deallocated when the dataset was dropped, resulting in a leak if many datasets were opened over time.
This commit puts weak references to the cache on the indexes so the cycle is broken.
> fix: circular reference in index caching leaks memory

- java/lance-jni/src/transaction.rs
- protos/table.proto
- protos/transaction.proto
- python/src/transaction.rs
- rust/lance-index/src/mem_wal.rs
- rust/lance/src/dataset/transaction.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/dataset/write/merge_insert.rs
- rust/lance/src/dataset/write/merge_insert/exec/write.rs
- rust/lance/src/dataset/write/update.rs
- rust/lance/src/index/mem_wal.rs
- rust/lance/src/io/commit/conflict_resolver.rs
Fixes #4611 
This PR adds a new MERGED state to the MemWAL state machine to better distinguish between data that has been flushed to disk versus data that has been fully merged into the source table. Previously FLUSHED directly means MERGED, which causes too many MemTables accumulated in memory and cannot be dropped until they are sequentially merged. This new state allows flushing MemTables to disk as soon as possible to mitigate memory pressure.
BREAKING CHANGE: related APIs `MergeInsertJobBuilder. mark_mem_wal_as_flushed` is renamed to `MergeInsertJobBuilder.mark_mem_wal_as_merged` based on the new definition.
> feat!: add MERGED state to MemWAL index

- rust/lance-io/src/scheduler.rs
This is probably paranoid premature optimization but ¯\_(ツ)_/¯
> perf: avoid per-iop clone of filename

- rust/lance-core/src/utils/cpu.rs
This pull request updates the detection logic for FP16 SIMD support on AArch64 platforms in the `lance-core` crate. The main change is to ensure that on iOS and tvOS, NEON SIMD support is assumed for FP16 operations, while on other AArch64 platforms, runtime detection is still used.
Platform-specific SIMD detection:
* In `rust/lance-core/src/utils/cpu.rs`, the initialization of `FP16_SIMD_SUPPORT` now always assumes NEON support for FP16 on AArch64 iOS and tvOS platforms, while retaining runtime detection for other AArch64 targets.
> fix: refine SIMD support detection for AArch64 on iOS/tvOS

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- rust/lance-index/Cargo.toml
- rust/lance-index/src/scalar/bloomfilter/sbbf.rs
Since split block bloom filters were added to Parquet from Impala, a bug was found and fixed regarding an underestimate of the false positive probability. Because the number of keys in each block is not identical, some blocks have higher fals positive probabilities and some lower. There is no closed-form formula for this, but there is an iterative way to calculate it. This patch adds that.
Fixes #4730.
> fix: correct underestimate of Bloom filter epsilon

- python/python/lance/indices/__init__.py
- python/python/lance/indices/builder.py
- python/python/lance/indices/ivf.py
- python/python/lance/indices/pq.py
Move `ivf`, `pq` and etc, Python code into separate files, 
preparing for external indexing support.
> chore: split python indexing code into small components

- java/lance-jni/Cargo.lock
- java/lance-jni/src/blocking_dataset.rs
- java/src/main/java/com/lancedb/lance/Dataset.java
- java/src/main/java/com/lancedb/lance/ReadOptions.java
- java/src/test/java/com/lancedb/lance/DatasetTest.java
Creates bindings for a user to provide a serialized manifest in the Java SDK (using the same methodology as the Python SDK)
> feat: exposing option to provide a serialized manifest to the Java SDK

- rust/lance-datafusion/src/projection.rs
In https://github.com/lancedb/lance/pull/4478 a change was introduced that added the `ProjectionPlan::full()` function. This will get the entire schema for a dataset and turn every column into a SQL expression in order to call `from_expressions`. This is causing us a significant performance hit when we have datasets that have very large schemas. Since we know for certain that this function is getting all of the columns, we should be able to short circuit the work being done in parsing strings to columns against the schema and instead jump straight to evaluating each column in the schema as an `Expr`.
Running one of our benchmarks (time in seconds):
- On commit 2b774a47 (before PR 4478): 0.4338
- On commit eeea03c2 (after PR 4478): 0.7486
- eeea03c2 with my update in this PR: 0.4274
> fix: speed up generating ProjectionPlan for full schema

- rust/lance-core/src/utils/tokio.rs
Super tiny optimization because I noticed in some micro benchmarking that the time spent here was not insignificant (not _that_ large but large enough to justify this small PR)
> perf: cache num_cpus::get

- Cargo.lock
- Cargo.toml
- python/Cargo.lock
- rust/lance-encoding/Cargo.toml
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encoder.rs
- rust/lance-encoding/src/encodings/fuzz_tests.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/encodings/physical/bitpacking.rs
- rust/lance-encoding/src/encodings/physical/fsst.rs
- rust/lance-encoding/src/encodings/physical/rle.rs
- rust/lance-encoding/src/encodings/physical/value.rs
- rust/lance-encoding/src/previous/encoder.rs
- rust/lance-encoding/src/previous/encodings/logical/blob.rs
- rust/lance-encoding/src/previous/encodings/physical/bitmap.rs
- rust/lance-encoding/src/previous/encodings/physical/bitpack.rs
- rust/lance-encoding/src/previous/encodings/physical/dictionary.rs
- rust/lance-encoding/src/previous/encodings/physical/fixed_size_binary.rs
- rust/lance-encoding/src/previous/encodings/physical/fixed_size_list.rs
- rust/lance-encoding/src/previous/encodings/physical/packed_struct.rs
- rust/lance-encoding/src/testing.rs
- rust/lance-encoding/src/version.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance/src/dataset/write/commit.rs
- rust/lance/src/index.rs
- rust/lance/src/io/commit/conflict_resolver.rs
This fixes various issues in the 2.1 list decoder.  In addition, I've reworked the test utilities slightly as a large number of tests were not running against 2.1.  This exposed several issues and some tests I've had to defer fixing for future PRs and I've created TODO's for those.
> fix: fix decoder bugs in 2.1 list handling, expand test coverage

- protos/encodings_v2_1.proto
- rust/lance-core/src/datatypes.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/blob.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/primitive/blob.rs
- rust/lance-encoding/src/encodings/logical/struct.rs
- rust/lance-encoding/src/format.rs
- rust/lance-encoding/src/previous/encodings/logical/blob.rs
- rust/lance-encoding/src/testing.rs
This PR fully adds the blob encoding back into 2.1.  The PR is slightly lazy at the moment.  For scheduling we simply load the descriptions as part of the search cache in the initialization of the scheduler.  In the future we may not want to do that since it could be memory intensive.  We should instead spawn a new task to decode the descriptions via indirect I/O.  That can be saved for a follow-up however.
> feat: implement blob encoding for 2.1

- rust/lance-index/src/scalar/inverted/builder.rs
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance-index/src/scalar/inverted/merger.rs
We are now building the FST at write time instead of reading time, so the token set is constructed once during ingestion and only loaded during read operations. (Thank you @BubbleCal for this great idea!)
On a test with a 40M Wikipedia dataset, this change reduces the P95 latency by **32.3%**, from `5708.43 ms` to `3863.13 ms`.
The token set file's size reduced from `93.1 MB` to `46.2 MB`.
Before:
```shell
- open(ms): mean=84.96, p95=111.08, p99=113.98, min=69.28, max=114.70
- search(ms): mean=4993.26, p95=5708.43, p99=5778.55, min=4424.76, max=5796.08
- total(ms): mean=5078.22, p95=5814.05, p99=5891.44, min=4521.33, max=5910.78
- wall-clock(s): 25.98
```
After:
```shell
- open(ms): mean=79.45, p95=107.79, p99=113.32, min=63.61, max=114.70
- search(ms): mean=3386.18, p95=3863.13, …
```
> feat(index/fts): build fst at write time instead of read time

- rust/lance-encoding/src/compression.rs
- rust/lance-encoding/src/data.rs
- rust/lance-encoding/src/decoder.rs
- rust/lance-encoding/src/encodings/logical/list.rs
- rust/lance-encoding/src/encodings/logical/primitive.rs
- rust/lance-encoding/src/encodings/logical/primitive/dict.rs
- rust/lance-encoding/src/encodings/physical/binary.rs
- rust/lance-encoding/src/previous/encodings/physical/dictionary.rs
This is the case where data is already dictionary encoded and so we don't need to re-encode it and can just store it encoded.
> feat: add support for already-dictionary to 2.1

- python/python/tests/test_scalar_index.py
- rust/lance-index/src/scalar/expression.rs
The current search logic with scalar indexes assumes that the list returned by a scalar index contains either:
* All the true rows and all other rows are false
* All the false rows and all other rows are true
This is a problem when dealing with nulls.  This is related to https://github.com/lancedb/lance/issues/4756
This PR doesn't fix #4756 however it does help avoid some areas where we are definitely likely to do the wrong thing.
> refactor: cowardly refuse to use scalar indexes on expressions with null literals

- docs/src/format/table/index/index.md
- docs/src/format/table/index/scalar/bloom_filter.md
- docs/src/format/table/index/scalar/btree.md
- docs/src/format/table/index/scalar/fts.md
- docs/src/format/table/index/system/frag_reuse.md
- docs/src/format/table/index/system/memwal.md
- docs/src/format/table/index/vector/index.md
- Make sure we are clear that the sub-sections under "Arrow schema metadata" in vector index refers to metadata keys
- Use "indices" consistently across the docs
- Fix broken links
- Fix notes indentation
- Fix typos in various sentences and add more information if necessary
- Add bffs information in bloom filter
- Ran grammar fix through claude code
> chore: fix various typos in the index spec and add sbbf details

- rust/lance-core/src/datatypes.rs
Fix typo "blfoat16" -> "bfloat16" in datatypes.rs
> fix: fix typo "blfoat16" -> "bfloat16" in datatypes.rs

- rust/lance/src/dataset/fragment.rs
A typo introduced by https://github.com/lancedb/lance/pull/4715. Conflict with https://github.com/lancedb/lance/pull/4860.
> fix: typo in ut test_fragment_update

- rust/lance-datagen/src/generator.rs
- rust/lance/src/datafusion/logical_plan.rs
- rust/lance/src/io/exec/filtered_read.rs
Remove unecessary parens that cause warnings.
> refactor: remove unecessary parens

- rust/lance-index/src/vector/transform.rs
- rust/lance/src/index/vector/ivf/v2.rs
This is a quick fix for #4842.
I think a long-term fix will need to make this aware of the distance type. Or maybe we filter when actually computing distances later, so we don't have false-positives. I know this mostly applies for l2. Cosine (IIRC) normalizes the vectors and doesn't have this problem.
> fix: filter out vectors that could produce infinite l2 distances

- rust/lance-encoding/src/version.rs
- rust/lance-file/src/v2/writer.rs
- rust/lance/src/dataset.rs
2.1 is now stable but we never had to distinguish between "stable" and "default" before so our old warning logic was still printing a warning for users when the storage version is set to 2.1.
> fix: don't log the 'experimental' warning if users are using 2.1

- .github/workflows/rust.yml
- python/python/tests/forward_compat/datagen.py
- python/python/tests/forward_compat/test_compat.py
- rust/lance-index/src/scalar/inverted/index.rs
- rust/lance/src/dataset.rs
- rust/lance/src/index.rs
When creating using 0.38 and reading using 0.36 for `list_indices` the operation fails with 
```
thread '<unnamed>' panicked at /home/runner/work/lance/lance/rust/lance-index/src/scalar/inverted/index.rs:846:30:
called `Option::unwrap()` on a `None` value
```
> fix: forward compatibility of FTS index
