lancedb/lance

.github/workflows/cpp.yml
cpp/CMakeLists.txt
cpp/README.md

Fix cmake build on Mac and add Mac Github Action runner

---

cpp/Doxyfile
cpp/src/lance/arrow/CMakeLists.txt
cpp/src/lance/arrow/stl.h
cpp/src/lance/encodings/binary.h
cpp/src/lance/encodings/binary_test.cc
cpp/src/lance/encodings/encoder.h
cpp/src/lance/encodings/plain.h
cpp/src/lance/encodings/plain_test.cc

* Add `Decoder::Take(arrow::Array indices)` interface
* Add STL adaptor to convert a vector / initialize_list to array
* Add tests.

Implement Decoder::Take to selectively read a chunk with indices

---

cpp/CMakeLists.txt
cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/bench_utils.cc
cpp/benchmarks/bench_utils.h
cpp/benchmarks/convert.cc
cpp/src/lance/format/lookup_table.cc
cpp/src/lance/format/lookup_table.h
cpp/src/lance/io/reader.cc
cpp/src/lance/io/reader.h

* Add conversion tool to convert parquet / rikai dataset into Lance format.
* Add point query benchmarks.

Convert parquet to lance and add point query test

---

cpp/src/lance/arrow/type.cc
cpp/src/lance/arrow/type.h
cpp/src/lance/arrow/type_test.cc

These code are not used anymore. Remove them can reduce the header.

Remove protobuf related code from arrow/types.h

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/point_query.cc

Bring back random access benchmark from POC.

Random Access Benchmark

---

python/benchmarks/README.md
python/benchmarks/bench.py

#65 
- Does the result need to be converted to records/json? currently they’re just pandas dataframes
- The use cases here don’t actually require parsing and reading any of the XML annotations

Minimal code for usecase benchmarking

---

.github/workflows/python.yml
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/io/record_batch_reader.cc
cpp/src/lance/io/record_batch_reader.h
python/setup.py
python/tools/Dockerfile.manylinux2014

Use Arrow's ThreadPool to load record batch

---

python/MANIFEST.in
python/setup.py
python/tools/Dockerfile.manylinux2014

also includes sdist fix to close #78

the protobuf rpms on pbone disappeared. switching to https download

---

cpp/benchmarks/convert.cc
cpp/include/lance/arrow/writer.h
cpp/src/lance/arrow/arrow_dataset_test.cc
cpp/src/lance/arrow/reader.cc
cpp/src/lance/arrow/writer.cc
cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h
cpp/src/lance/io/limit_test.cc
cpp/src/lance/io/reader_test.cc
cpp/src/lance/io/writer.cc
protos/format.proto
python/lance/__init__.py
python/lance/_lib.pyx
python/lance/tests/api_test.py
python/lance/tests/duckdb_test.py

This keeps the format a little simpler and gives us room to
figure out where to put it (along with index perhaps?)

Remove the primary key for now

---

cpp/CMakeLists.txt
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/arrow/testing.h
cpp/src/lance/arrow/writer_test.cc

Fix compile warnings for testing

---

cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/encodings/plain.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/io/reader.cc
cpp/src/lance/io/writer.cc

Add read / write support for
- Timestamp(unit)
- Time32 / Time64
- Date32 / Date64
Closes #98

Add read/write support for time / datetime types

---

cpp/include/lance/arrow/file_lance.h
cpp/include/lance/arrow/writer.h
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/writer.cc
cpp/src/lance/arrow/writer_test.cc
python/lance/__init__.py
python/lance/_lib.pyx

Set batch size when writing the file

---

python/benchmarks/bench_utils.py
python/benchmarks/parse_coco.py

1. Lance cannot write boolean array just yet so iscrowd stays int
2. Add kwargs to DatasetConverter.make_embedded_dataset to control parquet row_group_size
3. blacken

Minor fixes for benchmarks

---

cpp/src/lance/arrow/scanner.cc
cpp/src/lance/arrow/utils.cc
cpp/src/lance/arrow/utils.h
cpp/src/lance/io/project_test.cc

Rebind filter after lance schema projection.

---

cpp/src/lance/encodings/binary.cc
cpp/src/lance/encodings/binary.h
cpp/src/lance/encodings/binary_test.cc
cpp/src/lance/encodings/dictionary.cc
cpp/src/lance/encodings/dictionary.h
cpp/src/lance/encodings/encoder.h
cpp/src/lance/encodings/plain.cc
cpp/src/lance/encodings/plain.h

Fix offset calculation in VarBinaryEncoder for slices

---

cpp/src/lance/arrow/type.h
cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/io/writer.cc

Test writing fixed size list and fixed size binary via WriteTable

---

cpp/src/lance/encodings/plain.cc

Fix fixed size length calculation

---

cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/encodings/plain.cc

Fix PlainEncoder to read empty page

---

python/benchmarks/bench_utils.py
python/benchmarks/parse_coco.py
python/lance/tests/test_types.py
python/lance/types/__init__.py
python/lance/types/image.py

Make it easier to convert from iterable of Image and chunked arrays

Image Array

---

cpp/src/lance/arrow/CMakeLists.txt
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/arrow/testing.h
cpp/src/lance/arrow/type.h
cpp/src/lance/arrow/writer_test.cc
cpp/src/lance/encodings/encoder.h
cpp/src/lance/encodings/plain.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc
cpp/src/lance/format/visitors.cc
cpp/src/lance/io/reader.cc
cpp/src/lance/io/writer.cc
cpp/src/lance/io/writer.h
cpp/src/lance/testing/CMakeLists.txt
cpp/src/lance/testing/extension_types.h

Fix writing and reading extension type

---

python/benchmarks/bench_utils.py
python/benchmarks/coco_classes.csv
python/benchmarks/parse_coco.py
python/lance/tests/test_types.py
python/lance/types/image.py
python/lance/types/label.py

1. Use ImageType for the 3 url columns
2. Convert the annotations.name column to dictionary array
This will replace #171 until working with extension types are easier

Coco improvements

---

python/lance/pytorch/data.py
python/lance/tests/test_pytorch.py
python/lance/tests/test_types.py
python/lance/types/__init__.py
python/lance/types/image.py

And make a contract that Pytorch Dataset returns numeric values as `torch.Tensor`.

Support converting PIL from Image in pytorch Dataset

---

cpp/CMakeLists.txt
cpp/src/lance/encodings/plain.cc
cpp/src/lance/io/reader_test.cc
cpp/src/lance/testing/io.cc
cpp/src/lance/testing/io.h

Fix PlainDecoder handle empty filtered array

---

cpp/src/lance/format/schema.cc
cpp/src/lance/io/CMakeLists.txt
cpp/src/lance/io/record_batch_reader_test.cc
cpp/src/lance/testing/io.cc

Fix bug that attempt to partitioned columns which does not exist in the file.

---

cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/encodings/plain.cc
cpp/src/lance/io/exec/base.cc
cpp/src/lance/io/exec/base.h
cpp/src/lance/io/exec/filter.cc
cpp/src/lance/io/exec/limit.cc
cpp/src/lance/io/reader.cc
cpp/src/lance/io/record_batch_reader_test.cc

Pass filter indices via Limit and Return empty array in GetListArray

---

README.md

Updates the README.md with the correct URI and bindings for the latest oxford pet dataset

update README.md to reflect new URI and bindings

---

.github/workflows/benchmarks.yml

fix gh actions to test benchmarks
let's just keep the benchmark stuff running on this branch so we can keep using it for debugging GH actions

install fsspec and s3fs

---

cpp/src/lance/arrow/arrow_dataset_test.cc
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/testing/CMakeLists.txt
cpp/src/lance/testing/json.cc
cpp/src/lance/testing/json.h

Add ArrayFromJSON and TableFromJSON help functions for easy testing.

---

cpp/src/lance/format/manifest.cc
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc
protos/format.proto
python/lance/tests/test_api.py

Write schema metadata to Manifest

---

cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/file_lance_ext.h
cpp/src/lance/arrow/scanner.cc
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/io/CMakeLists.txt
cpp/src/lance/io/exec/CMakeLists.txt
cpp/src/lance/io/exec/counter.cc
cpp/src/lance/io/exec/counter.h
cpp/src/lance/io/exec/limit.cc
cpp/src/lance/io/exec/limit.h
cpp/src/lance/io/exec/limit_test.cc
cpp/src/lance/io/exec/project.cc
cpp/src/lance/io/record_batch_reader.cc
cpp/src/lance/testing/io.cc
cpp/src/lance/testing/io.h
python/lance/tests/test_api.py

Apply Limit cross multiple files in the dataset. 

---

cpp/src/lance/encodings/binary.cc

Fix false assertion during BinaryEncoding

---

cpp/src/lance/cmd/lance.cc
cpp/src/lance/format/schema.cc
python/benchmarks/converter.py
python/benchmarks/oxford_pet/datagen.py
python/benchmarks/requirements.txt

Using a int16 sequential number as primary key

Generate primary key for Oxford Pet dataset

---

integration/duckdb/.clang-format
integration/duckdb/CMakeLists.txt
integration/duckdb/Makefile
integration/duckdb/README.md
integration/duckdb/src/lance/duckdb/lance-extension.cc
integration/duckdb/src/lance/duckdb/list_functions.cc
integration/duckdb/src/lance/duckdb/list_functions.h
integration/duckdb/src/lance/duckdb/ml/catalog.cc
integration/duckdb/src/lance/duckdb/ml/catalog.h
integration/duckdb/src/lance/duckdb/ml/functions.cc
integration/duckdb/src/lance/duckdb/ml/functions.h
integration/duckdb/src/lance/duckdb/ml/pytorch.cc
integration/duckdb/src/lance/duckdb/ml/pytorch.h
integration/duckdb/src/lance/duckdb/vector_functions.cc
integration/duckdb/src/lance/duckdb/vector_functions.h

Initialize support of Duckdb Extension

DuckDB Extension

---

.gitattributes

tested locally:
```
github-linguist       
66.44%  367097     C++
28.30%  156347     Python
3.01%   16638      CMake
1.77%   9752       Cython
0.34%   1862       Shell
0.11%   621        Dockerfile
0.03%   182        Makefile
```

linguist fix

---

python/benchmarks/coco/datagen.py
python/benchmarks/converter.py
python/benchmarks/oxford_pet/datagen.py

since these are public we can use the https url so we don't need to pre-sign anything

Change datagen to use public https image urls

---

.github/workflows/benchmarks.yml
python/benchmarks/converter.py
python/benchmarks/functions/functions.py

Fix `main` branch benchmark test failures

[Python] use new write api in python benchmark

---

cpp/CMakeLists.txt
cpp/src/lance/encodings/plain.cc
cpp/src/lance/encodings/plain_test.cc

[C++] Fix write fixed list array bug

---

.github/workflows/cpp.yml
cpp/include/lance/arrow/file_lance.h
cpp/src/lance/arrow/file_lance.cc
cpp/src/lance/arrow/type.cc
cpp/src/lance/arrow/type.h
python/pyproject.toml
python/setup.py
python/tools/Dockerfile.manylinux2014
python/tools/auditwheel
python/tools/build_manylinux_wheels.sh

Arrow release starts to break build again.

Upgrade Apache Arrow to 10.0

---

.gitignore
integration/duckdb/upload.sh

make it easier to manage extension releases

script to upload lance extension zip

---

cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/format/schema_test.cc

- Add `Schema.Project()` over a list of field IDs(int32)
- Add `Schema.Intersection(const Schema&)`

[C++] Project schema via field Ids and Schema intersection

---

cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/type.cc
cpp/src/lance/arrow/type.h
cpp/src/lance/format/schema.cc

[C++] Support column projection during add_columns via expression

---

.github/workflows/cpp.yml
python/lance/pytorch/data.py
python/lance/tests/test_pytorch.py
python/tools/Dockerfile.manylinux2014

[Python] Pytorch Dataset uses Fragment instead of files and support versions

---

cpp/benchmarks/CMakeLists.txt
cpp/benchmarks/bench_utils.cc
cpp/benchmarks/bench_utils.h
cpp/benchmarks/convert.cc
cpp/benchmarks/oxford_pet.cc
cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/scanner.cc
cpp/src/lance/arrow/scanner_test.cc
cpp/src/lance/format/schema.cc
python/benchmarks/oxford_pet/analytics.py
python/lance/data/convert/base.py

```
SELECT image, class FROM oxford_pet WHERE class = 'pud' LIMIT 20 OFFSET 50
```
Before this PR:  8.1s
After: 0.85s
Closes #292

[C++] Performance profiling and improvement 

---

cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_test.cc
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h
python/lance/_lib.pyx
python/lance/tests/test_api.py
python/lance/tests/test_schema_evolution.py

[C++][Python] Add timestamp to each manifest version.

---

python/lance/_lib.pyx
python/lance/tests/test_schema_evolution.py

make the user be explicit about timestamp

fix timezone issue with version timestamp

---

cpp/include/lance/arrow/dataset.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/updater.cc
cpp/src/lance/arrow/updater_test.cc

[C++] Store relative path for data files

---

python/tools/update_pet.sh

make it easier for tutorial users who don't have s3 credentials

create and update tarball for pets

---

cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_test.cc

Dataset raises error when merging a Table with the same column (name).

[C++] Sanity check to verify column does not overlap when merging a new table

---

cpp/include/lance/arrow/dataset.h
cpp/include/lance/arrow/updater.h
cpp/src/lance/arrow/dataset.cc
cpp/src/lance/arrow/dataset_ext.h
cpp/src/lance/arrow/dataset_test.cc
cpp/src/lance/arrow/updater.cc
cpp/src/lance/arrow/updater_test.cc
cpp/src/lance/format/manifest.cc
cpp/src/lance/format/manifest.h
cpp/src/lance/format/schema.cc
cpp/src/lance/format/schema.h
cpp/src/lance/io/pb.cc
cpp/src/lance/io/pb.h
cpp/src/lance/io/reader.cc
cpp/src/lance/io/reader.h
cpp/src/lance/io/writer.cc
cpp/src/lance/io/writer.h
protos/format.proto
python/lance/_lib.pyx
python/lance/tests/test_schema_evolution.py

Supplement metadata key-value pairs for Schema when updating a dataset.

[C++] Attach new schema update when update dataset

---

integration/duckdb/README.md
integration/duckdb/src/lance/duckdb/lance-extension.cc
integration/duckdb/tests/test_query.py

Add a derivative macro `dy/dx`.

[DUCKDB] Add a Derivative macro

---

python/lance/data/convert/imagenet.py

Switch to creating imagenet from raw ImageNet dataset (Kaggle). 
Added fields:
* image id
* External image URI pointed to S3

[Benchmark] Create imagenet from raw dataset

---

python/lance/__init__.py
python/lance/data/convert/imagenet.py
python/lance/tests/test_schema_evolution.py
python/lance/tests/util/test_versioning.py
python/lance/util/versioning.py

Various fixes for imagenet and fmt changes

---

cpp/src/lance/encodings/binary.cc
rust/src/arrow.rs
rust/src/encodings.rs
rust/src/encodings/binary.rs
rust/src/encodings/dictionary.rs
rust/src/encodings/plain.rs
rust/src/format/page_table.rs

* Binary encoder
* Support nulls in binary encoding

[RUST] Binary encoder and null support.

---

rust/src/dataset/scanner.rs
rust/src/io/object_reader.rs

1. byte range in reader
2. iterator in scanner
3. projection in scanner

fix byte range and iterator bug

---

rust/src/arrow.rs

Provide a function to append column to `RecordBatch`.

Append column to RecordBatch

---

rust/pylance/python/lance/dataset.py

inherit from pyarrow Dataset/Scanner

---

rust/pylance/benchmarks/sift/README.md
rust/pylance/benchmarks/sift/datagen.py

Sift-1M is a popular vector search dataset.

Sift dataset generation

---

rust/src/io/local.rs
rust/src/io/object_reader.rs

Make ObjectReader prefetch size configurable

---

rust/benches/vector_index.rs
rust/src/dataset/scanner.rs
rust/src/index/vector.rs
rust/src/io/exec/knn.rs

Add a refining step at the end of the filter to use the raw vector to improve the sorting.

Add a refine stage for vector search

---

rust/src/datatypes.rs
rust/src/encodings/binary.rs
rust/src/io/object_reader.rs
rust/src/io/reader.rs

Handle null strings for both cases where nullability is set or not.

---

python/python/lance/dataset.py
python/python/tests/test_lance.py

[python] write_dataset returns new dataset

---

protos/index.proto
python/benchmarks/sift/datagen.py
python/benchmarks/sift/metrics.py
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/encodings/plain.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs
rust/src/io/exec/take.rs
rust/src/io/reader.rs

Using PQ quantizer globally to build a global codebook.

Reimplement IVF_PQ index.

---

rust/Cargo.toml
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/pq.rs
rust/src/utils/kmeans.rs

Support python SDK to call `dataset.create_index()`

Use pure rust kmean in IVF and PQ

---

rust/src/dataset/scanner.rs
rust/src/format/metadata.rs
rust/src/io/exec/scan.rs
rust/src/io/reader.rs

Reader honor batch size

---

python/Cargo.toml
rust/Cargo.toml
rust/src/io/reader.rs

Fix main branch GHA failure due to `cargo fmt`

[Rust] Fix main branch CI failure and bump arrow version

---

python/python/lance/dataset.py
python/python/tests/test_lance.py

Support writing pandas dataframes directly

---

integration/duckdb_lance/duckdb-ext/src/data_chunk.rs
integration/duckdb_lance/duckdb-ext/src/table_function.rs
integration/duckdb_lance/duckdb-ext/src/vector.rs
integration/duckdb_lance/src/arrow.rs
integration/duckdb_lance/src/scan.rs

Duckdb extension can support column projection now.

[DuckDB] Fix scan column projection in duckdb extension

---

python/python/lance/__init__.py
python/python/lance/dataset.py
python/src/lib.rs

Pass the version from the pylance Cargo.toml and make it accessible as `lance.__version__` in python.

[python] Add __version__ to python package. Closes #561

---

rust/src/arrow.rs
rust/src/format.rs
rust/src/format/metadata.rs
rust/src/format/page_table.rs
rust/src/index.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/pq.rs
rust/src/io/writer.rs

Clippy fixes

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/src/dataset.rs

Signed-off-by: yah01 <yah2er0ne@outlook.com>

Add take() to retrieve rows by indices

---

protos/format.proto
python/python/lance/dataset.py
python/python/lance/vector.py
python/python/tests/test_dataset.py
python/python/tests/test_lance.py
python/src/dataset.rs
rust/src/dataset.rs
rust/src/format/manifest.rs

Closes #581
@ananis25  thanks again for the bug report

Fix version timestamp issue

---

rust/src/datatypes.rs
rust/src/io/writer.rs

Decimal128 and Decimal256 support

---

rust/src/dataset.rs

This is half of #591 
The other half will be in separate PR since they're logically separate

Don't inherit the index_section if mode is Overwrite

---

rust/benches/distance.rs
rust/src/utils/distance.rs
rust/src/utils/distance/compute.rs
rust/src/utils/distance/cosine.rs

With X86_64 AVX2 and Aarch64 Neon SIMD impl

[Rust] Cosine Distance

---

rust/src/dataset/scanner.rs

Extract each node creation snippet into a separate method

refactor Scanner::try_into_stream

---

integration/duckdb_lance/duckdb-ext/src/duckdb_ext.cc
integration/duckdb_lance/duckdb-ext/src/duckdb_ext.h
integration/duckdb_lance/duckdb-ext/src/logical_type.rs
integration/duckdb_lance/duckdb-ext/src/vector.rs
integration/duckdb_lance/src/lib.rs

A few changes were made in v0.7.0 of duckdb that impacted this extension:
- list_vector changes were merged in https://github.com/duckdb/duckdb/pull/6155/
- JSON type was removed https://github.com/duckdb/duckdb/discussions/6288
- Some function signatures were changed
Fixes #567

Update extension for v0.7.0 compatibility

---

rust/src/dataset/scanner.rs
rust/src/datatypes.rs
rust/src/index/vector.rs

mainly refactor the scan method to support passing in a vec of fragments (so later we can do scan + flat search starting from a particular version)

a minor preparatory refactor

---

protos/index.proto
rust/src/arrow.rs
rust/src/bin/lq.rs
rust/src/dataset.rs
rust/src/dataset/scanner.rs
rust/src/index/vector.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/kmeans.rs
rust/src/index/vector/pq.rs
rust/src/io/exec/knn.rs
rust/src/utils/distance.rs
rust/src/utils/distance/cosine.rs
rust/src/utils/distance/l2.rs
rust/src/utils/kmeans.rs

* Persist MetricType in index protobuf
* `lq index --metric-type [l2|cosine]`

Use MetricType to specify the metric / distance compute function

---

python/python/lance/dataset.py

workaround to prevent the segfault until we figure out the real problem

---

rust/src/encodings/binary.rs
rust/src/io/exec/take.rs

Improve random access on binary encoding

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs

Support `dataset.scan(filter=...)` 
Closes #457

[Python] Support filter pushdown from Python Dataset API

---

rust/src/encodings/plain.rs

Support run `take()` random access on boolean columns

PlainDecoder take on boolean values

---

rust/src/io/local.rs

unix::read_at does not move files underlying cursor while window::seek_read does. If this is the only place file access actually happens this should be fine, because both methods take offsets relative to file, and don't care about cursor. If file access happens in other places this could be a potential footgun

Windows support

---

rust/Cargo.toml
rust/src/arrow/linalg.rs

Use cblas to do 2-D matrix mul and transpose.

Matrix mul and transpose

---

rust/src/arrow.rs
rust/src/datatypes.rs
rust/src/io/writer.rs

Support timestamp type

---

rust/src/utils/kmeans.rs

Iteractively kmean training to used in OPQ

Train kmeans iteratively

---

python/python/tests/test_filter.py
rust/src/dataset/scanner.rs
rust/src/error.rs
rust/src/io/exec/planner.rs
rust/src/utils.rs
rust/src/utils/sql.rs

* Support `col LIKE 'ab%'`
* Add test for `Like` and `In`

Support "LIKE" and "IN" in filters

---

notebooks/youtube_transcript_search.ipynb

add notebook for q&a bot

---

rust/src/arrow.rs
rust/src/arrow/schema.rs
rust/src/dataset/scanner.rs
rust/src/io/exec.rs
rust/src/io/exec/projection.rs
rust/src/io/exec/take.rs

1/N part of execution node contract.

Add input / output schema contract to Global Take

---

rust/src/datafusion/logical_expr.rs
rust/src/dataset/scanner.rs

Fix large utf filter issue mentioned in #720

[Rust] Fix filter on large UTF8 columns

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py

Fix LanceDataset.to_batches

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/fragment.rs
python/src/lib.rs
rust/src/arrow/linalg.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/dataset/scanner.rs
rust/src/datatypes.rs

[Python] Expose DataFragment via dataset

---

integration/duckdb_lance/Cargo.toml
integration/duckdb_lance/src/arrow.rs

update arrow version in duckdb extension

---

python/Cargo.toml
python/python/lance/__init__.py
python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/src/fragment.rs
python/src/lib.rs

Support pickling `FragmentMetadata` class.

Pickle Fragment Metadata

---

python/python/lance/dataset.py
python/src/dataset.rs
python/src/fragment.rs
rust/src/dataset.rs
rust/src/encodings/plain.rs
rust/src/index.rs
rust/src/index/cache.rs
rust/src/index/vector.rs
rust/src/index/vector/flat.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs
rust/src/index/vector/traits.rs
rust/src/io/reader.rs
rust/src/session.rs

[Rust] Caching index in LRU

---

python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/src/fragment.rs
python/src/lib.rs
rust/src/format/fragment.rs

[Python] Expose Fragment data files in Python

---

rust/src/io/reader.rs

ref #856 
Add a custom assertion error message.
Should be useful for debugging.

Add format string for the assertion

---

.github/workflows/duckdb.yml
integration/duckdb_lance/CMakeLists.txt

[DuckDB] Fix linux build

---

rust/Cargo.toml
rust/src/arrow/linalg.rs

make sure we can publish on docs.rs

---

rust/Cargo.toml
rust/src/arrow/linalg.rs

fix spelling of docsrs

---

rust/benches/l2.rs
rust/src/linalg/l2.rs

* Add RNG seed so performance variation run over run is low.
* Run bench mark over two seed, just to make sure the perf gain we see is not due to variation in the seed
* Add unroll to ARM simd, yields about 25%+ better latency
* Add parallel accumulators, yields another 70%+ speedup
* In all this PR reduced ARM simd latency by 75%
before
```
[309.61 ms 311.68 ms 314.93 ms] L2(simd)
[318.39 ms 345.18 ms 375.98 ms] L2(simd) second rng seed
```
after
```
[86.275 ms 86.387 ms 86.610 ms] L2(simd)
```
(I'm only with my M1 mac right now, will add this to the AVX code once I'm home)

seed l2 benchmark data generation and unroll ARM Neon simd

---

.github/workflows/pypi-publish.yml
python/Cargo.toml
rust/Cargo.toml

main branch is protected, so need to do a PR for now.

bump to v0.4.19

---

python/Cargo.toml
python/src/dataset.rs
python/src/lib.rs
rust/Cargo.toml
rust/src/dataset.rs
rust/src/index/vector/ivf.rs
rust/src/utils/kmeans.rs

Tested with `LANCE_LOG="info" pytest python/tests`
Closes #855

Use log and allow users to customize log via LANCE_LOG env

---

rust/Cargo.toml
rust/src/utils/kmeans.rs

Resulted in about 30% speedup in IVF256,PQ96

[Rust] Reduce arrow overhead during kmean training

---

rust/src/linalg/l2.rs
rust/src/utils/kmeans.rs

Another 2x improvement over #992

[Rust] Improve kmean training performance by removing dynamic dispatch

---

integration/duckdb_lance/Cargo.toml

forgot to update versions in duckdb integration

bump arrow versions on duckdb intergration as well

---

rust/Cargo.toml
rust/src/io/local.rs
rust/src/io/object_store.rs

Remove a directory (dataset) recursively.

---

docs/read_and_write.rst
python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/fragment.rs
rust/src/dataset.rs
rust/src/dataset/fragment.rs
rust/src/io.rs
rust/src/io/deletion.rs

Closes #944.
Will be ready once #916 is complete.

Add delete() method to Python API

---

rust/src/io/object_store.rs

closes #912 
`object_store` has a custom S3 client which does not accept `CredentialProviders` from `aws_config`. This PR implements an adaptor that adapts a `DefaultCredentialsChain` to a `object_store::CredentialProvider`.

wire in DefaultCredentialsChain from aws_config as the credential provider for object_store

---

protos/index.proto
python/python/lance/dataset.py
python/python/tests/test_vector_index.py
rust/src/index/vector.rs
rust/src/index/vector/diskann/builder.rs
rust/src/index/vector/ivf.rs
rust/src/linalg/dot.rs
rust/src/utils/kmeans.rs

Closes #802 
Caveats: Dot product does not have SIMD optimizations yet.

Support Dot product as metric type

---

rust/src/encodings/plain.rs

use default value for null boolean

---

rust/src/dataset/fragment.rs
rust/src/index/vector/kmeans.rs
rust/src/utils/kmeans.rs

Throw error instead of panic if kmeans training does not have sufficient data.

---

docs/format.rst
protos/format.proto

Realized I should put a bit more effort into keeping this up-to-date. I'll be doing that going forward.

docs: update format docs with feature flags and row indices

---

rust/README.md

Copypasta'ing the docs is currently a compile error

Docs: Dataset write takes reader by owner now

---

rust/src/io/object_store.rs

This PR allows caller to set custom aws credentials by setting `aws_credentials` attribute when calling `ObjectStore::from_uri_and_params`. Added a test to make sure we are using the injected creds.

allow custom AWS credentials when constructing object store

---

rust/src/dataset.rs
rust/src/datatypes/schema.rs

fix: don't compare metadata when checking schema in append

---

.github/workflows/run_tests/action.yml
python/pyproject.toml
python/python/lance/__init__.py
python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/lance/util.py
python/python/tests/conftest.py
python/python/tests/test_arrow.py
python/python/tests/test_dataset.py
python/python/tests/test_filter.py
python/python/tests/test_lance.py

This is to remove pandas as dependency of lance. See #1079.

feat: make pandas optional dependency

---

protos/format.proto
rust/src/dataset.rs
rust/src/dataset/write.rs
rust/src/format/manifest.rs

feat: track the max used fragment id

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py

Also small drive-by change to support Polars DataFrames.

fix: cast when passed an iterator

---

rust/src/dataset.rs
rust/src/error.rs

Added append method for dataset which takes self as arguemnt with tests

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/src/dataset.rs
rust/src/io/object_store.rs

feat: quick restore command

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/src/dataset.rs

This reverts commit 0a84cd35b5495aae0507a0f78d025c8db6ddc846.

Revert "feat: quick restore command (#1138)"

---

python/python/lance/fragment.py
python/src/fragment.rs
rust/src/dataset.rs
rust/src/dataset/chunker.rs
rust/src/dataset/fragment.rs
rust/src/dataset/write.rs

Fragment::write honors row group size 

---

benchmarks/flat/.gitignore
benchmarks/flat/README.md
benchmarks/flat/benchmark.py

This PR implements a flat index search benchmark. The benchmark script generates random data and writes to a dataset. Then, we search a few times using flat index, i.e. brute force.
The script generates a `benchmark.html` and `benchmark.csv` file. The html file is an interactive plot of the latency data, the csv file is the raw data.

implement flat vector index benchmark

---

python/python/lance/dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/src/dataset.rs
rust/src/index.rs
rust/src/index/vector/diskann/search.rs
rust/src/index/vector/ivf.rs
rust/src/index/vector/opq.rs
rust/src/index/vector/pq.rs
rust/src/io/local.rs

feat: expose index stats for debugging

---

python/python/tests/test_fragment.py
rust/src/format/page_table.rs

refactor: allow creating empty dataset fragments

---

rust/src/io/commit.rs
rust/src/io/commit/external_manifest.rs

In #1207 we made an update to the commit procedure. At the end of the commit process we want to repoint the manifest path to the finalized path `{x}.manifest` from `{x}.manifest-{uuid}`. This PR implements this new step.
A few changes that happened because of the update
* we used to check the object store for `{x}.manifest` as the sign that the commit has finalized. Now the code check the external store and if the returns path is does not end in UUID, we assume the manifest is finalized and does not require syncing.
* `ExternalManifestStore::get_latest_version` now returns both the version number and the path to the manifest
* Fix a few more non-atomic copys by using copy-rename. (Will undo these once we upgrade `object_store` to a version with atomic `copy` operation)

Implement path finalization for external manifest store

---

docs/format.rst
docs/read_and_write.rst

add doc on how to use `s3+ddb://` uri scheme

add documentation for dynamodb uri

---

rust/src/io/object_store.rs

Fix api breakage found when upgrading lance in lancedb

[Rust] fix API breakage in lancecb build

---

python/python/tests/test_arrow.py
python/src/arrow.rs
python/src/dataset.rs

As a temporary solution until https://github.com/apache/arrow-rs/pull/4806 is released

[Bug] Fix crashes when take extension types

---

python/python/tests/test_filter.py
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/planner.rs
rust/lance/src/utils/sql.rs

fix: can't filter on columns with uppercase names

---

python/.cargo/config.toml
python/Cargo.toml

Also increase code-gen units for release-with-debug.

refactor: move release-with-debug

---

rust/lance-arrow/src/floats.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/knn.rs

Closes https://github.com/lancedb/lancedb/issues/502

feat: fix error message to be more explicit

---

python/Cargo.toml
python/src/fragment.rs
rust/lance/src/datafusion/logical_expr.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/hash_joiner.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/updater.rs
rust/lance/src/encodings/binary.rs
rust/lance/src/encodings/plain.rs
rust/lance/src/error.rs
rust/lance/src/format.rs
rust/lance/src/format/index.rs
rust/lance/src/format/manifest.rs
rust/lance/src/format/metadata.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/commit/dynamodb.rs
rust/lance/src/io/commit/external_manifest.rs
rust/lance/src/io/exec/knn.rs
rust/lance/src/io/exec/planner.rs
rust/lance/src/io/local.rs
rust/lance/src/io/object_reader.rs
rust/lance/src/io/object_store.rs
rust/lance/src/io/reader.rs
rust/lance/src/io/writer.rs
rust/lance/src/utils/sql.rs
rust/lance/src/utils/tfrecord.rs

part of #1275
This helps with debugging tremendously.

chore: add location to all IO errors

---

python/DEVELOPMENT.md
python/Makefile
python/python/lance/optimize.py
python/python/tests/test_dataset.py
python/python/tests/test_optimize.py
python/src/dataset/optimize.rs
python/src/lib.rs
rust/lance/src/dataset/optimize.rs

fix: make CompactionPlan pickle-able and import-able

---

rust/Cargo.toml
rust/lance-arrow/src/bfloat16.rs
rust/lance-arrow/src/floats.rs
rust/lance-linalg/Cargo.toml
rust/lance-linalg/README.md
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/matrix.rs
rust/lance/Cargo.toml
rust/lance/src/index/vector/diskann/builder.rs
rust/lance/src/index/vector/graph/builder.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/opq.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/index/vector/utils.rs

* Implement a `From<FSL> for Matrix` to make conversion easier.
* Clean up float type trait

feat: improve DX for matrix struct

---

python/src/dataset.rs
rust/lance/benches/ivf_pq.rs
rust/lance/benches/vector_index.rs
rust/lance/src/bin/lq.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/vector/diskann.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/opq.rs
rust/lance/src/io/commit.rs

feat(api!): make create_index mutate self

---

python/python/tests/test_vector_index.py
python/src/dataset.rs

fix: allow limit as k

---

python/Cargo.toml
python/python/lance/dataset.py
python/python/lance/lance.pyi
python/python/lance/util.py
python/python/tests/test_dataset.py
python/src/dataset.rs
python/src/dataset/cleanup.rs
python/src/lib.rs
python/src/utils.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/cleanup.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/object_store.rs
rust/lance/src/utils/testing.rs

feat: add python bindings for the cleanup_old_versions function

---

rust/Cargo.toml
rust/lance-linalg/Cargo.toml
rust/lance-linalg/src/kmeans.rs
rust/lance-linalg/src/matrix.rs
rust/lance/Cargo.toml

chore(rust): improve kmean training time complexity

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/lance/src/dataset.rs

Added and modified two APIs
* Dataset.scanner(with_row_id)
* Dataset._take_rows(row_ids)

feat(python): expose row id in python API

---

benchmarks/dbpedia-openai/README.md
benchmarks/dbpedia-openai/datagen.py
benchmarks/dbpedia-openai/requirements.txt

Converting from huggingface [dbpedia openai](https://huggingface.co/datasets/KShivendu/dbpedia-entities-openai-1M) dataset

feat: data generation of dbpedia dataset

---

benchmarks/dbpedia-openai/README.md
benchmarks/dbpedia-openai/benchmarks.py

Test IVF_PQ performance (recall vs refine factor), cross multiple IVF,PQ configurations

chore: index / recall benchmark over dbpedia

---

.github/workflows/python.yml
.github/workflows/run_tests/action.yml
python/pyproject.toml
python/python/lance/torch/__init__.py
python/python/lance/torch/distance.py
python/python/tests/torch/test_distance.py
rust/lance/src/index/vector/pq.rs

Provide distance computation via pytorch tensors.

chore: compute distance using pytorch and GPU/MPS

---

python/python/benchmarks/test_kmeans.py
python/python/lance/torch/kmeans.py
python/python/tests/test_vector.py
python/python/tests/test_vector_index.py

Run faster on Apple Silicon GPUs

chore: improve kmean performance on MPS

---

rust/lance/src/datatypes/field.rs
rust/lance/src/datatypes/schema.rs

feat: schema::field_by_id() 

---

python/src/dataset.rs
rust/lance/src/dataset.rs

fix: handle larger arrays in take

---

integration/duckdb_lance/Cargo.toml
python/Cargo.toml
rust/Cargo.toml
rust/lance-core/src/error.rs
rust/lance-linalg/benches/dot.rs
rust/lance-linalg/benches/l2.rs
rust/lance/Cargo.toml
rust/lance/src/dataset/cleanup.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/hash_joiner.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/encodings/binary.rs
rust/lance/src/encodings/plain.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/io/reader.rs
rust/lance/src/utils/tfrecord.rs

I'll be working of this branch for the stats-aware scanner.

chore: upgrade to datafusion 32

---

python/python/benchmarks/test_search.py

This adds test datasets with deletion vectors and with new unindexed fragments

test: add new ann scenarios to the python benchmarks

---

python/python/lance/tf/data.py
python/python/tests/test_tf.py

feat: automatically convert image to tensors in TF data pipeline

---

rust/Cargo.toml
rust/lance-core/src/encodings/binary.rs
rust/lance-core/src/encodings/plain.rs

chore: use arrow 47 function

---

.github/workflows/build_linux_wheel/action.yml

ci: fix ARM build due to Ring dependency

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/lance/src/dataset.rs

https://github.com/lancedb/lance/issues/1423

feat: added dataset stats api

---

python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/tests/helper.py
python/python/tests/test_dataset.py
python/python/tests/test_fragment.py
python/src/dataset.rs
python/src/fragment.rs
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/progress.rs
rust/lance/src/dataset/write.rs

feat: expose progress on write_fragments and write_dataset

---

python/python/lance/torch/distance.py
python/python/lance/torch/kmeans.py
python/python/tests/torch_tests/test_distance.py

Use fast linear algebra instead of for-loop to compute L2 on GPU.

fix: fix L2 computation on GPU

---

rust/lance/src/dataset/scanner.rs

https://github.com/lancedb/lance/issues/1385

docs: clarify behaviour of refine_factor

---

rust/lance-core/src/error.rs

closes #1309
Use `#[track_caller]` to resolve the caller location in `From<SomeError> for Error` implementations.

feat: use caller location in error conversion functions

---

rust/lance/Cargo.toml
rust/lance/src/dataset/optimize.rs
rust/lance/src/io/commit.rs

Also adds some small performance improvements to the remapper.

fix: make sure we have physical rows

---

rust/lance-arrow/src/floats.rs
rust/lance-linalg/src/distance/cosine.rs
rust/lance-linalg/src/kmeans.rs

Make cosine distance work with bf16/f16/f32/f64

feat: generic cosine code

---

rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs

fix: pq index does not handle dot product metric correctly during search

---

python/python/lance/dataset.py
python/src/dataset.rs
rust/lance/src/dataset/fragment.rs

This is stacked on #1529. Review that PR first.

feat: expose `Dataset.validate()` in Python

---

protos/index.proto
python/src/dataset.rs
rust/lance-index/Cargo.toml
rust/lance-index/src/lib.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/pq.rs
rust/lance-index/src/vector/pq/builder.rs
rust/lance-index/src/vector/pq/transform.rs
rust/lance-index/src/vector/pq/utils.rs
rust/lance-index/src/vector/utils.rs
rust/lance/src/bin/lq.rs
rust/lance/src/index.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/session.rs

Prepare to support bf16/f16 in PQ

chore: provide a trait to dynamically dispatch different pq based on different vector data type

---

rust/lance-arrow/Cargo.toml
rust/lance-arrow/src/lib.rs

Add a `FixedSizeList::sample(n)` method.

feat: extend FSL with sample

---

rust/lance-core/src/utils.rs
rust/lance-core/src/utils/mask.rs
rust/lance-index/Cargo.toml
rust/lance-index/src/lib.rs
rust/lance-index/src/scalar.rs
rust/lance-index/src/scalar/expression.rs
rust/lance-index/src/util.rs
rust/lance-index/src/util/datafusion.rs
rust/lance/src/datafusion/logical_expr.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/prefilter.rs
rust/lance/src/io/exec/knn.rs
rust/lance/src/io/exec/planner.rs
rust/lance/src/io/exec/scalar_index.rs

There is still some work to do.  This will only use scalar indices if there is no new or deleted data.
#1566 will add the rest of the functionality but this PR is large enough as is.

feat: allow the scanner to take advantage of scalar indices

---

rust/Cargo.toml
rust/lance-core/src/io/object_store.rs
rust/lance-index/Cargo.toml
rust/lance-index/src/scalar.rs
rust/lance-index/src/scalar/btree.rs
rust/lance-index/src/scalar/flat.rs
rust/lance-index/src/scalar/lance_format.rs
rust/lance/Cargo.toml
rust/lance/benches/scalar_index.rs
rust/lance/src/dataset/index.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index.rs
rust/lance/src/index/scalar.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/diskann/search.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs

feat: add support for remapping scalar indices during compaction

---

rust/lance/src/index/cache.rs
rust/lance/src/session.rs

feat: track index cache hit rate

---

python/src/dataset.rs
rust/lance-core/src/io/object_store.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs
rust/lance/src/dataset/cleanup.rs

#1547 added and removed some APIs. This PR brings back some APIs that we still need,
and deprecates some APIs that were made redundant.

feat(rust): simplify object store option API

---

rust/lance-index/src/vector/ivf.rs

fix: fix chunk size issue

---

python/python/lance/dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs
rust/lance/src/dataset.rs

feat(python): add `index_cache_hit_rate` to `index_stats()`

---

rust/Cargo.toml
rust/lance-index/Cargo.toml
rust/lance-index/benches/pq_dist_table.rs
rust/lance-index/build.rs
rust/lance-index/src/lib.rs
rust/lance-index/src/vector/pq.rs
rust/lance-linalg/src/simd/f32.rs

Use avx512/avx2 gather instruction for L2 distance table building.

perf: fast L2 distance table build

---

rust/lance-core/src/encodings/plain.rs
rust/lance/benches/vector_index.rs

Add a branch when conversion bytes from file into arrow arrays. In this new branch, we check if the pointer to the bytes alignments with the target datatype. If they align, we convert the pointer into arrow buffer directly without copy.
benchmark, the effect is fairly significant when nprobes is set to a large number
```
Flat_Index(d=128,top_k=10,nprobes=10)
time:   [1.1026 ms 1.1167 ms 1.1326 ms]
change: [-4.7828% -0.4776% +3.8902%] (p = 0.85 > 0.10)
No change in performance detected.
Ivf_PQ_Refine(d=128,top_k=10,nprobes=10, refine=2)
time:   [1.2022 ms 1.2143 ms 1.2330 ms]
change: [-7.9295% -5.5750% -3.4885%] (p = 0.00 < 0.10)
Ivf_PQ_NoCache(d=128,top_k=10,nprobes=32, refine=1)
time:   [4.2582 ms 4.2736 ms 4.2869 ms]
change: [-28.852% -27.749% -26.565%] (p = …
```

perf: add a fast path for converting bytes into array when the bytes has the correct alignment

---

rust/lance/src/datafusion/logical_expr.rs

this is important for enabling scalar indices to work properly on filters that contain in-list expressions
closes #1641

perf: add type coersion for in-list expressions

---

python/python/tests/test_dataset.py
rust/lance/src/dataset/fragment.rs
rust/lance/src/dataset/scanner.rs

fix: support no-op filters again

---

rust/lance-core/src/io/object_reader.rs

fix: add retries for failed response stream

---

rust/lance-index/src/vector/flat.rs
rust/lance/src/dataset/scanner.rs

fix: make sure to prefilter the flat portion of a combined knn

---

python/python/lance/dataset.py
python/python/lance/torch/async_dataset.py
python/python/lance/torch/data.py
python/python/lance/vector.py
python/python/tests/torch_tests/test_data.py

closes #1686 
buffer batches together so GPU can train more efficiently

feat: add batch buffering and async loading to torch.LanceDataset

---

rust/lance/src/dataset/scanner.rs

When `use_stats=False`, we need to add `_rowid` to the projection if there are additional columns we need to pull. Otherwise we get:
```
ValueError: LanceError(IO): Error during planning: TakeExec requires the input plan to have a column named '_rowid'
```

fix: add _rowid when `use_stats=False`

---

python/python/tests/test_scalar_index.py
python/src/dataset.rs

fix: update list_indices to report if an index is vector or scalar

---

rust/lance/src/dataset.rs

We had previously commented out a call to buffered, probably to avoid the higher order lifetime issue that appears.  However, this lifetime issue is a bug and we can work around it by collecting the futures into a vector before buffering them.

perf: allow take to process multiple fragments in parallel

---

python/src/tracing.rs

These are nice to have, and don't seem to add that much to the size of traces. I got like 40% increase in one, but YMMV.

feat: turn on argument tracking in tracing

---

python/python/lance/torch/kmeans.py

Python kmeans to take FixedSizeListArray as input.

chore: kmeans fit takes pyarrow FixedSizeListArray

---

rust/lance-index/src/vector/pq.rs
rust/lance-linalg/src/distance/cosine.rs

This reverts commit a178ae512f81a7eff858f7ca80a974ecc0a6c01d.

revert: use eplison to handle all zero cosine values (#1696)

---

python/python/lance/torch/distance.py
python/python/tests/torch_tests/test_distance.py

Similar to `pairwise_l2`, it computes pairwise cosine distance.

chore: compute pairwise cosine using pytorch

---

rust/lance-linalg/src/kernels.rs

fix: fix l2 normalize

---

python/python/tests/test_dataset.py
rust/lance/src/dataset.rs

fix: take fails on non-unique indexes

---

protos/transaction.proto
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs

feat: support drop column api in Dataset

---

python/src/arrow.rs
python/src/fragment.rs

fix the CI failures shown in #1747

chore(rust): make clippy happy for the pyo3 code

---

python/python/lance/arrow.py
python/python/tests/test_arrow.py

Cast `fsl<float>` and `fsl<bf16>`

feat: cast between fsl of floats and fsl of bf16

---

benchmarks/sift/gt.py
python/python/lance/torch/bench_utils.py
python/python/lance/torch/distance.py

Add a tool to create in-sample ground truth

chore: add utility to materialize in-sample ground truth

---

python/python/lance/torch/kmeans.py
python/python/lance/vector.py

use fp32 for accumulation but cast back to the incoming data type when done

fix: proper mixed-percision training

---

python/python/lance/torch/async_dataset.py
python/python/lance/torch/kmeans.py

normalize centroids so we can use l2 for cosine
check shutdown value in async dataset each item

fix: fix gpu cosine and add early stop for async dataset

---

python/python/lance/vector.py
rust/lance/src/index/vector/ivf/io.rs

one bug fix, one minor improvment

fix: fix shuffler k-list merge and save GPU trained centroids to file

---

python/python/lance/sampler.py
python/python/lance/vector.py
rust/lance-index/src/vector/ivf/shuffler.rs

fix: switch back to stable sampling, and tune memory usage during IVF shuffle

---

python/python/lance/sampler.py
python/python/tests/torch_tests/test_data.py

when we hit the else branch on `n > max_take` the code does not respect batch size correctly

fix: fix latent sample size bug in torch dataset

---

python/python/lance/dataset.py

docs: update to_batches batch_size documentation

---

rust/lance/src/dataset/index.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/knn.rs

Expose planning as public API for third party.

chore: make create_plan a public API

---

python/src/fragment.rs

fix clippy for rust 1.75 upgrade

fix: fix 1.75 clippy

---

rust/lance-index/benches/find_partitions.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/shuffler.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs

Separate shuffling logic from IVF

refactor: do not leak precomputed partition map into IVF

---

rust/Cargo.toml

chore(rust): increase minimum rust version to 1.75 to prevent build issues

---

rust/lance-core/src/lib.rs

chore: remove empty trait

---

python/python/lance/torch/kmeans.py
python/python/lance/util.py
python/python/tests/test_vector_index.py

add a E2E test for torch training where the training data contains nans

chore: add E2E tests for torch training with nans

---

python/python/lance/dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs

allow python users to set custom PQ codebook calculated from external sources

feat: expose custom PQ codebook in python APIs

---

python/python/tests/test_vector_index.py

fix: function name

---

docs/read_and_write.rst

Code did not show up in documentation at https://lancedb.github.io/lance/read_and_write.html

docs: code blocks in lance/read_and_write.html not showing

---

python/python/lance/torch/data.py

User can define their own Tensor SerDe

feat: customize to tensor function in pytorch dataset

---

rust/lance/src/dataset/write/merge_insert.rs

This is because we do an outer join and the output columns of an outer join are always nullable.  As a result we try and insert nullable data and get a schema mismatch.  This fix avoids this problem by restoring the schema after we select the appropriate rows from the outer join output.

fix: merge insert operation fails if any of the payload columns are non-nullable

---

.github/workflows/build_linux_wheel/action.yml
.github/workflows/docs-check.yml
.github/workflows/docs-deploy.yml
.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/run_tests/action.yml
python/Makefile
python/pyproject.toml
python/python/lance/arrow.py
python/python/lance/dependencies.py
python/python/lance/tf/data.py
python/python/tests/conftest.py
python/python/tests/test_arrow.py

Pytorch 2.2 released, unblocked us to support 3.12 in CI.

chore: support python 3.12

---

rust/lance-file/src/writer.rs

fix: prevent timeouts while writing to object storage

---

python/python/tests/test_dataset.py
rust/lance-file/src/datatypes.rs

fix: support large_string dictionaries

---

rust/lance-index/Cargo.toml

Remove unnused sql parser as dependency

chore: remove sqlparser as dependency

---

rust/lance/src/dataset.rs

feat: make ReadParams Debug and Clone

---

python/Cargo.toml
rust/lance/Cargo.toml

fix: statically link lzma

---

rust/lance/src/index/vector/ivf.rs

Allow to take f16 and f64 codebook during index creation.

chore: take f16 codebook

---

python/python/lance/arrow.py
python/python/tests/test_arrow.py

feat: support large types for image ext types

---

python/python/lance/sampler.py
python/python/tests/torch_tests/test_data.py

The algorithm is described in more detail in the comments.  When there is a filter and randomness is requested then we will do our best to attempt randomness but the resulting sequence will not be perfectly randomized.

feat: add support for filtering to the ShardedBatchSampler

---

rust/lance-file/src/reader.rs
rust/lance-file/src/writer.rs
rust/lance-index/benches/hnsw.rs
rust/lance-index/examples/hnsw.rs
rust/lance-index/src/lib.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/graph/builder.rs
rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/graph/storage.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/pq.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/pq/utils.rs

Implement a PQ based VectorStorage, for graphs.

chore: pq storage

---

.github/workflows/rust.yml
rust/lance-index/src/vector/pq/distance.rs

We have a code path that is nightly only.

ci: enable rust nightly in CI

---

rust/lance-index/benches/hnsw.rs
rust/lance-linalg/build.rs

chore: make mac apple silicon build more reliable

---

rust/Cargo.toml
rust/lance-file/src/writer.rs
rust/lance-index/Cargo.toml
rust/lance-index/examples/hnsw.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/graph/builder.rs
rust/lance-index/src/vector/graph/io.rs
rust/lance-index/src/vector/graph/storage.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/hnsw/storage.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance/Cargo.toml

Persist a HNSW graph to a lance file on disk.

feat: persist hnsw graph on disk

---

rust/lance-index/src/vector/ivf/builder.rs
rust/lance-index/src/vector/pq.rs
rust/lance/src/index/vector/ivf.rs

BREAKING CHANGE: use residual to calculate cosine in PQ

chore: use residual in cosine inference

---

rust/lance-index/src/vector.rs
rust/lance-index/src/vector/bq.rs

Basic building block for Binary quantization

feat: binary quantization

---

python/python/lance/sampler.py
python/python/tests/torch_tests/test_data.py
rust/lance-index/examples/hnsw.rs
rust/lance-index/src/vector/graph/builder.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs

Implement the `SELECT-NEIGHBORS-HEURISTIC` algorithm from the HNSW paper.

feat: implement heuristic select neighbor algorithm

---

rust/lance-index/src/vector/hnsw.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/planner.rs

Add UDF for casting vector columns

feat: add `_cast_list_f16` function for casting list of floats to f16

---

python/python/lance/_dataset/sharded_batch_iterator.py
python/python/lance/dataset.py
python/python/lance/fragment.py
python/python/lance/sampler.py
python/python/lance/tf/data.py
python/python/lance/torch/data.py
python/python/tests/test_dataset.py
python/python/tests/test_vector_index.py
python/src/dataset.rs

expose dynamic projection to pylance.
TL;DR:
```python
dataset.to_table(columns={
"name": "func(my_col)"
})
```
is equal to
```SQL
SELECT func(my_col) AS name
FROM dataset
```
TODO:

feat: expose dynamic projection to pylance

---

rust/lance-index/src/vector/hnsw/builder.rs

before this, we may select all nodes to establish edges
this could improve the building perf

chore: select less but enough neighbors to establish edges

---

rust/lance-index/src/vector/transform.rs
rust/lance-linalg/src/kernels.rs
rust/lance-linalg/src/matrix.rs

To put normalize logic behand a `Transformer`, so that we can build pipeline of transforms.

chore: normalize transform

---

java/lance-jni/src/blocking_dataset.rs
java/lance-jni/src/fragment.rs
java/lance-jni/src/lib.rs
java/src/main/java/com/lancedb/lance/Dataset.java
java/src/main/java/com/lancedb/lance/Fragment.java
java/src/test/java/com/lancedb/lance/DatasetTest.java

Add `Dataset.getFragments()` API to Java.

feat(java): dataset get fragments

---

benchmarks/full_report/requirements.txt
benchmarks/full_report/tests/conftest.py
benchmarks/full_report/tests/test_config.py
benchmarks/full_report/tests/test_runner.py
benchmarks/full_report/vbench/__init__.py
benchmarks/full_report/vbench/experiment.py
benchmarks/full_report/vbench/runner.py
benchmarks/full_report/vbench/utils.py

a lance oriented vector benchmark framework.
This framework is similar in idea to ann-benchmark, with a lot more focus poured into exploring how index and query hyperparameters affect recall instead of just plotting the recall/throughput frontier.

feat: config plumbing for vector benchmark framework

---

Cargo.toml
rust/lance-datafusion/Cargo.toml
rust/lance-datafusion/src/expr.rs
rust/lance-index/src/scalar/btree.rs

chore: bump datafusion version

---

rust/lance-datafusion/src/chunker.rs
rust/lance/src/dataset.rs

chore: skip empty batch while chunking batches

---

.gitignore
Cargo.toml
python/python/benchmarks/test_merge_insert.py
rust/lance-core/Cargo.toml
rust/lance-core/src/error.rs
rust/lance-core/src/utils.rs
rust/lance-core/src/utils/futures.rs
rust/lance-datagen/Cargo.toml
rust/lance-datagen/src/generator.rs
rust/lance-io/Cargo.toml
rust/lance/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/io/exec.rs
rust/lance/src/io/exec/scalar_index.rs
rust/lance/src/io/exec/utils.rs

feat: use a scalar index, if available, during a merge insert operation

---

rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph/builder.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/examples/hnsw.rs

chore: add struct for parameters of HNSW

---

rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/examples/hnsw.rs

this enables prefilter for HNSW search

feat: support filter while searching in HNSW

---

rust/lance/src/index.rs
rust/lance/src/index/vector/ivf.rs

make a few unstable internal API public.

chore: expose internal index APIs

---

rust/lance/src/index.rs
rust/lance/src/index/prefilter.rs

expose internal prefilter traits

chore: expose prefilter traits

---

java/lance-jni/src/ffi.rs
java/lance-jni/src/fragment.rs
java/lance-jni/src/lib.rs
java/lance-jni/src/utils.rs
java/src/main/java/com/lancedb/lance/Dataset.java
java/src/main/java/com/lancedb/lance/Fragment.java
java/src/main/java/com/lancedb/lance/FragmentMetadata.java
java/src/main/java/com/lancedb/lance/WriteParams.java
java/src/test/java/com/lancedb/lance/FragmentTest.java

Add the Java Fragment Create basic structure

feat: add java fragment create

---

benchmarks/full_report/requirements.txt
benchmarks/full_report/vbench/data.py
benchmarks/full_report/vbench/experiment.py

* text2image dataset used in BigANN

perf: add a set of benchmark dataset

---

rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs

with PQ, the dist table is constructed for each level

chore: construct the dist table only once while searching

---

rust/lance-file/src/writer.rs
rust/lance-index/src/vector/ivf/shuffler.rs

then we can remain the vector column for building HNSW index, then reduce much time

chore: dynamically detect the schema while shuffling data

---

rust/lance/src/index/vector/ivf.rs

chore: expose find_partition method

---

rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/src/index/vector.rs
rust/lance/src/index/vector/hnsw.rs
rust/lance/src/index/vector/ivf.rs

missed to convert the query vector to the residual, also add test to validate the recall

fix: very low recall on IVF_HNSW

---

rust/lance/src/index/vector/ivf.rs

chore: expose query residulization

---

docs/arrays.rst

docs: update image_to_tensor to to_tensor

---

rust/lance-file/src/writer.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/builder.rs
rust/lance/src/index/vector/ivf/io.rs

This improves the index building by 2x faster,
also fixes a panic bug caused by passing wrong offset to read batch.

perf: independent parallel building for IVF_HNSW partitions

---

rust/lance-arrow/src/floats.rs
rust/lance-index/src/vector.rs
rust/lance-index/src/vector/sq.rs

plan to support scalar quantization
it's been without any optimization yet

feat: add scalar quantizer

---

rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/src/index/vector/ivf.rs

before this, we skip nodes with the same distance.

fix: may get lower recall from HNSW with quantization

---

rust/lance-io/src/object_reader.rs

A user was getting periodic errors from GCS:
```
OSError: Io error: Execution error: LanceError(IO): Generic GCS error: Error after 0 retries in 122.602µs, max_retries:10, retry_timeout:180s, source:error sending request for url (https://storage.googleapis.com/some-file.lance): connection error: unexpected end of file, /home/runner/work/lance/lance/rust/lance-io/src/object_reader.rs:61:12
```
This request was not retried because it was a request error (`error sending request`) and not a connection error and it is not a timeout.  Therefore it does not meet the criteria currently defined by `object_store`.  However, this does appear to be a legitimate "this can sometimes randomly fail" error that we want to retry.
We already had an outer retry loop in `get_range` for a similar kind of …

feat: add outer retry loop to CloudObjectReader::size

---

rust/lance-arrow/README.md

docs: fix typo in lance-arrow

---

protos/file2.proto
rust/lance-core/src/error.rs
rust/lance-file/Cargo.toml
rust/lance-file/build.rs
rust/lance-file/src/format.rs
rust/lance-file/src/lib.rs
rust/lance-file/src/v2.rs
rust/lance-file/src/v2/io.rs

feat: initial reader/writer for the v2 format

---

rust/lance-linalg/benches/l2.rs
rust/lance-linalg/src/distance/l2.rs

feat: fast l2 for uint8

---

rust/lance-index/src/vector/sq/storage.rs
rust/lance-linalg/src/distance/l2.rs

perf: use fast u8 l2 route in hnsw beam search

---

rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/graph/builder.rs
rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/graph/storage.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance/examples/hnsw.rs
rust/lance/src/index/vector/hnsw.rs
rust/lance/src/index/vector/ivf.rs

improve the recall from 90% to 99%,
according to the HNSW paper, this also improve performance, especially for highly clustered dataset

perf: impl heuristic pruning for HNSW

---

.github/workflows/python.yml
.github/workflows/run_tests/action.yml
python/pyproject.toml
python/python/lance/dependencies.py
python/python/lance/ray/__init__.py
python/python/lance/ray/sink.py
python/python/tests/test_ray.py

Provide a `LanceDatasink` to be used with `ray.data`.
It offers distributed write and compute via Ray

feat: lance ray data sink

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical.rs
rust/lance-encoding/src/encodings/logical/binary.rs
rust/lance-encoding/src/testing.rs

This renames the utf8 encoder to binary encoder and changes it to support both utf8 and binary.

feat: add support for binary encoding

---

.github/workflows/python.yml
python/pyproject.toml
python/python/lance/ray/sink.py
python/python/tests/test_ray.py

The current `ray.data.Datasink` API does not support writing larger than memory files. We have to provide more to support streaming large files into lance.

feat: add FragmentWriter and Commiter for streaming ray write

---

docs/examples/llm_training.rst

Fixed minor bugs in LLM pre-training doc due to the HF transformer version update.

fix: llm pre-training docs

---

python/src/utils.rs
rust/lance/src/index/vector/hnsw/builder.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/sq.rs

- retrieve all vectors in one call to leverage concurrency impl of `take_rows`
- build HNSW and quantization storage in parallel

perf: build HNSW and quantization storage in parallel

---

rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs

- search for enough candidates to build connections
- keep only connections which selected heuristic to get better graph quality
- select random level according to the paper's method

chore: search for enough candidates to build connections

---

Cargo.toml
rust/lance-io/Cargo.toml
rust/lance-io/src/object_store.rs
rust/lance/Cargo.toml
rust/lance/src/dataset.rs

Closes https://github.com/lancedb/lancedb/issues/1223

fix: do not create directory when open an non-existing dataset

---

rust/lance-encoding/benches/decoder.rs
rust/lance-file/benches/reader.rs
rust/lance/src/datafusion/logical_expr.rs
rust/lance/src/index/vector/ivf.rs

clippy was broken this morning
also make clippy happy on Mac

fix: clippy on main

---

python/python/tests/test_scalar_index.py
rust/lance-index/src/scalar/btree.rs
rust/lance-index/src/scalar/lance_format.rs

fix: allow for all-null pages in btree

---

.github/workflows/cargo-publish.yml
.github/workflows/make-release-commit.yml
.github/workflows/pypi-publish.yml
.github/workflows/upload_wheel/action.yml
README.md
ci/setup_version.py
docs/index.rst
python/Cargo.toml
release_process.md

ci: setup release process for preview releases

---

python/python/lance/fragment.py

feat: support storage options in write fragments

---

rust/lance-encoding/src/decoder.rs
rust/lance-encoding/src/encodings/logical/list.rs

Also removes some debug prints

fix: fix some corner cases that can arise in v2 list encoding

---

.github/workflows/upload_wheel/action.yml

https://github.com/lancedb/lance/actions/runs/8972479120/job/24640565296

ci: fix bug in upload wheel

---

.github/workflows/upload_wheel/action.yml

My local target dir is different from the one in CI.

ci: fix target dir for fury upload

---

.github/workflows/python.yml
.github/workflows/rust.yml
java/core/lance-jni/src/ffi.rs

Migrate to WarpBuild arm runner, which is 20% cheaper than alternative, and has better RAM / CPU ratio

ci: run arm64 runner on wrapbuild

---

protos/table.proto

docs: clearify comments in table.proto -> message DataFragment -> physical_rows

---

rust/lance-index/benches/find_partitions.rs
rust/lance-index/src/vector/bq.rs
rust/lance-index/src/vector/ivf.rs
rust/lance-index/src/vector/ivf/transform.rs
rust/lance-index/src/vector/pq.rs
rust/lance-linalg/benches/compute_partition.rs
rust/lance-linalg/src/kmeans.rs
rust/lance/src/index/vector/pq.rs

Part of the process is to switch to use rayon-based parallelism.

chore: consolidate compute partition implementation and remove async fn

---

rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/graph/storage.rs
rust/lance-index/src/vector/hnsw.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/pq/storage.rs
rust/lance-index/src/vector/quantizer.rs
rust/lance-index/src/vector/sq/storage.rs
rust/lance/src/index/vector/fixture_test.rs
rust/lance/src/index/vector/hnsw.rs
rust/lance/src/index/vector/ivf.rs
rust/lance/src/index/vector/ivf/io.rs
rust/lance/src/index/vector/pq.rs
rust/lance/src/index/vector/traits.rs
rust/lance/src/session/index_extension.rs

perf: make VectorStorage and DistCalculator static to generate better code

---

rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph/memory.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance/examples/hnsw.rs
rust/lance/src/index/vector/hnsw/builder.rs

it got 1.0182% faster on `InMemoryVectorStore & InMemoryDistCalculator`

chore: remove unnecessary arc

---

rust/lance/src/io.rs
rust/lance/src/io/exec.rs

for https://github.com/lancedb/sophon/issues/1947

chore: expose exec node internal APIs

---

rust/lance-linalg/src/simd/f32.rs

Shift did not reach only 1 value left.
For f32x8:
```
// min(4 elements)
m1  = [v0, v1, v2, v3, v4, v5, v6, v7]
m2  = [v4, v5, v6, v7, xx, xx, xx, xx]
min = [v0, v5, v2, v3, xx, xx, xx, xx]
// min(2 elements)
m1  = [v0, v5, v2, v3, xx, xx, xx, xx]
m2  = [v2, v3, xx, xx, xx, xx, xx, xx]
min = [v0, v3, xx, xx, xx, xx, xx, xx]
// min(1 element) (This step is missing now)
m1  = [v0, v3, xx, xx, xx, xx, xx, xx]
m2  = [v3, xx, xx, xx, xx, xx, xx, xx]
min = [v0, xx, xx, xx, xx, xx, xx, xx]
```

fix: f32 reduce_min for x86

---

rust/lance/src/io/exec/take.rs

expose dataset field
part of https://github.com/lancedb/sophon/issues/1947

chore: expose dataset field on TakeExec

---

docs/format.rst
protos/rowids.proto
protos/table.proto
python/python/lance/fragment.py
python/python/tests/test_fragment.py
rust/lance-table/src/feature_flags.rs
rust/lance-table/src/format/fragment.rs
rust/lance-table/src/format/manifest.rs
rust/lance-table/src/lib.rs
rust/lance-table/src/rowids.rs
rust/lance-table/src/rowids/bitmap.rs
rust/lance-table/src/rowids/encoded_array.rs
rust/lance-table/src/rowids/index.rs
rust/lance-table/src/rowids/segment.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/feature_flags.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/rowids.rs
rust/lance/src/dataset/schema_evolution.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/dataset/write.rs
rust/lance/src/io/commit.rs
rust/lance/src/utils/test.rs

* Adds stable row ids to manifest
* Support writing row id sequences for append, overwrite, and update.
Epic: #2307

feat: stable row id manifest changes

---

rust/lance-linalg/src/distance/l2.rs

* 7-10% faster in L2 benchmark
* 6% faster in hnsw build.

perf: better L2 code generation

---

Cargo.toml
rust/lance-index/Cargo.toml
rust/lance-index/src/vector/storage.rs
rust/lance/Cargo.toml
rust/lance/src/index/vector/builder.rs
rust/lance/src/index/vector/ivf/v2.rs

then we don't need to serialize/deserialize the IVF proto bytes

feat: store IVF in global buffer

---

docs/examples/clip_training.rst
docs/examples/examples.rst

Adds a CLIP training example to the Lance docs.

docs: clip training example

---

docs/integrations/pytorch.rst
docs/integrations/tensorflow.rst

docs(python): note multiprocessing incompatibility

---

python/python/lance/torch/kmeans.py
python/python/tests/test_kmeans.py
python/python/tests/test_vector_index.py

fix: pytorch dot inference pass unwanted parameters

---

java/pom.xml

necessary to run 
```
mvn -DskipTests release:prepare
mvn -DskipTests deploy -P deploy-to-ossrh
```
the last step should be done on nexus to move from staging to release. but that doesn't require code change

ci: prep for java release

---

rust/lance-core/Cargo.toml
rust/lance-core/src/utils/tokio.rs

reserve a few cpus for IO only. By default 2.

feat: reserve cores for IO

---

python/python/lance/dataset.py
python/src/dataset.rs

it's related to https://github.com/lancedb/lancedb/issues/1428

feat: support to set ef for search from python

---

python/pyproject.toml

feat: loosen pyarrow pin

---

rust/lance/src/dataset.rs

BREAKING-CHANGE: remove deprecated dataset factory methods

feat!: remove deprecated methods on dataset

---

python/python/tests/test_vector_index.py

Add tests for https://github.com/lancedb/lance/pull/2631.

chore: add tests for ann fragment scan validation

---

python/src/file.rs
python/src/indices.rs

Use object_store_from_uri_or_path to avoid creating directory on windows

chore: fix broken windows test

---

rust/lance-arrow/Cargo.toml
rust/lance-encoding/Cargo.toml
rust/lance-encoding/compression-algo/fsst/Cargo.toml
rust/lance-encoding/compression-algo/fsst/examples/benchmark.rs
rust/lance-encoding/compression-algo/fsst/src/fsst.rs
rust/lance-file/Cargo.toml
rust/lance-index/Cargo.toml
rust/lance-table/Cargo.toml
rust/lance/Cargo.toml

Fixed report from `cargo +nightly udeps`

chore: clean up unused rust dependencies

---

rust/lance/src/dataset/transaction.rs

docs: fix transaction conflict table

---

rust/lance-core/src/utils/deletion.rs
rust/lance-core/src/utils/mask.rs
rust/lance-table/src/rowids.rs
rust/lance-table/src/rowids/segment.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/index/prefilter.rs

Cache the row id mask prefilter and make it faster to construct.

perf: stable row id prefilter

---

rust/lance-index/src/scalar/inverted/index.rs

Minor fix for a clippy warning I've been seeing.

chore: fix clippy warning

---

rust/lance-encoding/benches/buffer.rs
rust/lance-file/src/v2/writer.rs
rust/lance-linalg/build.rs

New rust version => new clippy suggestions

chore: address clippy suggestions from new clippy version

---

.github/workflows/pypi-publish.yml

Manylinux 2014 is [EOL on June 2024](https://github.com/pypa/manylinux).

chore!: remove manylinux 2014 build

---

java/core/lance-jni/src/blocking_dataset.rs
java/core/src/main/java/com/lancedb/lance/Dataset.java
java/core/src/main/java/com/lancedb/lance/ReadOptions.java
java/core/src/test/java/com/lancedb/lance/DatasetTest.java

Add dataset open storage options to support connecting to S3
#2854

feat(java): add dataset open storage options

---

python/python/lance/dataset.py
python/python/lance/vector.py

Null filter causes slowdown right now, primarily on small datasets.

chore: option to disable null filter during builds

---

python/python/lance/dataset.py
python/src/dataset.rs

we name the index as FTS in lancedb, so add FTS as alias of INVERTED

chore: add FTS as alias of INVERTED

---

rust/lance/src/dataset/scanner.rs

fix: refine FTS error message if no index

---

python/python/tests/test_indices.py
python/python/tests/test_lance.py
rust/lance-encoding/src/compression_algo/fsst/src/fsst.rs

Just trying to cut down on overall test time

ci: shorten some of the longest tests

---

integration/duckdb_lance/src/arrow.rs
rust/lance-encoding/src/encodings/physical/dictionary.rs
rust/lance-encoding/src/statistics.rs
rust/lance-file/src/writer/statistics.rs
rust/lance-index/src/vector/hnsw/builder.rs

issue #3065
println in benchmark code/main function/some test code remains.

chore: clear println in codebase

---

rust/lance-index/src/scalar/expression.rs

Pushed my last PR too eagerly and broke clippy

chore: remove unused import

---

python/Makefile
python/pyproject.toml
python/python/lance/torch/kmeans.py
python/python/lance/util.py
python/python/lance/vector.py

ci(python): type checking with pyright

---

java/spark/src/main/java/com/lancedb/lance/spark/SparkOptions.java
java/spark/src/main/java/com/lancedb/lance/spark/write/LanceArrowWriter.java
java/spark/src/main/java/com/lancedb/lance/spark/write/LanceDataWriter.java
java/spark/src/test/java/com/lancedb/lance/spark/read/SparkConnectorReadTest.java

In this pr, I did:
1. remove some supported TODOs
2. add allow_http for storage_option
3. remove some unused code

chore(java): remove some supported TODO and add allow_http for storage_option

---

python/pyproject.toml

fix: fix pyproject.toml

---

python/python/lance/dataset.py
python/python/lance/vector.py
python/python/tests/test_f16.py

fix: the IVF/PQ centroids/codebook is with wrong data type if training on GPU

---

README.md

Update a bunch of outdated content / links

docs: update README to include new table format and format v2 blogs

---

rust/lance-linalg/build.rs

We made a bit of a noob mistake with the `build.rs` script: `cfg!(target_arch)` and `cfg!(target_os)` are the target of the build script itself, not the library. Therefore, they actually are the same as the host. Instead, we need to use these environment variables: https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

ci: fix cross compilation of fp16 kernels

---

docs/index.rst
docs/integrations/ray.rst
docs/tags.rst
python/python/lance/dataset.py

Add document to use `LanceDataset.tags`

docs: how to use tags

---

java/spark/src/main/java/com/lancedb/lance/spark/LanceConfig.java
java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceDatasetAdapter.java
java/spark/src/main/java/com/lancedb/lance/spark/internal/LanceFragmentScanner.java

fix #3598
After this pr, the parse time will decrease to 17 minutes from 4 hours.

perf(java): cache the fragments to avoid parse the fragment json for each task

---

python/python/tests/test_dataset.py
rust/lance/src/io/exec/take.rs

Addresses errors like: https://github.com/lancedb/lancedb/issues/2285

fix: merge insert with empty index

---

python/python/lance/vector.py
python/python/tests/test_vector_index.py

one more place that needed valid part id filter

fix: one more finite vector fix

---

Cargo.lock
python/Cargo.lock
rust/lance-datafusion/src/utils.rs
rust/lance-index/Cargo.toml
rust/lance-index/benches/inverted.rs
rust/lance-index/src/scalar/inverted/builder.rs
rust/lance-index/src/scalar/inverted/index.rs

3x faster for `with_position=False`

perf: refactor the FTS indexing algo

---

Cargo.lock
python/Cargo.lock
rust/lance-datafusion/src/utils.rs
rust/lance-index/Cargo.toml
rust/lance-index/benches/inverted.rs
rust/lance-index/src/scalar/inverted/builder.rs
rust/lance-index/src/scalar/inverted/index.rs

This reverts commit 026b98448c0a6fdc232be129dbea51837defbe9e.

Revert "perf: refactor the FTS indexing algo (#3670)"

---

java/.mvn/wrapper/maven-wrapper.properties
java/mvnw

Add Maven wrapper for Java build to use a consistent Maven version and simplify user setup

chore(java): add maven wrapper

---

python/python/lance/torch/data.py
python/python/tests/test_torch.py

fix issue : https://github.com/lancedb/lance/issues/3640

fix: prevent deadlock using torch multi worker

---

python/python/lance/_arrow/bf16.py
python/python/lance/arrow.py

Original error message:   https://github.com/lancedb/lance/actions/runs/14703221198/job/41257016490?pr=3745
related issue:  https://github.com/lancedb/lance/issues/3747
This error is blocking my PR check, so please solve it as a priority.
@westonpace @wjones127

fix: arrow version compatibility issues caused by API changes

---

Cargo.lock
Cargo.toml
python/Cargo.lock
python/Cargo.toml
python/python/lance/dataset.py
python/python/lance/torch/data.py
python/python/tests/test_blob.py
python/src/dataset.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/blob.rs
rust/lance/src/dataset/take.rs

feat!: allow take_blobs API to take on row address, indices or row ids

---

docs/blob.rst

Add documents about how to setting a large binary to be blob field

docs: how to set blob metadata

---

.github/workflows/pr-title.yml
README.md
docs/examples/artefact_management.rst
docs/examples/clip_training.rst
docs/examples/llm_dataset_creation.rst
docs/format.rst
python/python/lance/dataset.py
rust/lance-file/src/writer/statistics.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/dataset/schema_evolution.rs
rust/lance/src/io/commit.rs
rust/lance/src/io/exec/take.rs

docs: fix typos

---

.github/workflows/python.yml
Cargo.toml
python/Cargo.lock
python/Cargo.toml
python/pyproject.toml
python/python/lance/__init__.py
python/python/tests/test_table_provider.py
python/src/executor.rs
python/src/lib.rs
rust/lance/src/datafusion/dataframe.rs

Adds a Datafusion FFI for the LanceTableProvider

feat: a Datafusion FFI for the LanceTableProvider

---

java/README.md
java/core/lance-jni/src/blocking_dataset.rs
java/core/src/main/java/com/lancedb/lance/Dataset.java
java/core/src/test/java/com/lancedb/lance/DatasetTest.java

feat(java): support adding columns by schema and field definitions

---

docs/integrations/pytorch.rst

@eddyxu  I've enhanced the document here. Please take a look when you have time.

docs: add safe dataloader for lance dataset

---

python/python/tests/test_blob.py
rust/lance/src/io/exec/projection.rs

https://github.com/lancedb/lance/issues/3744
@yanghua @westonpace If you have time, please help review the fix for this issue.

fix: the error that the blob field requires a project

---

python/python/lance/dataset.py
python/python/tests/test_dataset.py
python/src/dataset.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/io/exec/scan.rs

fix https://github.com/lancedb/lance/issues/3790

fix: ensure to_batches output strictly adheres to configured batch size

---

rust/lance-io/src/object_store/providers/aws.rs

When a bucket ends with `--x-s3` it must be an express bucket, we can auto-set the s3_express config for object store. Also set the `list_is_lexically_ordered` to false when using S3 express bucket.
Fixes #3771

feat: auto-set S3 express and fix list ordering setting

---

protos/transaction.proto
python/python/lance/dataset.py
python/python/tests/test_scalar_index.py
python/src/transaction.rs
rust/lance/src/dataset/transaction.rs
rust/lance/src/dataset/write/commit.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/dataset/write/update.rs
rust/lance/src/io/commit/conflict_resolver.rs
rust/lance/src/utils/test.rs

fix: remove modified fragments indices during horizontal merge_insert

---

java/core/lance-jni/src/file_reader.rs
java/core/src/main/java/com/lancedb/lance/file/LanceFileReader.java
java/core/src/main/java/com/lancedb/lance/util/Range.java
java/core/src/test/java/com/lancedb/lance/FileReaderWriterTest.java

Inhance java LanceFileReader function, allow projection push down and ranges lookup push down.

feat: enhancing java LanceFileReader by adding projection push down and ranges lookup functionality

---

java/core/lance-jni/src/blocking_dataset.rs
java/core/lance-jni/src/file_writer.rs
java/core/lance-jni/src/utils.rs
java/core/src/main/java/com/lancedb/lance/file/LanceFileWriter.java

Enhance  java `LanceFileWriter`, enable it to access object store(like s3).

feat: add storage options for `LanceFileWriter`

---

rust/lance/src/dataset/optimize.rs
rust/lance/src/dataset/optimize/remapping.rs

feat: remap an index with fragment reuse index

---

rust/lance-index/src/lib.rs
rust/lance/src/dataset/optimize/remapping.rs
rust/lance/src/index/frag_reuse.rs

@wjones127 @westonpace  It seems that the pipeline compilation has failed and my PR has been blocked. Check if this PR can solve the problems on the pipeline.

fix: some compile error for index

---

rust/lance/src/dataset/index/frag_reuse.rs
rust/lance/src/index/frag_reuse.rs

Fix rebase error created by #3911 and #3920

chore: fix rebase error

---

rust/lance-table/src/io/manifest.rs
rust/lance/src/index.rs

tested on https://github.com/lancedb/lance/pull/3829

fix: newer indices may be read from cache

---

java/core/lance-jni/src/file_reader.rs
java/core/src/main/java/com/lancedb/lance/file/LanceFileReader.java
java/core/src/test/java/com/lancedb/lance/FileReaderWriterTest.java

Relation with pull request https://github.com/lancedb/lance/pull/3900

feat: add storage options for `LanceFileReader`

---

rust/lance-index/src/scalar/bitmap.rs

Currently after remap the null value rows are dropped from the index, verified by the new tests added in this PR.

fix: null value rows missing after bitmap remap

---

python/python/tests/test_dataset.py
rust/lance-table/src/format/manifest.rs
rust/lance-table/src/io/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/builder.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/insert.rs
rust/lance/src/dataset/write/merge_insert.rs

refactor: don't use schema dictionary unless using legacy storage

---

docs/mkdocs.yml
docs/src/index.md
docs/src/integrations/datafusion.md
docs/src/integrations/duckdb.md

docs: add DataFusion and DuckDB documentation

---

rust/lance-encoding/src/encodings/logical/primitive.rs

Follow-up of https://github.com/lancedb/lance/pull/4104, make the code more clear.

chore: rename RepetitionIndex to MiniBlockRepIndex

---

docs/mkdocs.yml
docs/src/community/lancelot.md
docs/src/index.md

Move from https://github.com/lancedb/lancedb/wiki?ref=blog.lancedb.com, since many people cannot easily find this information

docs: add lancelot page

---

.github/workflows/java-publish.yml

ci: fix java publish logic with separated workspace

---

python/src/dataset.rs

This ensures any new index types are shown as `Unknown`, instead of failing the entire index loading.

fix: forward compatibility of pylance load_indices

---

rust/lance-table/src/format/manifest.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/transaction.rs

chore: improve replacing semantics in code code of configuring dataset

---

README.md

fix: broken image link in README

---

Cargo.lock
python/Cargo.lock
rust/lance-linalg/Cargo.toml
rust/lance-linalg/src/kernels.rs

Fix https://github.com/lancedb/lance/issues/4222

fix: normalize_fsl should handle nulls

---

java/core/lance-jni/Cargo.lock
python/Cargo.lock
rust/lance/Cargo.toml

Enable oss support in python and java

feat: enable oss support in python and java

---

.github/workflows/python.yml
python/Makefile

There was no error in my local format, but there has been an error on the remote end. So, the details page has been printed out here.
This PR Before 
This PR After

chore: add format detail

---

rust/lance-table/src/io/commit.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/write.rs
rust/lance/src/dataset/write/commit.rs
rust/lance/src/dataset/write/insert.rs
rust/lance/src/dataset/write/merge_insert.rs
rust/lance/src/io/commit.rs

feat: support skipping auto cleanup during write

---

rust/examples/src/hnsw.rs
rust/lance-index/benches/hnsw.rs
rust/lance-index/src/vector/graph.rs
rust/lance-index/src/vector/hnsw/builder.rs
rust/lance-index/src/vector/utils.rs
rust/lance/src/index/vector/ivf/v2.rs

- fix https://github.com/lancedb/lancedb/issues/2473

fix: add hnsw range search support

---

rust/lance-io/src/object_store/providers/aws.rs
rust/lance-io/src/object_store/providers/oss.rs

fix: use debug format for object store provider errors

---

README.md

This small PR fixes the missing lance perf asset in `README.md`.

fix: update missing lance perf asset

---

python/python/tests/test_tracing.py
python/src/lib.rs
python/src/tracing.rs

closes: https://github.com/lancedb/lance/discussions/4234#discussioncomment-13860114

feat: add sdk_version in tracing events

---

.github/workflows/nightly_run.yml
rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/physical/binary.rs

close https://github.com/lancedb/lance/issues/3351

ci: run jombo tests for 2.1

---

Cargo.lock
Cargo.toml
java/core/lance-jni/Cargo.lock
java/core/lance-jni/Cargo.toml
java/core/pom.xml
java/pom.xml
python/Cargo.lock
python/Cargo.toml

chore: bump package versions by hand

---

python/python/tests/test_filter.py
rust/lance-index/src/scalar/expression.rs

fix: limit the depth of filter expression to 500

---

java/core/lance-jni/src/transaction.rs
java/core/src/main/java/com/lancedb/lance/operation/Merge.java
java/core/src/test/java/com/lancedb/lance/TransactionTest.java

feat(java): java transaction supports merge operation

---

.github/workflows/make-release-commit.yml

As described in title. Some follow up work after release workflow migration.

ci: fix git tag not run correct and preview version not created correctly

---

java/core/lance-jni/Cargo.lock
java/core/lance-jni/Cargo.toml
java/core/lance-jni/src/traits.rs
java/core/lance-jni/src/transaction.rs
java/core/lance-jni/src/utils.rs
java/core/src/main/java/com/lancedb/lance/index/Index.java
java/core/src/main/java/com/lancedb/lance/operation/Rewrite.java
java/core/src/main/java/com/lancedb/lance/operation/RewriteGroup.java
java/core/src/main/java/com/lancedb/lance/operation/RewrittenIndex.java
java/core/src/test/java/com/lancedb/lance/DatasetTest.java
java/core/src/test/java/com/lancedb/lance/TransactionTest.java

feat(java): java transaction supports rewrite operation

---

java/core/lance-jni/src/transaction.rs
java/core/src/main/java/com/lancedb/lance/Fragment.java
java/core/src/main/java/com/lancedb/lance/operation/ReserveFragments.java
java/core/src/main/java/com/lancedb/lance/operation/Restore.java
java/core/src/test/java/com/lancedb/lance/TransactionTest.java

feat(java): java transaction support restore and reserveFragments operation

---

rust/lance-encoding/src/encoder.rs
rust/lance-encoding/src/encodings/logical.rs
rust/lance-encoding/src/encodings/logical/blob.rs

Close https://github.com/lancedb/lance/issues/4372
This PR brings blob support from 2.0 to 2.1.

feat: support blob encoding in format 2.1

---

java/core/lance-jni/src/transaction.rs
java/core/src/main/java/com/lancedb/lance/operation/Delete.java
java/core/src/test/java/com/lancedb/lance/TransactionTest.java

Issue: https://github.com/lancedb/lance/issues/4332

feat(java): introduce delete in transaction

---

ci/bump_version.py

Fixes https://github.com/lancedb/lance/actions/runs/16955857958/job/48057820264

ci: fix stable release version bump

---

.bumpversion.toml

Fixes https://github.com/lancedb/lance/actions/runs/16956707046

ci: bump fsst version during release

---

rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs

fix #4466
---
Hi, @westonpace I'm not sure if this fix is correct. Maybe also related to my changes of https://github.com/lancedb/lance/pull/4440

fix: lance failed to encode 1025 rep/def values

---

rust/lance-index/src/scalar/inverted/index.rs

this is introduced by recent cache changes, reading the same token ID from another partition may hit a posting list from different partition, then it may cause index out of bound or wrong search results

fix: posting lists cache conflicts across partitions

---

rust/lance-encoding/src/encodings/logical/primitive.rs

close https://github.com/lancedb/lance/issues/4492

fix: address fuzz test #4492

---

rust/lance-datagen/src/generator.rs

The `cycle` generator requires that the data type be primitive.  Sadly, boolean is not a primitive data type and so we couldn't use it for cycling.

feat: add a cycle_bool data generator

---

rust/lance-datafusion/src/planner.rs

Fix parsing SQL Cast expressions properly to DataFusion expr based on Cast Kind.

fix: handle parsing sql_cast_expr to datafusion expr properly

---

.github/workflows/docs-deploy.yml

Fix the issue that Ray contributing guide is not showing in website, also add Spark and Namespace contributing guide.

chore: add contrib project docs to navigation sidebar

---

rust/lance-table/benches/row_id_index.rs
rust/lance-table/src/rowids.rs
rust/lance-table/src/rowids/index.rs
rust/lance-table/src/rowids/segment.rs
rust/lance/src/dataset/rowids.rs

feat(rust): support update stable row id for overlapping

---

docs/src/guide/.pages
docs/src/guide/json.md
docs/src/integrations/datafusion.md

This PR adds the docs for JSON support in Lance and JSON's UDFs.
---
**This PR was primarily authored with Claude Code using Opus 4.1 and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.**

docs: add docs for JSON and JSON UDFs

---

python/python/tests/test_vector_index.py
rust/lance-index/src/vector/transform.rs
rust/lance/src/dataset/scanner.rs
rust/lance/src/index/vector/builder.rs

fix: can't train vector index with cosine distance on GPU

---

rust/lance-tools/Cargo.toml

Failure: https://github.com/lancedb/lance/actions/runs/17450463354/job/49553974338

chore: fix publish for lance-tools

---

python/python/benchmarks/test_take.py

This PR contains several changes listed below:
* support parametrized compression;
* support cleanup os page cache automatically;
* re-group benchmark test;
* simply parameter represents;

refactor(python): refactor take bench and support parametrize compression

---

docs/src/guide/json.md

Updat documentation to reflect implementation changes.
---
**This PR was primarily authored with Claude Code using Opus 4.1 and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.**

docs: polish docs for JSON data types

---

rust/lance-index/src/scalar/inverted.rs
rust/lance-index/src/scalar/inverted/parser.rs
rust/lance-index/src/scalar/inverted/query.rs

This is the first step of adding FTS search UDTF
https://github.com/lancedb/lance/issues/4520

feat: add json parser for FtsQuery

---

.bumpversion.toml
.github/workflows/java-publish.yml
.github/workflows/license-header-check.yml

Failure: https://github.com/lancedb/lance/actions/runs/17566908418/job/49895532232?pr=4658

chore: fix wrong paths after java module refactoring

---

rust/lance-encoding/src/encodings/logical/list.rs
rust/lance-encoding/src/encodings/logical/primitive.rs

If all items in a list are null it triggers the complex null layout where we write the rep/def into a buffer but nothing else.  When reading from this layout we were not handling invisible items incorrectly.  As a result, a list with all nulls would still read out having items and return a null items array.  This could lead to errors if the list's items field was non-nullable.

fix: correctly decode lists with all nulls

---

rust/lance-io/src/object_store.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/cleanup.rs

Related to https://github.com/lancedb/lance/issues/4036

feat: add new cleanup policy to retain latest n versions

---

.github/workflows/make-release-commit.yml

This PR will fix lance's preview release didn't use the correct version.
---
**This PR was primarily authored with Codex using GPT-5-Codex and then hand-reviewed by me. I AM responsible for every change made in this PR. I aimed to keep it aligned with our goals, though I may have missed minor issues. Please flag anything that feels off, I'll fix it quickly.**

fix: fix the preview release is wrong for preview versions

---

docs/src/integrations/duckdb.md

Add the statement of opening lance dataset in the example

docs: make duckdb example runnable

---

rust/lance/src/datafusion/dataframe.rs
rust/lance/src/dataset.rs
rust/lance/src/dataset/udtf.rs
rust/lance/src/dataset/utils.rs

This is the second step of https://github.com/lancedb/lance/issues/4520

feat: add udtf for fts query

---

.github/workflows/pypi-publish.yml
.github/workflows/python.yml
.github/workflows/recurring-tests.yml
python/pyproject.toml

Change maximum python version to 3.13, by Codex

chore: bump python support version to 3.13

---

Cargo.lock
python/Cargo.lock
rust/lance-io/Cargo.toml

chore: remove unused dependency async-priority-channel
